import { assertChapterDefinition } from './schema.js'

export const bellmanPresetConfigs = {
  'target-propagation': {
    gamma: 0.9,
    noise: 0,
    policy: 'fixed',
    selected: { row: 3, col: 1 },
    actionOverride: null,
    seed: 'zeros',
    focusTerm: 'target',
  },
  'boundary-self-loop': {
    gamma: 0.9,
    noise: 0,
    policy: 'fixed',
    selected: { row: 0, col: 0 },
    actionOverride: 'up',
    seed: 'zeros',
    focusTerm: 'reward',
  },
  'discount-horizon': {
    gamma: 0.5,
    noise: 0,
    policy: 'fixed',
    selected: { row: 4, col: 4 },
    actionOverride: null,
    seed: 'converged',
    focusTerm: 'gamma',
  },
  'expected-transition': {
    gamma: 0.9,
    noise: 0.3,
    policy: 'fixed',
    selected: { row: 3, col: 1 },
    actionOverride: 'right',
    seed: 'zeros',
    focusTerm: 'future',
  },
}

const sources = [
  {
    id: 'return-recursion',
    label: 'L2 · Return recursion and state value',
    pages: 'PDF pp.18-22',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
  {
    id: 'bellman-derivation',
    label: 'L2 · Bellman equation derivation',
    pages: 'PDF pp.23-26',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
  {
    id: 'matrix-policy-evaluation',
    label: 'L2 · Matrix form and policy evaluation',
    pages: 'PDF pp.34-44',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
  {
    id: 'action-value',
    label: 'L2 · Action value',
    pages: 'PDF pp.46-53',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
]

export const bellmanChapter = assertChapterDefinition({
  id: 'bellman',
  prerequisiteIds: ['mdp', 'discounted-return', 'conditional-expectation'],
  termIds: ['return', 'stateValue', 'bellmanBackup', 'bootstrapping', 'continuingTask', 'policyEvaluation', 'actionValue'],
  sources,
  zh: {
    eyebrow: '第 3 章 · 状态价值与 Bellman 方程',
    title: '为什么一步更新能够表达长期价值？',
    intro: '状态价值不是对眼前奖励的评分，而是从当前状态出发，沿策略产生的全部未来回报的期望。Bellman 方程把这条无限长的时间链切成“下一步奖励”与“下一状态的价值”。',
    bridge: '下面的画布复现课件贯穿使用的 5×5 Grid World：进入黄色禁区或尝试越界奖励 −1，进入蓝色目标奖励 +1，其余移动奖励 0；目标状态不会终止任务。点击状态、调整参数并执行一次更新，观察课件中的数值如何从同一套环境模型中产生。',
    figure: '交互图 3.1 · 一次 Bellman backup 的显微镜',
    instruction: '点击任意状态，观察一次 Bellman 更新如何改变价值估计',
    exact: '已知模型 · 精确期望',
    microscope: {
      presetLabel: '教学预设',
      observationLabel: '观察目标',
      freeObservation: '当前已进入自由探索；选择预设可恢复一组有明确教学目标的状态。',
      currentEstimate: '当前估计',
      matchedComparison: '同条件收敛对照',
      baselineLabel: '课件基线 γ = 0.90',
      comparisonLabel: '短视野 γ = 0.50',
      courseReproduced: '课件表格复现',
      termByTerm: '逐项分解',
      presetAction: '预设动作',
      contributions: '期望中的各项贡献',
      ifApplied: '若执行',
      pseudocodeTitle: '与画布同步的伪代码',
      pseudocodeInstruction: '点击一行可定位对应变量',
      pseudocode: [
        { id: 'select', number: '1', label: '选择待评估状态 s' },
        { id: 'action', number: '2', label: '按照策略选择动作 a ← π(s)' },
        { id: 'target', number: '3', label: '计算 T ← Σ p(s′|s,a)[R + γV(s′)]' },
        { id: 'assign', number: '4', label: '写回 V(s) ← T' },
      ],
    },
    prelude: [
      {
        id: 'return-recursion',
        kicker: '从 Return 开始',
        title: '长期回报本身就具有一步递归结构',
        paragraphs: ['把第一步奖励从无限奖励序列中拿出来，括号里的剩余部分恰好是从下一时间步开始的回报。Bellman 递归首先是 return 的代数事实，还不是学习算法。'],
        formulas: [
          'Gₜ = Rₜ₊₁ + γRₜ₊₂ + γ²Rₜ₊₃ + ⋯',
          '= Rₜ₊₁ + γ(Rₜ₊₂ + γRₜ₊₃ + ⋯)',
          '= Rₜ₊₁ + γGₜ₊₁',
        ],
      },
      {
        id: 'conditional-expectation',
        kicker: '从一条轨迹到平均价值',
        title: '给定当前状态，对递归回报取条件期望',
        paragraphs: ['同一状态可能产生不同动作、奖励与后继状态。Vπ(s) 不是某一条轨迹的回报，而是遵循策略 π 时这些可能回报的条件期望。'],
        formulas: [
          'Vπ(s) = E[Gₜ | Sₜ = s]',
          '= E[Rₜ₊₁ | Sₜ = s] + γE[Gₜ₊₁ | Sₜ = s]',
        ],
      },
    ],
    sections: [
      {
        id: 'target-anatomy',
        kicker: '观察',
        title: '目标值由哪两部分组成？',
        paragraphs: ['即时奖励给出本步的直接回报；后继状态价值代表未来；γ 决定未来在今天的权重。默认确定性动作与课件一致；提高动作随机性后，目标会对所有可能后继状态进行概率加权。'],
        formula: 'T = E[Rₜ₊₁ + γVπ(Sₜ₊₁) | Sₜ = s]',
      },
      {
        id: 'bootstrapping',
        kicker: '机制',
        title: 'Bootstrapping 怎样传播信息？',
        paragraphs: ['一次 backup 只改写一个状态，但它使用了后继状态的现有估计。后续 backup 再把这个新估计带给其他状态；残差下降时，整张 value table 逐渐靠近同一个 Bellman fixed point。'],
      },
      {
        id: 'matrix-form',
        kicker: '深入',
        title: '每个状态一条方程，合起来就是矩阵形式',
        paragraphs: ['把 25 个状态的 Bellman 方程按行排列，得到 vπ = rπ + γPπvπ。当前画布的完整 sweep 对应迭代式 vₖ₊₁ = rπ + γPπvₖ；矩阵形式没有引入新假设，只是把相互依赖的状态方程放在一起。'],
        formula: 'vπ = rπ + γPπvπ',
      },
      {
        id: 'continuing-boundary',
        kicker: '边界情况',
        title: '目标不是终止状态，越界也不是零奖励',
        paragraphs: ['这个课件世界是持续型任务：进入蓝色目标得到 +1 后仍会继续行动，所以目标附近价值可以接近 1/(1−γ)。尝试越界时位置不变，但即时奖励为 −1，因此“下一状态没变”和“什么都没发生”并不等价。'],
      },
      {
        id: 'action-value-transfer',
        kicker: '下一步',
        title: '评价状态以后，怎样比较动作？',
        paragraphs: ['Vπ(s) 平均了策略在状态 s 选择的所有动作。要决定哪个动作更好，需要固定第一个动作并计算 Qπ(s,a)。下一章会把动作价值放到同一状态中竞争，从 policy evaluation 进入 Bellman optimality。'],
        formula: 'Vπ(s) = Σₐ π(a|s)Qπ(s,a)',
      },
    ],
    presets: [
      { id: 'target-propagation', title: '目标奖励传播', observation: '从全零 value 开始，+1 先改变目标邻居，再沿固定策略向外传播。' },
      { id: 'boundary-self-loop', title: '越界自循环', observation: '位置保持不变，但 target 中出现 −1 + γVπ(s)。' },
      { id: 'discount-horizon', title: '折扣视野', observation: '锁定策略、环境与收敛阈值，对照 γ=0.90 和 γ=0.50；离目标越远，长期奖励被压低得越明显。' },
      { id: 'expected-transition', title: '概率期望扩展', observation: '动作随机性大于 0 后，一个 target 由多条 successor contribution 加权组成。' },
    ],
    summary: [
      'Bellman 递归来自 return 的一步分解。',
      'State value 是给定状态并遵循策略时的期望回报。',
      '一次 backup 使用即时奖励与后继价值；反复应用才逼近 fixed point。',
      'Policy evaluation 已知策略与模型，求解相互依赖的状态价值。',
    ],
  },
  en: {
    eyebrow: 'Chapter 3 · State Value and the Bellman Equation',
    title: 'Why can a one-step update express long-term value?',
    intro: 'A state value is not a score for the immediate reward. It is the expected future return under a policy. The Bellman equation cuts that infinite chain into the next reward and the value of the next state.',
    bridge: 'The canvas reproduces the 5×5 Grid World used throughout the course: entering a yellow forbidden cell or attempting to cross the boundary yields −1, entering the blue target yields +1, and every other move yields 0. The target is non-terminal. Select a state, adjust parameters, and see the course values emerge from the same model.',
    figure: 'Interactive Figure 3.1 · Microscope for one Bellman backup',
    instruction: 'Select any state to see how one Bellman update changes its estimate',
    exact: 'Known model · exact expectation',
    microscope: {
      presetLabel: 'Teaching presets',
      observationLabel: 'What to notice',
      freeObservation: 'You are exploring freely. Choose a preset to restore a state with a specific learning objective.',
      currentEstimate: 'current estimate',
      matchedComparison: 'matched converged comparison',
      baselineLabel: 'Course baseline γ = 0.90',
      comparisonLabel: 'Short horizon γ = 0.50',
      courseReproduced: 'Course table reproduced',
      termByTerm: 'term by term',
      presetAction: 'preset action',
      contributions: 'Contributions to the expectation',
      ifApplied: 'if applied',
      pseudocodeTitle: 'Pseudocode synchronized with the canvas',
      pseudocodeInstruction: 'Choose a line to locate its variables',
      pseudocode: [
        { id: 'select', number: '1', label: 'Select a state s to evaluate' },
        { id: 'action', number: '2', label: 'Choose action a ← π(s)' },
        { id: 'target', number: '3', label: 'Compute T ← Σ p(s′|s,a)[R + γV(s′)]' },
        { id: 'assign', number: '4', label: 'Write back V(s) ← T' },
      ],
    },
    prelude: [
      {
        id: 'return-recursion',
        kicker: 'Start from return',
        title: 'Long-term return already has a one-step recursion',
        paragraphs: ['Take the first reward out of the infinite reward sequence. The remaining parenthesized tail is exactly the return starting at the next time step. Bellman recursion begins as an algebraic fact about return, not as a learning algorithm.'],
        formulas: [
          'Gₜ = Rₜ₊₁ + γRₜ₊₂ + γ²Rₜ₊₃ + ⋯',
          '= Rₜ₊₁ + γ(Rₜ₊₂ + γRₜ₊₃ + ⋯)',
          '= Rₜ₊₁ + γGₜ₊₁',
        ],
      },
      {
        id: 'conditional-expectation',
        kicker: 'From one trajectory to an average value',
        title: 'Condition the recursive return on the current state',
        paragraphs: ['The same state can lead to different actions, rewards, and successors. Vπ(s) is not the return of one trajectory; it is the conditional expectation over those possible returns under policy π.'],
        formulas: [
          'Vπ(s) = E[Gₜ | Sₜ = s]',
          '= E[Rₜ₊₁ | Sₜ = s] + γE[Gₜ₊₁ | Sₜ = s]',
        ],
      },
    ],
    sections: [
      {
        id: 'target-anatomy',
        kicker: 'Observe',
        title: 'Which two parts form the target?',
        paragraphs: ['The immediate reward is the direct return from this step; the successor value represents the future; γ controls how much the future matters now. Deterministic actions match the course by default. With action randomness, the target probability-weights every possible successor.'],
        formula: 'T = E[Rₜ₊₁ + γVπ(Sₜ₊₁) | Sₜ = s]',
      },
      {
        id: 'bootstrapping',
        kicker: 'Mechanism',
        title: 'How does bootstrapping propagate information?',
        paragraphs: ['One backup rewrites one state using an existing successor estimate. Later backups carry that new estimate to other states. As the residual falls, the value table approaches one Bellman fixed point.'],
      },
      {
        id: 'matrix-form',
        kicker: 'Deep dive',
        title: 'One equation per state becomes a matrix equation',
        paragraphs: ['Stack the Bellman equations for all 25 states to obtain vπ = rπ + γPπvπ. A full canvas sweep corresponds to vₖ₊₁ = rπ + γPπvₖ. Matrix form adds no new assumption; it collects the mutually dependent state equations.'],
        formula: 'vπ = rπ + γPπvπ',
      },
      {
        id: 'continuing-boundary',
        kicker: 'Boundary case',
        title: 'The target is non-terminal, and crossing a boundary is not reward-free',
        paragraphs: ['This course world is a continuing task. The agent keeps acting after receiving +1 on entering the blue target, so nearby values can approach 1/(1−γ). A boundary attempt leaves the state unchanged but yields −1: “same successor” does not mean “nothing happened.”'],
      },
      {
        id: 'action-value-transfer',
        kicker: 'Next',
        title: 'After evaluating states, how do we compare actions?',
        paragraphs: ['Vπ(s) averages over the actions selected by the policy in state s. To decide which action is better, fix the first action and evaluate Qπ(s,a). The next chapter lets action values compete within one state, moving from policy evaluation to Bellman optimality.'],
        formula: 'Vπ(s) = Σₐ π(a|s)Qπ(s,a)',
      },
    ],
    presets: [
      { id: 'target-propagation', title: 'Target reward propagation', observation: 'Starting from zero values, +1 first changes target neighbors and then moves outward along the fixed policy.' },
      { id: 'boundary-self-loop', title: 'Boundary self-loop', observation: 'The state stays fixed while the target includes −1 + γVπ(s).' },
      { id: 'discount-horizon', title: 'Discount horizon', observation: 'Hold policy, environment, and convergence fixed; compare γ=0.90 with γ=0.50 and watch distant long-term rewards shrink most.' },
      { id: 'expected-transition', title: 'Expected-transition extension', observation: 'With positive action randomness, one target becomes a weighted sum of successor contributions.' },
    ],
    summary: [
      'Bellman recursion starts from the one-step decomposition of return.',
      'State value is expected return from a state under a policy.',
      'One backup uses immediate reward and successor value; repeated application approaches a fixed point.',
      'Policy evaluation knows the policy and model and solves their mutually dependent state values.',
    ],
  },
})

export const bellmanSources = sources
