import { assertChapterDefinition } from './schema.js'

export const bellmanPresetConfigs = {
  'target-propagation': {
    gamma: 0.9,
    noise: 0,
    policy: 'fixed',
    selected: { row: 3, col: 1 },
    actionOverride: null,
    seed: 'zeros',
    focusTerm: 'target',
  },
  'boundary-self-loop': {
    gamma: 0.9,
    noise: 0,
    policy: 'fixed',
    selected: { row: 0, col: 0 },
    actionOverride: 'up',
    seed: 'zeros',
    focusTerm: 'reward',
  },
  'discount-horizon': {
    gamma: 0.5,
    noise: 0,
    policy: 'fixed',
    selected: { row: 4, col: 4 },
    actionOverride: null,
    seed: 'converged',
    focusTerm: 'gamma',
  },
  'expected-transition': {
    gamma: 0.9,
    noise: 0.3,
    policy: 'fixed',
    selected: { row: 3, col: 1 },
    actionOverride: 'right',
    seed: 'zeros',
    focusTerm: 'future',
  },
}

const sources = [
  {
    id: 'return-recursion',
    label: 'L2 · Return recursion and state value',
    pages: 'PDF pp.18-22',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
  {
    id: 'bellman-derivation',
    label: 'L2 · Bellman equation derivation',
    pages: 'PDF pp.23-26',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
  {
    id: 'matrix-policy-evaluation',
    label: 'L2 · Matrix form and policy evaluation',
    pages: 'PDF pp.34-44',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
  {
    id: 'action-value',
    label: 'L2 · Action value',
    pages: 'PDF pp.46-53',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
]

const bellmanDerivationZh = [
  {
    id: 'value-definition',
    rule: '从状态价值定义出发',
    latex: String.raw`V^{\pi}(s) \coloneqq \mathbb{E}_{\pi,p}\!\left[G_t\mid S_t=s\right]`,
    short: '价值是给定当前状态后的期望回报。',
    detail: '固定策略 π 与环境 p。状态 s 可能通向多条随机轨迹，因此先把 V^π(s) 定义为这些轨迹回报 G_t 的条件期望。此时还没有使用任何 Bellman 结构。',
    assumptions: ['未来动作遵循策略 π', '奖励与转移由环境 p 产生'],
    symbols: [[String.raw`V^{\pi}(s)`, '策略 π 下状态 s 的价值'], [String.raw`G_t`, '从时刻 t 开始的折扣回报']],
  },
  {
    id: 'substitute-return-recursion',
    rule: '代入回报的一步递归',
    latex: String.raw`V^{\pi}(s)=\mathbb{E}_{\pi,p}\!\left[R_{t+1}+\gamma G_{t+1}\mid S_t=s\right]`,
    short: '用 G_t=R_{t+1}+γG_{t+1} 替换 G_t。',
    detail: '上一章已经从折扣和中拆出第一项，得到回报恒等式 G_t=R_{t+1}+γG_{t+1}。将它代入价值定义，把无限未来分成下一步奖励和下一时刻的剩余回报。',
    assumptions: [String.raw`G_t=R_{t+1}+\gamma G_{t+1}`],
    symbols: [[String.raw`R_{t+1}`, '下一步即时奖励'], [String.raw`G_{t+1}`, '从下一时刻开始的回报']],
  },
  {
    id: 'total-expectation',
    rule: '按动作、后继状态和奖励展开全期望',
    latex: String.raw`V^{\pi}(s)=\sum_{a}\pi(a\mid s)\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma\,\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s',S_t=s,A_t=a\right]\right]`,
    short: '策略给出动作概率，环境给出后继状态与奖励概率。',
    detail: '对动作 A_t、后继状态 S_{t+1} 和奖励 R_{t+1} 使用全期望公式。外层 π(a|s) 属于智能体，内层 p(s′,r|s,a) 属于环境；每个可能的一步结果都按联合概率加权。',
    assumptions: [String.raw`\sum_a\pi(a\mid s)=1`, String.raw`\sum_{s',r}p(s',r\mid s,a)=1`],
    symbols: [[String.raw`\pi(a\mid s)`, '在状态 s 选择动作 a 的概率'], [String.raw`p(s',r\mid s,a)`, '环境产生后继 s′ 与奖励 r 的联合概率']],
  },
  {
    id: 'recognize-successor-value',
    rule: '用 Markov 性识别后继状态价值',
    latex: String.raw`\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s',S_t=s,A_t=a\right]=\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s'\right]=V^{\pi}(s')`,
    short: '给定后继状态后，更早历史不再改变剩余回报分布。',
    detail: 'Markov 状态已经包含预测未来所需的信息。给定 S_{t+1}=s′ 后，S_t 与 A_t 不再为未来提供额外条件；而从 s′ 继续遵循 π 的期望回报，按定义正是 V^π(s′)。',
    assumptions: ['状态表示满足 Markov 性', '从下一时刻起继续遵循同一策略 π'],
    symbols: [[String.raw`V^{\pi}(s')`, '从后继状态 s′ 继续时的状态价值']],
  },
  {
    id: 'bellman-equation',
    rule: '代回并得到 Bellman 期望方程',
    latex: String.raw`\boxed{V^{\pi}(s)=\sum_a\pi(a\mid s)\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^{\pi}(s')\right]}`,
    short: '长期价值被写成一步奖励与后继价值的概率加权和。',
    detail: '把上一行识别出的 V^π(s′) 代回全期望展开，即得到 Bellman 期望方程。它是固定策略 π 下每个状态都必须同时满足的不动点关系。',
    assumptions: [String.raw`0\le\gamma<1`, '状态与动作空间有限或相关期望存在'],
    symbols: [[String.raw`r+\gamma V^{\pi}(s')`, '一次转移对应的 Bellman target']],
  },
]

const bellmanDerivationEn = [
  { id: 'value-definition', rule: 'Start from the state-value definition', latex: String.raw`V^{\pi}(s) \coloneqq \mathbb{E}_{\pi,p}\!\left[G_t\mid S_t=s\right]`, short: 'Value is expected return conditioned on the current state.', detail: 'Fix policy π and environment p. State s may lead to many random trajectories, so V^π(s) is defined as the conditional expectation of their returns. No Bellman structure has been used yet.', assumptions: ['Future actions follow π', 'Rewards and transitions follow p'], symbols: [[String.raw`V^{\pi}(s)`, 'value of s under π'], [String.raw`G_t`, 'discounted return from time t']] },
  { id: 'substitute-return-recursion', rule: 'Substitute the one-step return recursion', latex: String.raw`V^{\pi}(s)=\mathbb{E}_{\pi,p}\!\left[R_{t+1}+\gamma G_{t+1}\mid S_t=s\right]`, short: 'Replace G_t with R_{t+1}+γG_{t+1}.', detail: 'Separating the first term of the discounted sum gives G_t=R_{t+1}+γG_{t+1}. Substitution splits the infinite future into the next reward and the remaining return.', assumptions: [String.raw`G_t=R_{t+1}+\gamma G_{t+1}`], symbols: [[String.raw`R_{t+1}`, 'next immediate reward'], [String.raw`G_{t+1}`, 'return beginning one step later']] },
  { id: 'total-expectation', rule: 'Expand total expectation over actions, successors, and rewards', latex: String.raw`V^{\pi}(s)=\sum_{a}\pi(a\mid s)\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma\,\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s',S_t=s,A_t=a\right]\right]`, short: 'Policy supplies action probabilities; the environment supplies successor and reward probabilities.', detail: 'Apply total expectation over A_t, S_{t+1}, and R_{t+1}. The outer π(a|s) belongs to the agent; the inner p(s′,r|s,a) belongs to the environment.', assumptions: [String.raw`\sum_a\pi(a\mid s)=1`, String.raw`\sum_{s',r}p(s',r\mid s,a)=1`], symbols: [[String.raw`\pi(a\mid s)`, 'action probability in s'], [String.raw`p(s',r\mid s,a)`, 'joint successor-reward probability']] },
  { id: 'recognize-successor-value', rule: 'Use the Markov property to recognize successor value', latex: String.raw`\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s',S_t=s,A_t=a\right]=\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s'\right]=V^{\pi}(s')`, short: 'Conditioned on the successor state, earlier history adds no information.', detail: 'A Markov state contains the information needed to predict the future. Once S_{t+1}=s′ is given, S_t and A_t provide no further condition; the remaining expected return is V^π(s′) by definition.', assumptions: ['The state representation is Markov', 'The same policy π continues'], symbols: [[String.raw`V^{\pi}(s')`, 'value when continuing from successor s′']] },
  { id: 'bellman-equation', rule: 'Substitute back to obtain the Bellman expectation equation', latex: String.raw`\boxed{V^{\pi}(s)=\sum_a\pi(a\mid s)\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^{\pi}(s')\right]}`, short: 'Long-term value becomes a probability-weighted one-step reward plus successor value.', detail: 'Substitute V^π(s′) into the total-expectation expansion. The result is the fixed-point relation that every state must satisfy under policy π.', assumptions: [String.raw`0\le\gamma<1`, 'State and action spaces are finite or the expectations exist'], symbols: [[String.raw`r+\gamma V^{\pi}(s')`, 'Bellman target for one transition']] },
]

export const bellmanChapter = assertChapterDefinition({
  id: 'bellman',
  prerequisiteIds: ['mdp', 'discounted-return', 'conditional-expectation'],
  termIds: ['return', 'stateValue', 'bellmanBackup', 'bootstrapping', 'continuingTask', 'policyEvaluation', 'actionValue'],
  sources,
  zh: {
    eyebrow: '第 3 章 · 状态价值与 Bellman 方程',
    title: '为什么一步更新能够表达长期价值？',
    intro: '状态价值不是对眼前奖励的评分，而是从当前状态出发，沿策略产生的全部未来回报的期望。Bellman 方程把这条无限长的时间链切成“下一步奖励”与“下一状态的价值”。',
    bridge: '下面继续使用同一个 5×5 网格环境：进入黄色禁区或尝试越界奖励 −1，进入蓝色目标奖励 +1，其余移动奖励 0；目标状态不会终止任务。点击状态、调整参数并执行一次更新，观察数值如何从同一套环境模型中产生。',
    figure: '交互图 3.1 · 一次 Bellman backup 的显微镜',
    instruction: '点击任意状态，观察一次 Bellman 更新如何改变价值估计',
    exact: '已知模型 · 精确期望',
    derivation: bellmanDerivationZh,
    microscope: {
      presetLabel: '教学预设',
      observationLabel: '观察目标',
      freeObservation: '当前已进入自由探索；选择预设可恢复一组有明确教学目标的状态。',
      currentEstimate: '当前估计',
      matchedComparison: '同条件收敛对照',
      baselineLabel: '长视野基线 γ = 0.90',
      comparisonLabel: '短视野 γ = 0.50',
      courseReproduced: '基准数值复现',
      termByTerm: '逐项分解',
      presetAction: '预设动作',
      contributions: '期望中的各项贡献',
      ifApplied: '若执行',
      pseudocodeTitle: '与画布同步的伪代码',
      pseudocodeInstruction: '点击一行可定位对应变量',
      pseudocode: [
        { id: 'select', number: '1', label: '选择待评估状态 s' },
        { id: 'action', number: '2', label: '按照策略选择动作 a ← π(s)' },
        { id: 'target', number: '3', label: '计算 T ← Σ p(s′|s,a)[R + γV(s′)]' },
        { id: 'assign', number: '4', label: '写回 V(s) ← T' },
      ],
    },
    prelude: [
      {
        id: 'return-recursion',
        kicker: '从 Return 开始',
        title: '长期回报本身就具有一步递归结构',
        paragraphs: ['把第一步奖励从无限奖励序列中拿出来，括号里的剩余部分恰好是从下一时间步开始的回报。Bellman 递归首先是 return 的代数事实，还不是学习算法。'],
        formulas: [
          String.raw`G_t=R_{t+1}+\gamma R_{t+2}+\gamma^2R_{t+3}+\cdots`,
          String.raw`G_t=R_{t+1}+\gamma\left(R_{t+2}+\gamma R_{t+3}+\cdots\right)`,
          String.raw`G_t=R_{t+1}+\gamma G_{t+1}`,
        ],
      },
      {
        id: 'conditional-expectation',
        kicker: '从一条轨迹到平均价值',
        title: '给定当前状态，对递归回报取条件期望',
        paragraphs: ['同一状态可能产生不同动作、奖励与后继状态。Vπ(s) 不是某一条轨迹的回报，而是遵循策略 π 时这些可能回报的条件期望。'],
        formulas: [
          String.raw`V^{\pi}(s)=\mathbb{E}[G_t\mid S_t=s]`,
          String.raw`V^{\pi}(s)=\mathbb{E}[R_{t+1}\mid S_t=s]+\gamma\mathbb{E}[G_{t+1}\mid S_t=s]`,
        ],
      },
    ],
    sections: [
      {
        id: 'target-anatomy',
        kicker: '观察',
        title: '目标值由哪两部分组成？',
        paragraphs: ['即时奖励给出本步的直接回报；后继状态价值代表未来；γ 决定未来在今天的权重。默认采用确定性动作；提高动作随机性后，目标会对所有可能后继状态进行概率加权。'],
        formula: String.raw`T=\mathbb{E}[R_{t+1}+\gamma V^{\pi}(S_{t+1})\mid S_t=s]`,
      },
      {
        id: 'bootstrapping',
        kicker: '机制',
        title: 'Bootstrapping 怎样传播信息？',
        paragraphs: ['一次 backup 只改写一个状态，但它使用了后继状态的现有估计。后续 backup 再把这个新估计带给其他状态；残差下降时，整张 value table 逐渐靠近同一个 Bellman fixed point。'],
      },
      {
        id: 'matrix-form',
        kicker: '深入',
        title: '每个状态一条方程，合起来就是矩阵形式',
        paragraphs: ['把 25 个状态的 Bellman 方程按行排列，得到 vπ = rπ + γPπvπ。当前画布的完整 sweep 对应迭代式 vₖ₊₁ = rπ + γPπvₖ；矩阵形式没有引入新假设，只是把相互依赖的状态方程放在一起。'],
        formula: String.raw`\mathbf{v}^{\pi}=\mathbf{r}^{\pi}+\gamma P^{\pi}\mathbf{v}^{\pi}`,
      },
      {
        id: 'continuing-boundary',
        kicker: '边界情况',
        title: '目标不是终止状态，越界也不是零奖励',
        paragraphs: ['这个网格世界是持续型任务：进入蓝色目标得到 +1 后仍会继续行动，所以目标附近价值可以接近 1/(1−γ)。尝试越界时位置不变，但即时奖励为 −1，因此“下一状态没变”和“什么都没发生”并不等价。'],
      },
      {
        id: 'action-value-transfer',
        kicker: '下一步',
        title: '评价状态以后，怎样比较动作？',
        paragraphs: ['Vπ(s) 平均了策略在状态 s 选择的所有动作。要决定哪个动作更好，需要固定第一个动作并计算 Qπ(s,a)。下一章会把动作价值放到同一状态中竞争，从 policy evaluation 进入 Bellman optimality。'],
        formula: String.raw`V^{\pi}(s)=\sum_a\pi(a\mid s)Q^{\pi}(s,a)`,
      },
    ],
    presets: [
      { id: 'target-propagation', title: '目标奖励传播', observation: '从全零 value 开始，+1 先改变目标邻居，再沿固定策略向外传播。' },
      { id: 'boundary-self-loop', title: '越界自循环', observation: '位置保持不变，但 target 中出现 −1 + γVπ(s)。' },
      { id: 'discount-horizon', title: '折扣视野', observation: '锁定策略、环境与收敛阈值，对照 γ=0.90 和 γ=0.50；离目标越远，长期奖励被压低得越明显。' },
      { id: 'expected-transition', title: '概率期望扩展', observation: '动作随机性大于 0 后，一个 target 由多条 successor contribution 加权组成。' },
    ],
    summary: [
      'Bellman 递归来自 return 的一步分解。',
      'State value 是给定状态并遵循策略时的期望回报。',
      '一次 backup 使用即时奖励与后继价值；反复应用才逼近 fixed point。',
      'Policy evaluation 已知策略与模型，求解相互依赖的状态价值。',
    ],
  },
  en: {
    eyebrow: 'Chapter 3 · State Value and the Bellman Equation',
    title: 'Why can a one-step update express long-term value?',
    intro: 'A state value is not a score for the immediate reward. It is the expected future return under a policy. The Bellman equation cuts that infinite chain into the next reward and the value of the next state.',
    bridge: 'The canvas continues with the same 5×5 grid environment: entering a yellow forbidden cell or attempting to cross the boundary yields −1, entering the blue target yields +1, and every other move yields 0. The target is non-terminal. Select a state, adjust parameters, and see the values emerge from the same model.',
    figure: 'Interactive Figure 3.1 · Microscope for one Bellman backup',
    instruction: 'Select any state to see how one Bellman update changes its estimate',
    exact: 'Known model · exact expectation',
    derivation: bellmanDerivationEn,
    microscope: {
      presetLabel: 'Teaching presets',
      observationLabel: 'What to notice',
      freeObservation: 'You are exploring freely. Choose a preset to restore a state with a specific learning objective.',
      currentEstimate: 'current estimate',
      matchedComparison: 'matched converged comparison',
      baselineLabel: 'Long-horizon baseline γ = 0.90',
      comparisonLabel: 'Short horizon γ = 0.50',
      courseReproduced: 'Reference values reproduced',
      termByTerm: 'term by term',
      presetAction: 'preset action',
      contributions: 'Contributions to the expectation',
      ifApplied: 'if applied',
      pseudocodeTitle: 'Pseudocode synchronized with the canvas',
      pseudocodeInstruction: 'Choose a line to locate its variables',
      pseudocode: [
        { id: 'select', number: '1', label: 'Select a state s to evaluate' },
        { id: 'action', number: '2', label: 'Choose action a ← π(s)' },
        { id: 'target', number: '3', label: 'Compute T ← Σ p(s′|s,a)[R + γV(s′)]' },
        { id: 'assign', number: '4', label: 'Write back V(s) ← T' },
      ],
    },
    prelude: [
      {
        id: 'return-recursion',
        kicker: 'Start from return',
        title: 'Long-term return already has a one-step recursion',
        paragraphs: ['Take the first reward out of the infinite reward sequence. The remaining parenthesized tail is exactly the return starting at the next time step. Bellman recursion begins as an algebraic fact about return, not as a learning algorithm.'],
        formulas: [
          String.raw`G_t=R_{t+1}+\gamma R_{t+2}+\gamma^2R_{t+3}+\cdots`,
          String.raw`G_t=R_{t+1}+\gamma\left(R_{t+2}+\gamma R_{t+3}+\cdots\right)`,
          String.raw`G_t=R_{t+1}+\gamma G_{t+1}`,
        ],
      },
      {
        id: 'conditional-expectation',
        kicker: 'From one trajectory to an average value',
        title: 'Condition the recursive return on the current state',
        paragraphs: ['The same state can lead to different actions, rewards, and successors. Vπ(s) is not the return of one trajectory; it is the conditional expectation over those possible returns under policy π.'],
        formulas: [
          String.raw`V^{\pi}(s)=\mathbb{E}[G_t\mid S_t=s]`,
          String.raw`V^{\pi}(s)=\mathbb{E}[R_{t+1}\mid S_t=s]+\gamma\mathbb{E}[G_{t+1}\mid S_t=s]`,
        ],
      },
    ],
    sections: [
      {
        id: 'target-anatomy',
        kicker: 'Observe',
        title: 'Which two parts form the target?',
        paragraphs: ['The immediate reward is the direct return from this step; the successor value represents the future; γ controls how much the future matters now. Actions are deterministic by default. With action randomness, the target probability-weights every possible successor.'],
        formula: String.raw`T=\mathbb{E}[R_{t+1}+\gamma V^{\pi}(S_{t+1})\mid S_t=s]`,
      },
      {
        id: 'bootstrapping',
        kicker: 'Mechanism',
        title: 'How does bootstrapping propagate information?',
        paragraphs: ['One backup rewrites one state using an existing successor estimate. Later backups carry that new estimate to other states. As the residual falls, the value table approaches one Bellman fixed point.'],
      },
      {
        id: 'matrix-form',
        kicker: 'Deep dive',
        title: 'One equation per state becomes a matrix equation',
        paragraphs: ['Stack the Bellman equations for all 25 states to obtain vπ = rπ + γPπvπ. A full canvas sweep corresponds to vₖ₊₁ = rπ + γPπvₖ. Matrix form adds no new assumption; it collects the mutually dependent state equations.'],
        formula: String.raw`\mathbf{v}^{\pi}=\mathbf{r}^{\pi}+\gamma P^{\pi}\mathbf{v}^{\pi}`,
      },
      {
        id: 'continuing-boundary',
        kicker: 'Boundary case',
        title: 'The target is non-terminal, and crossing a boundary is not reward-free',
        paragraphs: ['This grid world is a continuing task. The agent keeps acting after receiving +1 on entering the blue target, so nearby values can approach 1/(1−γ). A boundary attempt leaves the state unchanged but yields −1: “same successor” does not mean “nothing happened.”'],
      },
      {
        id: 'action-value-transfer',
        kicker: 'Next',
        title: 'After evaluating states, how do we compare actions?',
        paragraphs: ['Vπ(s) averages over the actions selected by the policy in state s. To decide which action is better, fix the first action and evaluate Qπ(s,a). The next chapter lets action values compete within one state, moving from policy evaluation to Bellman optimality.'],
        formula: String.raw`V^{\pi}(s)=\sum_a\pi(a\mid s)Q^{\pi}(s,a)`,
      },
    ],
    presets: [
      { id: 'target-propagation', title: 'Target reward propagation', observation: 'Starting from zero values, +1 first changes target neighbors and then moves outward along the fixed policy.' },
      { id: 'boundary-self-loop', title: 'Boundary self-loop', observation: 'The state stays fixed while the target includes −1 + γVπ(s).' },
      { id: 'discount-horizon', title: 'Discount horizon', observation: 'Hold policy, environment, and convergence fixed; compare γ=0.90 with γ=0.50 and watch distant long-term rewards shrink most.' },
      { id: 'expected-transition', title: 'Expected-transition extension', observation: 'With positive action randomness, one target becomes a weighted sum of successor contributions.' },
    ],
    summary: [
      'Bellman recursion starts from the one-step decomposition of return.',
      'State value is expected return from a state under a policy.',
      'One backup uses immediate reward and successor value; repeated application approaches a fixed point.',
      'Policy evaluation knows the policy and model and solves their mutually dependent state values.',
    ],
  },
})

export const bellmanSources = sources
