import { assertChapterDefinition } from './schema.js'

export const bellmanPresetConfigs = {
  'target-propagation': {
    gamma: 0.9,
    noise: 0,
    policy: 'fixed',
    selected: { row: 3, col: 1 },
    actionOverride: null,
    seed: 'zeros',
    focusTerm: 'target',
  },
  'boundary-self-loop': {
    gamma: 0.9,
    noise: 0,
    policy: 'fixed',
    selected: { row: 0, col: 0 },
    actionOverride: 'up',
    seed: 'zeros',
    focusTerm: 'reward',
  },
  'discount-horizon': {
    gamma: 0.5,
    noise: 0,
    policy: 'fixed',
    selected: { row: 4, col: 4 },
    actionOverride: null,
    seed: 'converged',
    focusTerm: 'gamma',
  },
}

const sources = [
  {
    id: 'return-recursion',
    label: 'L2 · Return recursion and state value',
    pages: 'PDF pp.18-22',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
  {
    id: 'bellman-derivation',
    label: 'L2 · Bellman equation derivation',
    pages: 'PDF pp.23-26',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
  {
    id: 'matrix-policy-evaluation',
    label: 'L2 · Matrix form and policy evaluation',
    pages: 'PDF pp.34-44',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
  {
    id: 'action-value',
    label: 'L2 · Action value',
    pages: 'PDF pp.46-53',
    href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning',
  },
]

const bellmanDerivationZh = [
  {
    id: 'value-definition',
    rule: '从状态价值定义出发',
    latex: String.raw`V^{\pi}(s) \coloneqq \mathbb{E}_{\pi,p}\!\left[G_t\mid S_t=s\right]`,
    short: '价值是给定当前状态后的期望回报。',
    detail: '固定策略 π 与环境 p。状态 s 可能通向多条随机轨迹，因此先把 V^π(s) 定义为这些轨迹回报 G_t 的条件期望。此时还没有使用任何 Bellman 结构。',
    assumptions: ['未来动作遵循策略 π', '奖励与转移由环境 p 产生'],
    symbols: [[String.raw`V^{\pi}(s)`, '策略 π 下状态 s 的价值'], [String.raw`G_t`, '从时刻 t 开始的折扣回报']],
  },
  {
    id: 'substitute-return-recursion',
    rule: '代入回报的一步递归',
    latex: String.raw`V^{\pi}(s)=\mathbb{E}_{\pi,p}\!\left[R_{t+1}+\gamma G_{t+1}\mid S_t=s\right]`,
    short: '用 G_t=R_{t+1}+γG_{t+1} 替换 G_t。',
    detail: '上一章已经从折扣和中拆出第一项，得到回报恒等式 G_t=R_{t+1}+γG_{t+1}。将它代入价值定义，把无限未来分成下一步奖励和下一时刻的剩余回报。',
    assumptions: [String.raw`G_t=R_{t+1}+\gamma G_{t+1}`],
    symbols: [[String.raw`R_{t+1}`, '下一步即时奖励'], [String.raw`G_{t+1}`, '从下一时刻开始的回报']],
  },
  {
    id: 'total-expectation',
    rule: '按动作、后继状态和奖励展开全期望',
    latex: String.raw`V^{\pi}(s)=\sum_{a}\pi(a\mid s)\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma\,\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s',S_t=s,A_t=a\right]\right]`,
    short: '策略给出动作概率，环境给出后继状态与奖励概率。',
    detail: '对动作 A_t、后继状态 S_{t+1} 和奖励 R_{t+1} 使用全期望公式。外层 π(a|s) 属于智能体，内层 p(s′,r|s,a) 属于环境；每个可能的一步结果都按联合概率加权。',
    assumptions: [String.raw`\sum_a\pi(a\mid s)=1`, String.raw`\sum_{s',r}p(s',r\mid s,a)=1`],
    symbols: [[String.raw`\pi(a\mid s)`, '在状态 s 选择动作 a 的概率'], [String.raw`p(s',r\mid s,a)`, '环境产生后继 s′ 与奖励 r 的联合概率']],
  },
  {
    id: 'recognize-successor-value',
    rule: '用 Markov 性识别后继状态价值',
    latex: String.raw`\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s',S_t=s,A_t=a\right]=\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s'\right]=V^{\pi}(s')`,
    short: '给定后继状态后，更早历史不再改变剩余回报分布。',
    detail: 'Markov 状态已经包含预测未来所需的信息。给定 S_{t+1}=s′ 后，S_t 与 A_t 不再为未来提供额外条件；而从 s′ 继续遵循 π 的期望回报，按定义正是 V^π(s′)。',
    assumptions: ['状态表示满足 Markov 性', '从下一时刻起继续遵循同一策略 π'],
    symbols: [[String.raw`V^{\pi}(s')`, '从后继状态 s′ 继续时的状态价值']],
  },
  {
    id: 'bellman-equation',
    rule: '代回并得到 Bellman 期望方程',
    latex: String.raw`\boxed{V^{\pi}(s)=\sum_a\pi(a\mid s)\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^{\pi}(s')\right]}`,
    short: '长期价值被写成一步奖励与后继价值的概率加权和。',
    detail: '把上一行识别出的 V^π(s′) 代回全期望展开，即得到 Bellman 期望方程。它是固定策略 π 下每个状态都必须同时满足的不动点关系。',
    assumptions: [String.raw`0\le\gamma<1`, '状态与动作空间有限或相关期望存在'],
    symbols: [[String.raw`r+\gamma V^{\pi}(s')`, '一次转移对应的 Bellman target']],
  },
]

const bellmanDerivationEn = [
  { id: 'value-definition', rule: 'Start from the state-value definition', latex: String.raw`V^{\pi}(s) \coloneqq \mathbb{E}_{\pi,p}\!\left[G_t\mid S_t=s\right]`, short: 'Value is expected return conditioned on the current state.', detail: 'Fix policy π and environment p. State s may lead to many random trajectories, so V^π(s) is defined as the conditional expectation of their returns. No Bellman structure has been used yet.', assumptions: ['Future actions follow π', 'Rewards and transitions follow p'], symbols: [[String.raw`V^{\pi}(s)`, 'value of s under π'], [String.raw`G_t`, 'discounted return from time t']] },
  { id: 'substitute-return-recursion', rule: 'Substitute the one-step return recursion', latex: String.raw`V^{\pi}(s)=\mathbb{E}_{\pi,p}\!\left[R_{t+1}+\gamma G_{t+1}\mid S_t=s\right]`, short: 'Replace G_t with R_{t+1}+γG_{t+1}.', detail: 'Separating the first term of the discounted sum gives G_t=R_{t+1}+γG_{t+1}. Substitution splits the infinite future into the next reward and the remaining return.', assumptions: [String.raw`G_t=R_{t+1}+\gamma G_{t+1}`], symbols: [[String.raw`R_{t+1}`, 'next immediate reward'], [String.raw`G_{t+1}`, 'return beginning one step later']] },
  { id: 'total-expectation', rule: 'Expand total expectation over actions, successors, and rewards', latex: String.raw`V^{\pi}(s)=\sum_{a}\pi(a\mid s)\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma\,\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s',S_t=s,A_t=a\right]\right]`, short: 'Policy supplies action probabilities; the environment supplies successor and reward probabilities.', detail: 'Apply total expectation over A_t, S_{t+1}, and R_{t+1}. The outer π(a|s) belongs to the agent; the inner p(s′,r|s,a) belongs to the environment.', assumptions: [String.raw`\sum_a\pi(a\mid s)=1`, String.raw`\sum_{s',r}p(s',r\mid s,a)=1`], symbols: [[String.raw`\pi(a\mid s)`, 'action probability in s'], [String.raw`p(s',r\mid s,a)`, 'joint successor-reward probability']] },
  { id: 'recognize-successor-value', rule: 'Use the Markov property to recognize successor value', latex: String.raw`\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s',S_t=s,A_t=a\right]=\mathbb{E}_{\pi,p}\!\left[G_{t+1}\mid S_{t+1}=s'\right]=V^{\pi}(s')`, short: 'Conditioned on the successor state, earlier history adds no information.', detail: 'A Markov state contains the information needed to predict the future. Once S_{t+1}=s′ is given, S_t and A_t provide no further condition; the remaining expected return is V^π(s′) by definition.', assumptions: ['The state representation is Markov', 'The same policy π continues'], symbols: [[String.raw`V^{\pi}(s')`, 'value when continuing from successor s′']] },
  { id: 'bellman-equation', rule: 'Substitute back to obtain the Bellman expectation equation', latex: String.raw`\boxed{V^{\pi}(s)=\sum_a\pi(a\mid s)\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^{\pi}(s')\right]}`, short: 'Long-term value becomes a probability-weighted one-step reward plus successor value.', detail: 'Substitute V^π(s′) into the total-expectation expansion. The result is the fixed-point relation that every state must satisfy under policy π.', assumptions: [String.raw`0\le\gamma<1`, 'State and action spaces are finite or the expectations exist'], symbols: [[String.raw`r+\gamma V^{\pi}(s')`, 'Bellman target for one transition']] },
]

const bellmanDeepeningZh = [
  {
    id: 'four-state-worked-system', kicker: '方程耦合 · 四状态网格', title: 'Bellman 方程把各状态的价值组织成耦合系统',
    paragraphs: ['先取原网格的一个四状态缩影，并固定策略：s₁ 以奖励 0 转移到 s₃；s₂ 和 s₃ 都以奖励 +1 转移到 s₄；s₄ 每一步获得 +1 并留在原地。令 γ=0.9。此时不能给每个状态单独“打分”，因为 V(s₁) 需要 V(s₃)，V(s₂) 与 V(s₃) 需要 V(s₄)，而 V(s₄) 又依赖自身。', '因此 Bellman 方程不是一条可以孤立代入的公式，而是所有状态必须同时满足的方程组。先由自循环方程得到 V(s₄)=1+0.9V(s₄)=10，再代回其余三式，可得 V(s₂)=V(s₃)=10、V(s₁)=9。'],
    formulas: [
      String.raw`\begin{aligned}V(s_1)&=0+0.9V(s_3),&V(s_2)&=1+0.9V(s_4),\\V(s_3)&=1+0.9V(s_4),&V(s_4)&=1+0.9V(s_4).\end{aligned}`,
      String.raw`\begin{bmatrix}V(s_1)\\V(s_2)\\V(s_3)\\V(s_4)\end{bmatrix}=\begin{bmatrix}0\\1\\1\\1\end{bmatrix}+0.9\begin{bmatrix}0&0&1&0\\0&0&0&1\\0&0&0&1\\0&0&0&1\end{bmatrix}\begin{bmatrix}V(s_1)\\V(s_2)\\V(s_3)\\V(s_4)\end{bmatrix}`,
    ],
    example: { title: '同一组未知量必须一起求解', caption: '每一行都对应一个状态的即时奖励和下一状态价值。', headers: ['状态', '策略下的一步结果', 'Bellman 方程', '解'], rows: [['s₁', '0 → s₃', 'V(s₁)=0+0.9V(s₃)', '9'], ['s₂', '+1 → s₄', 'V(s₂)=1+0.9V(s₄)', '10'], ['s₃', '+1 → s₄', 'V(s₃)=1+0.9V(s₄)', '10'], ['s₄', '+1 → s₄', 'V(s₄)=1+0.9V(s₄)', '10']] },
    handoff: '矩阵中的每一行正好保存一条状态方程。把四个状态推广到 n 个状态，就得到通用的矩阵形式。',
  },
  {
    id: 'matrix-and-iteration', kicker: '从方程组到求解', title: '直接求解与迭代更新指向同一个价值解',
    paragraphs: ['沿用上面的四状态例子，把四个未知价值依次放进向量 vπ，把四个期望即时奖励放进 rπ；矩阵 Pπ 的第 s 行、第 s′ 列记录遵循固定策略 π 时从 s 到 s′ 的概率。这样，vπ=rπ+γPπvπ 只是把刚才四条 Bellman 方程按行叠在一起，并没有引入新的数学关系。', '这组方程有两种求法。直接求解时，把所有含未知向量 vπ 的项移到等号左边，再乘逆矩阵；迭代求解时，不立即要求等号两边完全一致，而是把上一轮向量 vk 代入右侧，算出下一轮 vk+1。下面第二条公式继续使用同一个四状态例子，让两种计算方式可以逐行对照。'],
    formulas: [
      String.raw`\begin{aligned}\mathbf v^{\pi}&=\mathbf r^{\pi}+\gamma P^{\pi}\mathbf v^{\pi}\\\mathbf v^{\pi}-\gamma P^{\pi}\mathbf v^{\pi}&=\mathbf r^{\pi}\\(I-\gamma P^{\pi})\mathbf v^{\pi}&=\mathbf r^{\pi}\\\mathbf v^{\pi}&=(I-\gamma P^{\pi})^{-1}\mathbf r^{\pi}\end{aligned}`,
      String.raw`\begin{aligned}\mathbf v_0&=(0,\ 0,\ 0,\ 0)^{\mathsf T}\\\mathbf v_1=\mathcal T^{\pi}(\mathbf v_0)&=\mathbf r^{\pi}+0.9P^{\pi}\mathbf v_0=(0,\ 1,\ 1,\ 1)^{\mathsf T}\\\mathbf v_2=\mathcal T^{\pi}(\mathbf v_1)&=\mathbf r^{\pi}+0.9P^{\pi}\mathbf v_1=(0.9,\ 1.9,\ 1.9,\ 1.9)^{\mathsf T}\\&\ \vdots\\\mathbf v_k&\longrightarrow(9,\ 10,\ 10,\ 10)^{\mathsf T}=\mathbf v^{\pi}\end{aligned}`,
    ],
    formulaLabels: ['直接求解：把未知量集中到等号左侧', '迭代求解：把上一轮估计代入等号右侧'],
    formulaAfter: '直接法一次联立处理所有状态；第二条公式展示的是同步向量迭代：整轮都读取同一个旧向量 vk，再一起得到 vk+1。实验则把同一件事拆成逐状态的原地更新。Bellman backup 不是保存副本：它选定一个状态，只写回该状态的 V(s)，后面的更新会读取前面刚写入的最新估计；依次更新所有状态称为一次 sweep。两种次序的中间数值不同，但都在反复执行 Bellman 关系；当一次完整映射前后的价值表完全相同，这张表就到达不动点。这里策略 π 始终固定，“迭代”只表示反复评价它，并不是后面章节中会改变策略的“策略迭代”。',
    theorem: { claim: '当 0≤γ<1 且 Pπ 的每一行都是概率分布时，Tπ 只有一个不动点，迭代从任意有界初值收敛到该点。', why: 'Pπ 只对后继价值做概率加权，不会放大最大误差；再乘 γ 后，每轮误差至多保留原来的 γ 倍。', conditions: [String.raw`0\le\gamma<1`, String.raw`\sum_{s'}P^{\pi}_{ss'}=1`] },
    pseudocodeTitle: '用逐状态回传更新做迭代策略评价', pseudocode: ['初始化固定策略 π 的 V(s)，例如所有状态置 0', '重复一次 sweep：', '  Δ ← 0', '  对每个状态 s 做一次 backup（单状态回传更新）：', '    old ← V(s)', '    V(s) ← Σₐπ(a|s)Σₛ′,ᵣp(s′,r|s,a)[r+γV(s′)]', '    Δ ← max(Δ, |old−V(s)|)', '直到 Δ 小于停止阈值；返回 Vπ'],
  },
  {
    id: 'state-to-action-value', kicker: '动作价值 · 固定第一步', title: '动作价值保留第一步差异，状态价值按策略求平均',
    paragraphs: ['Vπ(s) 在第一步就按策略 π 对动作取平均，因此不能直接告诉我们某个具体动作会怎样。Qπ(s,a) 固定第一步动作 a，再从后继状态开始遵循 π。', '把 Qπ 重新按 π(a|s) 加权，就回到 Vπ；反过来，比较同一状态的 Qπ(s,a) 才能做策略改善。'],
    formulas: [String.raw`Q^{\pi}(s,a)=\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^{\pi}(s')\right]`, String.raw`V^{\pi}(s)=\sum_a\pi(a\mid s)Q^{\pi}(s,a)`],
    handoff: '下一章不再只评价给定 π，而是让同一状态中的动作价值竞争，并证明选择最大动作如何产生最优方程。',
  },
]

const bellmanDeepeningEn = [
  {
    id: 'four-state-worked-system', kicker: 'Equation coupling · Four-state grid', title: 'Bellman equations form a coupled system of state values',
    paragraphs: ['Take a four-state slice of the grid under a fixed policy. State s₁ moves to s₃ with reward 0; s₂ and s₃ move to s₄ with reward +1; s₄ earns +1 and remains in place. Let γ=0.9. The values cannot be assigned independently: V(s₁) needs V(s₃), V(s₂) and V(s₃) need V(s₄), and V(s₄) depends on itself.', 'The Bellman equation is therefore a coupled system that all states must satisfy simultaneously. The self-loop gives V(s₄)=1+0.9V(s₄)=10; substituting that result yields V(s₂)=V(s₃)=10 and V(s₁)=9.'],
    formulas: [
      String.raw`\begin{aligned}V(s_1)&=0+0.9V(s_3),&V(s_2)&=1+0.9V(s_4),\\V(s_3)&=1+0.9V(s_4),&V(s_4)&=1+0.9V(s_4).\end{aligned}`,
      String.raw`\begin{bmatrix}V(s_1)\\V(s_2)\\V(s_3)\\V(s_4)\end{bmatrix}=\begin{bmatrix}0\\1\\1\\1\end{bmatrix}+0.9\begin{bmatrix}0&0&1&0\\0&0&0&1\\0&0&0&1\\0&0&0&1\end{bmatrix}\begin{bmatrix}V(s_1)\\V(s_2)\\V(s_3)\\V(s_4)\end{bmatrix}`,
    ],
    example: { title: 'Solve one shared set of unknowns', caption: 'Each row records one state’s immediate reward and successor value.', headers: ['State', 'One-step outcome', 'Bellman equation', 'Solution'], rows: [['s₁', '0 → s₃', 'V(s₁)=0+0.9V(s₃)', '9'], ['s₂', '+1 → s₄', 'V(s₂)=1+0.9V(s₄)', '10'], ['s₃', '+1 → s₄', 'V(s₃)=1+0.9V(s₄)', '10'], ['s₄', '+1 → s₄', 'V(s₄)=1+0.9V(s₄)', '10']] },
    handoff: 'Each matrix row stores one state equation. Extending four states to n states gives the general matrix form.',
  },
  {
    id: 'matrix-and-iteration', kicker: 'From system to solution', title: 'Direct solution and iteration target the same value',
    paragraphs: ['Continue with the four-state example above. Stack its four unknown values into vπ and its four expected immediate rewards into rπ. Entry (s,s′) of Pπ is the probability of moving from s to s′ under the fixed policy π. The equation vπ=rπ+γPπvπ therefore adds no new relation; it simply stacks the four Bellman equations row by row.', 'There are two ways to solve the system. A direct solve moves every term containing the unknown vπ to the left and then applies the inverse matrix. An iterative solve does not require both sides to agree immediately: it inserts the previous vector vk on the right to produce vk+1. The second chain below uses the same four-state numbers so the two computations can be compared line by line.'],
    formulas: [
      String.raw`\begin{aligned}\mathbf v^{\pi}&=\mathbf r^{\pi}+\gamma P^{\pi}\mathbf v^{\pi}\\\mathbf v^{\pi}-\gamma P^{\pi}\mathbf v^{\pi}&=\mathbf r^{\pi}\\(I-\gamma P^{\pi})\mathbf v^{\pi}&=\mathbf r^{\pi}\\\mathbf v^{\pi}&=(I-\gamma P^{\pi})^{-1}\mathbf r^{\pi}\end{aligned}`,
      String.raw`\begin{aligned}\mathbf v_0&=(0,\ 0,\ 0,\ 0)^{\mathsf T}\\\mathbf v_1=\mathcal T^{\pi}(\mathbf v_0)&=\mathbf r^{\pi}+0.9P^{\pi}\mathbf v_0=(0,\ 1,\ 1,\ 1)^{\mathsf T}\\\mathbf v_2=\mathcal T^{\pi}(\mathbf v_1)&=\mathbf r^{\pi}+0.9P^{\pi}\mathbf v_1=(0.9,\ 1.9,\ 1.9,\ 1.9)^{\mathsf T}\\&\ \vdots\\\mathbf v_k&\longrightarrow(9,\ 10,\ 10,\ 10)^{\mathsf T}=\mathbf v^{\pi}\end{aligned}`,
    ],
    formulaLabels: ['Direct solve: collect every unknown term on the left', 'Iterative solve: insert the previous estimate on the right'],
    formulaAfter: 'The direct method handles all states simultaneously. The second chain shows synchronous vector iteration: every state reads the same old vector vk before the new vector vk+1 is installed. The experiment splits the same Bellman relation into in-place state backups: each step writes one V(s), and later steps read estimates written earlier in the sweep. The intermediate numbers differ, but both update orders seek the same fixed point. Policy π remains fixed here: “iterative” means repeated evaluation, not the policy-iteration algorithm that changes the policy in a later chapter.',
    theorem: { claim: 'For 0≤γ<1 and row-stochastic Pπ, Tπ has one fixed point and iteration converges to it from any bounded start.', why: 'Pπ only probability-weights successor values and cannot enlarge the maximum error; multiplying by γ leaves at most a γ fraction each round.', conditions: [String.raw`0\le\gamma<1`, String.raw`\sum_{s'}P^{\pi}_{ss'}=1`] },
    pseudocodeTitle: 'Iterative policy evaluation by state backups', pseudocode: ['Initialize V(s) for the fixed policy π, for example to zero', 'Repeat one sweep:', '  Δ ← 0', '  For every state s, perform one backup:', '    old ← V(s)', '    V(s) ← Σₐπ(a|s)Σₛ′,ᵣp(s′,r|s,a)[r+γV(s′)]', '    Δ ← max(Δ, |old−V(s)|)', 'Until Δ is below tolerance; return Vπ'],
  },
  {
    id: 'state-to-action-value', kicker: 'Action value · Fixing the first action', title: 'Action value preserves first-action differences; state value averages by policy',
    paragraphs: ['Vπ(s) averages the first action under π. Qπ(s,a) instead fixes that first action and follows π afterward.', 'Weighting Qπ by π(a|s) recovers Vπ. Comparing Qπ(s,a) values at one state enables policy improvement.'],
    formulas: [String.raw`Q^{\pi}(s,a)=\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^{\pi}(s')\right]`, String.raw`V^{\pi}(s)=\sum_a\pi(a\mid s)Q^{\pi}(s,a)`],
    handoff: 'The next chapter lets actions compete and proves why selecting the largest action value produces the optimal equation.',
  },
]

export const bellmanChapter = assertChapterDefinition({
  id: 'bellman',
  prerequisiteIds: ['mdp', 'discounted-return', 'conditional-expectation'],
  termIds: ['return', 'stateValue', 'bellmanBackup', 'bootstrapping', 'continuingTask', 'policyEvaluation', 'actionValue'],
  sources,
  zh: {
    eyebrow: '第 3 章 · 状态价值与 Bellman 方程',
    title: 'Bellman 方程',
    intro: '上一章已经知道：一条实际轨迹给出一个 return，而状态价值概括同一起点的所有可能 return；但若逐条枚举未来，状态价值仍然无法计算。本章先把 return 与状态价值函数的定义放在同一条推导链上，再利用 return 的一步递推，把状态价值改写成一组可以联立或迭代求解的 Bellman 方程。',
    bridge: '下面继续使用同一个 5×5 网格环境：进入黄色禁区或尝试越界奖励 −1，进入蓝色目标奖励 +1，其余移动奖励 0；目标状态不会终止任务。点击状态、调整参数并执行一次更新，观察数值如何从同一套环境模型中产生。',
    experimentIntro: '下面回到 5×5 网格执行一次 Bellman backup。先选择状态，沿网格上的实线查看当前策略会经过的主分支轨迹，再逐项核对动作、所有可能后继、即时奖励和折扣后继价值，最后才写回新的状态价值。',
    interpretation: '网格轨迹把状态之间的依赖和可能出现的循环直接画了出来；一次 backup 只改写所选状态，连续播放则逐格遍历，并让后面的更新读取刚写入的最新估计。这样，奖励及其折扣后的影响会沿状态依赖逐步传播。底部曲线记录每次写回前所选状态的局部 Bellman 残差，它会随状态切换而波动；只有所有状态的残差都接近 0，整张价值表才接近方程组的解。',
    figure: '交互图 3.1 · 一次 Bellman backup 的显微镜',
    instruction: '选择起点查看策略轨迹，再观察一次 Bellman 更新怎样聚合下一步结果',
    exact: '已知模型 · 精确期望',
    summaryTitle: 'Bellman 方程把策略评价转化为方程求解',
    derivation: bellmanDerivationZh,
    deepening: bellmanDeepeningZh,
    microscope: {
      presetLabel: '现象快捷入口',
      presetPurpose: '这些按钮不是额外算法，只会一键设置下方的起点、参数与检查动作，方便复现实验现象；动作随机性请直接使用下方滑杆。',
      observationLabel: '入口做了什么',
      freeObservation: '当前已进入自由探索；你可以直接选择状态和调整下方参数，快捷入口只是帮你恢复一组便于观察的设置。',
      currentEstimate: '当前估计',
      matchedComparison: '同条件收敛对照',
      baselineLabel: '长视野基线 γ = 0.90',
      comparisonLabel: '短视野 γ = 0.50',
      courseReproduced: '基准数值复现',
      termByTerm: '逐项分解',
      presetAction: '预设动作',
      contributions: '期望中的各项贡献',
      contributionHint: '每列先算一个后继分支的一步目标，再乘该分支概率；所有列相加才是本次 Bellman 目标值。',
      ifApplied: '若执行',
      singleBackupNote: '单步只写回所选状态 V(s)，其余 24 个状态保持不变；当前所选状态为',
      localResidual: '本次局部 Bellman 残差',
      residualHint: '每个点是一次写回前的 |TπV(s)−V(s)|；切换状态时曲线可能上下波动。',
      residualTraceLabel: '最近 75 次单状态更新的局部 Bellman 残差轨迹',
      residualConvergence: '整表收敛要看所有状态残差的最大值是否接近 0；曲线保留最近 75 次更新。',
      policyPath: '当前策略轨迹',
      mostLikelyPath: '当前策略主分支',
      policyPathNote: '实线从所选状态出发，沿当前策略与确定性转移展开，直到首次回到已经经过的状态。',
      mostLikelyPathNote: '存在动作随机性时，实线只标出每一步概率最高的主分支；Bellman target 仍会对所有后继分支加权。',
      pseudocodeTitle: '与画布同步的伪代码',
      pseudocodeInstruction: '点击一行可定位对应变量',
      pseudocode: [
        { id: 'select', number: '1', label: '选择待评估状态 s' },
        { id: 'action', number: '2', label: '按照策略选择动作 a ← π(s)' },
        { id: 'target', number: '3', label: '计算 T ← Σ p(s′|s,a)[R + γV(s′)]' },
        { id: 'assign', number: '4', label: '写回 V(s) ← T' },
      ],
    },
    prelude: [
      {
        id: 'return-recursion',
        kicker: '递推起点 · Return 定义',
        title: '长期回报可以拆成即时奖励与下一时刻回报',
        paragraphs: ['从时间 t 开始，return Gₜ 定义为这条轨迹后续奖励的折扣和：下一步奖励 Rₜ₊₁ 不折扣，再往后的奖励依次多乘一个 γ。未来轨迹尚未发生时，Gₜ 是随机变量；一条轨迹实现以后，它才成为这次运行对应的具体数值。', '从折扣和中拿出第一项，括号里的剩余部分恰好是 Gₜ₊₁，因此 Gₜ=Rₜ₊₁+γGₜ₊₁。这只是对同一串奖励的代数重排，却把“全部未来”变成“当前一步加上一个同类型的剩余问题”。'],
        formulas: [
          String.raw`G_t=R_{t+1}+\gamma R_{t+2}+\gamma^2R_{t+3}+\cdots`,
          String.raw`G_t=R_{t+1}+\gamma\left(R_{t+2}+\gamma R_{t+3}+\cdots\right)`,
          String.raw`G_t=R_{t+1}+\gamma G_{t+1}`,
        ],
      },
      {
        id: 'conditional-expectation',
        kicker: '评价对象 · 状态价值函数',
        title: '状态价值函数用条件期望汇总同一起点的所有 Return',
        paragraphs: ['固定策略 π 与环境模型 p 后，状态价值函数 Vπ(s) 定义为：已知当前状态 Sₜ=s 时，随机 return Gₜ 的条件期望。它以状态 s 为输入；策略或环境改变时，同一状态对应的函数值也可能改变。', '把 return 的递推式代入这个定义，再按动作、奖励与后继状态分组，剩余 return 的条件期望正好是后继状态价值 Vπ(s′)。这一步才把一棵完整的未来轨迹树压缩成一步转移关系。'],
        formulas: [
          String.raw`V^{\pi}(s)\coloneqq\mathbb{E}_{\pi,p}[G_t\mid S_t=s]`,
          String.raw`V^{\pi}(s)=\mathbb{E}[R_{t+1}\mid S_t=s]+\gamma\mathbb{E}[G_{t+1}\mid S_t=s]`,
        ],
      },
    ],
    sections: [
      {
        id: 'target-anatomy',
        kicker: '更新目标 · 单步组成',
        title: '一次 Bellman 更新只依赖一步奖励与后继价值',
        paragraphs: ['即时奖励给出本步的直接回报；后继状态价值代表未来；γ 决定未来在今天的权重。按照刚才的定义，一次 Bellman backup 先把这两部分合成目标 T，再用 T 更新当前 V(s)。', '默认动作是确定的，因此一次 backup 只有一个后继分支。提高动作随机性后，目标必须对所有可能后继进行概率加权；画布下方的贡献带会把这些分支并排展开，所有加权贡献之和才是最终目标值 T。'],
        formula: String.raw`T=\mathbb{E}[R_{t+1}+\gamma V^{\pi}(S_{t+1})\mid S_t=s]`,
      },
      {
        id: 'bootstrapping',
        kicker: '自举机制 · 原地更新',
        title: '原地更新复用最新估计，使奖励影响逐步传播',
        paragraphs: ['单步按钮只更新当前选中的状态 s：先用此刻 value table 中的后继估计计算目标 TπV(s)，再用目标覆盖旧的 V(s)，其余 24 个状态保持不变。连续播放按固定顺序遍历 25 个状态；因为采用原地更新，后面的 backup 会读取前面刚写回的最新值。一次遍历称为一个 sweep。', '这种“用现有估计更新另一个估计”的机制称为 bootstrapping。若从全零开始，靠近奖励的位置通常先改变，之后其他状态读取这些新值，于是奖励及其折扣影响逐步传向更远的位置。传播是反复应用 Bellman 关系在网格上的结果，并不是额外添加的规则。', 'Bellman 残差衡量当前估计与该状态方程右侧还差多少。交互图记录写回前的绝对局部残差 |δB(s)|：它接近 0，只说明这个状态在当时的 value table 下几乎满足自己的方程。判断整张表是否收敛，需要检查所有状态残差的最大值；逐状态曲线会因更新对象不同而上下波动，不必单调下降。'],
        formula: String.raw`\delta_{\mathrm B}(s)=\left(\mathcal T^{\pi}V\right)(s)-V(s)`,
      },
      {
        id: 'matrix-form',
        kicker: '深入',
        title: '每个状态一条方程，合起来就是矩阵形式',
        paragraphs: ['把 25 个状态的 Bellman 方程按行排列，得到 vπ = rπ + γPπvπ。同步向量迭代在一轮中统一读取 vk，再得到 vk+1；当前画布则把一轮拆成 25 次原地 backup，后面的状态可以读取本轮已经更新的值。矩阵形式没有引入新假设，只是把相互依赖的状态方程放在一起。', '线性求解、同步迭代和逐状态原地迭代的中间过程不同，但都以同一组 Bellman 方程的不动点为目标。交互图采用逐状态方式，是为了让每次“读什么、写哪里、信息如何传播”都可以被看见。'],
        formula: String.raw`\mathbf{v}^{\pi}=\mathbf{r}^{\pi}+\gamma P^{\pi}\mathbf{v}^{\pi}`,
      },
      {
        id: 'continuing-boundary',
        kicker: '边界条件 · 持续型任务',
        title: '任务是否终止决定后继价值是否归零',
        paragraphs: ['这个网格世界是持续型任务：进入蓝色目标得到 +1 后仍会继续行动，所以目标附近价值可以接近 1/(1−γ)。尝试越界时位置不变，但即时奖励为 −1，因此“下一状态没变”和“什么都没发生”并不等价。', '这两个规则都会进入 Bellman target：目标格没有把后继价值置零，越界动作则形成带负奖励的 self-loop。忽略任一规则，得到的价值表都会偏离本章设定的环境。'],
      },
      {
        id: 'action-value-transfer',
        kicker: '章节衔接 · 动作比较',
        title: '动作价值使同一状态下的不同选择可以直接比较',
        paragraphs: ['Vπ(s) 平均了策略在状态 s 选择的所有动作。要决定哪个动作更好，需要固定第一个动作并计算 Qπ(s,a)。', 'Qπ 保留第一步动作差异，再从后继状态继续遵循 π。下一章让同一状态的动作价值直接竞争，由评价给定策略转向寻找最优策略。'],
        formula: String.raw`V^{\pi}(s)=\sum_a\pi(a\mid s)Q^{\pi}(s,a)`,
      },
    ],
    presets: [
      { id: 'target-propagation', title: '从目标邻格开始', observation: '把 value table 重置为全零，并选中紧邻目标的状态 (4, 2)。先执行一次单步更新，可以看到 +1 先写入这个状态；再连续播放，才能看到它的折扣影响逐步传向其他状态。' },
      { id: 'boundary-self-loop', title: '检查越界 −1', observation: '选中边界状态 (1, 1)，并暂时检查“向上”动作。动作越过边界后，下一状态仍是 (1, 1)，但即时奖励为 −1；因此这是带负奖励的自循环，并不是什么都没有发生。' },
      { id: 'discount-horizon', title: '对照 γ=0.90 / 0.50', observation: '锁定策略、环境和收敛条件，同时展示两张已经收敛的价值表。较小的 γ 更快削弱远期奖励，因此离目标越远，两张表的差异通常越明显；这是单独拖动 γ 滑杆看不到的并排对照。' },
    ],
    summary: [
      'Return Gₜ 是一条轨迹上的折扣奖励和；状态价值函数 Vπ(s) 是给定起点后的条件期望。',
      '每个状态都有一条 Bellman 方程，状态价值因此必须作为一组相互依赖的未知量求解。',
      '矩阵形式既给出直接线性解，也解释了迭代 policy evaluation 为什么反复应用同一个映射。',
      '不动点就是一次 Bellman 映射后保持不变的价值表；一次 backup 只是向它靠近的一小步。',
    ],
  },
  en: {
    eyebrow: 'Chapter 3 · State Value and the Bellman Equation',
    title: 'The Bellman Equation',
    intro: 'The previous chapter established that one realized trajectory yields one return while state value summarizes every possible return from the same start. That definition is still impractical if it requires enumerating futures. This chapter places the return and state-value definitions on one derivation chain, then uses one-step return recursion to obtain a coupled Bellman system that can be solved directly or iteratively.',
    bridge: 'The canvas continues with the same 5×5 grid environment: entering a yellow forbidden cell or attempting to cross the boundary yields −1, entering the blue target yields +1, and every other move yields 0. The target is non-terminal. Select a state, adjust parameters, and see the values emerge from the same model.',
    experimentIntro: 'Return to the 5×5 grid for one Bellman backup. Select a state, follow the solid line through the current policy’s primary path, inspect the action, every possible successor, immediate reward, and discounted successor value, and only then write back the new state value.',
    interpretation: 'The grid path exposes state dependencies and cycles. One backup writes only the selected state; continuous play traverses the grid and lets later updates read the latest estimates written earlier. Reward and its discounted influence therefore propagate through the dependency graph. The bottom trace records the selected state’s local Bellman residual before each write, so it can oscillate as the selected state changes. The whole table is near the solution only when every state residual is near zero.',
    figure: 'Interactive Figure 3.1 · Microscope for one Bellman backup',
    instruction: 'Select a start to inspect the policy path, then see how one Bellman update aggregates one-step outcomes',
    exact: 'Known model · exact expectation',
    summaryTitle: 'The Bellman equation turns policy evaluation into equation solving',
    derivation: bellmanDerivationEn,
    deepening: bellmanDeepeningEn,
    microscope: {
      presetLabel: 'Phenomenon shortcuts',
      presetPurpose: 'These are not additional algorithms. Each shortcut only sets the start, parameters, and inspected action below. Use the action-randomness slider directly when you want stochastic successors.',
      observationLabel: 'What it changed',
      freeObservation: 'You are exploring freely. Select states and adjust the controls directly; a shortcut merely restores a useful observation setup.',
      currentEstimate: 'current estimate',
      matchedComparison: 'matched converged comparison',
      baselineLabel: 'Long-horizon baseline γ = 0.90',
      comparisonLabel: 'Short horizon γ = 0.50',
      courseReproduced: 'Reference values reproduced',
      termByTerm: 'term by term',
      presetAction: 'preset action',
      contributions: 'Contributions to the expectation',
      contributionHint: 'Each column computes one branch target and weights it by that branch probability; their sum is the Bellman target.',
      ifApplied: 'if applied',
      singleBackupNote: 'A single step writes only the selected V(s); the other 24 states stay unchanged. The selected state is',
      localResidual: 'Current local Bellman residual',
      residualHint: 'Each point is |TπV(s)−V(s)| before one write; it may move up or down when the selected state changes.',
      residualTraceLabel: 'Local Bellman residuals over the latest 75 single-state updates',
      residualConvergence: 'Whole-table convergence requires the maximum residual over all states to approach 0. The trace keeps 75 updates.',
      policyPath: 'Current policy path',
      mostLikelyPath: 'Most-likely policy path',
      policyPathNote: 'The solid line starts at the selected state and follows deterministic policy transitions until it first revisits a state.',
      mostLikelyPathNote: 'With action randomness, the solid line shows only the highest-probability branch at each step; the Bellman target still weights every successor.',
      pseudocodeTitle: 'Pseudocode synchronized with the canvas',
      pseudocodeInstruction: 'Choose a line to locate its variables',
      pseudocode: [
        { id: 'select', number: '1', label: 'Select a state s to evaluate' },
        { id: 'action', number: '2', label: 'Choose action a ← π(s)' },
        { id: 'target', number: '3', label: 'Compute T ← Σ p(s′|s,a)[R + γV(s′)]' },
        { id: 'assign', number: '4', label: 'Write back V(s) ← T' },
      ],
    },
    prelude: [
      {
        id: 'return-recursion',
        kicker: 'Recursion starting point · Return definition',
        title: 'Long-term return decomposes into immediate reward and next-step return',
        paragraphs: ['From time t, return Gₜ is the discounted sum of the rewards that follow on one trajectory. The next reward Rₜ₊₁ is undiscounted, and each more distant reward receives one additional factor of γ. Before the future occurs, Gₜ is random; after one trajectory is realized, it becomes that run’s concrete return.', 'Taking the first term out of the sum leaves exactly Gₜ₊₁ in parentheses, so Gₜ=Rₜ₊₁+γGₜ₊₁. This is only an algebraic rearrangement, but it converts the whole future into the current step plus a remaining problem of the same kind.'],
        formulas: [
          String.raw`G_t=R_{t+1}+\gamma R_{t+2}+\gamma^2R_{t+3}+\cdots`,
          String.raw`G_t=R_{t+1}+\gamma\left(R_{t+2}+\gamma R_{t+3}+\cdots\right)`,
          String.raw`G_t=R_{t+1}+\gamma G_{t+1}`,
        ],
      },
      {
        id: 'conditional-expectation',
        kicker: 'Evaluation object · State-value function',
        title: 'The state-value function uses a conditional expectation to summarize every return from one start',
        paragraphs: ['Fix policy π and environment model p. The state-value function Vπ(s) is defined as the conditional expectation of random return Gₜ given Sₜ=s. Its input is state s; changing the policy or environment can change the function value at that same state.', 'Substitute return recursion into this definition and group by action, reward, and successor. The remaining return within each successor group has expectation Vπ(s′), which compresses an entire future trajectory tree into a one-step relation.'],
        formulas: [
          String.raw`V^{\pi}(s)\coloneqq\mathbb{E}_{\pi,p}[G_t\mid S_t=s]`,
          String.raw`V^{\pi}(s)=\mathbb{E}[R_{t+1}\mid S_t=s]+\gamma\mathbb{E}[G_{t+1}\mid S_t=s]`,
        ],
      },
    ],
    sections: [
      {
        id: 'target-anatomy',
        kicker: 'Update target · One-step components',
        title: 'A Bellman update depends only on one-step reward and successor value',
        paragraphs: ['The immediate reward is the direct return from this step; successor value represents the future; γ controls how much the future matters now. Under the definition above, one Bellman backup combines these terms into target T and then uses T to update the current V(s).', 'Actions are deterministic by default, so a backup has one successor branch. With action randomness, the target must probability-weight every possible successor. The contribution strip below the canvas places those branches side by side; their weighted sum is the final target.'],
        formula: String.raw`T=\mathbb{E}[R_{t+1}+\gamma V^{\pi}(S_{t+1})\mid S_t=s]`,
      },
      {
        id: 'bootstrapping',
        kicker: 'Bootstrapping · In-place updates',
        title: 'In-place updates reuse the latest estimates and propagate reward influence',
        paragraphs: ['The single-step button updates only the selected state s. It computes target TπV(s) from the successor estimates in the current value table, overwrites the old V(s), and leaves the other 24 states unchanged. Continuous play visits the 25 states in a fixed order. Because updates are in place, later backups read the latest values written earlier in the same sweep.', 'Using an existing estimate to update another estimate is bootstrapping. Starting from zeros, states near a reward usually change first; other states then read those new values, so the reward and its discounted influence move outward. Propagation is the visible consequence of repeatedly applying the Bellman relation, not an extra rule.', 'The Bellman residual measures the gap between the current estimate and that state equation’s right-hand side. The canvas records the absolute local residual |δB(s)| before each write. A value near zero only means that state nearly satisfies its equation under the table at that moment. Whole-table convergence requires the maximum residual over all states to be small; a state-by-state trace need not decrease monotonically.'],
        formula: String.raw`\delta_{\mathrm B}(s)=\left(\mathcal T^{\pi}V\right)(s)-V(s)`,
      },
      {
        id: 'matrix-form',
        kicker: 'Deep dive',
        title: 'One equation per state becomes a matrix equation',
        paragraphs: ['Stack the 25 Bellman equations to obtain vπ = rπ + γPπvπ. Synchronous vector iteration reads vk throughout a round before installing vk+1. The canvas instead splits a round into 25 in-place backups, so later states may read values already updated in that sweep. Matrix form adds no new assumption; it only collects the coupled equations.', 'Linear solving, synchronous iteration, and in-place state iteration have different intermediate states but seek the same Bellman fixed point. The canvas uses state-by-state updates so the reader can see what is read, where the result is written, and how information propagates.'],
        formula: String.raw`\mathbf{v}^{\pi}=\mathbf{r}^{\pi}+\gamma P^{\pi}\mathbf{v}^{\pi}`,
      },
      {
        id: 'continuing-boundary',
        kicker: 'Boundary conditions · Continuing task',
        title: 'Termination determines whether successor value becomes zero',
        paragraphs: ['This grid world is a continuing task. The agent keeps acting after receiving +1 on entering the blue target, so nearby values can approach 1/(1−γ). A boundary attempt leaves the state unchanged but yields −1: “same successor” does not mean “nothing happened.”', 'Both rules enter the Bellman target: the target cell does not zero future value, and a boundary action creates a negative-reward self-loop. Omitting either rule changes the value table.'],
      },
      {
        id: 'action-value-transfer',
        kicker: 'Chapter transition · Action comparison',
        title: 'Action value makes choices at the same state directly comparable',
        paragraphs: ['Vπ(s) averages over the actions selected by the policy in state s. To decide which action is better, fix the first action and evaluate Qπ(s,a).', 'Qπ preserves the first-action difference and follows π afterward. The next chapter lets these action values compete within a state, moving from evaluating a fixed policy to searching for an optimal one.'],
        formula: String.raw`V^{\pi}(s)=\sum_a\pi(a\mid s)Q^{\pi}(s,a)`,
      },
    ],
    presets: [
      { id: 'target-propagation', title: 'Start beside the target', observation: 'Reset the value table to zero and select state (4, 2), next to the target. One update writes +1 into that state; continued play is required to see its discounted influence propagate to other states.' },
      { id: 'boundary-self-loop', title: 'Inspect boundary −1', observation: 'Select boundary state (1, 1) and temporarily inspect an upward action. Crossing the boundary leaves the successor at (1, 1) but still yields −1, so this is a negative-reward self-loop rather than “nothing happened.”' },
      { id: 'discount-horizon', title: 'Compare γ=0.90 / 0.50', observation: 'Lock policy, environment, and convergence conditions and show two converged value tables together. The smaller γ suppresses distant rewards faster, so differences usually grow farther from the target; this side-by-side counterfactual is not available from one slider position alone.' },
    ],
    summary: [
      'Return Gₜ is a discounted reward sum on one trajectory; state-value function Vπ(s) is its conditional expectation from a given start.',
      'Every state has a Bellman equation, so state values form one coupled set of unknowns.',
      'Matrix form supplies both a direct linear solution and the repeated map used by iterative policy evaluation.',
      'A fixed point is simply a value table unchanged by one Bellman map; one backup is only one step toward it.',
    ],
  },
})

export const bellmanSources = sources
