import { assertFoundationChapterDefinition } from './schema.js'

export const optimalityPresetConfigs = {
  'operator-switch': { selected: { row: 2, col: 1 }, gamma: 0.9, noise: 0, forbiddenReward: -1, operator: 'policy' },
  'risk-taking': { selected: { row: 2, col: 1 }, gamma: 0.9, noise: 0, forbiddenReward: -1, operator: 'optimal' },
  'short-horizon': { selected: { row: 2, col: 1 }, gamma: 0.5, noise: 0, forbiddenReward: -1, operator: 'optimal' },
  'strong-penalty': { selected: { row: 2, col: 1 }, gamma: 0.9, noise: 0, forbiddenReward: -10, operator: 'optimal' },
}

const sources = [
  { id: 'action-improvement', label: 'L3 · Five action values and policy improvement', pages: 'PDF pp.6-10', href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning' },
  { id: 'boe-max', label: 'L3 · Bellman optimality equation and right-hand maximization', pages: 'PDF pp.14-23', href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning' },
  { id: 'optimal-policy', label: 'L3 · Fixed point, greedy optimal policy, and reward analysis', pages: 'PDF pp.25-45', href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning' },
]

const explorer = {
  zh: {
    policyMode: '写回固定策略结果',
    optimalMode: '写回最大动作结果',
    policyOperator: '固定策略算子 Tπ',
    optimalOperator: '最优算子 T*',
    sameSnapshot: '五个动作都从左侧同一张价值表计算',
    selectedState: '当前状态',
    fixedAction: '固定策略选择',
    greedyAction: '当前最大值',
    actionCompetition: '先算五个动作，再比较两种写回规则',
    target: '一步目标',
    gap: '两种写回结果之差',
    gamma: '折扣因子 γ',
    noise: '动作随机性',
    forbiddenReward: '禁区奖励',
    preset: '反事实预设',
    valueMap: '用于本轮计算的价值表',
    policyValue: '参考 Vπ',
    optimalValue: '参考 V*',
    policyGap: '长期价值差',
    chosen: '选择本轮写回规则',
    tied: '并列最大',
    courseWorld: '共享网格世界',
    clickState: '点击格子，比较该状态的五个动作',
    expectationFormula: '固定策略读取其指定动作',
    maxFormula: '最优算子读取五个动作中的最大值',
    solveNote: '两种结果使用完全相同的状态、价值表与环境参数；唯一差别是如何从动作目标中选出写回值。',
    protocolLabel: '建议先做',
    protocolText: '先保持“固定策略”写回一次：因为初始表就是 Vπ，数值应几乎不变；再切到“最大动作”写回，观察同一格为何会改变。',
    policyCandidate: '固定策略写回值',
    optimalCandidate: '最大动作写回值',
    targetDefinition: '先用当前价值表定义每个动作的一步目标',
    candidateGap: '可改进幅度',
    policyFixedPoint: '固定点校验',
    policyFixedPointResult: 'Vπ 已满足固定策略方程，所以这次写回几乎不改变数值。',
    changedResult: '本轮只改写选中状态；其他格仍保留原值，便于观察局部变化。',
    sameChoice: '这个状态下固定策略恰好也选中了最大动作。',
    differentChoice: '这个状态下固定策略没有选择当前最大动作。',
    applyPolicyBackup: '按固定策略写回',
    applyOptimalBackup: '按最大动作写回',
    undo: '撤销上次写回',
    resetSnapshot: '恢复参考 Vπ',
    before: '本轮变化',
    residual: '写回幅度',
    stepCount: '已写回次数',
    rewardUnit: 'reward',
    actionLabels: { up: '上', right: '右', down: '下', left: '左', stay: '停留' },
    presetItems: {
      'operator-switch': { title: '同表对照', note: '在固定策略明显不是最优的状态，对照两种写回结果。' },
      'risk-taking': { title: '基线会冒险', note: 'γ=0.9、禁区 −1 时，最优策略可能穿过禁区。' },
      'short-horizon': { title: '短视会绕开', note: 'γ=0.5 降低远期目标奖励的吸引力。' },
      'strong-penalty': { title: '重罚会绕开', note: '禁区惩罚改为 −10，最优动作发生改变。' },
    },
  },
  en: {
    policyMode: 'Write policy result',
    optimalMode: 'Write maximum result',
    policyOperator: 'Fixed-policy operator Tπ',
    optimalOperator: 'Optimality operator T*',
    sameSnapshot: 'All five actions are computed from the same value table on the left',
    selectedState: 'Selected state',
    fixedAction: 'Fixed-policy choice',
    greedyAction: 'Current maximum',
    actionCompetition: 'Compute five actions, then compare two write-back rules',
    target: 'One-step target',
    gap: 'Difference between write-back rules',
    gamma: 'Discount γ',
    noise: 'Action randomness',
    forbiddenReward: 'Forbidden reward',
    preset: 'Counterfactual presets',
    valueMap: 'Value table used for this update',
    policyValue: 'Reference Vπ',
    optimalValue: 'Reference V*',
    policyGap: 'Long-run value gap',
    chosen: 'Choose this update rule',
    tied: 'Tied maximum',
    courseWorld: 'Shared grid world',
    clickState: 'Click a cell to compare its five actions',
    expectationFormula: 'The fixed policy reads its prescribed action',
    maxFormula: 'The optimality operator reads the largest of five action targets',
    solveNote: 'Both results use the same state, value table, and environment parameters. Only the rule that selects the write-back value changes.',
    protocolLabel: 'Try this first',
    protocolText: 'Apply the fixed-policy result first: the initial table is Vπ, so almost nothing should change. Then switch to the maximum result and see why the same cell moves.',
    policyCandidate: 'Fixed-policy result',
    optimalCandidate: 'Maximum-action result',
    targetDefinition: 'First define every one-step action target from the current value table',
    candidateGap: 'Improvement available',
    policyFixedPoint: 'Fixed-point check',
    policyFixedPointResult: 'Vπ already satisfies its policy equation, so this write-back barely changes the value.',
    changedResult: 'Only the selected state was written this round; every other cell stays fixed so the local change remains visible.',
    sameChoice: 'At this state, the fixed policy already selects a maximizing action.',
    differentChoice: 'At this state, the fixed policy does not select the current maximizing action.',
    applyPolicyBackup: 'Write policy result',
    applyOptimalBackup: 'Write maximum result',
    undo: 'Undo last write',
    resetSnapshot: 'Restore reference Vπ',
    before: 'This update',
    residual: 'Write-back size',
    stepCount: 'Writes applied',
    rewardUnit: 'reward',
    actionLabels: { up: 'Up', right: 'Right', down: 'Down', left: 'Left', stay: 'Stay' },
    presetItems: {
      'operator-switch': { title: 'Same-table contrast', note: 'Compare both update rules where the fixed policy is visibly suboptimal.' },
      'risk-taking': { title: 'Baseline takes risks', note: 'With γ=0.9 and forbidden −1, the optimum may cross a forbidden cell.' },
      'short-horizon': { title: 'Short horizon detours', note: 'γ=0.5 weakens the attraction of distant target rewards.' },
      'strong-penalty': { title: 'Strong penalty detours', note: 'Changing the forbidden penalty to −10 changes the optimal action.' },
    },
  },
}

const optimalityDerivationZh = [
  { id: 'policy-action-value', rule: '先定义给定策略下的动作价值', latex: String.raw`Q^{\pi}(s,a)=\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^{\pi}(s')\right]`, short: 'Qπ(s,a) 固定第一步动作，再沿用策略 π。', detail: '从状态 s 先执行动作 a；环境给出奖励 r 和后继状态 s′。从 s′ 起不再自由选动作，而是继续遵循 π，因此余下回报由 Vπ(s′) 概括。Qπ 比较的是“第一步换成不同动作”会怎样。', assumptions: ['状态具有马尔可夫性', String.raw`0\le\gamma<1`], symbols: [[String.raw`Q^{\pi}(s,a)`, '先执行 a、随后遵循 π 的期望回报'], [String.raw`V^{\pi}(s')`, '从 s′ 起始终遵循 π 的期望回报']] },
  { id: 'state-from-action', rule: '再由动作价值还原状态价值', latex: String.raw`V^{\pi}(s)=\sum_a\pi(a\mid s)Q^{\pi}(s,a)`, short: 'Vπ(s) 是真正按策略行动时的总体期望。', detail: '策略 π 决定在 s 选择每个动作的概率，所以 Vπ(s) 对刚才得到的各个 Qπ(s,a) 做概率加权。Qπ 保留第一步动作的区别，Vπ 则把这个区别按策略混合起来。', assumptions: [String.raw`\pi(a\mid s)\ge0`, String.raw`\sum_a\pi(a\mid s)=1`], symbols: [[String.raw`\pi(a\mid s)`, '策略在状态 s 选择动作 a 的概率']] },
  { id: 'optimize-policy', rule: '用星号表示“在所有策略中取最好结果”', latex: String.raw`V^*(s)\coloneqq\max_\pi V^{\pi}(s),\qquad Q^*(s,a)\coloneqq\max_\pi Q^{\pi}(s,a)`, narrowLatex: String.raw`\begin{aligned}V^*(s)&\coloneqq\max_\pi V^{\pi}(s),\\Q^*(s,a)&\coloneqq\max_\pi Q^{\pi}(s,a).\end{aligned}`, short: '星号不是新的运算，只说明这个价值已经对策略取过最大值。', detail: 'V*(s) 是从 s 出发能够达到的最大长期回报。Q*(s,a) 先把第一步固定为 a，再让之后的每一步都按最好的方式行动。因而不同第一步动作可以在相同的“最优后续”条件下公平比较。', assumptions: ['有限状态与动作集合'], symbols: [[String.raw`V^*(s)`, '从 s 出发可达到的最大期望回报'], [String.raw`Q^*(s,a)`, '先做 a、之后始终最优时的期望回报']] },
  { id: 'convex-max', rule: '概率加权的最大值由最大动作达到', latex: String.raw`\max_\pi\sum_a\pi(a\mid s)Q^*(s,a)=\max_a Q^*(s,a)`, short: '随机混合不会超过其中最大的动作价值。', detail: '任何概率加权平均都不超过最大分量；把概率 1 放在任意最大动作上即可达到上界。因此至少存在一个确定性的贪心最优策略。', assumptions: [String.raw`\sum_a\pi(a\mid s)=1`], symbols: [[String.raw`\operatorname*{arg\,max}_a`, '所有达到最大值的动作集合']] },
  { id: 'expand-q-star', rule: '展开最优动作价值的一步递推', latex: String.raw`Q^*(s,a)=\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^*(s')\right]`, short: '固定第一步动作后，对环境可能响应取期望。', detail: '执行 a 后，环境产生奖励 r 与后继状态 s′；从 s′ 开始的余下决策已经包含在 V*(s′) 中。', assumptions: ['状态具有马尔可夫性', String.raw`0\le\gamma<1`], symbols: [[String.raw`p(s',r\mid s,a)`, '环境的后继与奖励分布']] },
  { id: 'optimality-equation', rule: '把动作价值代回，得到 Bellman 最优方程', latex: String.raw`\boxed{V^*(s)=\max_a\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^*(s')\right]}`, narrowLatex: String.raw`\boxed{\begin{aligned}V^*(s)&=\max_a\sum_{s',r}p(s',r\mid s,a)\\&\qquad\cdot\left[r+\gamma V^*(s')\right]\end{aligned}}`, short: '对每个动作算完一步长期回报后，取其中最大的一个。', detail: '等号右侧对动作 a 做两件事：先对环境可能产生的奖励与后继状态取期望，再比较所有动作。方程要求整张 V* 表与这些最大结果彼此一致；后文将说明它的解唯一。', assumptions: [String.raw`0\le\gamma<1`], symbols: [] },
]

const optimalityDerivationEn = [
  { id: 'policy-action-value', rule: 'Define action value under a given policy', latex: String.raw`Q^{\pi}(s,a)=\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^{\pi}(s')\right]`, short: 'Qπ(s,a) fixes the first action, then follows policy π.', detail: 'Start at s and take a. The environment produces reward r and successor s′. From s′ onward, actions are no longer free choices: they follow π, so Vπ(s′) summarizes the remaining return. Qπ lets us compare alternative first actions.', assumptions: ['The state is Markov', String.raw`0\le\gamma<1`], symbols: [[String.raw`Q^{\pi}(s,a)`, 'expected return after taking a and then following π'], [String.raw`V^{\pi}(s')`, 'expected return from s′ while following π']] },
  { id: 'state-from-action', rule: 'Recover state value from action values', latex: String.raw`V^{\pi}(s)=\sum_a\pi(a\mid s)Q^{\pi}(s,a)`, short: 'Vπ(s) is the overall expectation when the policy actually chooses the action.', detail: 'Policy π supplies the probability of each action at s, so Vπ(s) averages the corresponding Qπ(s,a) values. Qπ keeps first-action alternatives separate; Vπ mixes them according to the policy.', assumptions: [String.raw`\pi(a\mid s)\ge0`, String.raw`\sum_a\pi(a\mid s)=1`], symbols: [[String.raw`\pi(a\mid s)`, 'probability that the policy chooses a at s']] },
  { id: 'optimize-policy', rule: 'Use a star to mean “take the best result over all policies”', latex: String.raw`V^*(s)\coloneqq\max_\pi V^{\pi}(s),\qquad Q^*(s,a)\coloneqq\max_\pi Q^{\pi}(s,a)`, narrowLatex: String.raw`\begin{aligned}V^*(s)&\coloneqq\max_\pi V^{\pi}(s),\\Q^*(s,a)&\coloneqq\max_\pi Q^{\pi}(s,a).\end{aligned}`, short: 'The star is not a new operation; it says the value has already been maximized over policies.', detail: 'V*(s) is the largest long-run return attainable from s. Q*(s,a) fixes the first action to a and then makes every later decision optimally. Alternative first actions can therefore be compared under the same optimal continuation.', assumptions: ['Finite state and action sets'], symbols: [[String.raw`V^*(s)`, 'largest expected return attainable from s'], [String.raw`Q^*(s,a)`, 'expected return after taking a first and acting optimally thereafter']] },
  { id: 'convex-max', rule: 'A probability-weighted maximum is attained by a largest action', latex: String.raw`\max_\pi\sum_a\pi(a\mid s)Q^*(s,a)=\max_a Q^*(s,a)`, short: 'Random mixing cannot exceed the largest action value.', detail: 'Every probability-weighted average is at most its largest member. Assigning probability one to any maximizing action reaches that bound, so a deterministic greedy optimum exists.', assumptions: [String.raw`\sum_a\pi(a\mid s)=1`], symbols: [[String.raw`\operatorname*{arg\,max}_a`, 'set of maximizing actions']] },
  { id: 'expand-q-star', rule: 'Expand optimal action value by one step', latex: String.raw`Q^*(s,a)=\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^*(s')\right]`, short: 'Fix the first action and average the environment responses.', detail: 'After action a, the environment produces r and s′; all optimal decisions after s′ are summarized by V*(s′).', assumptions: ['The state is Markov', String.raw`0\le\gamma<1`], symbols: [[String.raw`p(s',r\mid s,a)`, 'successor-reward distribution']] },
  { id: 'optimality-equation', rule: 'Substitute action value to obtain the Bellman optimality equation', latex: String.raw`\boxed{V^*(s)=\max_a\sum_{s',r}p(s',r\mid s,a)\left[r+\gamma V^*(s')\right]}`, narrowLatex: String.raw`\boxed{\begin{aligned}V^*(s)&=\max_a\sum_{s',r}p(s',r\mid s,a)\\&\qquad\cdot\left[r+\gamma V^*(s')\right]\end{aligned}}`, short: 'Compute each action’s one-step long-run return, then retain the largest one.', detail: 'For every action a, the right-hand side first averages over possible rewards and successors, then compares all actions. The equation requires the whole V* table to agree with those maximum results; the next section establishes that its solution is unique.', assumptions: [String.raw`0\le\gamma<1`], symbols: [] },
]

const optimalityDeepeningZh = [
  {
    id: 'contraction-proof', kicker: '收敛依据', title: 'Bellman 最优更新会持续缩小价值误差',
    paragraphs: ['为了简写，把“用一张价值表 V 计算所有动作的一步回报，再在每个状态取最大值”这一整步记作 T*V。这里的 T* 只是 Bellman 最优方程右侧的简写；V*=T*V* 表示 V* 经过这一步计算后不再改变。', '最优方程含有 max，不能像固定策略那样直接写成线性矩阵逆。不过最大值之差不超过逐动作差的最大值，环境概率的加权平均也不会放大最大误差。因此对任意两张价值表 U、V，更新后的距离至多是原来的 γ 倍。'],
    formulas: [String.raw`|\max_a x_a-\max_a y_a|\le\max_a|x_a-y_a|`, String.raw`\|T^*U-T^*V\|_{\infty}\le\gamma\|U-V\|_{\infty}`],
    theorem: { claim: 'Bellman 最优算子在最大范数下是 γ-压缩映射。', why: 'max 只选择分量，环境概率只做凸组合；唯一可能放大或缩小未来差异的系数是 γ。', conditions: [String.raw`0\le\gamma<1`, String.raw`\sum_{s',r}p(s',r\mid s,a)=1`] },
    handoff: '压缩性同时给出三个结果：V* 存在、V* 唯一，并且从任意有界初值反复更新都能逼近它。',
  },
  {
    id: 'greedy-policy-proof', kicker: '从价值恢复动作规则', title: '知道 V* 后，逐状态选择最大动作即可得到最优策略',
    paragraphs: ['先把 V* 看成已经求得的一张表。在网格状态 s，对上、右、下、左和停留分别计算“当前奖励 + 折扣后的后继最优价值”。这个结果就是 Q*(s,a)：第一步先做 a，之后始终采用最好的动作。', '把同一状态的五个 Q*(s,a) 并排比较，选择其中最大的动作；对每个状态都重复这一步，就得到策略 π*。Bellman 最优方程已经保证 V*(s) 等于这些动作价值中的最大值，所以 π* 在每个状态都能实现 V*，不存在另一套策略还能给出更高价值。'],
    formulas: [String.raw`\pi^*(s)\in\operatorname*{arg\,max}_a Q^*(s,a)`],
    formulaLabels: ['逐状态的选择规则'],
    formulaAfter: 'arg max 返回的是“达到最大值的动作”，而不是最大数值本身。若几个动作并列最大，它们都可以被选入最优策略。',
    theorem: { claim: '只要每个状态都选择一个最大 Q* 动作，得到的整套策略就是最优策略。', why: 'Q* 的后继项已经把之后所有决策的最好结果算在内，因此这里的逐状态选择并不是短视选择。比较时需要覆盖该状态的全部可用动作；若有多个动作并列最大，任选其一都不会降低价值。', conditions: [] },
  },
  {
    id: 'reward-transformations', kicker: '反事实 · 奖励变化', title: '全局奖励变换不改排序，局部变化可能改变策略',
    paragraphs: ['奖励变化对策略有两类不同影响，区别在于它是否同样作用于环境中的每一次转移。如果所有奖励都乘同一个正数 c，并且每一步都再加同一个常数 b，那么每个动作的长期回报都会经历相同的缩放与平移。', '下面的 Q′* 表示变换后的最优动作价值。因为 c>0 不会颠倒大小关系，而 b/(1−γ) 对所有动作都是同一个增量，所以原来的动作排序保持不变。'],
    formulas: [String.raw`r'=cr+b\ (c>0)\quad\Longrightarrow\quad Q'^*(s,a)=cQ^*(s,a)+\frac{b}{1-\gamma}`],
    formulaLabels: ['全局统一变换'],
    formulaAfter: '只把禁区奖励从 −1 改成 −10 并不符合这个条件：只有经过禁区的动作受到额外影响，动作间的相对差异会改变。调整 γ 也不是奖励平移，它会重新分配近期与远期奖励的权重，因此同样可能改变最优动作。',
    example: { title: '四种参数变化对动作排序的影响', caption: '全局统一变换只改数值刻度；局部奖励或时间权重变化才会重新排列动作。', headers: ['变化', '是否同样作用于所有转移', '动作排序'], rows: [['全部奖励 ×2', '是：都乘 2', '保持'], ['每一步奖励都 +1', '是：都增加同一长期常数', '保持'], ['仅禁区 −1→−10', '否：只影响经过禁区的动作', '可能改变'], ['γ 从 0.9→0.5', '不是奖励变换：远期权重降低', '可能改变']] },
  },
]

const optimalityDeepeningEn = [
  {
    id: 'contraction-proof', kicker: 'Convergence argument', title: 'Bellman optimality updates continually shrink value error',
    paragraphs: ['For brevity, write T*V for the whole operation “compute every action’s one-step return from value table V, then keep the largest action at each state.” T* is only shorthand for the right-hand side of the Bellman optimality equation; V*=T*V* says that this operation no longer changes V*.', 'The max prevents the direct linear inverse used for fixed-policy evaluation. Still, the difference between two maxima cannot exceed the largest actionwise difference, and probability averaging cannot enlarge the maximum error. Thus updating two value tables U and V reduces their distance to at most γ times its previous size.'],
    formulas: [String.raw`|\max_a x_a-\max_a y_a|\le\max_a|x_a-y_a|`, String.raw`\|T^*U-T^*V\|_{\infty}\le\gamma\|U-V\|_{\infty}`],
    theorem: { claim: 'The Bellman optimality operator is a γ-contraction under the maximum norm.', why: 'Max selects components and environment probabilities form convex combinations; only γ scales future differences.', conditions: [String.raw`0\le\gamma<1`, String.raw`\sum_{s',r}p(s',r\mid s,a)=1`] },
    handoff: 'Contraction gives existence, uniqueness, and convergence of fixed-point iteration from any bounded start.',
  },
  {
    id: 'greedy-policy-proof', kicker: 'Recover an action rule from value', title: 'Once V* is known, choosing a largest action at each state gives an optimal policy',
    paragraphs: ['First regard V* as a completed table. At a grid state s, compute “current reward plus discounted optimal successor value” for Up, Right, Down, Left, and Stay. The result is Q*(s,a): take a first, then choose the best actions thereafter.', 'Compare the five Q*(s,a) values at the same state and select a largest one. Repeating this for every state defines policy π*. The Bellman optimality equation already says that V*(s) is the largest of these action values, so π* attains V* everywhere and no other policy can do better.'],
    formulas: [String.raw`\pi^*(s)\in\operatorname*{arg\,max}_a Q^*(s,a)`],
    formulaLabels: ['Statewise selection rule'],
    formulaAfter: 'arg max returns an action attaining the maximum, not the maximum number itself. If several actions tie, each may be used by an optimal policy.',
    theorem: { claim: 'Any policy that selects one maximizing Q* action at every state is optimal.', why: 'The successor term in Q* already includes the best decisions at every later state, so this statewise choice is not myopic. The comparison must cover every available action; if several actions tie for the maximum, choosing any one of them preserves the value.', conditions: [] },
  },
  {
    id: 'reward-transformations', kicker: 'Counterfactual · Reward changes', title: 'Global reward transforms preserve ranking; local changes may alter the policy',
    paragraphs: ['Reward changes affect a policy in two different ways, depending on whether they apply uniformly to every transition. If every reward is multiplied by the same positive c and the same b is then added at every step, every action’s long-run return receives the same scaling and shift.', 'Q′* below denotes optimal action value after the transformation. Positive c preserves order, and b/(1−γ) is the same increment for every action, so the original action ranking is unchanged.'],
    formulas: [String.raw`r'=cr+b\ (c>0)\quad\Longrightarrow\quad Q'^*(s,a)=cQ^*(s,a)+\frac{b}{1-\gamma}`],
    formulaLabels: ['Globally uniform transformation'],
    formulaAfter: 'Changing only the forbidden reward from −1 to −10 does not meet this condition: only actions whose futures cross a forbidden cell receive the extra penalty. Changing γ is not a reward shift either; it reweights near and distant rewards. Both can therefore change the maximizing action.',
    example: { title: 'How four parameter changes affect action ranking', caption: 'A global uniform transform changes the numeric scale; local rewards or time weights can reorder actions.', headers: ['Change', 'Uniform across transitions?', 'Action ranking'], rows: [['All rewards ×2', 'Yes: every reward is doubled', 'Preserved'], ['Every step reward +1', 'Yes: every action gets the same long-run shift', 'Preserved'], ['Forbidden −1→−10 only', 'No: only paths crossing forbidden cells change', 'May change'], ['γ from 0.9→0.5', 'Not a reward transform: distant rewards lose weight', 'May change']] },
  },
]

export const optimalityChapter = assertFoundationChapterDefinition({
  id: 'optimality',
  sources,
  zh: {
    prerequisite: '前置：状态价值、动作价值与 Bellman 期望方程',
    summaryTitle: '从准确评价一套策略，到判断它还能否改进',
    eyebrow: '第 4 章 · Bellman 最优方程与最优策略',
    title: '评价已经准确，为什么策略仍可能不是最好的',
    intro: '上一章已经能够求出给定策略 π 的价值 Vπ，它准确回答“始终照这套规则行动，长期回报是多少”。但准确评价不等于策略已经合理：即使 Vπ 完全满足 Bellman 期望方程，π 仍可能在某个状态坚持选择较差动作。本章要解决的是这个尚未回答的控制问题：如何比较同一状态的所有第一步动作，证明选择最大动作价值确实得到最优策略，并用 Bellman 最优方程同时刻画最优价值与最优动作。',
    bridge: '现在把“比较备选动作”写成完整的等式链。先区分给定策略下的 Qπ 与 Vπ，再把策略本身纳入最大化；随后证明概率加权不会超过最大动作价值，最后展开 Q* 的一步递推，得到 Bellman 最优方程。',
    experimentIntro: '实验始终先计算选中状态的五个一步动作目标，再并排给出固定策略结果与最大动作结果。这样，滑块只是用来做后续反事实；首要任务是看清“同一份证据，不同选择规则”如何产生不同更新。',
    interpretation: '固定策略写回几乎不改变 Vπ，说明策略评价已经收敛，却不能证明策略最优。若最大动作写回给出更高数值，它直接指出当前策略在该状态还有改进空间；若两者相同，只能说明这个状态的固定动作恰好已是最大动作。价值表最终收敛到 V* 后，逐状态选择最大动作即可恢复最优策略。',
    derivation: optimalityDerivationZh,
    deepening: optimalityDeepeningZh,
    figure: '交互图 4.1 · Optimality Switch',
    instruction: '从参考 Vπ 出发，对照固定策略写回与最大动作写回；每次只改一个格子',
    question: '为什么一张已经满足固定策略 Bellman 方程的价值表，仍然可能被最大动作写回继续提高？',
    prelude: [
      { id: 'evaluation-control', kicker: '策略评价的边界', title: '动作价值揭示固定策略的改进空间', paragraphs: ['固定策略 π 后，Vπ(s) 表示从状态 s 开始一直遵循 π 的期望回报。为了判断 π 在 s 选择的动作是否合理，还需要保留第一步动作 a 的区别：Qπ(s,a) 表示先执行 a，随后再遵循 π 的期望回报。', '因此可以先对每个动作计算 Qπ，再按策略概率得到 Vπ。确定性策略只给一个动作概率 1，于是 Vπ(s) 就等于它指定动作的 Qπ；其他动作的 Qπ 虽不参与当前价值，却提供了策略能否改进的直接证据。', '这解释了上一章留下的缺口：Bellman 期望方程能够把 π 评价得完全准确，但它只服从 π 的动作概率，不会主动改掉较差动作。下一节将把这两个量的关系写成正式公式，并继续推到最优性方程。'] },
      { id: 'max-reduction', kicker: '从评价转向控制', title: '新的问题不是再算一次 Vπ，而是找出所有策略都无法超过的价值', paragraphs: ['我们希望找到一套策略 π*，使它在每个状态的价值都不低于任何其他策略。为此，必须把原本固定的策略也纳入优化：对同一状态、同一后续价值，比较所有动作可能给出的长期回报。', '下面的推导会证明，策略概率只是对动作价值做加权平均，而任何加权平均都不超过最大动作价值。因此最优性方程中的最大化最终可以逐状态落到动作上；这不是定义出来的捷径，而是由概率权重的约束得到的结论。'] },
    ],
    sections: [
      { id: 'fixed-point-optimality', kicker: '存在、唯一与最优', title: 'Bellman 最优方程只有一个解，它就是 V*', paragraphs: ['当 0 < γ < 1 时，从任意有界初值反复使用 Bellman 最优更新都会收敛到同一张价值表。这个唯一解就是所有策略都无法超过的 V*。', '有了解的唯一性，下一步只需回答一个更具体的问题：怎样从 V* 的每个状态读出应当采取的动作。'], formula: String.raw`V^*(s)=\max_a Q^*(s,a)` },
      { id: 'reward-horizon', kicker: '策略为何改变', title: '禁区惩罚与 γ 会重新排列同一状态的动作价值', paragraphs: ['回到共享网格：在同一个状态 s，上、右、下、左和停留各有一个 Q*(s,a)。基准参数下，某个穿过禁区的动作虽然先承受 −1，却可能更快获得远期目标奖励，因此仍排在最前。', '每个 Q*(s,a) 都由两部分组成：这一步得到的奖励，以及由 γ 加权的后继最优价值。下面的条件期望只是把这两部分连在一起；竖线后的条件表示当前状态与第一步动作已经固定。', '只把禁区奖励改成 −10，会降低经过禁区的动作；把 γ 从 0.9 降到 0.5，会同时削弱所有远期奖励。两种变化的机制不同，但都可能改变五个动作的大小顺序。'], formula: { latex: String.raw`Q^*(s,a)=\mathbb{E}\!\left[R_{t+1}+\gamma V^*(S_{t+1})\mid S_t=s,A_t=a\right]`, narrowLatex: String.raw`\begin{aligned}Q^*(s,a)&=\mathbb{E}\!\left[R_{t+1}+\gamma V^*(S_{t+1})\right.\\&\qquad\left.\mid S_t=s,A_t=a\right]\end{aligned}` } },
      { id: 'ties-transfer', kicker: '边界与迁移', title: '最优策略可以不唯一，最优价值仍唯一', paragraphs: ['若多个动作拥有相同最大 q 值，它们都可进入最优策略；确定性选择只是其中一种实现。', '下一章将把 T* 反复作用于整张价值表，并比较 Value Iteration 与 Policy Iteration 怎样到达同一不动点。'], formula: String.raw`\left|\operatorname*{arg\,max}_a q^*(s,a)\right|>1` },
    ],
    summary: ['Vπ(s) 评价从状态 s 起始终遵循 π 的回报；Qπ(s,a) 固定第一步动作 a，因此能够暴露当前策略没有选择的备选动作。', '固定策略算子按 π 的动作概率汇总，最优算子则选择最大动作价值。概率加权平均不超过最大分量，所以至少存在一套确定性的贪心最优策略。', 'Bellman 最优算子的唯一不动点是 V*；对 V* 逐状态取最大动作即可恢复最优策略，但并列最大动作可能对应多套同样最优的策略。', '下一章将不再只做一次局部写回，而是把最优算子反复作用到整张价值表，比较价值迭代与策略迭代如何到达同一个 V*。'],
    explorer: explorer.zh,
  },
  en: {
    prerequisite: 'Prerequisites: state value, action value, and the Bellman expectation equation',
    summaryTitle: 'From evaluating one policy exactly to deciding whether it can improve',
    eyebrow: 'Chapter 4 · Bellman optimality equation and optimal policy',
    title: 'An exact evaluation can still describe a suboptimal policy',
    intro: 'The previous chapter showed how to compute Vπ for a given policy π. It answers exactly: “What long-run return results if we keep following this rule?” Exact evaluation, however, does not make the rule good. Even when Vπ perfectly satisfies the Bellman expectation equation, π may still insist on a worse action at some state. This chapter addresses that unresolved control problem: compare every possible first action, prove why choosing a largest action value yields an optimal policy, and use the Bellman optimality equation to characterize optimal values and actions together.',
    bridge: 'We can now turn “compare the alternative actions” into a complete equality chain. First separate Qπ from Vπ under a given policy, then place the policy itself inside the maximization. Next prove that probability weighting cannot exceed a largest action value, and finally expand the one-step recursion for Q* to obtain the Bellman optimality equation.',
    experimentIntro: 'The experiment always computes all five one-step action targets before showing the fixed-policy and maximum-action results side by side. The sliders support later counterfactuals; the first task is to see how the same evidence yields different updates under different selection rules.',
    interpretation: 'A policy write-back barely changes Vπ because policy evaluation has converged, but this does not prove the policy is optimal. A higher maximum-action result identifies immediate room for improvement at that state. Equal results only mean the fixed action already maximizes this local comparison. Once the whole value table converges to V*, choosing a maximizing action at every state recovers an optimal policy.',
    derivation: optimalityDerivationEn,
    deepening: optimalityDeepeningEn,
    figure: 'Interactive figure 4.1 · Optimality Switch',
    instruction: 'Start from reference Vπ and contrast a fixed-policy write-back with a maximum-action write-back; each step changes one cell',
    question: 'Why can a value table that already satisfies its fixed-policy Bellman equation still increase under a maximum-action write-back?',
    prelude: [
      { id: 'evaluation-control', kicker: 'The boundary of policy evaluation', title: 'Action value exposes room to improve a fixed policy', paragraphs: ['For a fixed policy π, Vπ(s) is the expected return from state s while following π throughout. To judge whether π chooses well at s, we must preserve the identity of the first action: Qπ(s,a) is the expected return after taking a first and then following π.', 'Compute Qπ for each action, then average those values with the policy probabilities to obtain Vπ. A deterministic policy assigns probability one to one action, so Vπ(s) equals the Qπ of its prescribed action. The other Qπ values do not affect the current policy value, but they reveal whether a better first action exists.', 'This is the gap left by the previous chapter. The Bellman expectation equation can evaluate π exactly, yet it obeys π’s action probabilities and never replaces a poor action on its own. The next section writes the relationship between these quantities formally and continues to the optimality equation.'] },
      { id: 'max-reduction', kicker: 'From evaluation to control', title: 'The new task is not another Vπ calculation, but a value no policy can exceed', paragraphs: ['We seek a policy π* whose value is at least as large as every other policy’s value in every state. The policy itself must therefore enter the optimization: at a fixed state and continuation-value table, compare the long-run return offered by every action.', 'The derivation below proves that policy probabilities only form a weighted average of action values, and no such average can exceed the largest member. The maximization in the optimality equation can therefore be reduced state by state to an action maximum; this is a consequence of probability constraints, not an assumed shortcut.'] },
    ],
    sections: [
      { id: 'fixed-point-optimality', kicker: 'Existence, uniqueness, optimality', title: 'The Bellman optimality equation has one solution: V*', paragraphs: ['For 0 < γ < 1, repeatedly applying the Bellman optimality update from any bounded initial table converges to the same value table. That unique solution is V*, which no policy can exceed.', 'With uniqueness established, the next question is concrete: how can the action at each state be read from V*?'], formula: String.raw`V^*(s)=\max_a Q^*(s,a)` },
      { id: 'reward-horizon', kicker: 'Why policies change', title: 'Forbidden penalties and γ can reorder the actions at one state', paragraphs: ['Return to the shared grid. At the same state s, Up, Right, Down, Left, and Stay each have a Q*(s,a). Under the baseline parameters, an action that crosses a forbidden cell may pay −1 first yet still rank highest because it reaches repeated target reward sooner.', 'Each Q*(s,a) has two parts: reward received now and optimal successor value weighted by γ. The conditional expectation below joins those parts; the terms after the vertical bar say that the current state and first action are fixed.', 'Changing only the forbidden reward to −10 lowers actions whose futures cross forbidden cells. Reducing γ from 0.9 to 0.5 instead weakens all distant rewards. The mechanisms differ, but either can change the ranking of the five actions.'], formula: { latex: String.raw`Q^*(s,a)=\mathbb{E}\!\left[R_{t+1}+\gamma V^*(S_{t+1})\mid S_t=s,A_t=a\right]`, narrowLatex: String.raw`\begin{aligned}Q^*(s,a)&=\mathbb{E}\!\left[R_{t+1}+\gamma V^*(S_{t+1})\right.\\&\qquad\left.\mid S_t=s,A_t=a\right]\end{aligned}` } },
      { id: 'ties-transfer', kicker: 'Boundary and transfer', title: 'Optimal policies may be non-unique even though optimal value is unique', paragraphs: ['If several actions share the largest q value, each can belong to an optimal policy. A deterministic choice is only one realization.', 'The next chapter repeatedly applies T* to the whole value table and compares how Value Iteration and Policy Iteration reach the same fixed point.'], formula: String.raw`\left|\operatorname*{arg\,max}_a q^*(s,a)\right|>1` },
    ],
    summary: ['Vπ(s) evaluates the return from following π throughout, whereas Qπ(s,a) fixes the first action a and therefore exposes alternatives the current policy does not choose.', 'The fixed-policy operator aggregates with π; the optimality operator selects a largest action value. A probability-weighted average cannot exceed its largest member, so at least one deterministic greedy optimal policy exists.', 'The Bellman optimality operator has the unique fixed point V*. Greedily choosing from V* recovers an optimal policy, although tied maximizing actions can produce several equally optimal policies.', 'The next chapter applies the optimality operator repeatedly to the full value table and compares how value iteration and policy iteration reach the same V*.'],
    explorer: explorer.en,
  },
})

Object.assign(optimalityChapter.en.deepening[2].example, { title: 'Policy preservation under reward transformations' })
