import {
  approximationDeepeningEn,
  approximationDeepeningZh,
  controlDeepeningEn,
  controlDeepeningZh,
  tdDeepeningEn,
  tdDeepeningZh,
} from './deepening-part23.js'
import {
  actorCriticDeepeningEn,
  actorCriticDeepeningZh,
  dqnDeepeningEn,
  dqnDeepeningZh,
  policyGradientDeepeningEn,
  policyGradientDeepeningZh,
  vfaDeepeningEn,
  vfaDeepeningZh,
} from './deepening-part3.js'

const book = 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning'

const source = (id, label, pages) => ({ id, label, pages, href: book })
const section = (id, kicker, title, paragraphs, formula) => ({ id, kicker, title, paragraphs, ...(formula ? { formula } : {}) })
const step = (id, rule, latex, short, detail, assumptions, symbols) => ({ id, rule, latex, short, detail, assumptions, symbols })

function chapter(id, sources, zh, en) {
  return { id, sources, zh, en }
}

export const monteCarloChapter = chapter('montecarlo', [source('mc', 'Monte Carlo Learning', 'L5, pp.5–47')], {
  prerequisite: '前置：Return、动作价值与策略迭代', eyebrow: '第 6 章 · 从模型转向经验', title: 'Monte Carlo 经验估计',
  intro: '已知模型时，策略迭代能够计算每个状态—动作对的期望回报并据此改善策略；模型未知后，这个精确评价步骤失去了转移概率，却仍然需要可比较的动作价值。本章从共享网格中真正发生的完整回合出发，推导 return 样本怎样替代模型期望，并检验评价、策略改善与探索怎样重新组成闭环。',
  bridge: '完整 episode 让 return 成为可观察的动作价值样本，样本平均则把随机经历汇总成估计。接下来的算法演化依次改变评价批量、轨迹复用方式和覆盖机制，但始终保留“用回合经验估计 Q，再让策略使用新 Q”的主线。', experimentIntro: '实验继续使用共享的 5×5 网格，只把目标格设为真正的终止状态。协议轨道会同步标出经验从哪里产生、哪些 return 能进入 Q，以及策略在什么边界提交；访问协议对照则固定同一条 episode，只改变重复访问的纳入规则。路径图、时间步 tape、反向 return、Q 更新和下一回合入口仍保持同步，达到步数上限的截断尝试只计数而不参与更新。',
  interpretation: 'MC Basic 冻结策略完成整批经验评价，定义清楚却等待久且浪费途中访问；Exploring Starts 逐回合复用整条轨迹，却要求能够控制起始状态—动作；ε-greedy 把覆盖写进行为策略，取消特殊起点，同时承担持续探索的代价。三种方法的差别既体现在用了哪些数据，也体现在何时提交策略以及下一回合使用哪一版策略。',
  figure: '交互图 06.1 · Monte Carlo 回合更新实验室', instruction: '沿协议轨道比较经验来源、证据纳入和策略提交，再用同一条回合对照首次访问与每次访问', question: '完整回合结束后，哪一部分经验进入更新，新策略又在什么时候开始影响数据？', experiment: { id: 'chapter-experiment' },
  reasoningPath: [
    section('batch-evaluation', 'MC Basic', '固定策略下的整批回合完成一次经验评价', ['样本均值要估计同一版本策略的动作价值，收集样本时就必须让当前策略保持不变。MC Basic 因而为每个状态—动作对分别收集回合，只使用指定起始对的 return；等整张动作价值表完成后，才统一产生下一版策略。', '这个协议忠实保留了策略迭代的外层边界，却必须等待全部状态—动作对完成评价，而且一条回合途中经过的其他访问不会进入估计。'], String.raw`\pi_k\xrightarrow{\text{fixed-policy episodes}}\widehat q_k\xrightarrow{\text{one improvement}}\pi_{k+1}`),
    section('episode-gpi', '更新时机', '逐回合交替让新策略更早影响后续数据', ['一条完整回合的 return 虽然噪声较大，仍然能为被访问的状态—动作对提供一次修正。把这次修正立即写入 Q，再改善访问状态上的策略，下一条回合就会使用刚提交的新策略；这种评价与改善不断交替的组织方式称为广义策略迭代（Generalized Policy Iteration）。', '此时历史 return 来自逐渐变化的策略，不能再把整个训练过程简单看成固定策略下的一组独立同分布样本。算法能否持续修正早期误差，取决于状态—动作覆盖、策略变化速度以及每个估计是否继续获得新样本。'], String.raw`\mathrm{episode}_k\longrightarrow Q^{+}\longrightarrow\pi^{+}\longrightarrow\mathrm{episode}_{k+1}`),
    section('coverage-feedback', '数据与探索', '复用轨迹提高效率，也把覆盖变成闭环条件', ['逐回合更新使整条轨迹都可以成为证据。first-visit 对同一状态—动作对每回合最多更新一次，every-visit 则保留全部出现；两者改变的是回合内部的计权，而不是 return 的定义。', '复用数据仍不能保证未见动作获得样本。Exploring Starts 通过随机起始对提供覆盖，ε-greedy 则让行为策略在普通起点下持续给所有动作正概率；后一种方法取消了控制起点的要求，却会在执行时持续选择部分非贪心动作。']),
  ],
  algorithms: [
    { id: 'basic', label: 'MC Basic', premise: '直接把 model-based policy iteration 的策略评价换成 episode 平均。', solves: '不需要环境模型即可估计 q^π。', limitation: '每次只使用指定起始 (s,a) 的 return，途中访问全部被浪费；还要求为每个 (s,a) 收集足够多的专门 episode。', pseudocode: ['初始化策略 π₀', '对每轮 k：', '  对每个状态 s 与动作 a：', '    收集大量从 (s,a) 出发并遵循 πₖ 的 episode', '    qₖ(s,a) ← 这些 episode return 的平均', '  对每个状态 s：', '    a* ← arg maxₐ qₖ(s,a)', '    πₖ₊₁(a*|s) ← 1，其余动作概率置 0'] },
    { id: 'exploring', label: 'MC Exploring Starts', premise: '一条 episode 途中会访问许多状态—动作对；把这些访问全部变成训练证据。', solves: 'first-visit 或 every-visit 更新显著提高数据利用率；随机起始对保证所有 (s,a) 有机会被采样。', limitation: '需要人为选择任意起始状态—动作。在真实系统中，这个 exploring-starts 假设往往不可实现。', pseudocode: ['初始化 π、Q、Returns(s,a) 与 N(s,a)', '对每条 episode：', '  随机选择可覆盖任意 (s₀,a₀) 的起始对', '  遵循当前策略生成完整 episode', '  G ← 0', '  从 T−1 到 0 反向扫描：', '    G ← γG + Rₜ₊₁', '    若满足访问协议：更新 Returns、N 与 Q=Returns/N', '  对本条 episode 访问到的状态做贪心策略改善'] },
    { id: 'epsilon', label: 'MC ε-Greedy', premise: '不再要求特殊起点，而让行为策略本身持续给所有动作正概率。', solves: '足够长的采样过程可以从普通起点访问不同状态—动作对，移除 exploring-starts 假设。', limitation: 'ε>0 意味着策略会持续选择非贪心动作；它优化的是 ε-soft 策略集合，而非全部确定性策略。', pseudocode: ['初始化 ε-soft 策略 π、Q、Returns(s,a) 与 N(s,a)', '对每条 episode：', '  从普通起点按 π 生成完整 episode', '  G ← 0', '  从 T−1 到 0 反向扫描：', '    G ← γG + Rₜ₊₁', '    若满足访问协议：更新 Returns、N 与 Q=Returns/N', '  对访问到的每个状态：', '    a* ← arg maxₐ Q(s,a)', '    π(a*|s) ← 1−ε+ε/|A|', '    π(a|s) ← ε/|A|, a≠a*'] },
  ],
  derivation: [
    step('value-definition', '从动作价值的定义开始', String.raw`q^{\pi}(s,a)=\mathbb E_{\pi}[G_t\mid S_t=s,A_t=a]`, '动作价值是从指定状态和动作出发的 return 条件期望。', '策略决定后续动作，环境决定后续转移；未知模型使这个期望无法直接求和，但定义本身没有改变。', ['episode 最终结束或 return 有界'], [[String.raw`G_t`, '一条 episode 中从时刻 t 开始的 return']]),
    step('episode-sample', '用完整 episode 产生样本', String.raw`G_t^{(i)}=\sum_{k=0}^{T_i-t-1}\gamma^kR_{t+k+1}^{(i)}`, '第 i 条 episode 为被访问的状态—动作对提供一个 return 样本。', '必须等待终点，才能知道该时刻之后的全部奖励。这里的 T_i 是该条 episode 的结束时刻。', ['episode i 确实访问了 (s,a)'], [[String.raw`T_i`, '第 i 条 episode 的终止时刻']]),
    step('sample-average', '用大数定律替代未知期望', String.raw`\widehat q_N(s,a)=\frac{1}{N(s,a)}\sum_{i=1}^{N(s,a)}G_t^{(i)}`, '对同一状态—动作对的 return 样本取平均。', '在访问样本满足适当独立性且覆盖持续增加时，样本均值逼近动作价值。N(s,a) 只统计协议选中的访问。', ['每个需要估计的 (s,a) 被反复访问'], [[String.raw`N(s,a)`, '被纳入估计的访问次数']]),
    step('incremental-mean', '把批量平均改写成增量更新', String.raw`\widehat q_N=\widehat q_{N-1}+\frac{1}{N}\left(G_N-\widehat q_{N-1}\right)`, '无需保存全部历史 return，只保存计数与当前估计。', '新样本与旧估计之差是估计误差；步长 1/N 恰好让递推结果等于算术平均。', ['N 从 1 递增'], [[String.raw`G_N-\widehat q_{N-1}`, '第 N 个样本产生的估计误差']]),
    step('policy-improvement', '把经验评价接回策略迭代', String.raw`\begin{aligned}a^*(s)&\in\arg\max_a \widehat q_k(s,a),\\ \pi_{k+1}(a\mid s)&=\mathbf 1[a=a^*(s)].\end{aligned}`, '当前估计最高的动作成为下一轮策略的选择。', 'MC 只替换策略评价的数据来源；策略改善仍使用动作价值排序。问题是确定性贪心会让其他动作失去后续样本。', ['每个状态至少有一个可比较的动作估计'], [[String.raw`a^*(s)`, '当前贪心动作']]),
    step('epsilon-greedy', '用软策略保证探索', String.raw`\begin{aligned}a^*(s)&\in\arg\max_b q(s,b),\\ \pi(a\mid s)&=\begin{cases}1-\epsilon+\epsilon/|\mathcal A|,&a=a^*(s),\\ \epsilon/|\mathcal A|,&a\ne a^*(s).\end{cases}\end{aligned}`, '大部分时间利用当前最好动作，同时保留访问其他动作的正概率。', '纯贪心策略可能永远看不到早期估计较低的动作。ε-greedy 通过持续探索为后续控制算法提供覆盖。', [String.raw`0<\epsilon\le 1`], [[String.raw`\epsilon`, '用于探索的概率质量']]),
  ],
  prelude: [section('model-to-data', '评价障碍', '模型未知使动作价值无法直接求和', ['在共享网格中，已知模型的策略评价可以枚举一个动作之后的全部奖励和后继状态，再按转移概率计算条件期望。现实交互只揭示真正发生的一条分支，因此算法不能再直接求出 q^π，却仍然必须比较同一状态中的不同动作。', '动作价值的定义没有改变，改变的是获得期望的方式：让同一状态—动作对反复出现在经验中，把每次随机未来产生的 return 当作样本，再用样本平均逼近原先由模型给出的期望。']), section('episode-unit', '样本条件', '完整 return 只能在回合终止后确定', ['Episode（回合）是从起点持续到终止状态的一段完整交互序列。Monte Carlo 不使用当前价值估计补全尚未发生的未来，因此只有回合结束后，某次访问之后的全部奖励才已知，对应的 return 才能计算。', '这种 target 完全由真实后续奖励组成，不包含 bootstrap 尾项；代价是必须等待终点，随机轨迹的全部波动都会进入 return，而且没有自然终点的持续型任务不能直接套用普通回合式 MC。'])],
  sections: [section('visit-protocol', '数据复用', '访问协议决定一条 episode 贡献多少证据', ['MC Basic 只使用指定起始对，相当于最严格的 initial-visit。first-visit 让每条 episode 对同一状态—动作对至多贡献一次，every-visit 则保留轨迹中的全部出现。', '三者估计同一个条件期望，却给同一条轨迹内部的相关访问不同权重。数据利用率提高时，样本相关性也会增强，因此不能把这些名称当作无关的实现选项。'], String.raw`N_{\mathrm{initial}}(s,a)\le N_{\mathrm{first}}(s,a)\le N_{\mathrm{every}}(s,a)`), section('coverage', '探索前提', '可靠的贪心改善依赖持续覆盖', ['如果某个动作从未被访问，它的 Q 值就只是初值；纯贪心策略可能把一次偶然低估永久固化，并停止收集能够纠正它的证据。', 'Exploring Starts 在 episode 起点保证每个状态—动作对有机会出现，ε-soft 策略则在整个行为过程中保持正概率。后者取消了控制起点的假设，却必须持续承担探索成本。'], String.raw`\pi(a\mid s)>0\quad\forall(s,a)`), section('optimality', '能力边界', 'ε-greedy 用执行效率换取覆盖', ['更大的 ε 提高发现替代动作的机会，却让策略更频繁执行当前看来较差的动作；固定 ε 时，算法优化的是 ε-soft 策略集合中的最佳行为。', '若要逐渐逼近确定性贪心最优，ε 需要随训练减小，同时又不能过快归零，否则早期误差仍可能失去纠正机会。这正是“趋于贪心且保持充分探索”的双重要求。'], String.raw`\epsilon_k\to 0,\qquad \sum_k\epsilon_k=\infty`), section('consistency', '一致性问题', '最优 ε-greedy 策略不一定与全局最优贪心策略一致', ['软策略改变了未来状态分布：即使当前状态选择同一个贪心动作，后续仍可能随机进入禁区或离开目标。因此它评价和优化的是另一套受探索约束的长期行为。', '这解释了为什么探索不是算法外的“小技巧”，而是目标集合与数据分布的一部分。']), section('forward', '下一步', '增量均值揭示了更一般的误差修正形式', ['步长 1/N 让所有历史 return 等权，恰好复现算术平均，适合目标固定且希望渐近消除噪声的情形。', '策略持续变化或环境非平稳时，旧样本不应永远保持同样权重。下一章将保留“旧估计加误差修正”的结构，并用 Robbins–Monro 条件讨论更一般的步长。'])],
  summary: ['MC 保留价值定义，只把模型期望替换为完整 episode 的 return 样本。', 'MC Basic、Exploring Starts 与 ε-greedy 是一条由数据效率和覆盖假设推动的演化链。', 'first-visit 与 every-visit 决定同一 episode 内的证据怎样计权。', 'ε-soft 策略用持续探索换取覆盖，也因此改变可达到的最优策略集合。', '只有同时检查估计、覆盖、策略改善与假设，才真正理解 MC 控制。'], explorer: { cue: '切换算法时沿三道协议门阅读；切换访问规则时比较同一条 tape 中重复时间步的“跳过/再次纳入”。' },
}, {
  prerequisite: 'Prerequisites: return, action value, and policy iteration', eyebrow: 'Chapter 6 · From models to experience', title: 'Monte Carlo Learning',
  intro: 'With a known model, policy iteration can evaluate every state-action pair and improve the policy from those expectations. Once the transition model is unavailable, exact evaluation loses its input while control still needs comparable action values. This chapter derives how complete episodes replace model expectations with return samples, then tests how evaluation, policy improvement, and exploration reconnect.',
  bridge: 'A complete episode makes a return observable, and sample averaging turns random experience into an estimate. The algorithm family changes evaluation batch size, trajectory reuse, and coverage while preserving one spine: estimate Q from episodes, commit a policy, and let later episodes use it.', experimentIntro: 'The lab keeps the shared 5×5 grid and makes the goal a true terminal state. A protocol track identifies where experience comes from, which returns may enter Q, and the boundary that commits a policy. The visit comparison holds one episode fixed and changes only how repeated visits are admitted. The path, timestep tape, backward returns, Q updates, and next-episode input remain synchronized; step-limit truncations are counted but excluded from updates.',
  interpretation: 'MC Basic freezes the policy for a full empirical evaluation, which is clear but slow and discards intermediate visits. Exploring Starts reuses complete trajectories episode by episode but assumes control over the initial pair. ε-greedy moves coverage into behavior, removes the special-start interface, and pays for persistent exploration. The methods differ both in which evidence they use and in when a committed policy begins generating new data.',
  figure: 'Interactive Figure 06.1 · Monte Carlo Episode Update Lab', instruction: 'Compare experience source, evidence admission, and policy commit on the protocol track, then contrast first-visit and every-visit on one fixed episode', question: 'After an episode terminates, which evidence enters the update and when does the new policy begin changing data?', experiment: { id: 'chapter-experiment' },
  reasoningPath: [
    section('batch-evaluation', 'MC Basic', 'A fixed-policy episode batch completes one empirical evaluation', ['A sample mean targets the action value of one policy version, so that policy must remain fixed while its samples are collected. MC Basic therefore gathers dedicated episodes for every state-action pair, uses only the requested starting pair, and creates the next policy only after the full action-value table is ready.', 'This protocol preserves policy iteration’s outer boundary, but it waits for every pair to be evaluated and discards the other visits that occur along each episode.'], String.raw`\pi_k\xrightarrow{\text{fixed-policy episodes}}\widehat q_k\xrightarrow{\text{one improvement}}\pi_{k+1}`),
    section('episode-gpi', 'Update timing', 'Episode-by-episode alternation lets a new policy affect data earlier', ['One complete-episode return is noisy, but it can still correct the estimate of a visited pair. Committing that correction to Q and improving the policy immediately means the next episode uses the newly committed policy. This continuing alternation of evaluation and improvement is Generalized Policy Iteration.', 'Historical returns now come from a changing sequence of policies, so the entire run is no longer a simple iid sample set for one fixed policy. Repairing early errors depends on continued state-action coverage, the rate of policy change, and whether every estimate keeps receiving evidence.'], String.raw`\mathrm{episode}_k\longrightarrow Q^{+}\longrightarrow\pi^{+}\longrightarrow\mathrm{episode}_{k+1}`),
    section('coverage-feedback', 'Data and exploration', 'Trajectory reuse raises efficiency and makes coverage a loop condition', ['Episode-by-episode updates can reuse the complete trajectory. First-visit contributes at most one update per state-action pair in an episode, while every-visit retains every occurrence. The protocol changes within-episode weighting, not the definition of return.', 'Reuse alone cannot give an unseen action evidence. Exploring Starts obtains coverage through randomized starting pairs; ε-greedy keeps every action at positive probability from ordinary starts. The latter removes start control but continues to execute some non-greedy actions.']),
  ],
  algorithms: [
    { id: 'basic', label: 'MC Basic', premise: 'Replace model-based evaluation with episode averages for each requested pair.', solves: 'Estimate q^π without an environment model.', limitation: 'Intermediate visits are discarded, and every pair needs dedicated starting episodes.', pseudocode: ['Initialize policy π₀', 'For iteration k:', '  For every state s and action a:', '    Collect many episodes starting from (s,a) under πₖ', '    qₖ(s,a) ← average return of those episodes', '  For every state s:', '    a* ← arg maxₐ qₖ(s,a)', '    Set πₖ₊₁(a*|s)=1 and all other probabilities to 0'] },
    { id: 'exploring', label: 'MC Exploring Starts', premise: 'Reuse every state-action visit along an episode.', solves: 'First-visit or every-visit updates improve data use; randomized starting pairs guarantee possible coverage.', limitation: 'The environment must allow arbitrary starting state-action pairs.', pseudocode: ['Initialize π, Q, Returns(s,a), and N(s,a)', 'For each episode:', '  Select a starting pair (s₀,a₀) so every pair is possible', '  Generate a complete episode under the current policy', '  G ← 0', '  Scan backward from T−1 to 0:', '    G ← γG + Rₜ₊₁', '    If allowed by the visit protocol, update Returns, N, and Q=Returns/N', '  Greedily improve the policy at visited states'] },
    { id: 'epsilon', label: 'MC ε-Greedy', premise: 'Keep every action at positive probability instead of requiring special starts.', solves: 'Long ordinary rollouts can cover pairs without an exploring-starts interface.', limitation: 'Persistent ε explores forever and optimizes inside the ε-soft policy class.', pseudocode: ['Initialize ε-soft π, Q, Returns(s,a), and N(s,a)', 'For each episode:', '  Generate a complete episode from an ordinary start under π', '  G ← 0', '  Scan backward from T−1 to 0:', '    G ← γG + Rₜ₊₁', '    If allowed by the visit protocol, update Returns, N, and Q=Returns/N', '  For every visited state:', '    a* ← arg maxₐ Q(s,a)', '    π(a*|s) ← 1−ε+ε/|A|', '    π(a|s) ← ε/|A| for a≠a*'] },
  ],
  derivation: [
    step('value-definition', 'Start from action value', String.raw`q^{\pi}(s,a)=\mathbb E_{\pi}[G_t\mid S_t=s,A_t=a]`, 'Action value is the conditional mean return after a specified state and action.', 'The policy selects later actions and the environment produces later transitions. An unknown model blocks direct summation, not the definition.', ['episodes terminate or returns are bounded'], [[String.raw`G_t`, 'return from time t in one episode']]),
    step('episode-sample', 'Generate a sample with a complete episode', String.raw`G_t^{(i)}=\sum_{k=0}^{T_i-t-1}\gamma^kR_{t+k+1}^{(i)}`, 'Episode i supplies one return sample for a visited pair.', 'The full target is known only after the episode ends. T_i is the terminal time of episode i.', ['episode i visits (s,a)'], [[String.raw`T_i`, 'terminal time of episode i']]),
    step('sample-average', 'Replace expectation by a sample mean', String.raw`\widehat q_N(s,a)=\frac{1}{N(s,a)}\sum_{i=1}^{N(s,a)}G_t^{(i)}`, 'Average return samples for the same state-action pair.', 'With continuing coverage and suitable sampling, the empirical average approaches action value.', ['each required pair is revisited'], [[String.raw`N(s,a)`, 'included visit count']]),
    step('incremental-mean', 'Rewrite the batch mean incrementally', String.raw`\widehat q_N=\widehat q_{N-1}+\frac{1}{N}\left(G_N-\widehat q_{N-1}\right)`, 'Keep only the count and current estimate.', 'The new-sample error corrects the old estimate; step size 1/N exactly reproduces the arithmetic mean.', ['N increases from 1'], [[String.raw`G_N-\widehat q_{N-1}`, 'sample estimation error']]),
    step('policy-improvement', 'Reconnect experience to policy iteration', String.raw`\begin{aligned}a^*(s)&\in\arg\max_a \widehat q_k(s,a),\\ \pi_{k+1}(a\mid s)&=\mathbf 1[a=a^*(s)].\end{aligned}`, 'The largest current estimate defines the next greedy policy.', 'MC replaces policy-evaluation evidence; policy improvement still ranks actions. Deterministic greed can remove future samples for alternatives.', ['at least one comparable action estimate per state'], [[String.raw`a^*(s)`, 'current greedy action']]),
    step('epsilon-greedy', 'Maintain coverage with a soft policy', String.raw`\begin{aligned}a^*(s)&\in\arg\max_b q(s,b),\\ \pi(a\mid s)&=\begin{cases}1-\epsilon+\epsilon/|\mathcal A|,&a=a^*(s),\\ \epsilon/|\mathcal A|,&a\ne a^*(s).\end{cases}\end{aligned}`, 'Exploit the current best action while preserving positive probability for alternatives.', 'A purely greedy policy may never repair an unlucky early estimate. ε-greedy keeps exploration alive.', [String.raw`0<\epsilon\le 1`], [[String.raw`\epsilon`, 'probability mass reserved for exploration']]),
  ],
  prelude: [section('model-to-data', 'Evaluation barrier', 'An unknown model blocks direct action-value summation', ['In the shared grid, model-based policy evaluation can enumerate every reward and successor after an action and weight them by transition probability. Real interaction reveals only the branch that occurred, so the algorithm can no longer calculate action value directly even though it still has to compare actions within each state.', 'The action-value definition remains unchanged. What changes is the route to its expectation: revisit the same state-action pair, treat the return from each random future as a sample, and average those samples in place of a model-based sum.']), section('episode-unit', 'Sample availability', 'A complete return is known only after termination', ['An episode is the complete interaction sequence from a start to a terminal state. Monte Carlo does not fill an unseen future with a current value estimate, so the rewards following a visit—and therefore its return—become available only after the episode ends.', 'The target contains only realized future rewards and no bootstrapped tail. In exchange, learning waits for termination, absorbs the full trajectory’s variance, and does not directly apply to continuing tasks without a natural endpoint.'])],
  sections: [section('visit-protocol', 'Data reuse', 'A visit protocol determines how much evidence one episode contributes', ['MC Basic uses only a requested starting pair. First-visit lets one episode contribute once for a pair, while every-visit retains every occurrence along the trajectory.', 'All three estimate the same conditional expectation but weight correlated visits within one episode differently. Higher data reuse therefore changes dependence as well as sample count.'], String.raw`N_{\mathrm{initial}}(s,a)\le N_{\mathrm{first}}(s,a)\le N_{\mathrm{every}}(s,a)`), section('coverage', 'Exploration premise', 'Reliable greedy improvement requires continuing coverage', ['An unvisited action retains only its initialization. A greedy policy can freeze an unlucky early underestimate and stop collecting evidence that would repair it.', 'Exploring Starts supplies coverage at the episode start, whereas ε-soft behavior preserves positive action probability throughout interaction. The latter removes start-state control at the cost of persistent exploration.'], String.raw`\pi(a\mid s)>0\quad\forall(s,a)`), section('optimality', 'Boundary', 'ε-greedy exchanges execution efficiency for coverage', ['Larger ε discovers alternatives more reliably but executes currently inferior actions more often. With fixed ε, the algorithm optimizes inside the ε-soft policy class.', 'Approaching deterministic greedy optimality requires ε to decrease without vanishing so fast that early errors lose all chance of correction. This is the joint requirement of becoming greedy while preserving sufficient exploration.'], String.raw`\epsilon_k\to 0,\qquad \sum_k\epsilon_k=\infty`), section('consistency', 'Consistency', 'An optimal ε-greedy policy need not match the globally greedy optimum', ['Soft behavior changes the future state distribution. Even if the current greedy action agrees, later random actions can enter forbidden cells or leave the target.', 'Exploration is therefore part of the objective class and data distribution, not an external trick.']), section('forward', 'Next step', 'The incremental mean exposes a more general correction form', ['Step size 1/N weights every historical return equally and exactly reproduces an arithmetic mean, which suits a fixed target and asymptotic noise removal.', 'When policy or environment changes, old evidence should not retain equal weight forever. The next chapter keeps estimate-plus-error correction and derives more general schedules through Robbins–Monro conditions.'])],
  summary: ['MC preserves the value definition and replaces model expectations with complete-episode return samples.', 'MC Basic, Exploring Starts, and ε-greedy form a chain driven by data efficiency and coverage assumptions.', 'First-visit and every-visit determine how within-episode evidence is weighted.', 'ε-soft policies trade persistent exploration for a restricted optimal-policy class.', 'Understanding MC control requires inspecting estimates, coverage, policy improvement, and assumptions together.'], explorer: { cue: 'Read the three protocol gates when switching algorithms; when switching visit rules, compare “skip/again” on repeated time steps in the same tape.' },
})

export const approximationChapter = chapter('approximation', [source('sa', 'Stochastic Approximation', 'L6, pp.7–60')], {
  prerequisite: '前置：样本均值、期望与基本梯度', eyebrow: 'Part II · 带噪声的增量更新', title: '噪声观测下的增量估计与随机逼近',
  intro: 'Monte Carlo 的增量均值已经具有“当前估计加一步纠正”的结构。随机逼近把这个结构推广到未知方程：只要能获得无偏或受控偏差的 noisy observation，就能沿着随机方向逐步靠近根。步长既决定每次相信新数据多少，也决定噪声是否最终被平均掉。',
  bridge: '从求根问题出发，定义带噪声观测，再得到 Robbins–Monro 更新及其步长条件。', experimentIntro: '在同一条噪声序列上比较固定步长与衰减步长。改变噪声幅度和步长，观察追踪速度、残余波动和最终误差。', interpretation: '固定步长不会完全忘记新数据，因此能追踪变化，但会在真值附近持续波动。衰减步长早期移动快、后期逐渐平均噪声；衰减过快则可能在尚未到达根时失去调整能力。',
  figure: '交互图 07.1 · Stochastic Approximation Lab', instruction: '在相同 seed 下比较固定和衰减步长', question: '步长怎样同时控制学习速度与噪声残留？',
  deepening: approximationDeepeningZh,
  derivation: [
    step('root', '把目标写成求根', String.raw`g(w^*)=0`, '未知量 w* 由方程的根定义。', '均值估计可写成 g(w)=w-E[X]；强化学习中的许多 value 方程也可改写为残差等于零。', ['根存在'], [[String.raw`g`, '期望残差函数']]),
    step('noisy-observation', '用样本构造 noisy observation', String.raw`\widetilde g(w_k,\eta_k)=g(w_k)+\eta_k`, '我们看不到 g，只看到包含随机误差的单次观测。', '当条件期望中的噪声为零时，多次观测的平均方向仍指向真实残差。', [String.raw`\mathbb E[\eta_k\mid w_k]=0`], [[String.raw`\eta_k`, '第 k 次观测噪声']]),
    step('rm-update', '沿观测到的残差反方向移动', String.raw`w_{k+1}=w_k-\alpha_k\widetilde g(w_k,\eta_k)`, '正残差让估计减小，负残差让估计增大。', '这就是 Robbins–Monro 更新。α_k 把 noisy direction 转换为实际移动距离。', [String.raw`\alpha_k>0`], [[String.raw`\alpha_k`, '第 k 步步长']]),
    step('mean-special-case', '均值估计是一个特例', String.raw`w_{k+1}=w_k+\alpha_k(X_k-w_k)`, '令 g(w)=w-E[X]，单样本 X_k 直接给出 noisy residual。', '当 α_k=1/(k+1) 时，递推与样本平均完全一致；其他步长则改变历史样本的权重。', ['X_k 具有有限方差'], [[String.raw`X_k-w_k`, '新观测相对当前均值的误差']]),
    step('step-conditions', '让总移动无限而总噪声有限', String.raw`\sum_{k=1}^{\infty}\alpha_k=\infty,\qquad\sum_{k=1}^{\infty}\alpha_k^2<\infty`, '第一条避免过早停止，第二条让累计噪声能被控制。', '典型选择 α_k=1/k 同时满足两条；固定步长不满足第二条，因此通常只在根附近形成稳态波动。', ['残差方向稳定且噪声方差有界'], [[String.raw`\sum\alpha_k^2`, '随机扰动的累计尺度']]),
  ],
  prelude: [section('increment', '统一形式', '学习是估计加上误差驱动的纠正', ['MC、TD 和随机梯度都可以看成旧参数加步长乘 noisy direction。']), section('two-jobs', '步长的双重职责', '既要走得到，也要停得稳', ['较大步长快速响应，较小步长压低噪声；调度决定二者如何随时间交换。'])],
  sections: [section('constant-decay', '两种目标', '收敛到常数与跟踪变化不是同一个任务', ['衰减步长适合固定真值和渐近收敛；固定步长保留对新数据的敏感度，适合非平稳问题。'], String.raw`w_{k+1}=(1-\alpha)w_k+\alpha X_k`), section('sgd-bridge', '连接优化', 'SGD 是随机逼近在梯度求根上的应用', ['最小化期望损失等价于寻找期望梯度为零的参数。单样本梯度是这个期望梯度的 noisy observation。'], String.raw`\mathbf w_{k+1}=\mathbf w_k-\alpha_k\nabla_{\mathbf w}f(\mathbf w_k,X_k)`), section('forward', '下一步', 'TD 用一次转移构造 Bellman 残差样本', ['下一章把未知的 value 方程写成求根，并用当前 value 估计构造单步 target。'])],
  summary: ['随机逼近用 noisy observation 求未知期望方程的根。', '步长决定新样本与历史估计的权重。', '衰减条件平衡持续移动和噪声抑制。', 'SGD 与 TD 都继承同一个增量结构。'], explorer: { cue: '先比较收敛速度，再看后半段波动；最终点偶然接近真值不等于整个过程稳定。' },
}, {
  prerequisite: 'Prerequisites: sample means, expectations, and basic gradients', eyebrow: 'Part II · Noisy incremental updates', title: 'Incremental estimation and stochastic approximation under noise',
  intro: 'The incremental Monte Carlo mean already has the form “current estimate plus a correction.” Stochastic approximation generalizes that structure to unknown equations: a noisy observation of the residual can guide estimates toward a root. Step size determines both how much to trust new data and whether noise is eventually averaged away.',
  bridge: 'Start with root finding, define a noisy observation, and derive the Robbins–Monro update and its step-size conditions.', experimentIntro: 'Compare constant and decaying step sizes on the same noise sequence. Vary noise and step size to inspect response speed, residual fluctuation, and final error.', interpretation: 'A constant step keeps responding to new data and can track change, but it continues to fluctuate near the truth. A decaying step averages noise increasingly well; if it decays too fast, it can lose the ability to reach the root.',
  figure: 'Interactive Figure 07.1 · Stochastic Approximation Lab', instruction: 'Compare constant and decaying steps under one seed', question: 'How does step size control both learning speed and residual noise?',
  deepening: approximationDeepeningEn,
  derivation: [step('root', 'Write the target as a root', String.raw`g(w^*)=0`, 'The unknown w* is defined by a root.', 'Mean estimation uses g(w)=w-E[X]; value equations can also be written as zero residuals.', ['a root exists'], [[String.raw`g`, 'expected residual function']]), step('noisy-observation', 'Construct a noisy observation', String.raw`\widetilde g(w_k,\eta_k)=g(w_k)+\eta_k`, 'The true residual is hidden; one sample contains random error.', 'With conditionally zero-mean noise, the average observed direction still points to the true residual.', [String.raw`\mathbb E[\eta_k\mid w_k]=0`], [[String.raw`\eta_k`, 'observation noise']]), step('rm-update', 'Move opposite the observed residual', String.raw`w_{k+1}=w_k-\alpha_k\widetilde g(w_k,\eta_k)`, 'Positive residual decreases the estimate and negative residual increases it.', 'This is the Robbins–Monro update; α_k turns a noisy direction into a displacement.', [String.raw`\alpha_k>0`], [[String.raw`\alpha_k`, 'step size']]), step('mean-special-case', 'Recover incremental mean estimation', String.raw`w_{k+1}=w_k+\alpha_k(X_k-w_k)`, 'Set g(w)=w-E[X] and use X_k as the sample observation.', 'With α_k=1/(k+1), the recursion equals the sample mean exactly.', ['X_k has finite variance'], [[String.raw`X_k-w_k`, 'sample error']]), step('step-conditions', 'Keep total motion infinite and total noise finite', String.raw`\sum_{k=1}^{\infty}\alpha_k=\infty,\qquad\sum_{k=1}^{\infty}\alpha_k^2<\infty`, 'The first condition prevents premature stopping; the second controls accumulated noise.', 'The schedule 1/k satisfies both. A constant step violates the second and usually fluctuates around the root.', ['stable residual direction and bounded noise variance'], [[String.raw`\sum\alpha_k^2`, 'accumulated noise scale']])],
  prelude: [section('increment', 'Common form', 'Learning is an estimate plus an error-driven correction', ['MC, TD, and stochastic gradients all update an old parameter with a noisy direction.']), section('two-jobs', 'Two jobs', 'The step must arrive and settle', ['Large steps respond quickly; small steps suppress noise. A schedule trades these roles over time.'])],
  sections: [section('constant-decay', 'Two objectives', 'Converging to a constant and tracking change differ', ['Decaying steps suit stationary targets and asymptotic convergence. Constant steps retain sensitivity to recent data.'], String.raw`w_{k+1}=(1-\alpha)w_k+\alpha X_k`), section('sgd-bridge', 'Optimization bridge', 'SGD applies stochastic approximation to a gradient root', ['Minimizing expected loss means finding a zero expected gradient; a sample gradient is its noisy observation.'], String.raw`\mathbf w_{k+1}=\mathbf w_k-\alpha_k\nabla_{\mathbf w}f(\mathbf w_k,X_k)`), section('forward', 'Next step', 'TD samples a Bellman residual from one transition', ['The next chapter writes value prediction as root finding and builds a one-step target from the current value estimate.'])],
  summary: ['Stochastic approximation solves expectation-defined roots with noisy observations.', 'Step size weights new evidence against history.', 'Decay conditions balance continued motion and noise control.', 'SGD and TD inherit the same incremental structure.'], explorer: { cue: 'Compare convergence speed and late fluctuation; one lucky final point is not evidence of a stable process.' },
})

export const tdChapter = chapter('td', [source('td', 'Temporal-Difference Learning', 'L7, pp.6–23')], {
  prerequisite: '前置：Bellman 期望方程与随机逼近', eyebrow: 'Part II · 不等待终点的预测', title: '从单步转移学习长期价值',
  intro: 'Monte Carlo 只有等一个回合结束后，才能计算从某个时刻开始的完整回报。可是智能体每执行一步，就已经观察到即时奖励和下一状态。TD prediction 要解决的问题是：能否利用这部分刚刚到达的信息，先修正当前状态的价值，而不必等到终点？', bridge: 'Bellman 方程提供了答案。它把当前状态的长期价值写成“一步奖励加后继状态价值”的期望。真实交互给出一步奖励和后继状态；尚未发生的未来则暂时由当前价值估计补上。由此可以从一次转移依次得到 TD target、TD error 和增量更新。',
  experimentIntro: '下面让 MC、TD(0) 和 n-step 方法读取同一段网格轨迹与同一张当前价值表。改变折扣因子和 n，逐项核对已经发生的奖励，并确认尾项确实从高亮的后继状态表项读取，而不是由步数人工生成。', interpretation: 'n 较小时，target 更早出现，但更依赖当前价值表中靠前的后继估计；n 增大时，target 纳入更多已经发生的奖励，也承受更多轨迹随机性和等待时间。逐项账本把这项取舍落实到同一段轨迹、同一张价值表和一个明确的自举边界上。',
  figure: '交互图 08.1 · Target Comparator', instruction: '改变 n 与 γ，对照三个 target 的数值与信用跨度', question: 'bootstrap 怎样用当前估计换取更及时的学习信号？',
  deepening: tdDeepeningZh,
  derivation: [step('bellman-root', '从给定策略的 Bellman 方程出发', String.raw`v^{\pi}(s)=\mathbb E_{\pi}[R_{t+1}+\gamma v^{\pi}(S_{t+1})\mid S_t=s]`, '真实 value 等于一步奖励与后继真实 value 的期望。', '这是预测问题，不包含动作最大化。', ['策略 π 固定'], [[String.raw`v^{\pi}`, '待估计的真实状态价值']]), step('sample-target', '用一次转移构造 target', String.raw`U_t^{\mathrm{TD}}=R_{t+1}+\gamma V_t(S_{t+1})`, '把未知后继真实 value 换成当前估计。', 'U_t 在 S_{t+1} 到达时即可计算，因此无需等待 episode 结束。', ['V_t 是当前估计'], [[String.raw`U_t^{\mathrm{TD}}`, '一步 TD target']]), step('td-error', '比较 target 与当前预测', String.raw`\delta_t=U_t^{\mathrm{TD}}-V_t(S_t)`, '正误差说明实际一步结果比当前预测好。', 'TD error 同时包含奖励惊喜和后继价值变化，是局部 Bellman 残差样本。', [], [[String.raw`\delta_t`, '时间差分误差']]), step('td-update', '用随机逼近更新被访问状态', String.raw`V_{t+1}(S_t)=V_t(S_t)+\alpha_t\delta_t`, '只更新当前访问状态，其余状态保持不变。', '在适当访问和步长条件下，随机样本更新可以逼近给定策略的真实 value。', [String.raw`0<\alpha_t\le 1`], [[String.raw`\alpha_t`, '该状态本次更新的步长']]), step('n-step', '连接一步 TD 与 Monte Carlo', String.raw`G_t^{(n)}=\sum_{k=0}^{n-1}\gamma^kR_{t+k+1}+\gamma^nV(S_{t+n})`, 'n-step target 使用 n 个真实奖励后再 bootstrap。', 'n=1 得到 TD(0)；当 n 延伸到 episode 末端且尾项为零时得到 MC return。', ['终止状态 value 为 0'], [[String.raw`n`, '真实奖励向前展开的步数']])],
  prelude: [section('timing', '新信息到达的时刻', '每次转移都提供一次检验当前价值估计的机会', ['在时刻 t，智能体从 S_t 出发执行动作。环境返回 R_{t+1} 和 S_{t+1} 时，完整回报 G_t 还不能计算，因为后面的奖励尚未发生；但这次转移已经告诉我们，当前预测至少应当与“一步奖励加后继价值”保持一致。', 'TD 正是利用这条局部一致性。它不预测尚未发生的每个奖励，而是在每次转移结束后立即构造一个临时 target，用它修正刚刚离开的状态。']), section('bootstrap', '自举机制', '尚未发生的未来由下一状态的当前估计暂时代替', ['把已有估计 V_t(S_{t+1}) 放进新 target 的做法称为 bootstrapping（自举）。它让学习无需等待回合结束，也让持续型任务能够边交互边更新。', '代价是 target 会继承当前价值表的误差。如果后继价值估得过高，当前状态也会被向上拉；随着更多状态反复更新，这些相互依赖的估计才逐渐逼近同一个 Bellman 不动点。'])],
  sections: [section('bias-variance', '多步展开', '展开的真实奖励越多，对后继估计的依赖越少', ['一步 TD 只等待一个奖励，然后立即用 V(S_{t+1}) 补上尾部。n-step target 会继续等待 n 个奖励，再从 S_{t+n} 自举；因此 n 增大时，自举误差的影响减弱，但等待时间和轨迹方差同时增加。', '这条连续变化把 TD(0) 与 Monte Carlo 放在同一条轴上：n=1 位于及时更新的一端，展开到终点则位于完整回报的一端。'], String.raw`G_t^{(1)}\longleftrightarrow G_t^{(n)}\longleftrightarrow G_t`), section('online', '在线学习', 'TD 在轨迹生成过程中持续修正价值', ['S_{t+1} 一出现，算法就可以更新 V(S_t)，随后再从 S_{t+1} 继续采样。后面的动作因此可能使用已经更新过的价值估计，数据采集与学习发生在同一条时间线上。', '这种在线性质使 TD 不必依赖自然终点；只要长期回报的定义有效，它也可以处理持续型任务。']), section('forward', '从预测到控制', '选择动作需要把状态价值扩展为动作价值', ['本章假定策略固定，只估计每个状态在该策略下的长期价值；控制问题还要比较同一状态中的不同动作，因而学习对象必须从 V 扩展到 Q。', '下一章会把同一个单步 target 写到 Q(S_t,A_t) 上。实际下一动作与最大下一动作给出两种不同 target，并由此区分 on-policy 的 Sarsa 和 off-policy 的 Q-learning。'])],
  summary: ['每次转移都会提供奖励和后继状态，因此价值可以在完整回报出现前更新。', 'TD target 用当前后继价值估计补上尚未发生的未来，这就是 bootstrapping。', 'TD error 是一次转移提供的局部 Bellman 残差样本。', 'n-step target 通过改变真实奖励的展开长度，在 TD(0) 与 Monte Carlo 之间连续取舍。'], explorer: { cue: '比较 target 时，不仅看最终数值，还要确认它何时可用、包含几个真实奖励，以及尾部是否来自当前价值估计。' },
}, {
  prerequisite: 'Prerequisites: Bellman expectation equation and stochastic approximation', eyebrow: 'Part II · Prediction before termination', title: 'Learning long-term value from one-step transitions',
  intro: 'Monte Carlo can calculate a complete return only after an episode ends. Yet every action immediately reveals a reward and a successor state. TD prediction asks whether that newly arrived evidence can revise the value of the current state before termination.', bridge: 'The Bellman equation supplies the missing link by expressing long-term value as expected one-step reward plus successor value. Interaction reveals the reward and successor; the current value estimate temporarily fills in the future that has not occurred. One transition then yields a TD target, TD error, and incremental update.',
  experimentIntro: 'Let MC, TD(0), and n-step methods read one grid trajectory and one visible value table. Change discount and n, audit each realized reward, and verify that the tail is read from the highlighted successor-state entry rather than synthesized from the step count.', interpretation: 'Small n produces an earlier target but relies on an earlier successor estimate in the current table. Larger n includes more realized rewards while adding delay and trajectory variance. The term ledger makes that tradeoff concrete on one trajectory, one value table, and one explicit bootstrap boundary.',
  figure: 'Interactive Figure 08.1 · Target Comparator', instruction: 'Change n and γ, then compare the three targets', question: 'How does bootstrapping exchange current estimates for earlier learning?',
  deepening: tdDeepeningEn,
  derivation: [step('bellman-root', 'Start from policy evaluation', String.raw`v^{\pi}(s)=\mathbb E_{\pi}[R_{t+1}+\gamma v^{\pi}(S_{t+1})\mid S_t=s]`, 'True value equals expected reward plus successor value.', 'This is prediction under a fixed policy, not action maximization.', ['policy π is fixed'], [[String.raw`v^{\pi}`, 'true state value']]), step('sample-target', 'Build a target from one transition', String.raw`U_t^{\mathrm{TD}}=R_{t+1}+\gamma V_t(S_{t+1})`, 'Replace unknown successor truth with the current estimate.', 'The target becomes available as soon as S_{t+1} arrives.', ['V_t is the current estimate'], [[String.raw`U_t^{\mathrm{TD}}`, 'one-step TD target']]), step('td-error', 'Compare target and prediction', String.raw`\delta_t=U_t^{\mathrm{TD}}-V_t(S_t)`, 'Positive error means the observed step was better than predicted.', 'TD error is a sample of the local Bellman residual.', [], [[String.raw`\delta_t`, 'temporal-difference error']]), step('td-update', 'Apply stochastic approximation', String.raw`V_{t+1}(S_t)=V_t(S_t)+\alpha_t\delta_t`, 'Only the visited state changes.', 'With suitable coverage and step sizes, sample updates approach the policy value.', [String.raw`0<\alpha_t\le 1`], [[String.raw`\alpha_t`, 'step size for this visit']]), step('n-step', 'Connect TD and Monte Carlo', String.raw`G_t^{(n)}=\sum_{k=0}^{n-1}\gamma^kR_{t+k+1}+\gamma^nV(S_{t+n})`, 'Use n realized rewards before bootstrapping.', 'n=1 yields TD(0); extending to termination yields the MC return.', ['terminal value is zero'], [[String.raw`n`, 'number of realized reward steps']])],
  prelude: [section('timing', 'Arrival of new evidence', 'Every transition tests the current value prediction', ['At time t, the agent acts from S_t. When the environment returns R_{t+1} and S_{t+1}, the complete G_t is still unavailable because later rewards have not happened. The transition nevertheless reveals whether the current prediction is locally consistent with one-step reward plus successor value.', 'TD uses that local consistency. It forms a provisional target as soon as the transition ends and revises the state just left instead of predicting every future reward.']), section('bootstrap', 'Bootstrapping', 'The current successor estimate fills in the unobserved future', ['Using an existing estimate V_t(S_{t+1}) inside a new target is called bootstrapping. It removes the need to wait for termination and supports stepwise updates in continuing tasks.', 'The target consequently inherits error from the current value table. An overestimated successor pulls the current state upward; repeated coupled updates are needed before the table approaches the Bellman fixed point.'])],
  sections: [section('bias-variance', 'Multi-step expansion', 'More realized rewards reduce dependence on the successor estimate', ['One-step TD waits for one reward and then bootstraps from V(S_{t+1}). An n-step target waits for n rewards before bootstrapping from S_{t+n}. Increasing n reduces reliance on the estimated tail while adding delay and trajectory variance.', 'This continuum puts TD(0) and Monte Carlo on one axis: n=1 is the early-update endpoint, while expansion through termination is the complete-return endpoint.'], String.raw`G_t^{(1)}\longleftrightarrow G_t^{(n)}\longleftrightarrow G_t`), section('online', 'Online learning', 'TD revises values while the trajectory is still being generated', ['As soon as S_{t+1} appears, TD can update V(S_t) and continue sampling from the successor. Later actions may therefore use values already changed by earlier transitions.', 'Because updates do not require a natural endpoint, TD also applies to continuing tasks whenever long-term return is well defined.']), section('forward', 'Prediction to control', 'Action selection requires action values rather than state values alone', ['This chapter fixes the policy and predicts state value. Control compares actions within one state, so the learned object must expand from V to Q.', 'The next chapter applies the same one-step target to Q(S_t,A_t). Using the action actually selected or the largest successor value yields different targets and separates on-policy Sarsa from off-policy Q-learning.'])],
  summary: ['Every transition reveals a reward and successor, so value can update before a complete return exists.', 'A TD target bootstraps by filling the unobserved future with the current successor estimate.', 'TD error is a local Bellman-residual sample from one transition.', 'n-step targets vary realized reward span to move continuously between TD(0) and Monte Carlo.'], explorer: { cue: 'When comparing targets, inspect not only magnitude but also availability time, number of realized rewards, and the source of the tail value.' },
})

export const controlChapter = chapter('control', [source('control', 'Sarsa and Q-learning', 'L7, pp.25–54')], {
  prerequisite: '前置：动作价值、TD target 与 ε-greedy 探索', eyebrow: 'Part II · 从预测到控制', title: 'Sarsa 与 Q-learning 的策略目标及风险行为',
  intro: '预测只评价给定策略；控制还要在学习过程中改善策略。Sarsa 的 target 使用行为策略实际选择的下一动作，因此把未来探索风险计入价值。Q-learning 的 target 使用下一状态的最大动作价值，因此学习一个贪心目标策略，即使数据来自更有探索性的行为策略。', bridge: '在同一个五元转移上分别写出 Sarsa 与 Q-learning target，再明确 behavior policy 和 target policy 的职责。',
  experimentIntro: 'Control Arena 先冻结同一张 Q 表和同一条 transition，只改变后继动作的读取方式：Sarsa 读取行为策略实际采样的动作，Q-learning 读取贪心动作。随后再用相同探索预算训练两张独立策略图，比较危险状态频率与累计回报。', interpretation: '冻结快照中的 target gap 只来自后继动作选择，因此能直接说明 on-policy 与 off-policy 的区别。完整训练图则展示这种差异长期累积后的行为后果：探索率升高时，Sarsa 会把行为随机性计入 target，Q-learning 仍按贪心后继估值。',
  figure: '交互图 09.1 · Sarsa / Q-learning Control Arena', instruction: '锁定 seed 与探索预算，只改变 target 定义', question: '更新目标是否跟随实际下一动作，会怎样改变学到的策略？',
  deepening: controlDeepeningZh,
  derivation: [step('sarsa-target', '先跟随实际下一动作', String.raw`U_t^{\mathrm{Sarsa}}=R_{t+1}+\gamma Q_t(S_{t+1},A_{t+1})`, 'A_{t+1} 由当前行为策略实际采样。', '名称 Sarsa 来自一次更新使用的 S,A,R,S,A 五个对象。', ['A_{t+1} 已经被行为策略选择'], [[String.raw`A_{t+1}`, '下一时刻实际将执行的动作']]), step('sarsa-update', '更新被访问的动作价值', String.raw`\begin{aligned}Q_{t+1}(S_t,A_t)&=Q_t(S_t,A_t)\\ &\quad+\alpha_t U_t^{\mathrm{Sarsa}}\\ &\quad-\alpha_t Q_t(S_t,A_t).\end{aligned}`, 'Sarsa 评价正在产生数据的策略。', '当行为策略持续 ε-greedy 时，target 中保留未来探索动作的后果，因此是 on-policy。', ['状态—动作对持续被访问'], [[String.raw`U_t^{\mathrm{Sarsa}}`, 'on-policy TD target']]), step('q-target', '把下一动作换成最大化', String.raw`U_t^{Q}=R_{t+1}+\gamma\max_a Q_t(S_{t+1},a)`, 'target 假设下一步选择当前最优动作。', '生成数据的行为策略可以仍然探索，但求解对象是 Bellman 最优方程。', [], [[String.raw`\max_a Q_t(S_{t+1},a)`, '目标策略的贪心后继价值']]), step('q-update', '用同一经验更新最优动作价值估计', String.raw`\begin{aligned}Q_{t+1}(S_t,A_t)&=Q_t(S_t,A_t)\\ &\quad+\alpha_t U_t^{Q}\\ &\quad-\alpha_t Q_t(S_t,A_t).\end{aligned}`, '采到的动作可以不是贪心动作，target 仍指向贪心后继。', '数据分布与被学习的策略分离，因此 Q-learning 是 off-policy。', ['behavior policy 提供充分覆盖'], [[String.raw`U_t^{Q}`, 'off-policy optimality target']]), step('policy-roles', '显式分开两种策略', String.raw`A_t\sim b(\cdot\mid S_t),\qquad \pi(s)\in\arg\max_a Q(s,a)`, 'b 负责探索和采样，π 表示希望学习的目标行为。', 'Sarsa 的 target 跟随 b；Q-learning 的 target 跟随贪心 π。区分二者是理解 on/off-policy 的关键。', [String.raw`b(a\mid s)>0\ \text{for required actions}`], [[String.raw`b`, '行为策略'], [String.raw`\pi`, '目标策略']])],
  prelude: [section('prediction-control', '目标变化', '控制在评价之外加入策略改善', ['TD prediction 只需在固定策略下估计价值；控制还要依据当前 Q 值改变动作选择，因此一次更新会影响后续采到哪些数据。', '价值估计、探索行为和策略改善由此形成闭环。算法不再面对固定的数据分布，早期估计误差也可能通过动作选择被持续放大。']), section('fair-comparison', '比较协议', '只改变 target，才能识别算法差异', ['比较 Sarsa 与 Q-learning 时，需要锁定环境、随机 seed、ε-greedy 行为、步长和交互预算，并让两者看到可比的转移序列。', '在这些条件下，二者唯一关键差异是下一状态 target：Sarsa 使用实际将执行的动作，Q-learning 使用当前最大动作价值，因此路径风险差异才能归因于更新机制。'])],
  sections: [section('on-policy', 'On-policy', 'Sarsa 评价并改进正在执行的探索策略', ['Sarsa 的 target 使用行为策略在下一状态实际选择的 A_{t+1}，所以禁区附近偶尔发生的探索动作也会进入长期价值。', '它学习的是持续 ε-greedy 行为本身的动作价值；ε 改变时，策略的风险和对应最优解也会随之改变。'], String.raw`Q\approx q^{b}`), section('off-policy', 'Off-policy', 'Q-learning 从探索数据中逼近贪心目标', ['Q-learning 仍可用行为策略 b 收集数据，但 target 在下一状态直接选择最大 Q 值，相当于评价另一条贪心目标策略。', '这种分离允许边探索边学习贪心解，却不免除覆盖要求：从未访问的动作没有样本，错误初值也就无法被纠正。'], String.raw`Q\approx q^*,\qquad A\sim b`), section('forward', '表格的边界', '参数共享替代逐项存储', ['表格方法为每个状态—动作对保存独立数值，空间规模随状态与动作数量相乘增长，未访问项之间也不能共享证据。', '下一章把 Q 或 V 写成带参数的函数，使一次样本能够影响具有相似表示的多个状态，同时引入泛化与相互干扰的新问题。'])],
  summary: ['Sarsa target 使用实际下一动作，是 on-policy 控制。', 'Q-learning target 使用动作最大值，是 off-policy 控制。', '行为策略负责数据覆盖，目标策略定义学习对象。', '公平比较必须锁定探索预算与随机条件。'], explorer: { cue: '把危险率和平均回报一起读；最短贪心路线不一定是在探索行为下最安全的路线。' },
}, {
  prerequisite: 'Prerequisites: action value, TD targets, and ε-greedy exploration', eyebrow: 'Part II · Prediction to control', title: 'Policy targets and risk behavior in Sarsa and Q-learning',
  intro: 'Prediction evaluates a fixed policy; control improves policy during learning. Sarsa uses the next action actually selected by the behavior policy, so its target includes future exploration risk. Q-learning uses the largest next action value and learns a greedy target policy even when data comes from an exploratory behavior policy.', bridge: 'Write both targets on the same five-part transition, then separate the roles of behavior and target policies.',
  experimentIntro: 'Control Arena first freezes one Q table and one transition, changing only how the successor action is read: Sarsa uses the behavior action actually sampled, while Q-learning uses the greedy action. It then trains two separate policy maps under the same exploration budget to compare danger frequency and return.', interpretation: 'The frozen-snapshot target gap isolates the on-policy versus off-policy distinction. The trained maps show its accumulated behavioral consequence: with more exploration, Sarsa includes behavioral randomness in its target while Q-learning continues to value a greedy successor.',
  figure: 'Interactive Figure 09.1 · Sarsa / Q-learning Control Arena', instruction: 'Lock seed and exploration; change only the target', question: 'How does following the actual next action change the learned policy?',
  deepening: controlDeepeningEn,
  derivation: [step('sarsa-target', 'Follow the actual next action', String.raw`U_t^{\mathrm{Sarsa}}=R_{t+1}+\gamma Q_t(S_{t+1},A_{t+1})`, 'A_{t+1} is sampled by the behavior policy.', 'Sarsa is named for the S,A,R,S,A objects used in one update.', ['A_{t+1} has been selected'], [[String.raw`A_{t+1}`, 'next action actually taken']]), step('sarsa-update', 'Update the visited action value', String.raw`\begin{aligned}Q_{t+1}(S_t,A_t)&=Q_t(S_t,A_t)\\ &\quad+\alpha_t U_t^{\mathrm{Sarsa}}\\ &\quad-\alpha_t Q_t(S_t,A_t).\end{aligned}`, 'Sarsa evaluates the policy that generates its data.', 'With continuing ε-greedy behavior, future exploration consequences remain in the target.', ['continued state-action coverage'], [[String.raw`U_t^{\mathrm{Sarsa}}`, 'on-policy TD target']]), step('q-target', 'Replace the next action by maximization', String.raw`U_t^{Q}=R_{t+1}+\gamma\max_a Q_t(S_{t+1},a)`, 'The target assumes the current greedy next action.', 'Behavior may still explore, but the equation being solved is the Bellman optimality equation.', [], [[String.raw`\max_a Q_t(S_{t+1},a)`, 'greedy successor value']]), step('q-update', 'Update optimal action value from the same experience', String.raw`\begin{aligned}Q_{t+1}(S_t,A_t)&=Q_t(S_t,A_t)\\ &\quad+\alpha_t U_t^{Q}\\ &\quad-\alpha_t Q_t(S_t,A_t).\end{aligned}`, 'The sampled action can be exploratory while the target remains greedy.', 'Separating data and target policies makes Q-learning off-policy.', ['behavior provides coverage'], [[String.raw`U_t^{Q}`, 'off-policy optimality target']]), step('policy-roles', 'Name both policies explicitly', String.raw`A_t\sim b(\cdot\mid S_t),\qquad \pi(s)\in\arg\max_a Q(s,a)`, 'b samples experience; π names the behavior being learned.', 'Sarsa targets b while Q-learning targets greedy π.', [String.raw`b(a\mid s)>0\ \text{for required actions}`], [[String.raw`b`, 'behavior policy'], [String.raw`\pi`, 'target policy']])],
  prelude: [section('prediction-control', 'Changed objective', 'Control adds improvement to evaluation', ['TD prediction estimates value under a fixed policy. Control also changes action selection from current Q estimates, so an update changes which evidence will be collected next.', 'Value estimation, exploration, and policy improvement therefore form a feedback loop. The data distribution moves, and early estimation errors can be reinforced through behavior.']), section('fair-comparison', 'Comparison protocol', 'Change only the target to identify the algorithmic effect', ['A Sarsa–Q-learning comparison must hold the environment, random seed, ε-greedy behavior, step size, and interaction budget fixed and expose comparable transitions.', 'Under that protocol, the decisive difference is the successor target: Sarsa uses the action actually selected, while Q-learning uses the current maximum. Resulting risk differences can then be attributed to the update.'])],
  sections: [section('on-policy', 'On-policy', 'Sarsa evaluates the exploratory policy it executes', ['The Sarsa target uses A_{t+1}, the action that the behavior policy actually selects. Exploratory moves near a hazard therefore enter its long-term value.', 'It learns action values for the continuing ε-greedy behavior itself, so changing ε changes both the experienced risk and the corresponding optimum.'], String.raw`Q\approx q^{b}`), section('off-policy', 'Off-policy', 'Q-learning approaches a greedy target from exploratory data', ['Q-learning can collect experience with behavior policy b while its target selects the largest successor Q value, thereby evaluating a different greedy target policy.', 'This separation supports exploration during data collection, but it does not remove coverage requirements. An action that is never sampled cannot have a mistaken initialization corrected.'], String.raw`Q\approx q^*,\qquad A\sim b`), section('forward', 'Table limits', 'Parameter sharing replaces independent entries', ['A table stores an independent number for every state-action pair, grows with their product, and transfers no evidence to an unvisited pair.', 'The next chapter uses a parameterized function so one sample can affect states with related representations, introducing both generalization and interference.'])],
  summary: ['Sarsa uses the actual next action and is on-policy.', 'Q-learning uses a maximizing target and is off-policy.', 'Behavior policy supplies coverage; target policy defines the learning objective.', 'Fair comparison locks exploration and randomness.'], explorer: { cue: 'Read danger rate with return; the shortest greedy route may not be safest under exploratory behavior.' },
})

export const vfaChapter = chapter('vfa', [source('vfa', 'Value Function Approximation', 'L8, pp.5–160')], {
  prerequisite: '前置：时序差分更新、均方误差与梯度', eyebrow: 'Part III · 从表格到函数', title: '无法枚举所有状态时，参数怎样共享价值信息？', intro: '表格方法为每个状态保存一个独立数值，状态一多便无法继续扩展。函数近似改用特征和共享参数表示状态价值：一次样本不只改变当前状态，也会改变特征相似的其他状态。这个机制既带来泛化，也会造成干扰，并使近似误差取决于训练数据分布。', bridge: '先定义参数化状态价值与按访问频率加权的均方误差，再推导半梯度更新。在线性特征中，一次更新对其他状态的影响可以被直接计算。',
  experimentIntro: '函数近似实验室让五个相邻位置共享一个局部特征。改变特征宽度和步长，观察中心样本如何影响邻居，并判断这种传播何时是有益泛化、何时是错误干扰。', interpretation: '窄特征接近表格更新，影响局部却需要更多样本；宽特征把一条证据传播到更远状态，学习更快，也可能把本不相似的状态拉向同一个目标。特征不是单纯的压缩格式，而是算法对状态相似性的假设。',
  figure: '交互图 10.1 · 共享特征传播实验室', instruction: '改变特征宽度与步长，观察一次更新怎样传到相邻状态', question: '一次状态样本为什么会改变其他状态的预测？',
  deepening: vfaDeepeningZh,
  derivation: [step('parameterization', '用共享参数表示 value', String.raw`v^{\pi}(s)\approx\widehat v(s,\mathbf w)`, '状态不再对应独立表项，而是通过同一参数向量产生预测。', '参数数量可以远小于状态数量，因此相似状态共享统计信息。', [], [[String.raw`\mathbf w`, '共享参数向量']]), step('objective', '用访问分布定义近似误差', String.raw`J(\mathbf w)=\frac12\sum_s\mu(s)\left(v^{\pi}(s)-\widehat v(s,\mathbf w)\right)^2`, '经常访问的状态在目标函数中权重更高。', '函数容量有限时不可能同时精确拟合全部状态；stationary distribution μ 指定误差被怎样折中。', [String.raw`\mu(s)\ge0,\ \sum_s\mu(s)=1`], [[String.raw`\mu`, '训练数据诱导的状态权重']]), step('sample-target', '用可观测 target 替代未知真值', String.raw`U_t=R_{t+1}+\gamma\widehat v(S_{t+1},\mathbf w_t)`, 'TD target 提供当前样本的监督信号。', '因为真实 vπ 未知，训练使用 MC return 或 bootstrap target。semi-gradient 暂时把 target 当作常数。', [], [[String.raw`U_t`, '当前样本 target']]), step('semi-gradient', '沿预测误差的负梯度更新', String.raw`\mathbf w_{t+1}=\mathbf w_t+\alpha_t\left(U_t-\widehat v(S_t,\mathbf w_t)\right)\nabla_{\mathbf w}\widehat v(S_t,\mathbf w_t)`, '误差决定方向和大小，梯度决定哪些参数响应。', '只对当前预测求梯度，不对 bootstrap target 中的参数依赖求导，因此称 semi-gradient。', ['target 在本步求导时固定'], [[String.raw`\nabla_{\mathbf w}\widehat v`, '当前状态对各参数的敏感度']]), step('linear', '在线性特征中看见共享', String.raw`\widehat v(s,\mathbf w)=\boldsymbol\phi(s)^\top\mathbf w,\qquad\Delta\mathbf w=\alpha\left(U-\widehat v(s,\mathbf w)\right)\boldsymbol\phi(s)`, '当前状态激活的特征决定参数更新。', '另一个状态若使用相同特征，其预测也会立刻改变；这就是泛化与干扰的共同来源。', [], [[String.raw`\boldsymbol\phi(s)`, '状态特征向量']])],
  prelude: [section('capacity', '表示问题', '有限参数规定了状态之间如何共享证据', ['表格让每个状态拥有独立数值，样本只修正被访问的那一项；函数近似则让所有预测共同依赖有限参数。', '因此从 table 到 function 的关键不是更换存储容器，而是选择相似性结构：哪些状态应当一起变化，哪些状态必须保持区分。']), section('distribution', '数据问题', '访问分布决定近似误差被放在哪里', ['参数数量不足以同时精确拟合所有状态时，优化目标会更重视经常出现在训练数据中的区域。', '同一个函数族在不同策略或起始分布下会得到不同的最佳近似；训练误差较小并不意味着所有状态都同样准确。'])],
  sections: [section('generalization', '泛化', '共享特征把一次修正传播到相似状态', ['更新参数后，即使状态 s′ 没有出现在当前样本中，只要它与被访问状态共享特征，其预测也会变化。', '这种传播能够提高样本效率，但前提是特征表达了任务中真正相关的结构；错误相似性会把局部证据扩散到不该改变的位置。'], String.raw`\Delta\widehat v(s')=\boldsymbol\phi(s')^\top\Delta\mathbf w`), section('interference', '干扰', '共享参数也会承受互相冲突的修正', ['当两个状态需要不同的状态价值却使用相似特征时，它们会把同一参数推向不同方向；修正一个状态，可能同时伤害另一个。', '因此需要同时观察各状态的误差和参数更新方向。只看总体误差，可能掩盖局部震荡与遗忘。']), section('forward', '非线性近似', '神经网络提升表示能力，也加强训练耦合', ['神经网络能够从高维观测中学习特征，却会让大量动作价值预测随一次更新共同变化；而自举目标本身又由网络预测构造。', '下一章将区分目标漂移与连续样本相关这两种反馈来源，并说明 DQN 为什么分别引入目标网络与经验回放。'])],
  summary: ['函数近似用共享参数替代独立 value 表。', '访问分布定义有限容量下的误差权重。', 'semi-gradient 用样本 target 更新当前预测。', '泛化与干扰来自同一个参数共享机制。'], explorer: { cue: '宽特征带来的邻居变化既不是纯收益也不是纯错误；要结合状态相似性判断它是泛化还是干扰。' },
}, {
  prerequisite: 'Prerequisites: TD updates, squared error, and gradients', eyebrow: 'Part III · Tables to functions', title: 'How do shared parameters transfer value across states?', intro: 'A table stores one independent number per state and stops scaling when states become numerous. Function approximation represents value with features and shared parameters. One sample changes the current state and other states with similar features, producing both generalization and interference.', bridge: 'Define parameterized value and weighted squared error, derive a semi-gradient update, and expose sharing in linear features.',
  experimentIntro: 'Function Studio shares one local feature across five positions. Change feature width and step size to see a center sample affect neighbors.', interpretation: 'Narrow features approach tabular updates: local but data-hungry. Wide features spread evidence farther and can learn faster, but may pull dissimilar states toward one target. Features encode an assumption about similarity.',
  figure: 'Interactive Figure 10.1 · Function Studio', instruction: 'Vary feature width and step size to inspect spatial propagation', question: 'Why does one state sample change predictions at other states?',
  deepening: vfaDeepeningEn,
  derivation: [step('parameterization', 'Represent value with shared parameters', String.raw`v^{\pi}(s)\approx\widehat v(s,\mathbf w)`, 'States no longer own independent entries.', 'A parameter vector smaller than the state space shares statistical information.', [], [[String.raw`\mathbf w`, 'shared parameter vector']]), step('objective', 'Weight error by the visitation distribution', String.raw`J(\mathbf w)=\frac12\sum_s\mu(s)\left(v^{\pi}(s)-\widehat v(s,\mathbf w)\right)^2`, 'Frequently visited states receive more weight.', 'Limited capacity cannot fit every state exactly; μ defines the compromise.', [String.raw`\mu(s)\ge0,\ \sum_s\mu(s)=1`], [[String.raw`\mu`, 'state weighting induced by data']]), step('sample-target', 'Replace unknown truth with an observable target', String.raw`U_t=R_{t+1}+\gamma\widehat v(S_{t+1},\mathbf w_t)`, 'A TD target supervises the current sample.', 'MC returns or bootstrap targets substitute for unknown true value.', [], [[String.raw`U_t`, 'sample target']]), step('semi-gradient', 'Follow prediction error', String.raw`\mathbf w_{t+1}=\mathbf w_t+\alpha_t\left(U_t-\widehat v(S_t,\mathbf w_t)\right)\nabla_{\mathbf w}\widehat v(S_t,\mathbf w_t)`, 'Error sets direction and magnitude; the gradient selects responding parameters.', 'The target is held fixed during differentiation, hence semi-gradient.', ['target is fixed for this derivative'], [[String.raw`\nabla_{\mathbf w}\widehat v`, 'parameter sensitivity']]), step('linear', 'Expose sharing with linear features', String.raw`\widehat v(s,\mathbf w)=\boldsymbol\phi(s)^\top\mathbf w,\qquad\Delta\mathbf w=\alpha\left(U-\widehat v(s,\mathbf w)\right)\boldsymbol\phi(s)`, 'Active features determine the update.', 'Any other state using those features changes immediately.', [], [[String.raw`\boldsymbol\phi(s)`, 'state feature vector']])],
  prelude: [section('capacity', 'Representation', 'Finite parameters determine how states share evidence', ['A table gives each state an independent number, so a sample corrects only the visited entry. Function approximation makes many predictions depend on a shared parameter vector.', 'Moving from a table to a function is therefore a choice of similarity structure: which states should move together, and which distinctions must the representation preserve?']), section('distribution', 'Data distribution', 'Visitation determines where approximation error is spent', ['When limited parameters cannot fit every state exactly, the objective gives more influence to regions that appear frequently in training data.', 'The same function class can have a different best approximation under another policy or start distribution. Low aggregate loss does not imply uniform accuracy.'])],
  sections: [section('generalization', 'Generalization', 'Shared features propagate one correction to related states', ['After a parameter update, the prediction at an unvisited state s′ changes whenever it shares features with the sampled state.', 'This transfer improves sample efficiency only when the representation captures task-relevant similarity. A poor representation spreads local evidence to states that should remain distinct.'], String.raw`\Delta\widehat v(s')=\boldsymbol\phi(s')^\top\Delta\mathbf w`), section('interference', 'Interference', 'Shared parameters can receive conflicting corrections', ['If two states require different values but use similar features, their updates push the same parameters in competing directions. Correcting one can damage the other.', 'Statewise errors and parameter directions must therefore be inspected together; a falling average loss can hide local oscillation or forgetting.']), section('forward', 'Nonlinear approximation', 'Neural networks increase capacity and training coupling', ['A neural network can learn features from high-dimensional observations, but a single update changes many Q predictions while bootstrap targets are themselves built from network predictions.', 'The next chapter separates target drift from sequential sample correlation and derives why DQN introduces a target network and replay for different reasons.'])],
  summary: ['Shared parameters replace independent value entries.', 'The visitation distribution weights approximation error.', 'Semi-gradients update predictions from sample targets.', 'Generalization and interference share one cause.'], explorer: { cue: 'Neighbor change is not inherently good or bad; judge it against whether those states should share value information.' },
})

export const dqnChapter = chapter('dqn', [source('dqn', 'Deep Q-learning', 'L8, pp.162–226')], {
  prerequisite: '前置：Q-learning、函数近似与梯度下降', eyebrow: 'Part III · 稳定深度价值学习', title: '目标网络与经验回放分别稳定什么？', intro: '把 Q-learning 的表格换成神经网络，不只是增加表示容量。在线网络的参数既决定当前预测，又参与构造下一状态的自举目标；一次更新还会同时改变许多其他状态的预测。连续轨迹又让相邻训练样本高度相关。DQN 必须分别减慢目标变化，并重排训练证据。', bridge: '先让最朴素的网络 Q-learning 暴露“预测追逐自己”和“连续梯度偏向局部”这两个问题，再推导目标网络与经验回放各自改变了什么，最后把它们放回同一次更新。',
  experimentIntro: 'DQN 更新实验室沿一次真实抽样展示完整链条：从缓冲区抽出一条转移，用冻结目标网络计算目标，得到时序差分误差，更新在线网络，并在同步周期到达时复制目标参数。改变回放强度、同步间隔与更新步数，观察每个环节怎样变化。', interpretation: '经验回放越充分，相邻样本的相关性通常越低，但缓冲区数据也可能更陈旧。目标同步太频繁会重新形成快速移动的监督信号，太慢又会让监督长期落后。逐更新账本能区分两种机制的实际作用，单看一条更平滑的误差曲线做不到这一点。',
  figure: '交互图 11.1 · DQN 单步更新与同步账本', instruction: '调节回放、同步间隔与更新步数，追踪一次完整参数更新', question: '一条缓冲区转移怎样依次经过目标计算、误差、在线更新和周期同步？',
  deepening: dqnDeepeningZh,
  derivation: [step('network-q', '用网络近似动作价值', String.raw`q^*(s,a)\approx Q_{\theta}(s,a)`, '一个参数向量为多个状态和动作共同产生预测。', '共享表示让 DQN 能处理高维输入，也让单次更新产生广泛耦合。', [], [[String.raw`\theta`, 'online Q-network 参数']]), step('naive-target', '直接写出 bootstrap target', String.raw`Y_t(\theta)=R_{t+1}+\gamma\max_{a'}Q_{\theta}(S_{t+1},a')`, '同一 θ 同时出现在预测和监督信号中。', '梯度更新 θ 后，当前预测变化，target 也立即变化；优化器追逐一个快速移动的目标。', [], [[String.raw`Y_t(\theta)`, '依赖 online 参数的 target']]), step('target-network', '冻结一份 target 参数', String.raw`Y_t=R_{t+1}+\gamma\max_{a'}Q_{\bar\theta}(S_{t+1},a')`, '在若干训练步内保持 target network 不变。', 'online 参数 θ 被连续优化，target 参数 θ̄ 只周期性复制，从而把监督信号的变化时间尺度放慢。', [], [[String.raw`\bar\theta`, '冻结的 target-network 参数']]), step('replay-loss', '从 replay 中随机抽取 minibatch', String.raw`L(\theta)=\frac1B\sum_{i=1}^{B}\left(Y_i-Q_{\theta}(S_i,A_i)\right)^2`, '随机重排旧经验，降低相邻样本相关性。', 'buffer 也让一条经验被多次使用，提高数据效率；但采样分布与当前策略不再完全相同。', ['样本存储为 (S,A,R,S′,done)'], [[String.raw`B`, 'minibatch 大小']]), step('sync', '周期性同步两个网络', String.raw`\bar\theta\leftarrow\theta\quad\text{every }C\text{ updates}`, 'target 会跳变，但在两次同步之间保持稳定。', 'C 小时 target 更新快；C 大时监督更稳但更陈旧。它是稳定性与响应速度的时间尺度参数。', [String.raw`C\in\mathbb N^+`], [[String.raw`C`, 'target 同步间隔']])],
  prelude: [section('coupling', '新增困难', '共享参数让原本独立的表项开始互相影响', ['表格 Q-learning 更新一个状态—动作对时，其他表项保持不变；神经网络更新共享参数后，许多没有出现在当前小批量中的预测也会移动。', '这种耦合既带来泛化，也会让一处自举误差传播到更大范围。因此，DQN 不能被理解成“把表格换成网络”这么简单。']), section('two-instabilities', '两种来源', '目标漂移与数据相关需要分别处理', ['在线网络同时产生当前预测和下一状态目标，参数一变，监督信号也跟着移动；连续轨迹又让相邻样本高度相关，偏离随机小批量训练的理想条件。', '目标网络主要放慢第一条反馈回路，经验回放主要重排并复用第二类数据。两种机制作用于不同对象，不能互相替代。'])],
  sections: [section('target-role', 'Target network', '滞后参数为 bootstrap 提供短期稳定参照', ['target network 不是第二个独立学习目标，而是 online network 的滞后副本；在两个同步时刻之间，target 参数保持不变。', '优化器因此可以对近似固定的监督信号执行若干步更新。同步太频繁会重新形成快速移动的 target，太慢则让监督信号长期陈旧。'], String.raw`\theta\ \text{trains continuously},\qquad\bar\theta\ \text{updates discretely}`), section('replay-role', 'Experience replay', '经验回放把连续轨迹变成可重排的训练集合', ['每个转移先写入 buffer，再从不同时间和 episode 中随机抽取 minibatch，降低相邻样本共同携带的局部相关性。', '同一经验能够被多次利用，提高数据效率；代价是 buffer 分布落后于当前策略，因此容量、采样方式和数据新鲜度都会改变训练偏差。']), section('limits', '边界', '稳定训练仍不等于获得收敛保证', ['target network 与 replay 缓和了反馈速度和样本相关，却没有消除函数近似、off-policy 数据与 bootstrapping 的联合风险。', 'Double DQN 针对最大化偏差，优先 replay 改变样本效率；它们修复的是不同问题，不能由一条更平滑的 loss 曲线一并证明。'])],
  summary: ['DQN 用网络共享动作价值表示。', 'target network 放慢 bootstrap target 的漂移。', 'replay 降低连续样本相关性并复用经验。', '同步周期和 buffer 分布形成新的稳定性权衡。'], explorer: { cue: '分别观察 correlation 与 drift；一条更平滑的 loss 曲线不能说明两个问题都已解决。' },
}, {
  prerequisite: 'Prerequisites: Q-learning, function approximation, and gradient descent', eyebrow: 'Part III · Stable deep value learning', title: 'What do target networks and replay solve?', intro: 'Replacing a Q-table with a neural network changes more than capacity. Parameters determine both current predictions and bootstrap targets, and one update affects many states. Consecutive trajectories also create correlated data. DQN slows target movement with a frozen network and randomizes reusable experience with replay.', bridge: 'Start from a parameterized Q target, identify moving targets and correlated data separately, then place both mechanisms in one training step.',
  experimentIntro: 'DQN System Lab varies replay mixing and target synchronization. Inspect sample correlation, target drift, and error stability.', interpretation: 'More replay mixing reduces sequential correlation but can use older data. Frequent target synchronization recreates a fast-moving target; very slow synchronization makes targets stale. The mechanisms address different problems and do not replace each other.',
  figure: 'Interactive Figure 11.1 · DQN System Lab', instruction: 'Vary replay and target synchronization independently', question: 'Why are both a fixed target and shuffled experience needed?',
  deepening: dqnDeepeningEn,
  derivation: [step('network-q', 'Approximate action value with a network', String.raw`q^*(s,a)\approx Q_{\theta}(s,a)`, 'One parameter vector predicts many state-action values.', 'Shared representation scales to high-dimensional inputs and couples updates.', [], [[String.raw`\theta`, 'online-network parameters']]), step('naive-target', 'Write the direct bootstrap target', String.raw`Y_t(\theta)=R_{t+1}+\gamma\max_{a'}Q_{\theta}(S_{t+1},a')`, 'The same θ controls prediction and supervision.', 'Updating θ changes both sides, so the optimizer chases a moving target.', [], [[String.raw`Y_t(\theta)`, 'online-dependent target']]), step('target-network', 'Freeze target parameters', String.raw`Y_t=R_{t+1}+\gamma\max_{a'}Q_{\bar\theta}(S_{t+1},a')`, 'Hold the target network fixed for several updates.', 'Online θ trains continuously while target θ̄ copies only periodically.', [], [[String.raw`\bar\theta`, 'frozen target-network parameters']]), step('replay-loss', 'Sample a replay minibatch', String.raw`L(\theta)=\frac1B\sum_{i=1}^{B}\left(Y_i-Q_{\theta}(S_i,A_i)\right)^2`, 'Randomized old experience lowers adjacent-sample correlation.', 'Replay also reuses data, while making the batch distribution differ from the current policy.', ['store (S,A,R,S′,done)'], [[String.raw`B`, 'minibatch size']]), step('sync', 'Synchronize periodically', String.raw`\bar\theta\leftarrow\theta\quad\text{every }C\text{ updates}`, 'Targets jump at synchronization and remain fixed between copies.', 'Small C responds quickly; large C is stable but stale.', [String.raw`C\in\mathbb N^+`], [[String.raw`C`, 'target synchronization period']])],
  prelude: [section('coupling', 'New difficulty', 'Shared parameters turn independent entries into coupled predictions', ['A tabular Q-learning update leaves every other state-action entry unchanged. A neural-network update moves many predictions that were absent from the minibatch.', 'That coupling enables generalization but also spreads bootstrap error across the representation. DQN is therefore more than a Q-table with a larger storage mechanism.']), section('two-instabilities', 'Two sources', 'Target drift and data correlation require separate mechanisms', ['The online network produces both the current prediction and the successor target, so changing its parameters moves the supervision. Consecutive trajectory samples are also strongly correlated rather than resembling randomized minibatches.', 'A target network slows the first feedback loop; experience replay primarily rearranges and reuses the second kind of evidence. Neither mechanism substitutes for the other.'])],
  sections: [section('target-role', 'Target network', 'Lagged parameters provide a temporarily stable bootstrap reference', ['The target network is not an independent objective. It is a lagged copy of the online network whose parameters stay fixed between synchronization events.', 'The optimizer can therefore take several steps against approximately stationary labels. Synchronizing too often recreates rapid target motion; synchronizing too slowly leaves stale supervision.'], String.raw`\theta\ \text{trains continuously},\qquad\bar\theta\ \text{updates discretely}`), section('replay-role', 'Experience replay', 'Replay turns a trajectory into a resampleable training collection', ['Transitions enter a buffer and minibatches mix times and episodes, reducing the local correlation carried by adjacent experience.', 'Reusing a transition improves data efficiency, but the buffer distribution lags behind current behavior. Capacity, sampling policy, and freshness therefore affect bias as well as compute.']), section('limits', 'Boundary', 'Stable optimization is not a convergence guarantee', ['Target networks and replay moderate feedback speed and sample correlation, but function approximation, off-policy data, and bootstrapping still interact.', 'Double DQN addresses maximization bias and prioritized replay changes data efficiency. A smoother loss curve does not demonstrate that all of these failure modes are controlled.'])],
  summary: ['DQN shares action-value predictions through a network.', 'A target network slows bootstrap-target drift.', 'Replay reduces sequential correlation and reuses experience.', 'Synchronization and replay distributions introduce new tradeoffs.'], explorer: { cue: 'Inspect correlation and drift separately; a smooth loss curve does not prove both sources are controlled.' },
})

export const policyGradientChapter = chapter('policygradient', [source('pg', 'Policy Gradient Methods', 'L9, pp.6–41')], {
  prerequisite: '前置：参数化函数、概率分布与梯度上升', eyebrow: 'Part III · 直接优化策略', title: '怎样直接提高高回报动作的概率？', intro: '价值方法先估计动作价值，再选出价值最大的动作。策略梯度则直接用参数表示动作概率，并优化策略的长期表现。一次采样的结果若好于该状态下的通常水平，就提高所选动作的概率；若更差，就降低它的概率。', bridge: '要让这个直觉成为算法，需要先定义一个标量目标，再把它的梯度改写成能够由当前策略轨迹估计的形式。由此得到 REINFORCE，以及不改变期望方向的状态基线。',
  experimentIntro: '策略梯度实验室让轨迹中的每个状态拥有独立的三动作分布，并列出每一步的回报、优势与梯度贡献。选择一个决策点后，可以观察它的概率重分配；下方多轨迹账本则固定该状态，比较使用状态基线前后的梯度方差。', interpretation: '一次更新只改变所选状态对应的策略参数，但 softmax 会在该状态的三个动作之间重新分配概率。单条轨迹说明每一步贡献如何形成；多条轨迹说明同一状态、同一梯度坐标为何波动，以及合适的状态基线怎样在不改变期望方向的前提下降低这种波动。',
  figure: '交互图 12.1 · 策略梯度概率重分配实验室', instruction: '选择一个决策点，观察三个动作更新前后的概率守恒', question: '一次样本怎样在保持概率总和为一的同时改变整个动作分布？',
  deepening: policyGradientDeepeningZh,
  derivation: [step('objective', '先定义策略好坏的标量指标', String.raw`J(\theta)=\mathbb E_{S\sim\eta_\theta}\left[v^{\pi_\theta}(S)\right]`, 'θ 通过策略影响动作，也通过长期访问分布影响状态。', 'J 可以采用 discounted average value 或 continuing average reward；二者细节不同，但都把策略比较转成标量优化。', [], [[String.raw`\eta_\theta`, '策略诱导的状态权重']]), step('theorem', '用策略梯度定理消去状态分布导数', String.raw`\nabla_\theta J(\theta)=\sum_s\eta_\theta(s)\sum_a\nabla_\theta\pi_\theta(a\mid s)q^{\pi_\theta}(s,a)`, '梯度可写成状态—动作上的加权和。', '定理把复杂的长期分布变化吸收到 η 中，使更新只需策略导数与动作价值。', ['π 对 θ 可微'], [[String.raw`q^{\pi_\theta}`, '当前策略的动作价值']]), step('log-trick', '把概率导数改写为 score function', String.raw`\nabla_\theta\pi_\theta(a\mid s)=\pi_\theta(a\mid s)\nabla_\theta\log\pi_\theta(a\mid s)`, '概率本身提供采样权重，对数概率梯度提供方向。', '代入后，求和正好成为从当前策略采样的期望。', [String.raw`\pi_\theta(a\mid s)>0`], [[String.raw`\nabla\log\pi`, 'score function']]), step('sample-gradient', '用一条样本估计期望梯度', String.raw`\widehat g_t=\nabla_\theta\log\pi_\theta(A_t\mid S_t)G_t`, '高 return 动作提高 log probability，低 return 动作产生相反方向。', '用完整 return 得到 REINFORCE。估计无偏但常有较高方差，因为一条轨迹的随机结果乘到了每个动作上。', ['轨迹由当前策略采样'], [[String.raw`\widehat g_t`, '单样本策略梯度估计']]), step('baseline', '减去与动作无关的 baseline', String.raw`\widehat g_t=\nabla_\theta\log\pi_\theta(A_t\mid S_t)\left(G_t-b(S_t)\right)`, '只奖励相对该状态通常水平更好的动作。', '因为对动作求期望的 score function 为零，状态 baseline 不改变梯度期望，却可以显著降低方差。', ['b 不依赖 A_t'], [[String.raw`b(S_t)`, '状态相关 baseline']])],
  prelude: [section('value-policy', '表示变化', '策略从取最大值的规则变成可微的概率模型', ['价值方法先估计动作价值，再取最大值选动作。这个离散选择不便直接求导，也不能自然表达必须保留随机性的策略。', '策略梯度直接让动作概率依赖参数。softmax 保证各概率非负且总和为一，并允许梯度连续地在动作之间转移概率质量。']), section('credit', '样本贡献', '敏感度决定怎样改，长期结果决定改多少', ['对数概率梯度描述参数怎样改变已采样动作的概率，却不判断该动作是否值得增加。回报或优势提供更新的正负与强度。', '二者相乘后，一条轨迹才成为目标梯度的随机估计：结果好于基线的动作被强化，结果较差的动作被抑制。'])],
  sections: [section('softmax', '常用参数化', '提高一个动作的概率必然挤压其他动作', ['提高某个动作的 logit 会增大它的概率，同时通过共同的归一化分母降低其他动作的相对概率；一次更新因此是在动作之间重新分配概率质量。', '当某个动作已经接近必选时，相同 logit 变化带来的概率增量会变小。这正是交互实验中更新幅度依赖起始策略的原因。'], String.raw`\pi_\theta(a\mid s)=\frac{e^{h_\theta(s,a)}}{\sum_b e^{h_\theta(s,b)}}`), section('variance', '方差来源', '完整回报把后续随机性带回每个早期动作', ['同一个动作可能因为后续决策和环境转移不同而得到差异很大的回报，因此单条轨迹给出的梯度具有较高方差。', '增加轨迹数量可以平均噪声；减去与动作无关的基线能在保持期望不变的同时降低方差；更及时的评价器则以一定估计偏差换取更低方差。']), section('forward', '下一步', '把状态基线学出来，才能在每次转移后更新', ['REINFORCE 必须等一条轨迹结束后才能得到完整回报，而且同一段遥远结果会同时影响许多早期动作。', 'Actor–Critic 学习状态价值作为基线，并用时序差分误差近似优势。策略梯度的方向没有改变，但每次环境转移后都能得到更新权重。'])],
  summary: ['Policy Gradient 直接优化参数化动作概率。', 'policy gradient theorem 把长期目标梯度写成可采样期望。', 'REINFORCE 用 return 加权对数概率梯度。', '状态 baseline 保持期望不变并降低方差。'], explorer: { cue: '先看权重相对 baseline 的正负，再看当前动作概率；二者共同决定这一步概率移动的方向和幅度。' },
}, {
  prerequisite: 'Prerequisites: parameterized functions, probability distributions, and gradient ascent', eyebrow: 'Part III · Optimize policy directly', title: 'How can high-return actions become more probable?', intro: 'Value methods learn Q and derive a policy with argmax. Policy Gradient directly parameterizes action probabilities and differentiates average value or reward. An action with an outcome above baseline moves along its log-probability gradient; a worse outcome moves in the opposite direction.', bridge: 'Start from a scalar policy objective, apply the policy-gradient theorem and log-derivative trick, and obtain a sample-based REINFORCE update.',
  experimentIntro: 'The Policy Gradient Lab assigns a separate three-action distribution to every visited state and lists each step’s return, advantage, and gradient contribution. Selecting a decision reveals its probability redistribution; a fixed-state multi-rollout ledger then compares gradient variance before and after the state baseline.', interpretation: 'One update changes only the policy parameters associated with the selected state, while softmax redistributes mass among that state’s actions. The single trajectory explains where each step contribution comes from; repeated rollouts expose fluctuation in one fixed gradient coordinate and how a suitable state baseline reduces it without changing the expected direction.',
  figure: 'Interactive Figure 12.1 · Policy Gradient Probability Redistribution Lab', instruction: 'Select one decision and compare all three action probabilities before and after the update', question: 'How can one sample change the whole action distribution while preserving a total probability of one?',
  deepening: policyGradientDeepeningEn,
  derivation: [step('objective', 'Define a scalar policy objective', String.raw`J(\theta)=\mathbb E_{S\sim\eta_\theta}\left[v^{\pi_\theta}(S)\right]`, 'θ affects actions and the long-run state distribution.', 'Discounted average value and continuing average reward differ in detail but both support scalar optimization.', [], [[String.raw`\eta_\theta`, 'policy-induced state weighting']]), step('theorem', 'Apply the policy-gradient theorem', String.raw`\nabla_\theta J(\theta)=\sum_s\eta_\theta(s)\sum_a\nabla_\theta\pi_\theta(a\mid s)q^{\pi_\theta}(s,a)`, 'The gradient becomes a weighted state-action sum.', 'The theorem absorbs difficult distribution derivatives into η.', ['π is differentiable'], [[String.raw`q^{\pi_\theta}`, 'current-policy action value']]), step('log-trick', 'Use the score-function identity', String.raw`\nabla_\theta\pi_\theta(a\mid s)=\pi_\theta(a\mid s)\nabla_\theta\log\pi_\theta(a\mid s)`, 'Probability supplies sampling weight and log probability supplies direction.', 'The sum becomes an expectation under the current policy.', [String.raw`\pi_\theta(a\mid s)>0`], [[String.raw`\nabla\log\pi`, 'score function']]), step('sample-gradient', 'Estimate with one trajectory sample', String.raw`\widehat g_t=\nabla_\theta\log\pi_\theta(A_t\mid S_t)G_t`, 'High-return actions raise log probability; low-return actions push the other way.', 'Using full return produces REINFORCE: unbiased but often high variance.', ['trajectory follows the current policy'], [[String.raw`\widehat g_t`, 'sample policy-gradient estimate']]), step('baseline', 'Subtract an action-independent baseline', String.raw`\widehat g_t=\nabla_\theta\log\pi_\theta(A_t\mid S_t)\left(G_t-b(S_t)\right)`, 'Reward actions relative to the usual outcome at that state.', 'The expected score is zero, so a state baseline preserves the expected gradient while reducing variance.', ['b does not depend on A_t'], [[String.raw`b(S_t)`, 'state-dependent baseline']])],
  prelude: [section('value-policy', 'Changed representation', 'Policy becomes a differentiable probability model', ['Value methods estimate Q and apply argmax, a discrete operation that does not naturally represent stochastic behavior or differentiate through action choice.', 'Policy Gradient instead parameterizes π_θ(a|s). Softmax keeps probabilities nonnegative and normalized while allowing gradients to move probability mass continuously.']), section('credit', 'Sample contribution', 'The score sets direction and the long-term outcome sets weight', ['The score function describes how parameters change the sampled action log probability, but it does not say whether that action deserves more probability. Return or advantage supplies the sign and magnitude.', 'Their product turns one trajectory into a stochastic objective-gradient estimate: outcomes above baseline reinforce the action, while worse outcomes suppress it.'])],
  sections: [section('softmax', 'Common parameterization', 'Softmax conserves probability mass across actions', ['Raising one logit increases its action probability and, through the shared denominator, lowers the relative probabilities of alternatives.', 'When an action is already near probability one, the same logit change produces a smaller probability change. This is why update magnitude depends on the starting policy.'], String.raw`\pi_\theta(a\mid s)=\frac{e^{h_\theta(s,a)}}{\sum_b e^{h_\theta(s,b)}}`), section('variance', 'Variance', 'Long-term outcomes carry future randomness back to early actions', ['The same action can receive very different returns because later actions and transitions differ, so a single-trajectory gradient has high variance.', 'More trajectories average noise, an action-independent baseline preserves expectation while reducing variance, and a timely critic trades some estimation bias for a less variable weight.']), section('forward', 'Next step', 'A critic turns the baseline into a learned timely signal', ['REINFORCE waits for episode termination and applies one long return to many actions.', 'Actor–Critic learns state value as a baseline and uses TD error to approximate advantage. The policy-gradient direction remains, but a weight becomes available after each transition.'])],
  summary: ['Policy Gradient directly optimizes action probabilities.', 'The theorem expresses a long-term gradient as a sampleable expectation.', 'REINFORCE weights log-probability gradients by return.', 'A state baseline preserves expectation and lowers variance.'], explorer: { cue: 'Read the weight relative to baseline first, then current action probability; together they set direction and magnitude.' },
})

export const actorCriticChapter = chapter('actorcritic', [source('ac', 'Actor-Critic Methods', 'L10, pp.6–43')], {
  prerequisite: '前置：策略梯度、状态价值与时序差分误差', eyebrow: 'Part III · 策略与价值协作', title: '评价器怎样给策略更及时、低方差的学习信号？', intro: 'REINFORCE 要等完整回报才能更新策略，信号来得晚且方差较高。Actor–Critic 把职责分开：Actor 表示策略并决定动作概率，Critic 估计状态价值。一次环境转移产生的时序差分误差既能修正 Critic，也能近似该动作相对通常水平的优势，从而更新 Actor。', bridge: '最直接的动作价值加权仍会把同一状态下的共同回报波动传给策略。减去只依赖状态的参照值后，权重变成优势；再用一步时序差分误差估计它，就形成每次转移都能运行的闭环。',
  experimentIntro: 'Actor–Critic 实验室沿一次环境转移同步展开两条更新账本：Critic 显示当前价值、一步目标、修正量与更新后价值；Actor 显示三个动作的 logit 和概率在更新前后的变化。改变奖励、后继状态价值与重要性比率，可以确认两条路径共享误差数值，却分别作用于不同参数。', interpretation: '正误差会抬高 Critic 对当前状态的价值估计，同时提高 Actor 中已采样动作的概率；负误差则让两者反向调整。账本还显示未采样动作如何因 softmax 归一化而变化，因此“Actor 更新”不再只是一个抽象步长。重要性比率只在行为策略与目标策略不同时需要，过大的比率会成比例放大整条策略更新。',
  figure: '交互图 13.1 · Actor–Critic 单步更新闭环', instruction: '按一步目标、误差、Critic 更新、Actor 更新的顺序追踪计算', question: '为什么同一个误差数值可以训练两个网络，却不能共享同一条梯度路径？',
  deepening: actorCriticDeepeningZh,
  derivation: [step('q-gradient', '从动作价值加权的策略梯度开始', String.raw`\nabla_\theta J(\theta)=\mathbb E\left[\nabla_\theta\log\pi_\theta(A_t\mid S_t)q^{\pi}(S_t,A_t)\right]`, 'Actor 的方向由 score function 与动作价值共同决定。', '直接学习 q 可以形成最简单的 Q Actor–Critic，但 action value 估计仍可能方差较高。', [], [[String.raw`\theta`, 'Actor 参数']]), step('baseline-invariance', '减去不依赖动作的 state baseline', String.raw`\mathbb E_{A\sim\pi}\left[\nabla_\theta\log\pi_\theta(A\mid s)b(s)\right]=0`, 'baseline 项在动作期望下消失。', '因此可以选择 b(s)=vπ(s) 而不改变梯度期望，用状态平均水平消除共同波动。', ['b 与动作 A 无关'], [[String.raw`b(s)`, '方差降低基线']]), step('advantage', '把梯度权重写成 advantage', String.raw`A^{\pi}(s,a)=q^{\pi}(s,a)-v^{\pi}(s)`, '动作只需相对该状态的平均表现更好。', '这使 Actor 的更新关注“选择这个动作比平常好多少”，而不是回报的绝对尺度。', [], [[String.raw`A^{\pi}`, '动作相对状态平均水平的优势']]), step('td-advantage', '用一步 TD error 近似 advantage', String.raw`\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t)\approx A^{\pi}(S_t,A_t)`, '一次转移结束后即可得到低延迟权重。', '若 Critic 准确，给定状态与动作时 TD error 的条件期望等于 advantage。', ['Vφ 逼近当前策略的 state value'], [[String.raw`\phi`, 'Critic 参数']]), step('two-updates', '让一个误差驱动两组参数', String.raw`\phi\leftarrow\phi+\alpha_v\delta_t\nabla_\phi V_\phi(S_t),\qquad\theta\leftarrow\theta+\alpha_\pi\delta_t\nabla_\theta\log\pi_\theta(A_t\mid S_t)`, 'Critic 减小 value error，Actor 改变动作概率。', '两者在每个 transition 后形成闭环。Actor 改变数据分布，Critic 随之重新估计新策略。', [], [[String.raw`\alpha_v`, 'Critic 步长'], [String.raw`\alpha_\pi`, 'Actor 步长']]), step('importance', '用 importance ratio 处理 behavior 数据', String.raw`\rho_t=\frac{\pi_\theta(A_t\mid S_t)}{b(A_t\mid S_t)},\qquad\Delta\theta\propto\rho_t\delta_t\nabla_\theta\log\pi_\theta(A_t\mid S_t)`, 'ratio 把 behavior policy 下的动作样本重新加权到 target policy。', '当 π 与 b 差异很大时，ratio 的高方差会使更新不稳定；现代方法会限制策略偏移。', [String.raw`b(A_t\mid S_t)>0\ \text{whenever }\pi_\theta(A_t\mid S_t)>0`], [[String.raw`\rho_t`, '动作概率的重要性比率']])],
  prelude: [section('roles', '两种职责', 'Actor 决定动作分布，Critic 估计当前预期', ['Actor 用参数 θ 表示策略并负责采样动作；Critic 用参数 φ 估计状态价值，但不替 Actor 选择动作。', 'Critic 的作用是为结果建立参照：实际一步结果高于当前预期时，Actor 应提高该动作概率；低于预期时则反向调整。']), section('timing', '同一步闭环', '一次环境转移同时产生两组参数的学习信号', ['环境返回奖励和下一状态后，Critic 可以构造一步目标与时序差分误差，并用这个误差修正当前状态价值。', '同一个误差又能近似当前动作的优势，因此立即更新 Actor。更及时的信号降低了完整回报的方差，但也会继承当前价值估计带来的自举偏差。'])],
  sections: [section('variance-bias', '权衡', 'Critic 用可学习估计替代高方差的完整回报', ['完整回报作为策略梯度权重通常无偏，但包含整段未来轨迹的随机性；时序差分误差只使用一步奖励与后继状态价值，因此方差更低。', 'Critic 不准确时，优势估计会偏离真实值；随着状态价值估计改善，Actor 的更新权重也会更可靠。这是用可学习偏差换取较低方差。'], String.raw`\mathbb E[\delta_t\mid s,a]\approx A^{\pi}(s,a)`), section('two-timescales', '耦合训练', 'Actor 与 Critic 必须在相容的时间尺度上变化', ['Critic 太慢时，Actor 会持续收到过时的参照值；Actor 太快时，策略不断改变访问分布，Critic 便只能追逐一个快速移动的评价对象。', '实践中通常为两者设置不同步长或更新次数，并同时监测价值误差、策略熵与优势分布，不能只看总回报。']), section('forward', '进入 PPO', '重复使用旧策略数据时必须限制策略移动', ['基础 Actor–Critic 最自然地使用当前策略刚采到的数据；对同一批样本做多轮更新后，新策略会逐渐偏离产生这些样本的策略。', '重要性比率可以校正动作概率变化，但比率过大会放大方差。PPO 保存旧策略概率，并通过裁剪替代目标，取消继续远离采样策略所带来的额外收益。'])],
  summary: ['Actor 参数化策略，Critic 估计 state value。', 'state baseline 保持策略梯度期望并降低方差。', 'TD error 是及时的 advantage 样本近似。', '一个 transition 同时产生 Critic 与 Actor 更新。', 'importance ratio 为 off-policy 与 PPO 建立接口。'], explorer: { cue: '按 TD target → δ → Critic step → Actor step 的顺序读图；两次更新共享误差，但梯度对象不同。' },
}, {
  prerequisite: 'Prerequisites: Policy Gradient, state value, and TD error', eyebrow: 'Part III · Policy and value cooperate', title: 'How does a critic give the actor timely, lower-variance feedback?', intro: 'REINFORCE waits for complete returns and often has high variance. Actor–Critic separates roles: the actor parameterizes action probabilities, the critic learns state value, and one transition produces a TD error that updates the critic and approximates advantage for the actor.', bridge: 'Start from action-value-weighted policy gradient, subtract a state baseline, obtain advantage, and use TD error to update actor and critic together.',
  experimentIntro: 'The Actor–Critic Lab expands one transition into synchronized update ledgers. The critic shows value before, one-step target, correction, and value after; the actor shows all three logits and probabilities before and after. Vary reward, successor value, and importance ratio to verify that both paths share one error but act on different parameters.', interpretation: 'A positive error raises the critic’s current-state estimate and the actor’s sampled-action probability; a negative error reverses both. The actor ledger also exposes how softmax normalization moves the unselected actions, replacing an abstract scalar “actor step” with a complete policy change. Importance correction is needed only for behavior-policy data and scales the entire policy update.',
  figure: 'Interactive Figure 13.1 · Actor–Critic Loop', instruction: 'Trace one transition through critic and actor updates', question: 'Why can one TD error train both value and policy?',
  deepening: actorCriticDeepeningEn,
  derivation: [step('q-gradient', 'Start from action-value policy gradient', String.raw`\nabla_\theta J(\theta)=\mathbb E\left[\nabla_\theta\log\pi_\theta(A_t\mid S_t)q^{\pi}(S_t,A_t)\right]`, 'The actor direction combines score and action value.', 'Learning q directly gives Q Actor–Critic but can retain high variance.', [], [[String.raw`\theta`, 'actor parameters']]), step('baseline-invariance', 'Subtract an action-independent baseline', String.raw`\mathbb E_{A\sim\pi}\left[\nabla_\theta\log\pi_\theta(A\mid s)b(s)\right]=0`, 'The baseline term vanishes in expectation over actions.', 'Choose b(s)=vπ(s) to remove state-level common variation.', ['b is independent of A'], [[String.raw`b(s)`, 'variance-reduction baseline']]), step('advantage', 'Express the weight as advantage', String.raw`A^{\pi}(s,a)=q^{\pi}(s,a)-v^{\pi}(s)`, 'An action matters relative to the state average.', 'The actor now responds to how much better the action is than usual.', [], [[String.raw`A^{\pi}`, 'relative action quality']]), step('td-advantage', 'Approximate advantage with TD error', String.raw`\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t)\approx A^{\pi}(S_t,A_t)`, 'The weight is available after one transition.', 'With an accurate critic, conditional expected TD error equals advantage.', ['Vφ approximates current-policy state value'], [[String.raw`\phi`, 'critic parameters']]), step('two-updates', 'Drive two parameter updates with one error', String.raw`\phi\leftarrow\phi+\alpha_v\delta_t\nabla_\phi V_\phi(S_t),\qquad\theta\leftarrow\theta+\alpha_\pi\delta_t\nabla_\theta\log\pi_\theta(A_t\mid S_t)`, 'The critic reduces value error and the actor changes action probability.', 'Both update after every transition; actor changes the data distribution that critic must track.', [], [[String.raw`\alpha_v`, 'critic step size'], [String.raw`\alpha_\pi`, 'actor step size']]), step('importance', 'Correct behavior-policy data', String.raw`\rho_t=\frac{\pi_\theta(A_t\mid S_t)}{b(A_t\mid S_t)},\qquad\Delta\theta\propto\rho_t\delta_t\nabla_\theta\log\pi_\theta(A_t\mid S_t)`, 'The ratio reweights behavior actions toward the target policy.', 'Large policy mismatch produces high-variance ratios and motivates constrained policy updates.', [String.raw`b(A_t\mid S_t)>0\ \text{whenever }\pi_\theta(A_t\mid S_t)>0`], [[String.raw`\rho_t`, 'importance ratio']])],
  prelude: [section('roles', 'Two parameter sets', 'The actor sets action probabilities; the critic estimates expectation', ['The actor uses θ to represent the policy and sample actions. The critic uses w to estimate state value but does not choose actions for the actor.', 'Its role is to establish a reference: an outcome above current expectation should raise the sampled action probability, while an outcome below expectation should lower it.']), section('timing', 'One-step loop', 'One transition supplies learning signals to both parameter sets', ['After reward and successor state arrive, the critic forms a TD target and error and uses that error to revise current state value.', 'The same TD error approximates action advantage and can update the actor immediately. Timeliness reduces return variance while introducing bootstrap bias from the current value estimate.'])],
  sections: [section('variance-bias', 'Tradeoff', 'The critic replaces a high-variance return with a learned estimate', ['A complete return is typically unbiased for the policy-gradient weight but includes randomness from the entire future. TD error uses one reward and successor value and therefore has lower variance.', 'An inaccurate critic biases the advantage estimate; as value prediction improves, actor weights become more reliable. The mechanism explicitly exchanges learnable bias for variance.'], String.raw`\mathbb E[\delta_t\mid s,a]\approx A^{\pi}(s,a)`), section('two-timescales', 'Coupled training', 'Actor and critic must move on compatible time scales', ['A slow critic gives the actor stale baselines. A fast actor continually changes the visitation distribution that the critic is trying to evaluate.', 'Implementations therefore tune separate learning rates or update counts and inspect value error, policy entropy, and the advantage distribution rather than relying on total reward alone.']), section('forward', 'Toward PPO', 'Old-policy data reuse requires controlling policy movement', ['Basic Actor–Critic most naturally uses data sampled by the current policy. Repeated updates on one batch progressively separate the new policy from that data distribution.', 'Importance ratios correct action-probability changes but can amplify variance when large. PPO stores old probabilities and clips further surrogate gains from moving too far away.'])],
  summary: ['Actor parameterizes policy; critic estimates state value.', 'A state baseline preserves expected policy gradient and lowers variance.', 'TD error is a timely advantage estimate.', 'One transition drives critic and actor updates.', 'Importance ratios connect Actor–Critic to PPO.'], explorer: { cue: 'Read TD target → δ → critic step → actor step; the error is shared, but each update differentiates a different function.' },
})

Object.assign(vfaChapter.zh, { title: '通过共享参数在状态之间传播价值信息' })
Object.assign(vfaChapter.en, { title: 'Transferring value across states with shared parameters' })
Object.assign(dqnChapter.zh, { title: '目标网络与经验回放的稳定化分工' })
Object.assign(dqnChapter.en, { title: 'Distinct stabilization roles of target networks and replay' })
Object.assign(policyGradientChapter.zh, { title: '让高回报动作在策略中更常出现' })
Object.assign(policyGradientChapter.en, { title: 'Directly increasing the probability of high-return actions' })
Object.assign(actorCriticChapter.zh, { title: '用状态价值给策略提供及时、低方差的反馈' })
Object.assign(actorCriticChapter.en, { title: 'Timely, lower-variance actor feedback from a critic' })
Object.assign(monteCarloChapter.zh, { eyebrow: '第 6 章 · Monte Carlo 经验估计' })
Object.assign(monteCarloChapter.en, { eyebrow: 'Chapter 6 · Monte Carlo estimation from experience' })
Object.assign(tdChapter.zh, { eyebrow: '第 8 章 · TD 单步预测', derivationEyebrow: '单步 Bellman 残差', derivationTitle: '从一次环境转移得到 TD(0) 更新' })
Object.assign(tdChapter.en, { eyebrow: 'Chapter 8 · One-step TD prediction', derivationEyebrow: 'One-step Bellman residual', derivationTitle: 'Derive a TD(0) update from one transition' })
Object.assign(controlChapter.zh, { eyebrow: '第 9 章 · Sarsa 与 Q-learning 控制', derivationEyebrow: '动作价值控制', derivationTitle: '从动作价值评价得到 Sarsa 与 Q-learning 更新' })
Object.assign(controlChapter.en, { eyebrow: 'Chapter 9 · Sarsa and Q-learning control', derivationEyebrow: 'Action-value control', derivationTitle: 'Derive Sarsa and Q-learning updates from action-value evaluation' })
Object.assign(vfaChapter.zh, { eyebrow: '第 10 章 · 价值函数近似', derivationEyebrow: '参数共享', derivationTitle: '从参数化价值误差得到半梯度更新' })
Object.assign(vfaChapter.en, { eyebrow: 'Chapter 10 · Value-function approximation', derivationEyebrow: 'Parameter sharing', derivationTitle: 'Derive a semi-gradient update from parameterized value error' })
Object.assign(dqnChapter.zh, { eyebrow: '第 11 章 · 深度 Q-learning', derivationEyebrow: '稳定化训练步', derivationTitle: '把冻结目标与经验回放写入同一次 Q-learning 更新' })
Object.assign(dqnChapter.en, { eyebrow: 'Chapter 11 · Deep Q-learning', derivationEyebrow: 'A stabilized training step', derivationTitle: 'Put a frozen target and replay into one Q-learning update' })
Object.assign(policyGradientChapter.zh, { eyebrow: '第 12 章 · 策略梯度', derivationEyebrow: '轨迹梯度估计', derivationTitle: '从策略目标得到可由轨迹估计的梯度' })
Object.assign(policyGradientChapter.en, { eyebrow: 'Chapter 12 · Policy gradient', derivationEyebrow: 'Trajectory gradient estimation', derivationTitle: 'Turn a policy objective into a trajectory-estimated gradient' })
Object.assign(actorCriticChapter.zh, { eyebrow: '第 13 章 · Actor–Critic', derivationEyebrow: '协同更新', derivationTitle: '从状态基线推导两组参数的单步更新' })
Object.assign(actorCriticChapter.en, { eyebrow: 'Chapter 13 · Actor–Critic', derivationEyebrow: 'Coupled updates', derivationTitle: 'Use TD error to update the critic and actor together' })
Object.assign(monteCarloChapter.zh, { summaryTitle: '从完整经验到可改进的动作价值' })
Object.assign(monteCarloChapter.en, { summaryTitle: 'From complete experience to improvable action values' })
Object.assign(tdChapter.zh, { summaryTitle: '从完整回报到单步自举' })
Object.assign(tdChapter.en, { summaryTitle: 'From complete returns to one-step bootstrapping' })
Object.assign(controlChapter.zh, { summaryTitle: '从策略内更新到策略外控制' })
Object.assign(controlChapter.en, { summaryTitle: 'From on-policy updates to off-policy control' })
Object.assign(vfaChapter.zh, { summaryTitle: '从逐状态表格到参数共享' })
Object.assign(vfaChapter.en, { summaryTitle: 'From state tables to shared parameters' })
Object.assign(dqnChapter.zh, { summaryTitle: '从 Q-learning 到稳定的深度价值更新' })
Object.assign(dqnChapter.en, { summaryTitle: 'From Q-learning to stable deep value updates' })
Object.assign(policyGradientChapter.zh, { summaryTitle: '从价值比较到直接优化策略' })
Object.assign(policyGradientChapter.en, { summaryTitle: 'From value comparison to direct policy optimization' })
Object.assign(actorCriticChapter.zh, { summaryTitle: '从高方差回报到及时的 Actor–Critic 信号' })
Object.assign(actorCriticChapter.en, { summaryTitle: 'From high-variance returns to timely actor–critic signals' })

export const part23Chapters = [monteCarloChapter, approximationChapter, tdChapter, controlChapter, vfaChapter, dqnChapter, policyGradientChapter, actorCriticChapter]
