import {
  approximationDeepeningEn,
  approximationDeepeningZh,
  controlDeepeningEn,
  controlDeepeningZh,
  tdDeepeningEn,
  tdDeepeningZh,
} from './deepening-part23.js'
import {
  actorCriticDeepeningEn,
  actorCriticDeepeningZh,
  dqnDeepeningEn,
  dqnDeepeningZh,
  policyGradientDeepeningEn,
  policyGradientDeepeningZh,
  vfaDeepeningEn,
  vfaDeepeningZh,
} from './deepening-part3.js'

const book = 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning'

const source = (id, label, pages) => ({ id, label, pages, href: book })
const section = (id, kicker, title, paragraphs, formula) => ({ id, kicker, title, paragraphs, ...(formula ? { formula } : {}) })
const step = (id, rule, latex, short, detail, assumptions, symbols) => ({ id, rule, latex, short, detail, assumptions, symbols })

function chapter(id, sources, zh, en) {
  return { id, sources, zh, en }
}

export const monteCarloChapter = chapter('montecarlo', [source('mc', 'Monte Carlo Learning', 'L5, pp.5–47')], {
  prerequisite: '前置：Return、动作价值与策略迭代', eyebrow: 'Part II · 从模型转向经验', title: '利用完整经历进行无模型价值估计',
  intro: '动态规划的策略迭代知道环境模型，因此可以在策略评价时枚举所有后继并计算期望。现实交互往往只给出真正发生的一条状态—动作—奖励序列。Monte Carlo 的关键不是“换一个公式”，而是回答：模型未知以后，策略评价还能依靠什么证据完成？',
  bridge: '答案从一条完整 episode 开始：return 是动作价值的随机样本，样本平均替代精确期望；随后每一个算法变体都在修复前一种方法的数据效率或覆盖假设。', experimentIntro: '下面不再只画一条估计曲线，而是把同一批经验拆成 episode tape、访问热图、Q 更新账本与改进后的策略分布。',
  interpretation: 'MC Basic 最贴近策略迭代的定义，却浪费 episode 中的大量访问；Exploring Starts 复用整条轨迹，却要求能够控制起始状态—动作；ε-greedy 取消这一假设，却用持续探索换取覆盖。算法族的变化由失败模式推动，而不是三个平行名称。',
  figure: '交互图 06.1 · Monte Carlo 算法族实验室', instruction: '切换三种算法，检查数据复用、覆盖、Q 更新与策略分布怎样一起变化', question: '怎样在没有模型的前提下，同时得到可用的价值估计和足够的探索？',
  reasoningPath: [
    section('planning-limit', '出发点', '策略迭代的哪一步失效了？', ['策略改善仍然可以对当前动作价值取最大值；真正失效的是策略评价：未知转移概率时，Bellman 方程右侧的期望无法被直接展开。', '因此 model-free 方法不需要重新定义价值，而要重新设计获得价值证据的方式。'], String.raw`q^{\pi}(s,a)=\mathbb E_{\pi}[G_t\mid S_t=s,A_t=a]`),
    section('sample-evidence', '证据替换', '一条 episode 为什么能提供价值样本？', ['给定起点 (s,a) 并遵循策略 π，后续动作与环境响应共同生成一条随机未来。该未来的 return 是随机变量 G_t 的一次实现。', '重复获得同条件下的 episode，就能用经验平均逼近条件期望；这正是 MC 评价与模型求和之间的接口。']),
    section('control-loop', '从评价到控制', '估计 Q 以后为什么还要改善策略？', ['只估计 q^π 得到的是当前策略的质量，不会自动得到更好的策略。MC 控制沿用策略迭代的两步闭环：先从经验评价，再让策略偏向当前更高的动作价值。', '困难随即变成：如果改善得过于贪心，后续数据是否还会覆盖那些暂时看起来较差的动作？'], String.raw`\pi_k\xrightarrow{\text{episodes}}\widehat q_{\pi_k}\xrightarrow{\text{improvement}}\pi_{k+1}`),
  ],
  algorithms: [
    { id: 'basic', label: 'MC Basic', premise: '直接把 model-based policy iteration 的策略评价换成 episode 平均。', solves: '不需要环境模型即可估计 q^π。', limitation: '每次只使用指定起始 (s,a) 的 return，途中访问全部被浪费；还要求为每个 (s,a) 收集足够多的专门 episode。', pseudocode: ['初始化策略 π₀', '对每轮 k：', '  对每个状态 s 与动作 a：', '    收集大量从 (s,a) 出发并遵循 πₖ 的 episode', '    qₖ(s,a) ← 这些 episode return 的平均', '  对每个状态 s：', '    a* ← arg maxₐ qₖ(s,a)', '    πₖ₊₁(a*|s) ← 1，其余动作概率置 0'] },
    { id: 'exploring', label: 'MC Exploring Starts', premise: '一条 episode 途中会访问许多状态—动作对；把这些访问全部变成训练证据。', solves: 'first-visit 或 every-visit 更新显著提高数据利用率；随机起始对保证所有 (s,a) 有机会被采样。', limitation: '需要人为选择任意起始状态—动作。在真实系统中，这个 exploring-starts 假设往往不可实现。', pseudocode: ['初始化 π、Q、Returns(s,a) 与 N(s,a)', '对每条 episode：', '  随机选择可覆盖任意 (s₀,a₀) 的起始对', '  遵循当前策略生成完整 episode', '  G ← 0', '  从 T−1 到 0 反向扫描：', '    G ← γG + Rₜ₊₁', '    若满足访问协议：更新 Returns、N 与 Q=Returns/N', '  对本条 episode 访问到的状态做贪心策略改善'] },
    { id: 'epsilon', label: 'MC ε-Greedy', premise: '不再要求特殊起点，而让行为策略本身持续给所有动作正概率。', solves: '足够长的采样过程可以从普通起点访问不同状态—动作对，移除 exploring-starts 假设。', limitation: 'ε>0 意味着策略会持续选择非贪心动作；它优化的是 ε-soft 策略集合，而非全部确定性策略。', pseudocode: ['初始化 ε-soft 策略 π、Q、Returns(s,a) 与 N(s,a)', '对每条 episode：', '  从普通起点按 π 生成完整 episode', '  G ← 0', '  从 T−1 到 0 反向扫描：', '    G ← γG + Rₜ₊₁', '    若满足访问协议：更新 Returns、N 与 Q=Returns/N', '  对访问到的每个状态：', '    a* ← arg maxₐ Q(s,a)', '    π(a*|s) ← 1−ε+ε/|A|', '    π(a|s) ← ε/|A|, a≠a*'] },
  ],
  derivation: [
    step('value-definition', '从动作价值的定义开始', String.raw`q^{\pi}(s,a)=\mathbb E_{\pi}[G_t\mid S_t=s,A_t=a]`, '动作价值是从指定状态和动作出发的 return 条件期望。', '策略决定后续动作，环境决定后续转移；未知模型使这个期望无法直接求和，但定义本身没有改变。', ['episode 最终结束或 return 有界'], [[String.raw`G_t`, '一条 episode 中从时刻 t 开始的 return']]),
    step('episode-sample', '用完整 episode 产生样本', String.raw`G_t^{(i)}=\sum_{k=0}^{T_i-t-1}\gamma^kR_{t+k+1}^{(i)}`, '第 i 条 episode 为被访问的状态—动作对提供一个 return 样本。', '必须等待终点，才能知道该时刻之后的全部奖励。这里的 T_i 是该条 episode 的结束时刻。', ['episode i 确实访问了 (s,a)'], [[String.raw`T_i`, '第 i 条 episode 的终止时刻']]),
    step('sample-average', '用大数定律替代未知期望', String.raw`\widehat q_N(s,a)=\frac{1}{N(s,a)}\sum_{i=1}^{N(s,a)}G_t^{(i)}`, '对同一状态—动作对的 return 样本取平均。', '在访问样本满足适当独立性且覆盖持续增加时，样本均值逼近动作价值。N(s,a) 只统计协议选中的访问。', ['每个需要估计的 (s,a) 被反复访问'], [[String.raw`N(s,a)`, '被纳入估计的访问次数']]),
    step('incremental-mean', '把批量平均改写成增量更新', String.raw`\widehat q_N=\widehat q_{N-1}+\frac{1}{N}\left(G_N-\widehat q_{N-1}\right)`, '无需保存全部历史 return，只保存计数与当前估计。', '新样本与旧估计之差是估计误差；步长 1/N 恰好让递推结果等于算术平均。', ['N 从 1 递增'], [[String.raw`G_N-\widehat q_{N-1}`, '第 N 个样本产生的估计误差']]),
    step('policy-improvement', '把经验评价接回策略迭代', String.raw`a^*(s)\in\arg\max_a \widehat q_k(s,a),\qquad \pi_{k+1}(a\mid s)=\mathbf 1[a=a^*(s)]`, '当前估计最高的动作成为下一轮策略的选择。', 'MC 只替换策略评价的数据来源；策略改善仍使用动作价值排序。问题是确定性贪心会让其他动作失去后续样本。', ['每个状态至少有一个可比较的动作估计'], [[String.raw`a^*(s)`, '当前贪心动作']]),
    step('epsilon-greedy', '用软策略保证探索', String.raw`\pi(a\mid s)=\begin{cases}1-\epsilon+\epsilon/|\mathcal A|,&a\in\arg\max_b q(s,b),\\\epsilon/|\mathcal A|,&\text{otherwise},\end{cases}`, '大部分时间利用当前最好动作，同时保留访问其他动作的正概率。', '纯贪心策略可能永远看不到早期估计较低的动作。ε-greedy 通过持续探索为后续控制算法提供覆盖。', [String.raw`0<\epsilon\le 1`], [[String.raw`\epsilon`, '用于探索的概率质量']]),
  ],
  prelude: [section('model-to-data', '问题改变', '精确求和被经验样本替代', ['已知模型时可以枚举所有后继；model-free 学习只能看到实际发生的一条分支。']), section('episode-unit', '数据单位', '完整 episode 是一次可计算 return 的证据', ['MC 不在中途 bootstrap，因此目标由真实后续奖励组成。'])],
  sections: [section('visit-protocol', '数据复用', '首次访问与每次访问不是两个孤立名词', ['MC Basic 只使用起始对，相当于更严格的 initial-visit。first-visit 让每条 episode 对同一 (s,a) 至多贡献一次，every-visit 则保留所有出现。它们都在回答：同一条轨迹内部的相关访问应怎样计权？'], String.raw`N_{\mathrm{initial}}(s,a)\le N_{\mathrm{first}}(s,a)\le N_{\mathrm{every}}(s,a)`), section('coverage', '探索前提', '没有覆盖，就没有可靠的贪心改善', ['如果某个动作从未被访问，它的 Q 值只是初值；纯贪心策略可能把一次偶然低估永久固化。Exploring Starts 从起点保证覆盖，ε-soft 策略从整个行为过程保证覆盖。'], String.raw`\pi(a\mid s)>0\quad\forall(s,a)`), section('optimality', '能力边界', 'ε-greedy 的优势与代价必须同时看到', ['更大的 ε 带来更强覆盖，却让策略更频繁执行非贪心动作。固定 ε 下得到的是 ε-soft 策略类中的最优解；若要逼近全局贪心最优，通常需要让 ε 随训练逐渐减小，同时仍保证充分探索。'], String.raw`\epsilon_k\to 0,\qquad \sum_k\epsilon_k=\infty`), section('consistency', '一致性问题', '最优 ε-greedy 策略不一定与全局最优贪心策略一致', ['软策略改变了未来状态分布：即使当前状态选择同一个贪心动作，后续仍可能随机进入禁区或离开目标。因此它评价和优化的是另一套受探索约束的长期行为。', '这解释了为什么探索不是算法外的“小技巧”，而是目标集合与数据分布的一部分。']), section('forward', '下一步', '样本平均只是随机逼近的一种步长', ['1/N 让所有历史样本等权，适合固定目标；持续变化的策略和环境往往需要更一般的步长。下一章将从均值递推抽象出 Robbins–Monro 随机逼近。'])],
  summary: ['MC 保留价值定义，只把模型期望替换为完整 episode 的 return 样本。', 'MC Basic、Exploring Starts 与 ε-greedy 是一条由数据效率和覆盖假设推动的演化链。', 'first-visit 与 every-visit 决定同一 episode 内的证据怎样计权。', 'ε-soft 策略用持续探索换取覆盖，也因此改变可达到的最优策略集合。', '只有同时检查估计、覆盖、策略改善与假设，才真正理解 MC 控制。'], explorer: { cue: '依次切换三种算法；不要只看 Q 数值，还要同时检查访问热图、更新账本和动作概率。' },
}, {
  prerequisite: 'Prerequisites: return, action value, and policy iteration', eyebrow: 'Part II · From models to experience', title: 'Model-free value estimation from complete experience',
  intro: 'Dynamic-programming policy iteration knows the environment model and can enumerate successors during policy evaluation. Real interaction reveals only the state-action-reward sequence that actually occurred. Monte Carlo is not merely a new formula; it answers what evidence can replace model-based policy evaluation.',
  bridge: 'A complete episode supplies a realized return. Sample means replace exact expectations, and each algorithmic variant then repairs a data-efficiency or coverage failure in its predecessor.', experimentIntro: 'The lab exposes the same data as an episode tape, visit heatmap, Q-update ledger, and improved policy distribution.',
  interpretation: 'MC Basic mirrors policy iteration but wastes intermediate visits. Exploring Starts reuses the full trajectory but assumes control over the initial pair. ε-greedy removes that assumption by keeping exploration alive, at the cost of optimizing within a soft-policy class.',
  figure: 'Interactive Figure 06.1 · Monte Carlo Algorithm Family Lab', instruction: 'Switch algorithms and inspect data reuse, coverage, Q updates, and policy probabilities', question: 'How can model-free control obtain both usable estimates and sufficient exploration?',
  reasoningPath: [
    section('planning-limit', 'Starting point', 'Which step of policy iteration breaks?', ['Policy improvement can still maximize current action values. Policy evaluation is what fails: without transition probabilities, the Bellman expectation cannot be expanded directly.', 'Model-free learning therefore preserves the definition of value and redesigns how evidence for value is collected.'], String.raw`q^{\pi}(s,a)=\mathbb E_{\pi}[G_t\mid S_t=s,A_t=a]`),
    section('sample-evidence', 'Evidence replacement', 'Why can one episode supply a value sample?', ['Given (s,a) and policy π, future choices and responses generate one random future. Its return is one realization of G_t.', 'Repeated episodes under the same condition let an empirical mean approach the conditional expectation.']),
    section('control-loop', 'Evaluation to control', 'Why improve the policy after estimating Q?', ['Estimating q^π only describes the current policy. MC control retains policy iteration: evaluate from experience, then bias the policy toward actions with larger estimates.', 'The new question is whether a greedy improvement removes the very coverage needed to repair early errors.'], String.raw`\pi_k\xrightarrow{\text{episodes}}\widehat q_{\pi_k}\xrightarrow{\text{improvement}}\pi_{k+1}`),
  ],
  algorithms: [
    { id: 'basic', label: 'MC Basic', premise: 'Replace model-based evaluation with episode averages for each requested pair.', solves: 'Estimate q^π without an environment model.', limitation: 'Intermediate visits are discarded, and every pair needs dedicated starting episodes.', pseudocode: ['Initialize policy π₀', 'For iteration k:', '  For every state s and action a:', '    Collect many episodes starting from (s,a) under πₖ', '    qₖ(s,a) ← average return of those episodes', '  For every state s:', '    a* ← arg maxₐ qₖ(s,a)', '    Set πₖ₊₁(a*|s)=1 and all other probabilities to 0'] },
    { id: 'exploring', label: 'MC Exploring Starts', premise: 'Reuse every state-action visit along an episode.', solves: 'First-visit or every-visit updates improve data use; randomized starting pairs guarantee possible coverage.', limitation: 'The environment must allow arbitrary starting state-action pairs.', pseudocode: ['Initialize π, Q, Returns(s,a), and N(s,a)', 'For each episode:', '  Select a starting pair (s₀,a₀) so every pair is possible', '  Generate a complete episode under the current policy', '  G ← 0', '  Scan backward from T−1 to 0:', '    G ← γG + Rₜ₊₁', '    If allowed by the visit protocol, update Returns, N, and Q=Returns/N', '  Greedily improve the policy at visited states'] },
    { id: 'epsilon', label: 'MC ε-Greedy', premise: 'Keep every action at positive probability instead of requiring special starts.', solves: 'Long ordinary rollouts can cover pairs without an exploring-starts interface.', limitation: 'Persistent ε explores forever and optimizes inside the ε-soft policy class.', pseudocode: ['Initialize ε-soft π, Q, Returns(s,a), and N(s,a)', 'For each episode:', '  Generate a complete episode from an ordinary start under π', '  G ← 0', '  Scan backward from T−1 to 0:', '    G ← γG + Rₜ₊₁', '    If allowed by the visit protocol, update Returns, N, and Q=Returns/N', '  For every visited state:', '    a* ← arg maxₐ Q(s,a)', '    π(a*|s) ← 1−ε+ε/|A|', '    π(a|s) ← ε/|A| for a≠a*'] },
  ],
  derivation: [
    step('value-definition', 'Start from action value', String.raw`q^{\pi}(s,a)=\mathbb E_{\pi}[G_t\mid S_t=s,A_t=a]`, 'Action value is the conditional mean return after a specified state and action.', 'The policy selects later actions and the environment produces later transitions. An unknown model blocks direct summation, not the definition.', ['episodes terminate or returns are bounded'], [[String.raw`G_t`, 'return from time t in one episode']]),
    step('episode-sample', 'Generate a sample with a complete episode', String.raw`G_t^{(i)}=\sum_{k=0}^{T_i-t-1}\gamma^kR_{t+k+1}^{(i)}`, 'Episode i supplies one return sample for a visited pair.', 'The full target is known only after the episode ends. T_i is the terminal time of episode i.', ['episode i visits (s,a)'], [[String.raw`T_i`, 'terminal time of episode i']]),
    step('sample-average', 'Replace expectation by a sample mean', String.raw`\widehat q_N(s,a)=\frac{1}{N(s,a)}\sum_{i=1}^{N(s,a)}G_t^{(i)}`, 'Average return samples for the same state-action pair.', 'With continuing coverage and suitable sampling, the empirical average approaches action value.', ['each required pair is revisited'], [[String.raw`N(s,a)`, 'included visit count']]),
    step('incremental-mean', 'Rewrite the batch mean incrementally', String.raw`\widehat q_N=\widehat q_{N-1}+\frac{1}{N}\left(G_N-\widehat q_{N-1}\right)`, 'Keep only the count and current estimate.', 'The new-sample error corrects the old estimate; step size 1/N exactly reproduces the arithmetic mean.', ['N increases from 1'], [[String.raw`G_N-\widehat q_{N-1}`, 'sample estimation error']]),
    step('policy-improvement', 'Reconnect experience to policy iteration', String.raw`a^*(s)\in\arg\max_a \widehat q_k(s,a),\qquad \pi_{k+1}(a\mid s)=\mathbf 1[a=a^*(s)]`, 'The largest current estimate defines the next greedy policy.', 'MC replaces policy-evaluation evidence; policy improvement still ranks actions. Deterministic greed can remove future samples for alternatives.', ['at least one comparable action estimate per state'], [[String.raw`a^*(s)`, 'current greedy action']]),
    step('epsilon-greedy', 'Maintain coverage with a soft policy', String.raw`\pi(a\mid s)=\begin{cases}1-\epsilon+\epsilon/|\mathcal A|,&a\in\arg\max_b q(s,b),\\\epsilon/|\mathcal A|,&\text{otherwise},\end{cases}`, 'Exploit the current best action while preserving positive probability for alternatives.', 'A purely greedy policy may never repair an unlucky early estimate. ε-greedy keeps exploration alive.', [String.raw`0<\epsilon\le 1`], [[String.raw`\epsilon`, 'probability mass reserved for exploration']]),
  ],
  prelude: [section('model-to-data', 'Changed problem', 'Experience replaces exact summation', ['A known model exposes every successor; model-free learning sees only the branch that happened.']), section('episode-unit', 'Data unit', 'A complete episode makes return observable', ['MC does not bootstrap mid-episode, so its target contains realized future rewards.'])],
  sections: [section('visit-protocol', 'Data reuse', 'Visit protocols are not isolated vocabulary', ['MC Basic uses only the initial pair. First-visit uses a pair once per episode, while every-visit keeps all occurrences. Each choice answers how correlated evidence within one trajectory should be weighted.'], String.raw`N_{\mathrm{initial}}(s,a)\le N_{\mathrm{first}}(s,a)\le N_{\mathrm{every}}(s,a)`), section('coverage', 'Exploration premise', 'Greedy improvement is unreliable without coverage', ['An unvisited action retains only its initialization. Exploring Starts enforces coverage at the start; ε-soft behavior enforces it throughout interaction.'], String.raw`\pi(a\mid s)>0\quad\forall(s,a)`), section('optimality', 'Boundary', 'ε-greedy has both an advantage and a cost', ['Larger ε improves coverage but executes non-greedy actions more often. Fixed ε optimizes within the ε-soft class; approaching globally greedy optimality usually requires decreasing ε while preserving infinite exploration.'], String.raw`\epsilon_k\to 0,\qquad \sum_k\epsilon_k=\infty`), section('consistency', 'Consistency', 'An optimal ε-greedy policy need not match the globally greedy optimum', ['Soft behavior changes the future state distribution. Even if the current greedy action agrees, later random actions can enter forbidden cells or leave the target. Exploration is therefore part of the objective class and data distribution, not an external trick.']), section('forward', 'Next step', 'The sample mean is one stochastic-approximation schedule', ['Step size 1/N weights all historical samples equally. The next chapter abstracts this recursion into Robbins–Monro updates for more general learning dynamics.'])],
  summary: ['MC preserves the value definition and replaces model expectations with complete-episode return samples.', 'MC Basic, Exploring Starts, and ε-greedy form a chain driven by data efficiency and coverage assumptions.', 'First-visit and every-visit determine how within-episode evidence is weighted.', 'ε-soft policies trade persistent exploration for a restricted optimal-policy class.', 'Understanding MC control requires inspecting estimates, coverage, policy improvement, and assumptions together.'], explorer: { cue: 'Switch the three algorithms in order; inspect the visit map, update ledger, and action probabilities together with Q.' },
})

export const approximationChapter = chapter('approximation', [source('sa', 'Stochastic Approximation', 'L6, pp.7–60')], {
  prerequisite: '前置：样本均值、期望与基本梯度', eyebrow: 'Part II · 带噪声的增量更新', title: '噪声观测下的增量估计与随机逼近',
  intro: 'Monte Carlo 的增量均值已经具有“当前估计加一步纠正”的结构。随机逼近把这个结构推广到未知方程：只要能获得无偏或受控偏差的 noisy observation，就能沿着随机方向逐步靠近根。步长既决定每次相信新数据多少，也决定噪声是否最终被平均掉。',
  bridge: '从求根问题出发，定义带噪声观测，再得到 Robbins–Monro 更新及其步长条件。', experimentIntro: '在同一条噪声序列上比较固定步长与衰减步长。改变噪声幅度和步长，观察追踪速度、残余波动和最终误差。', interpretation: '固定步长不会完全忘记新数据，因此能追踪变化，但会在真值附近持续波动。衰减步长早期移动快、后期逐渐平均噪声；衰减过快则可能在尚未到达根时失去调整能力。',
  figure: '交互图 07.1 · Stochastic Approximation Lab', instruction: '在相同 seed 下比较固定和衰减步长', question: '步长怎样同时控制学习速度与噪声残留？',
  deepening: approximationDeepeningZh,
  derivation: [
    step('root', '把目标写成求根', String.raw`g(w^*)=0`, '未知量 w* 由方程的根定义。', '均值估计可写成 g(w)=w-E[X]；强化学习中的许多 value 方程也可改写为残差等于零。', ['根存在'], [[String.raw`g`, '期望残差函数']]),
    step('noisy-observation', '用样本构造 noisy observation', String.raw`\widetilde g(w_k,\eta_k)=g(w_k)+\eta_k`, '我们看不到 g，只看到包含随机误差的单次观测。', '当条件期望中的噪声为零时，多次观测的平均方向仍指向真实残差。', [String.raw`\mathbb E[\eta_k\mid w_k]=0`], [[String.raw`\eta_k`, '第 k 次观测噪声']]),
    step('rm-update', '沿观测到的残差反方向移动', String.raw`w_{k+1}=w_k-\alpha_k\widetilde g(w_k,\eta_k)`, '正残差让估计减小，负残差让估计增大。', '这就是 Robbins–Monro 更新。α_k 把 noisy direction 转换为实际移动距离。', [String.raw`\alpha_k>0`], [[String.raw`\alpha_k`, '第 k 步步长']]),
    step('mean-special-case', '均值估计是一个特例', String.raw`w_{k+1}=w_k+\alpha_k(X_k-w_k)`, '令 g(w)=w-E[X]，单样本 X_k 直接给出 noisy residual。', '当 α_k=1/(k+1) 时，递推与样本平均完全一致；其他步长则改变历史样本的权重。', ['X_k 具有有限方差'], [[String.raw`X_k-w_k`, '新观测相对当前均值的误差']]),
    step('step-conditions', '让总移动无限而总噪声有限', String.raw`\sum_{k=1}^{\infty}\alpha_k=\infty,\qquad\sum_{k=1}^{\infty}\alpha_k^2<\infty`, '第一条避免过早停止，第二条让累计噪声能被控制。', '典型选择 α_k=1/k 同时满足两条；固定步长不满足第二条，因此通常只在根附近形成稳态波动。', ['残差方向稳定且噪声方差有界'], [[String.raw`\sum\alpha_k^2`, '随机扰动的累计尺度']]),
  ],
  prelude: [section('increment', '统一形式', '学习是估计加上误差驱动的纠正', ['MC、TD 和随机梯度都可以看成旧参数加步长乘 noisy direction。']), section('two-jobs', '步长的双重职责', '既要走得到，也要停得稳', ['较大步长快速响应，较小步长压低噪声；调度决定二者如何随时间交换。'])],
  sections: [section('constant-decay', '两种目标', '收敛到常数与跟踪变化不是同一个任务', ['衰减步长适合固定真值和渐近收敛；固定步长保留对新数据的敏感度，适合非平稳问题。'], String.raw`w_{k+1}=(1-\alpha)w_k+\alpha X_k`), section('sgd-bridge', '连接优化', 'SGD 是随机逼近在梯度求根上的应用', ['最小化期望损失等价于寻找期望梯度为零的参数。单样本梯度是这个期望梯度的 noisy observation。'], String.raw`\mathbf w_{k+1}=\mathbf w_k-\alpha_k\nabla_{\mathbf w}f(\mathbf w_k,X_k)`), section('forward', '下一步', 'TD 用一次转移构造 Bellman 残差样本', ['下一章把未知的 value 方程写成求根，并用当前 value 估计构造单步 target。'])],
  summary: ['随机逼近用 noisy observation 求未知期望方程的根。', '步长决定新样本与历史估计的权重。', '衰减条件平衡持续移动和噪声抑制。', 'SGD 与 TD 都继承同一个增量结构。'], explorer: { cue: '先比较收敛速度，再看后半段波动；最终点偶然接近真值不等于整个过程稳定。' },
}, {
  prerequisite: 'Prerequisites: sample means, expectations, and basic gradients', eyebrow: 'Part II · Noisy incremental updates', title: 'Incremental estimation and stochastic approximation under noise',
  intro: 'The incremental Monte Carlo mean already has the form “current estimate plus a correction.” Stochastic approximation generalizes that structure to unknown equations: a noisy observation of the residual can guide estimates toward a root. Step size determines both how much to trust new data and whether noise is eventually averaged away.',
  bridge: 'Start with root finding, define a noisy observation, and derive the Robbins–Monro update and its step-size conditions.', experimentIntro: 'Compare constant and decaying step sizes on the same noise sequence. Vary noise and step size to inspect response speed, residual fluctuation, and final error.', interpretation: 'A constant step keeps responding to new data and can track change, but it continues to fluctuate near the truth. A decaying step averages noise increasingly well; if it decays too fast, it can lose the ability to reach the root.',
  figure: 'Interactive Figure 07.1 · Stochastic Approximation Lab', instruction: 'Compare constant and decaying steps under one seed', question: 'How does step size control both learning speed and residual noise?',
  deepening: approximationDeepeningEn,
  derivation: [step('root', 'Write the target as a root', String.raw`g(w^*)=0`, 'The unknown w* is defined by a root.', 'Mean estimation uses g(w)=w-E[X]; value equations can also be written as zero residuals.', ['a root exists'], [[String.raw`g`, 'expected residual function']]), step('noisy-observation', 'Construct a noisy observation', String.raw`\widetilde g(w_k,\eta_k)=g(w_k)+\eta_k`, 'The true residual is hidden; one sample contains random error.', 'With conditionally zero-mean noise, the average observed direction still points to the true residual.', [String.raw`\mathbb E[\eta_k\mid w_k]=0`], [[String.raw`\eta_k`, 'observation noise']]), step('rm-update', 'Move opposite the observed residual', String.raw`w_{k+1}=w_k-\alpha_k\widetilde g(w_k,\eta_k)`, 'Positive residual decreases the estimate and negative residual increases it.', 'This is the Robbins–Monro update; α_k turns a noisy direction into a displacement.', [String.raw`\alpha_k>0`], [[String.raw`\alpha_k`, 'step size']]), step('mean-special-case', 'Recover incremental mean estimation', String.raw`w_{k+1}=w_k+\alpha_k(X_k-w_k)`, 'Set g(w)=w-E[X] and use X_k as the sample observation.', 'With α_k=1/(k+1), the recursion equals the sample mean exactly.', ['X_k has finite variance'], [[String.raw`X_k-w_k`, 'sample error']]), step('step-conditions', 'Keep total motion infinite and total noise finite', String.raw`\sum_{k=1}^{\infty}\alpha_k=\infty,\qquad\sum_{k=1}^{\infty}\alpha_k^2<\infty`, 'The first condition prevents premature stopping; the second controls accumulated noise.', 'The schedule 1/k satisfies both. A constant step violates the second and usually fluctuates around the root.', ['stable residual direction and bounded noise variance'], [[String.raw`\sum\alpha_k^2`, 'accumulated noise scale']])],
  prelude: [section('increment', 'Common form', 'Learning is an estimate plus an error-driven correction', ['MC, TD, and stochastic gradients all update an old parameter with a noisy direction.']), section('two-jobs', 'Two jobs', 'The step must arrive and settle', ['Large steps respond quickly; small steps suppress noise. A schedule trades these roles over time.'])],
  sections: [section('constant-decay', 'Two objectives', 'Converging to a constant and tracking change differ', ['Decaying steps suit stationary targets and asymptotic convergence. Constant steps retain sensitivity to recent data.'], String.raw`w_{k+1}=(1-\alpha)w_k+\alpha X_k`), section('sgd-bridge', 'Optimization bridge', 'SGD applies stochastic approximation to a gradient root', ['Minimizing expected loss means finding a zero expected gradient; a sample gradient is its noisy observation.'], String.raw`\mathbf w_{k+1}=\mathbf w_k-\alpha_k\nabla_{\mathbf w}f(\mathbf w_k,X_k)`), section('forward', 'Next step', 'TD samples a Bellman residual from one transition', ['The next chapter writes value prediction as root finding and builds a one-step target from the current value estimate.'])],
  summary: ['Stochastic approximation solves expectation-defined roots with noisy observations.', 'Step size weights new evidence against history.', 'Decay conditions balance continued motion and noise control.', 'SGD and TD inherit the same incremental structure.'], explorer: { cue: 'Compare convergence speed and late fluctuation; one lucky final point is not evidence of a stable process.' },
})

export const tdChapter = chapter('td', [source('td', 'Temporal-Difference Learning', 'L7, pp.6–23')], {
  prerequisite: '前置：Bellman 期望方程与随机逼近', eyebrow: 'Part II · 不等待终点的预测', title: '从单步转移学习长期价值',
  intro: 'Monte Carlo 只有等一个回合结束后，才能计算从某个时刻开始的完整回报。可是智能体每执行一步，就已经观察到即时奖励和下一状态。TD prediction 要解决的问题是：能否利用这部分刚刚到达的信息，先修正当前状态的价值，而不必等到终点？', bridge: 'Bellman 方程提供了答案。它把当前状态的长期价值写成“一步奖励加后继状态价值”的期望。真实交互给出一步奖励和后继状态；尚未发生的未来则暂时由当前价值估计补上。由此可以从一次转移依次得到 TD target、TD error 和增量更新。',
  experimentIntro: '下面让 MC、TD(0) 和 n-step 方法读取同一段奖励序列。改变折扣因子和 n，观察每种 target 在第几步可用、包含多少个已经发生的奖励，以及有多少尾部仍由当前价值估计提供。', interpretation: 'n 较小时，target 更早出现，但更依赖当前价值估计；n 增大时，target 纳入更多已经发生的奖励，也承受更多轨迹随机性和等待时间。因此，TD(0) 与 MC 的区别不是谁在所有情况下都更准确，而是如何在更新时机、抽样方差和自举误差之间取舍。',
  figure: '交互图 08.1 · Target Comparator', instruction: '改变 n 与 γ，对照三个 target 的数值与信用跨度', question: 'bootstrap 怎样用当前估计换取更及时的学习信号？',
  deepening: tdDeepeningZh,
  derivation: [step('bellman-root', '从给定策略的 Bellman 方程出发', String.raw`v^{\pi}(s)=\mathbb E_{\pi}[R_{t+1}+\gamma v^{\pi}(S_{t+1})\mid S_t=s]`, '真实 value 等于一步奖励与后继真实 value 的期望。', '这是预测问题，不包含动作最大化。', ['策略 π 固定'], [[String.raw`v^{\pi}`, '待估计的真实状态价值']]), step('sample-target', '用一次转移构造 target', String.raw`U_t^{\mathrm{TD}}=R_{t+1}+\gamma V_t(S_{t+1})`, '把未知后继真实 value 换成当前估计。', 'U_t 在 S_{t+1} 到达时即可计算，因此无需等待 episode 结束。', ['V_t 是当前估计'], [[String.raw`U_t^{\mathrm{TD}}`, '一步 TD target']]), step('td-error', '比较 target 与当前预测', String.raw`\delta_t=U_t^{\mathrm{TD}}-V_t(S_t)`, '正误差说明实际一步结果比当前预测好。', 'TD error 同时包含奖励惊喜和后继价值变化，是局部 Bellman 残差样本。', [], [[String.raw`\delta_t`, '时间差分误差']]), step('td-update', '用随机逼近更新被访问状态', String.raw`V_{t+1}(S_t)=V_t(S_t)+\alpha_t\delta_t`, '只更新当前访问状态，其余状态保持不变。', '在适当访问和步长条件下，随机样本更新可以逼近给定策略的真实 value。', [String.raw`0<\alpha_t\le 1`], [[String.raw`\alpha_t`, '该状态本次更新的步长']]), step('n-step', '连接一步 TD 与 Monte Carlo', String.raw`G_t^{(n)}=\sum_{k=0}^{n-1}\gamma^kR_{t+k+1}+\gamma^nV(S_{t+n})`, 'n-step target 使用 n 个真实奖励后再 bootstrap。', 'n=1 得到 TD(0)；当 n 延伸到 episode 末端且尾项为零时得到 MC return。', ['终止状态 value 为 0'], [[String.raw`n`, '真实奖励向前展开的步数']])],
  prelude: [section('timing', '新信息到达的时刻', '每次转移都提供一次检验当前价值估计的机会', ['在时刻 t，智能体从 S_t 出发执行动作。环境返回 R_{t+1} 和 S_{t+1} 时，完整回报 G_t 还不能计算，因为后面的奖励尚未发生；但这次转移已经告诉我们，当前预测至少应当与“一步奖励加后继价值”保持一致。', 'TD 正是利用这条局部一致性。它不预测尚未发生的每个奖励，而是在每次转移结束后立即构造一个临时 target，用它修正刚刚离开的状态。']), section('bootstrap', '自举机制', '尚未发生的未来由下一状态的当前估计暂时代替', ['把已有估计 V_t(S_{t+1}) 放进新 target 的做法称为 bootstrapping（自举）。它让学习无需等待回合结束，也让持续型任务能够边交互边更新。', '代价是 target 会继承当前价值表的误差。如果后继价值估得过高，当前状态也会被向上拉；随着更多状态反复更新，这些相互依赖的估计才逐渐逼近同一个 Bellman 不动点。'])],
  sections: [section('bias-variance', '多步展开', '展开的真实奖励越多，对后继估计的依赖越少', ['一步 TD 只等待一个奖励，然后立即用 V(S_{t+1}) 补上尾部。n-step target 会继续等待 n 个奖励，再从 S_{t+n} 自举；因此 n 增大时，自举误差的影响减弱，但等待时间和轨迹方差同时增加。', '这条连续变化把 TD(0) 与 Monte Carlo 放在同一条轴上：n=1 位于及时更新的一端，展开到终点则位于完整回报的一端。'], String.raw`G_t^{(1)}\longleftrightarrow G_t^{(n)}\longleftrightarrow G_t`), section('online', '在线学习', 'TD 在轨迹生成过程中持续修正价值', ['S_{t+1} 一出现，算法就可以更新 V(S_t)，随后再从 S_{t+1} 继续采样。后面的动作因此可能使用已经更新过的价值估计，数据采集与学习发生在同一条时间线上。', '这种在线性质使 TD 不必依赖自然终点；只要长期回报的定义有效，它也可以处理持续型任务。']), section('forward', '从预测到控制', '选择动作需要把状态价值扩展为动作价值', ['本章假定策略固定，只估计每个状态在该策略下的长期价值。控制问题还要比较同一状态中的不同动作。下一章将把同一个单步 target 写到 Q(S_t,A_t) 上，并区分 target 使用实际下一动作还是价值最大的下一动作。'])],
  summary: ['每次转移都会提供奖励和后继状态，因此价值可以在完整回报出现前更新。', 'TD target 用当前后继价值估计补上尚未发生的未来，这就是 bootstrapping。', 'TD error 是一次转移提供的局部 Bellman 残差样本。', 'n-step target 通过改变真实奖励的展开长度，在 TD(0) 与 Monte Carlo 之间连续取舍。'], explorer: { cue: '比较 target 时，不仅看最终数值，还要确认它何时可用、包含几个真实奖励，以及尾部是否来自当前价值估计。' },
}, {
  prerequisite: 'Prerequisites: Bellman expectation equation and stochastic approximation', eyebrow: 'Part II · Prediction before termination', title: 'Learning long-term value from one-step transitions',
  intro: 'Monte Carlo can calculate a complete return only after an episode ends. Yet every action immediately reveals a reward and a successor state. TD prediction asks whether that newly arrived evidence can revise the value of the current state before termination.', bridge: 'The Bellman equation supplies the missing link by expressing long-term value as expected one-step reward plus successor value. Interaction reveals the reward and successor; the current value estimate temporarily fills in the future that has not occurred. One transition then yields a TD target, TD error, and incremental update.',
  experimentIntro: 'Let MC, TD(0), and n-step methods read the same reward sequence. Change discount and n to inspect when each target becomes available, how many realized rewards it contains, and how much of its tail still comes from the current value estimate.', interpretation: 'Small n gives an earlier target but depends more strongly on the current value table. Larger n includes more realized rewards while adding trajectory randomness and delay. TD(0) and MC therefore trade update time, sampling variance, and bootstrap error rather than having one universally more accurate target.',
  figure: 'Interactive Figure 08.1 · Target Comparator', instruction: 'Change n and γ, then compare the three targets', question: 'How does bootstrapping exchange current estimates for earlier learning?',
  deepening: tdDeepeningEn,
  derivation: [step('bellman-root', 'Start from policy evaluation', String.raw`v^{\pi}(s)=\mathbb E_{\pi}[R_{t+1}+\gamma v^{\pi}(S_{t+1})\mid S_t=s]`, 'True value equals expected reward plus successor value.', 'This is prediction under a fixed policy, not action maximization.', ['policy π is fixed'], [[String.raw`v^{\pi}`, 'true state value']]), step('sample-target', 'Build a target from one transition', String.raw`U_t^{\mathrm{TD}}=R_{t+1}+\gamma V_t(S_{t+1})`, 'Replace unknown successor truth with the current estimate.', 'The target becomes available as soon as S_{t+1} arrives.', ['V_t is the current estimate'], [[String.raw`U_t^{\mathrm{TD}}`, 'one-step TD target']]), step('td-error', 'Compare target and prediction', String.raw`\delta_t=U_t^{\mathrm{TD}}-V_t(S_t)`, 'Positive error means the observed step was better than predicted.', 'TD error is a sample of the local Bellman residual.', [], [[String.raw`\delta_t`, 'temporal-difference error']]), step('td-update', 'Apply stochastic approximation', String.raw`V_{t+1}(S_t)=V_t(S_t)+\alpha_t\delta_t`, 'Only the visited state changes.', 'With suitable coverage and step sizes, sample updates approach the policy value.', [String.raw`0<\alpha_t\le 1`], [[String.raw`\alpha_t`, 'step size for this visit']]), step('n-step', 'Connect TD and Monte Carlo', String.raw`G_t^{(n)}=\sum_{k=0}^{n-1}\gamma^kR_{t+k+1}+\gamma^nV(S_{t+n})`, 'Use n realized rewards before bootstrapping.', 'n=1 yields TD(0); extending to termination yields the MC return.', ['terminal value is zero'], [[String.raw`n`, 'number of realized reward steps']])],
  prelude: [section('timing', 'Arrival of new evidence', 'Every transition tests the current value prediction', ['At time t, the agent acts from S_t. When the environment returns R_{t+1} and S_{t+1}, the complete G_t is still unavailable because later rewards have not happened. The transition nevertheless reveals whether the current prediction is locally consistent with one-step reward plus successor value.', 'TD uses that local consistency. It forms a provisional target as soon as the transition ends and revises the state just left instead of predicting every future reward.']), section('bootstrap', 'Bootstrapping', 'The current successor estimate fills in the unobserved future', ['Using an existing estimate V_t(S_{t+1}) inside a new target is called bootstrapping. It removes the need to wait for termination and supports stepwise updates in continuing tasks.', 'The target consequently inherits error from the current value table. An overestimated successor pulls the current state upward; repeated coupled updates are needed before the table approaches the Bellman fixed point.'])],
  sections: [section('bias-variance', 'Multi-step expansion', 'More realized rewards reduce dependence on the successor estimate', ['One-step TD waits for one reward and then bootstraps from V(S_{t+1}). An n-step target waits for n rewards before bootstrapping from S_{t+n}. Increasing n reduces reliance on the estimated tail while adding delay and trajectory variance.', 'This continuum puts TD(0) and Monte Carlo on one axis: n=1 is the early-update endpoint, while expansion through termination is the complete-return endpoint.'], String.raw`G_t^{(1)}\longleftrightarrow G_t^{(n)}\longleftrightarrow G_t`), section('online', 'Online learning', 'TD revises values while the trajectory is still being generated', ['As soon as S_{t+1} appears, TD can update V(S_t) and continue sampling from the successor. Later actions may therefore use values already changed by earlier transitions.', 'Because updates do not require a natural endpoint, TD also applies to continuing tasks whenever long-term return is well defined.']), section('forward', 'Prediction to control', 'Action selection requires action values rather than state values alone', ['This chapter fixes the policy and predicts state value. Control must compare actions within one state. The next chapter applies the same one-step target to Q(S_t,A_t) and distinguishes targets that follow the action actually taken from targets that select the largest successor value.'])],
  summary: ['Every transition reveals a reward and successor, so value can update before a complete return exists.', 'A TD target bootstraps by filling the unobserved future with the current successor estimate.', 'TD error is a local Bellman-residual sample from one transition.', 'n-step targets vary realized reward span to move continuously between TD(0) and Monte Carlo.'], explorer: { cue: 'When comparing targets, inspect not only magnitude but also availability time, number of realized rewards, and the source of the tail value.' },
})

export const controlChapter = chapter('control', [source('control', 'Sarsa and Q-learning', 'L7, pp.25–54')], {
  prerequisite: '前置：动作价值、TD target 与 ε-greedy 探索', eyebrow: 'Part II · 从预测到控制', title: 'Sarsa 与 Q-learning 的策略目标及风险行为',
  intro: '预测只评价给定策略；控制还要在学习过程中改善策略。Sarsa 的 target 使用行为策略实际选择的下一动作，因此把未来探索风险计入价值。Q-learning 的 target 使用下一状态的最大动作价值，因此学习一个贪心目标策略，即使数据来自更有探索性的行为策略。', bridge: '在同一个五元转移上分别写出 Sarsa 与 Q-learning target，再明确 behavior policy 和 target policy 的职责。',
  experimentIntro: 'Control Arena 用相同探索预算比较两种 target。调节 ε 与步长，观察危险状态频率、累计回报和 target gap。', interpretation: '探索率升高时，两种算法收集的数据都更随机；Sarsa 的 target 也包含这份随机性，因此倾向为探索留出安全余量。Q-learning 的 target 假设下一步执行贪心动作，可能学习更短但在行为探索下更危险的路线。',
  figure: '交互图 09.1 · Sarsa / Q-learning Control Arena', instruction: '锁定 seed 与探索预算，只改变 target 定义', question: '更新目标是否跟随实际下一动作，会怎样改变学到的策略？',
  deepening: controlDeepeningZh,
  derivation: [step('sarsa-target', '先跟随实际下一动作', String.raw`U_t^{\mathrm{Sarsa}}=R_{t+1}+\gamma Q_t(S_{t+1},A_{t+1})`, 'A_{t+1} 由当前行为策略实际采样。', '名称 Sarsa 来自一次更新使用的 S,A,R,S,A 五个对象。', ['A_{t+1} 已经被行为策略选择'], [[String.raw`A_{t+1}`, '下一时刻实际将执行的动作']]), step('sarsa-update', '更新被访问的动作价值', String.raw`Q_{t+1}(S_t,A_t)=Q_t(S_t,A_t)+\alpha_t\left(U_t^{\mathrm{Sarsa}}-Q_t(S_t,A_t)\right)`, 'Sarsa 评价正在产生数据的策略。', '当行为策略持续 ε-greedy 时，target 中保留未来探索动作的后果，因此是 on-policy。', ['状态—动作对持续被访问'], [[String.raw`U_t^{\mathrm{Sarsa}}`, 'on-policy TD target']]), step('q-target', '把下一动作换成最大化', String.raw`U_t^{Q}=R_{t+1}+\gamma\max_a Q_t(S_{t+1},a)`, 'target 假设下一步选择当前最优动作。', '生成数据的行为策略可以仍然探索，但求解对象是 Bellman 最优方程。', [], [[String.raw`\max_a Q_t(S_{t+1},a)`, '目标策略的贪心后继价值']]), step('q-update', '用同一经验更新最优动作价值估计', String.raw`Q_{t+1}(S_t,A_t)=Q_t(S_t,A_t)+\alpha_t\left(U_t^{Q}-Q_t(S_t,A_t)\right)`, '采到的动作可以不是贪心动作，target 仍指向贪心后继。', '数据分布与被学习的策略分离，因此 Q-learning 是 off-policy。', ['behavior policy 提供充分覆盖'], [[String.raw`U_t^{Q}`, 'off-policy optimality target']]), step('policy-roles', '显式分开两种策略', String.raw`A_t\sim b(\cdot\mid S_t),\qquad \pi(s)\in\arg\max_a Q(s,a)`, 'b 负责探索和采样，π 表示希望学习的目标行为。', 'Sarsa 的 target 跟随 b；Q-learning 的 target 跟随贪心 π。区分二者是理解 on/off-policy 的关键。', [String.raw`b(a\mid s)>0\ \text{for required actions}`], [[String.raw`b`, '行为策略'], [String.raw`\pi`, '目标策略']])],
  prelude: [section('prediction-control', '目标变化', '控制在评价之外加入策略改善', ['value 更新与策略选择相互影响，数据分布不再固定。']), section('fair-comparison', '比较协议', '环境、seed、探索预算和步长必须锁定', ['只有 target 定义不同，才可以把路径风险差异归因于算法。'])],
  sections: [section('on-policy', 'On-policy', '学习对象与数据策略一致', ['Sarsa 学习持续探索时实际执行的策略，因此最优解也取决于 ε。'], String.raw`Q\approx q^{b}`), section('off-policy', 'Off-policy', '用一种策略的数据学习另一种策略', ['Q-learning 允许 b 探索，同时用最大化 target 学习贪心策略。覆盖不足仍会导致未访问动作无法纠正。'], String.raw`Q\approx q^*,\qquad A\sim b`), section('forward', '表格的边界', '状态—动作空间变大后无法为每一项单独存值', ['下一部分用参数化函数共享统计强度，一个样本将同时影响多个状态。'])],
  summary: ['Sarsa target 使用实际下一动作，是 on-policy 控制。', 'Q-learning target 使用动作最大值，是 off-policy 控制。', '行为策略负责数据覆盖，目标策略定义学习对象。', '公平比较必须锁定探索预算与随机条件。'], explorer: { cue: '把危险率和平均回报一起读；最短贪心路线不一定是在探索行为下最安全的路线。' },
}, {
  prerequisite: 'Prerequisites: action value, TD targets, and ε-greedy exploration', eyebrow: 'Part II · Prediction to control', title: 'Policy targets and risk behavior in Sarsa and Q-learning',
  intro: 'Prediction evaluates a fixed policy; control improves policy during learning. Sarsa uses the next action actually selected by the behavior policy, so its target includes future exploration risk. Q-learning uses the largest next action value and learns a greedy target policy even when data comes from an exploratory behavior policy.', bridge: 'Write both targets on the same five-part transition, then separate the roles of behavior and target policies.',
  experimentIntro: 'Control Arena compares both targets under one exploration budget. Vary ε and step size to inspect danger frequency, return, and target gap.', interpretation: 'Higher exploration makes both data streams more random. Sarsa also includes that randomness in its target and tends to leave safety margin. Q-learning assumes a greedy next action and may learn a shorter route that is risky when exploration remains active.',
  figure: 'Interactive Figure 09.1 · Sarsa / Q-learning Control Arena', instruction: 'Lock seed and exploration; change only the target', question: 'How does following the actual next action change the learned policy?',
  deepening: controlDeepeningEn,
  derivation: [step('sarsa-target', 'Follow the actual next action', String.raw`U_t^{\mathrm{Sarsa}}=R_{t+1}+\gamma Q_t(S_{t+1},A_{t+1})`, 'A_{t+1} is sampled by the behavior policy.', 'Sarsa is named for the S,A,R,S,A objects used in one update.', ['A_{t+1} has been selected'], [[String.raw`A_{t+1}`, 'next action actually taken']]), step('sarsa-update', 'Update the visited action value', String.raw`Q_{t+1}(S_t,A_t)=Q_t(S_t,A_t)+\alpha_t\left(U_t^{\mathrm{Sarsa}}-Q_t(S_t,A_t)\right)`, 'Sarsa evaluates the policy that generates its data.', 'With continuing ε-greedy behavior, future exploration consequences remain in the target.', ['continued state-action coverage'], [[String.raw`U_t^{\mathrm{Sarsa}}`, 'on-policy TD target']]), step('q-target', 'Replace the next action by maximization', String.raw`U_t^{Q}=R_{t+1}+\gamma\max_a Q_t(S_{t+1},a)`, 'The target assumes the current greedy next action.', 'Behavior may still explore, but the equation being solved is the Bellman optimality equation.', [], [[String.raw`\max_a Q_t(S_{t+1},a)`, 'greedy successor value']]), step('q-update', 'Update optimal action value from the same experience', String.raw`Q_{t+1}(S_t,A_t)=Q_t(S_t,A_t)+\alpha_t\left(U_t^{Q}-Q_t(S_t,A_t)\right)`, 'The sampled action can be exploratory while the target remains greedy.', 'Separating data and target policies makes Q-learning off-policy.', ['behavior provides coverage'], [[String.raw`U_t^{Q}`, 'off-policy optimality target']]), step('policy-roles', 'Name both policies explicitly', String.raw`A_t\sim b(\cdot\mid S_t),\qquad \pi(s)\in\arg\max_a Q(s,a)`, 'b samples experience; π names the behavior being learned.', 'Sarsa targets b while Q-learning targets greedy π.', [String.raw`b(a\mid s)>0\ \text{for required actions}`], [[String.raw`b`, 'behavior policy'], [String.raw`\pi`, 'target policy']])],
  prelude: [section('prediction-control', 'Changed objective', 'Control adds improvement to evaluation', ['Value updates and action selection now change each other and the data distribution.']), section('fair-comparison', 'Comparison protocol', 'Lock environment, seed, exploration, and step size', ['Only then can behavior differences be attributed to the target.'])],
  sections: [section('on-policy', 'On-policy', 'The learned object matches the data policy', ['Sarsa learns the policy that continues to explore, so its solution depends on ε.'], String.raw`Q\approx q^{b}`), section('off-policy', 'Off-policy', 'One policy supplies data for another', ['Q-learning lets b explore while a maximizing target learns a greedy policy. Coverage is still required.'], String.raw`Q\approx q^*,\qquad A\sim b`), section('forward', 'Table limits', 'Large spaces cannot store every state-action value separately', ['The next part shares statistical strength through parameterized functions.'])],
  summary: ['Sarsa uses the actual next action and is on-policy.', 'Q-learning uses a maximizing target and is off-policy.', 'Behavior policy supplies coverage; target policy defines the learning objective.', 'Fair comparison locks exploration and randomness.'], explorer: { cue: 'Read danger rate with return; the shortest greedy route may not be safest under exploratory behavior.' },
})

export const vfaChapter = chapter('vfa', [source('vfa', 'Value Function Approximation', 'L8, pp.5–160')], {
  prerequisite: '前置：TD 更新、均方误差与梯度', eyebrow: 'Part III · 从表格到函数', title: '无法枚举所有状态时，参数怎样共享价值信息？', intro: '表格方法为每个状态保存独立数值，状态一多就失去可扩展性。函数近似用特征和共享参数表示 value：一次样本不只改变当前状态，也会改变特征相似的其他状态。泛化带来效率，也带来干扰和由数据分布决定的近似误差。', bridge: '先定义参数化 value 与加权均方误差，再推导 semi-gradient 更新，并在线性特征中看见一次更新如何传播。',
  experimentIntro: 'Function Studio 在五个相邻位置上共享一个局部特征。改变特征宽度和步长，观察中心样本怎样影响邻居，以及泛化与干扰如何同时增强。', interpretation: '窄特征接近表格更新，影响局部但需要更多样本；宽特征把一个样本传播到更远状态，学习更快却可能把不相似状态拉向同一个 target。特征不是纯粹的压缩格式，而是算法关于相似性的假设。',
  figure: '交互图 10.1 · Function Studio', instruction: '改变特征宽度与步长，观察一次更新的空间传播', question: '一次状态样本为什么会改变其他状态的预测？',
  deepening: vfaDeepeningZh,
  derivation: [step('parameterization', '用共享参数表示 value', String.raw`v^{\pi}(s)\approx\widehat v(s,\mathbf w)`, '状态不再对应独立表项，而是通过同一参数向量产生预测。', '参数数量可以远小于状态数量，因此相似状态共享统计信息。', [], [[String.raw`\mathbf w`, '共享参数向量']]), step('objective', '用访问分布定义近似误差', String.raw`J(\mathbf w)=\frac12\sum_s\mu(s)\left(v^{\pi}(s)-\widehat v(s,\mathbf w)\right)^2`, '经常访问的状态在目标函数中权重更高。', '函数容量有限时不可能同时精确拟合全部状态；stationary distribution μ 指定误差被怎样折中。', [String.raw`\mu(s)\ge0,\ \sum_s\mu(s)=1`], [[String.raw`\mu`, '训练数据诱导的状态权重']]), step('sample-target', '用可观测 target 替代未知真值', String.raw`U_t=R_{t+1}+\gamma\widehat v(S_{t+1},\mathbf w_t)`, 'TD target 提供当前样本的监督信号。', '因为真实 vπ 未知，训练使用 MC return 或 bootstrap target。semi-gradient 暂时把 target 当作常数。', [], [[String.raw`U_t`, '当前样本 target']]), step('semi-gradient', '沿预测误差的负梯度更新', String.raw`\mathbf w_{t+1}=\mathbf w_t+\alpha_t\left(U_t-\widehat v(S_t,\mathbf w_t)\right)\nabla_{\mathbf w}\widehat v(S_t,\mathbf w_t)`, '误差决定方向和大小，梯度决定哪些参数响应。', '只对当前预测求梯度，不对 bootstrap target 中的参数依赖求导，因此称 semi-gradient。', ['target 在本步求导时固定'], [[String.raw`\nabla_{\mathbf w}\widehat v`, '当前状态对各参数的敏感度']]), step('linear', '在线性特征中看见共享', String.raw`\widehat v(s,\mathbf w)=\boldsymbol\phi(s)^\top\mathbf w,\qquad\Delta\mathbf w=\alpha\left(U-\widehat v(s,\mathbf w)\right)\boldsymbol\phi(s)`, '当前状态激活的特征决定参数更新。', '另一个状态若使用相同特征，其预测也会立刻改变；这就是泛化与干扰的共同来源。', [], [[String.raw`\boldsymbol\phi(s)`, '状态特征向量']])],
  prelude: [section('capacity', '表示问题', '有限参数必须决定哪些状态共享信息', ['从 table 到 function 的关键不是换一个存储容器，而是引入相似性结构。']), section('distribution', '数据问题', '训练分布决定最常被纠正的区域', ['同一个函数族在不同访问分布下会得到不同的最佳近似。'])],
  sections: [section('generalization', '泛化', '相似特征让未访问状态也发生变化', ['共享可以提高样本效率，但只在特征表达了真正相关性时有益。'], String.raw`\Delta\widehat v(s')=\boldsymbol\phi(s')^\top\Delta\mathbf w`), section('interference', '干扰', '同一参数收到多个状态的冲突更新', ['当两个状态需要不同 value 却使用相似特征时，修正一个会伤害另一个。训练曲线可能因此震荡。']), section('forward', '非线性近似', '神经网络提供更强表示，也让 target 同时移动', ['下一章研究 DQN 如何用 target network 与 replay 缓解共享参数下的不稳定。'])],
  summary: ['函数近似用共享参数替代独立 value 表。', '访问分布定义有限容量下的误差权重。', 'semi-gradient 用样本 target 更新当前预测。', '泛化与干扰来自同一个参数共享机制。'], explorer: { cue: '宽特征带来的邻居变化既不是纯收益也不是纯错误；要结合状态相似性判断它是泛化还是干扰。' },
}, {
  prerequisite: 'Prerequisites: TD updates, squared error, and gradients', eyebrow: 'Part III · Tables to functions', title: 'How do shared parameters transfer value across states?', intro: 'A table stores one independent number per state and stops scaling when states become numerous. Function approximation represents value with features and shared parameters. One sample changes the current state and other states with similar features, producing both generalization and interference.', bridge: 'Define parameterized value and weighted squared error, derive a semi-gradient update, and expose sharing in linear features.',
  experimentIntro: 'Function Studio shares one local feature across five positions. Change feature width and step size to see a center sample affect neighbors.', interpretation: 'Narrow features approach tabular updates: local but data-hungry. Wide features spread evidence farther and can learn faster, but may pull dissimilar states toward one target. Features encode an assumption about similarity.',
  figure: 'Interactive Figure 10.1 · Function Studio', instruction: 'Vary feature width and step size to inspect spatial propagation', question: 'Why does one state sample change predictions at other states?',
  deepening: vfaDeepeningEn,
  derivation: [step('parameterization', 'Represent value with shared parameters', String.raw`v^{\pi}(s)\approx\widehat v(s,\mathbf w)`, 'States no longer own independent entries.', 'A parameter vector smaller than the state space shares statistical information.', [], [[String.raw`\mathbf w`, 'shared parameter vector']]), step('objective', 'Weight error by the visitation distribution', String.raw`J(\mathbf w)=\frac12\sum_s\mu(s)\left(v^{\pi}(s)-\widehat v(s,\mathbf w)\right)^2`, 'Frequently visited states receive more weight.', 'Limited capacity cannot fit every state exactly; μ defines the compromise.', [String.raw`\mu(s)\ge0,\ \sum_s\mu(s)=1`], [[String.raw`\mu`, 'state weighting induced by data']]), step('sample-target', 'Replace unknown truth with an observable target', String.raw`U_t=R_{t+1}+\gamma\widehat v(S_{t+1},\mathbf w_t)`, 'A TD target supervises the current sample.', 'MC returns or bootstrap targets substitute for unknown true value.', [], [[String.raw`U_t`, 'sample target']]), step('semi-gradient', 'Follow prediction error', String.raw`\mathbf w_{t+1}=\mathbf w_t+\alpha_t\left(U_t-\widehat v(S_t,\mathbf w_t)\right)\nabla_{\mathbf w}\widehat v(S_t,\mathbf w_t)`, 'Error sets direction and magnitude; the gradient selects responding parameters.', 'The target is held fixed during differentiation, hence semi-gradient.', ['target is fixed for this derivative'], [[String.raw`\nabla_{\mathbf w}\widehat v`, 'parameter sensitivity']]), step('linear', 'Expose sharing with linear features', String.raw`\widehat v(s,\mathbf w)=\boldsymbol\phi(s)^\top\mathbf w,\qquad\Delta\mathbf w=\alpha\left(U-\widehat v(s,\mathbf w)\right)\boldsymbol\phi(s)`, 'Active features determine the update.', 'Any other state using those features changes immediately.', [], [[String.raw`\boldsymbol\phi(s)`, 'state feature vector']])],
  prelude: [section('capacity', 'Representation', 'Finite parameters choose which states share evidence', ['Moving from a table to a function introduces a similarity structure.']), section('distribution', 'Data distribution', 'Frequently sampled regions receive more correction', ['The best approximation changes with the visitation distribution.'])],
  sections: [section('generalization', 'Generalization', 'Shared features change unvisited states', ['Sharing improves sample efficiency only when features encode useful relatedness.'], String.raw`\Delta\widehat v(s')=\boldsymbol\phi(s')^\top\Delta\mathbf w`), section('interference', 'Interference', 'One parameter receives conflicting state updates', ['When states need different values but share features, correcting one can hurt another.']), section('forward', 'Nonlinear approximation', 'Neural networks add capacity and a moving target', ['The next chapter uses target networks and replay to stabilize DQN.'])],
  summary: ['Shared parameters replace independent value entries.', 'The visitation distribution weights approximation error.', 'Semi-gradients update predictions from sample targets.', 'Generalization and interference share one cause.'], explorer: { cue: 'Neighbor change is not inherently good or bad; judge it against whether those states should share value information.' },
})

export const dqnChapter = chapter('dqn', [source('dqn', 'Deep Q-learning', 'L8, pp.162–226')], {
  prerequisite: '前置：Q-learning、函数近似与梯度下降', eyebrow: 'Part III · 稳定深度价值学习', title: 'Target network 与 replay 分别解决什么问题？', intro: '把 Q-learning 的表换成神经网络并不只是扩大容量。网络参数同时决定当前预测和 bootstrap target，一个样本更新还会改变许多其他状态。连续轨迹又带来强相关数据。DQN 用冻结的 target network 减慢目标漂移，用 replay buffer 打散采样顺序并复用经验。', bridge: '从参数化 Q target 出发，分别识别 moving target 与 correlated data，再把两个稳定化机制放进同一训练步。',
  experimentIntro: 'DQN System Lab 让你改变 replay 打散强度和 target 同步间隔。观察样本相关性、target 漂移和误差曲线的稳定性。', interpretation: 'replay 越充分，连续样本的相关性越低，但 buffer 中的数据也可能更陈旧。target 同步太频繁会重新形成快速移动的监督信号，太慢则让 target 落后。两种机制作用不同，不能互相替代。',
  figure: '交互图 11.1 · DQN System Lab', instruction: '分别调节 replay 与 target 同步，辨认两种不稳定来源', question: '为什么固定 target 和打散数据必须同时存在？',
  deepening: dqnDeepeningZh,
  derivation: [step('network-q', '用网络近似动作价值', String.raw`q^*(s,a)\approx Q_{\theta}(s,a)`, '一个参数向量为多个状态和动作共同产生预测。', '共享表示让 DQN 能处理高维输入，也让单次更新产生广泛耦合。', [], [[String.raw`\theta`, 'online Q-network 参数']]), step('naive-target', '直接写出 bootstrap target', String.raw`Y_t(\theta)=R_{t+1}+\gamma\max_{a'}Q_{\theta}(S_{t+1},a')`, '同一 θ 同时出现在预测和监督信号中。', '梯度更新 θ 后，当前预测变化，target 也立即变化；优化器追逐一个快速移动的目标。', [], [[String.raw`Y_t(\theta)`, '依赖 online 参数的 target']]), step('target-network', '冻结一份 target 参数', String.raw`Y_t=R_{t+1}+\gamma\max_{a'}Q_{\bar\theta}(S_{t+1},a')`, '在若干训练步内保持 target network 不变。', 'online 参数 θ 被连续优化，target 参数 θ̄ 只周期性复制，从而把监督信号的变化时间尺度放慢。', [], [[String.raw`\bar\theta`, '冻结的 target-network 参数']]), step('replay-loss', '从 replay 中随机抽取 minibatch', String.raw`L(\theta)=\frac1B\sum_{i=1}^{B}\left(Y_i-Q_{\theta}(S_i,A_i)\right)^2`, '随机重排旧经验，降低相邻样本相关性。', 'buffer 也让一条经验被多次使用，提高数据效率；但采样分布与当前策略不再完全相同。', ['样本存储为 (S,A,R,S′,done)'], [[String.raw`B`, 'minibatch 大小']]), step('sync', '周期性同步两个网络', String.raw`\bar\theta\leftarrow\theta\quad\text{every }C\text{ updates}`, 'target 会跳变，但在两次同步之间保持稳定。', 'C 小时 target 更新快；C 大时监督更稳但更陈旧。它是稳定性与响应速度的时间尺度参数。', [String.raw`C\in\mathbb N^+`], [[String.raw`C`, 'target 同步间隔']])],
  prelude: [section('coupling', '新增困难', '函数共享把原本独立的表项耦合起来', ['更新一个样本可能改变未出现在 minibatch 中的许多预测。']), section('two-instabilities', '两种来源', '目标漂移与数据相关不是同一个问题', ['target network 处理前者，experience replay 主要处理后者。'])],
  sections: [section('target-role', 'Target network', '冻结监督信号的短期参照', ['它不是第二个独立学习目标，而是 online network 的滞后副本。'], String.raw`\theta\ \text{trains continuously},\qquad\bar\theta\ \text{updates discretely}`), section('replay-role', 'Experience replay', '把时间序列变成可重排的数据集', ['均匀采样降低连续转移相关性，并允许跨 episode 组成 minibatch。']), section('limits', '边界', '稳定化不等于收敛保证', ['近似误差、off-policy 数据和 bootstrap 仍然共同作用。Double DQN、优先 replay 等改进针对其他偏差或效率问题。'])],
  summary: ['DQN 用网络共享动作价值表示。', 'target network 放慢 bootstrap target 的漂移。', 'replay 降低连续样本相关性并复用经验。', '同步周期和 buffer 分布形成新的稳定性权衡。'], explorer: { cue: '分别观察 correlation 与 drift；一条更平滑的 loss 曲线不能说明两个问题都已解决。' },
}, {
  prerequisite: 'Prerequisites: Q-learning, function approximation, and gradient descent', eyebrow: 'Part III · Stable deep value learning', title: 'What do target networks and replay solve?', intro: 'Replacing a Q-table with a neural network changes more than capacity. Parameters determine both current predictions and bootstrap targets, and one update affects many states. Consecutive trajectories also create correlated data. DQN slows target movement with a frozen network and randomizes reusable experience with replay.', bridge: 'Start from a parameterized Q target, identify moving targets and correlated data separately, then place both mechanisms in one training step.',
  experimentIntro: 'DQN System Lab varies replay mixing and target synchronization. Inspect sample correlation, target drift, and error stability.', interpretation: 'More replay mixing reduces sequential correlation but can use older data. Frequent target synchronization recreates a fast-moving target; very slow synchronization makes targets stale. The mechanisms address different problems and do not replace each other.',
  figure: 'Interactive Figure 11.1 · DQN System Lab', instruction: 'Vary replay and target synchronization independently', question: 'Why are both a fixed target and shuffled experience needed?',
  deepening: dqnDeepeningEn,
  derivation: [step('network-q', 'Approximate action value with a network', String.raw`q^*(s,a)\approx Q_{\theta}(s,a)`, 'One parameter vector predicts many state-action values.', 'Shared representation scales to high-dimensional inputs and couples updates.', [], [[String.raw`\theta`, 'online-network parameters']]), step('naive-target', 'Write the direct bootstrap target', String.raw`Y_t(\theta)=R_{t+1}+\gamma\max_{a'}Q_{\theta}(S_{t+1},a')`, 'The same θ controls prediction and supervision.', 'Updating θ changes both sides, so the optimizer chases a moving target.', [], [[String.raw`Y_t(\theta)`, 'online-dependent target']]), step('target-network', 'Freeze target parameters', String.raw`Y_t=R_{t+1}+\gamma\max_{a'}Q_{\bar\theta}(S_{t+1},a')`, 'Hold the target network fixed for several updates.', 'Online θ trains continuously while target θ̄ copies only periodically.', [], [[String.raw`\bar\theta`, 'frozen target-network parameters']]), step('replay-loss', 'Sample a replay minibatch', String.raw`L(\theta)=\frac1B\sum_{i=1}^{B}\left(Y_i-Q_{\theta}(S_i,A_i)\right)^2`, 'Randomized old experience lowers adjacent-sample correlation.', 'Replay also reuses data, while making the batch distribution differ from the current policy.', ['store (S,A,R,S′,done)'], [[String.raw`B`, 'minibatch size']]), step('sync', 'Synchronize periodically', String.raw`\bar\theta\leftarrow\theta\quad\text{every }C\text{ updates}`, 'Targets jump at synchronization and remain fixed between copies.', 'Small C responds quickly; large C is stable but stale.', [String.raw`C\in\mathbb N^+`], [[String.raw`C`, 'target synchronization period']])],
  prelude: [section('coupling', 'New difficulty', 'Shared parameters couple former table entries', ['One sample changes predictions outside its minibatch.']), section('two-instabilities', 'Two sources', 'Target drift and data correlation are different', ['Target networks address the first; replay primarily addresses the second.'])],
  sections: [section('target-role', 'Target network', 'A short-term fixed supervision reference', ['It is a lagged copy, not a second independent objective.'], String.raw`\theta\ \text{trains continuously},\qquad\bar\theta\ \text{updates discretely}`), section('replay-role', 'Experience replay', 'Turn a time sequence into a resampleable dataset', ['Uniform sampling reduces local temporal correlation and mixes episodes.']), section('limits', 'Boundary', 'Stabilization is not a convergence guarantee', ['Approximation, off-policy data, and bootstrapping still interact.'])],
  summary: ['DQN shares action-value predictions through a network.', 'A target network slows bootstrap-target drift.', 'Replay reduces sequential correlation and reuses experience.', 'Synchronization and replay distributions introduce new tradeoffs.'], explorer: { cue: 'Inspect correlation and drift separately; a smooth loss curve does not prove both sources are controlled.' },
})

export const policyGradientChapter = chapter('policygradient', [source('pg', 'Policy Gradient Methods', 'L9, pp.6–41')], {
  prerequisite: '前置：参数化函数、概率分布与梯度上升', eyebrow: 'Part III · 直接优化策略', title: '怎样直接提高高回报动作的概率？', intro: '价值方法先学习 Q，再通过 argmax 得到策略。Policy Gradient 直接参数化动作概率，并对平均价值或平均奖励求梯度。采到的动作若带来高于基线的结果，就沿对数概率梯度提高它的概率；结果较差则降低概率。', bridge: '从标量策略目标开始，经 policy gradient theorem 和 log-derivative trick 得到可由样本估计的 REINFORCE 更新。',
  experimentIntro: 'Policy Gradient Studio 用两动作 softmax 展示一次样本更新。改变当前 logit、样本权重与 baseline，观察梯度和动作概率怎样变化。', interpretation: '同样的正回报在动作已经很可能时产生较小概率变化，在动作罕见时产生更明显的纠正。baseline 不改变期望梯度，却会改变单个样本的权重和方差；它不能依赖当前动作，否则通常会引入偏差。',
  figure: '交互图 12.1 · Policy Gradient Studio', instruction: '改变动作概率、样本权重与 baseline，观察更新方向', question: '为什么乘上对数概率梯度就能改变策略？',
  deepening: policyGradientDeepeningZh,
  derivation: [step('objective', '先定义策略好坏的标量指标', String.raw`J(\theta)=\mathbb E_{S\sim\eta_\theta}\left[v^{\pi_\theta}(S)\right]`, 'θ 通过策略影响动作，也通过长期访问分布影响状态。', 'J 可以采用 discounted average value 或 continuing average reward；二者细节不同，但都把策略比较转成标量优化。', [], [[String.raw`\eta_\theta`, '策略诱导的状态权重']]), step('theorem', '用策略梯度定理消去状态分布导数', String.raw`\nabla_\theta J(\theta)=\sum_s\eta_\theta(s)\sum_a\nabla_\theta\pi_\theta(a\mid s)q^{\pi_\theta}(s,a)`, '梯度可写成状态—动作上的加权和。', '定理把复杂的长期分布变化吸收到 η 中，使更新只需策略导数与动作价值。', ['π 对 θ 可微'], [[String.raw`q^{\pi_\theta}`, '当前策略的动作价值']]), step('log-trick', '把概率导数改写为 score function', String.raw`\nabla_\theta\pi_\theta(a\mid s)=\pi_\theta(a\mid s)\nabla_\theta\log\pi_\theta(a\mid s)`, '概率本身提供采样权重，对数概率梯度提供方向。', '代入后，求和正好成为从当前策略采样的期望。', [String.raw`\pi_\theta(a\mid s)>0`], [[String.raw`\nabla\log\pi`, 'score function']]), step('sample-gradient', '用一条样本估计期望梯度', String.raw`\widehat g_t=\nabla_\theta\log\pi_\theta(A_t\mid S_t)G_t`, '高 return 动作提高 log probability，低 return 动作产生相反方向。', '用完整 return 得到 REINFORCE。估计无偏但常有较高方差，因为一条轨迹的随机结果乘到了每个动作上。', ['轨迹由当前策略采样'], [[String.raw`\widehat g_t`, '单样本策略梯度估计']]), step('baseline', '减去与动作无关的 baseline', String.raw`\widehat g_t=\nabla_\theta\log\pi_\theta(A_t\mid S_t)\left(G_t-b(S_t)\right)`, '只奖励相对该状态通常水平更好的动作。', '因为对动作求期望的 score function 为零，状态 baseline 不改变梯度期望，却可以显著降低方差。', ['b 不依赖 A_t'], [[String.raw`b(S_t)`, '状态相关 baseline']])],
  prelude: [section('value-policy', '表示变化', '策略从 argmax 结果变成可微概率函数', ['softmax 让所有动作保持正概率，并允许梯度连续移动概率质量。']), section('credit', '样本贡献', '动作方向由 score function 决定，强度由长期结果决定', ['两部分相乘后形成一次 trajectory contribution。'])],
  sections: [section('softmax', '常用参数化', 'softmax 把 logits 变成合法概率', ['提高一个动作 logit 会提高其概率，同时通过归一化降低其他动作概率。'], String.raw`\pi_\theta(a\mid s)=\frac{e^{h_\theta(s,a)}}{\sum_b e^{h_\theta(s,b)}}`), section('variance', '方差来源', '同一动作会因后续随机性获得不同 return', ['增加 trajectory 数量、使用 baseline 或更及时的 critic 都是在改善梯度估计质量。']), section('forward', '下一步', 'Critic 学习 baseline 和更及时的 advantage', ['Actor–Critic 不改变策略梯度方向，而是用 value 与 TD error 改造权重。'])],
  summary: ['Policy Gradient 直接优化参数化动作概率。', 'policy gradient theorem 把长期目标梯度写成可采样期望。', 'REINFORCE 用 return 加权对数概率梯度。', '状态 baseline 保持期望不变并降低方差。'], explorer: { cue: '先看权重相对 baseline 的正负，再看当前动作概率；二者共同决定这一步概率移动的方向和幅度。' },
}, {
  prerequisite: 'Prerequisites: parameterized functions, probability distributions, and gradient ascent', eyebrow: 'Part III · Optimize policy directly', title: 'How can high-return actions become more probable?', intro: 'Value methods learn Q and derive a policy with argmax. Policy Gradient directly parameterizes action probabilities and differentiates average value or reward. An action with an outcome above baseline moves along its log-probability gradient; a worse outcome moves in the opposite direction.', bridge: 'Start from a scalar policy objective, apply the policy-gradient theorem and log-derivative trick, and obtain a sample-based REINFORCE update.',
  experimentIntro: 'Policy Gradient Studio shows one sample update for a two-action softmax. Change the current logit, sample weight, and baseline to inspect gradient and probability movement.', interpretation: 'The same positive return changes an already likely action less than a rare action. A baseline preserves the expected gradient but changes sample weights and variance; it must not depend on the selected action.',
  figure: 'Interactive Figure 12.1 · Policy Gradient Studio', instruction: 'Vary probability, sample weight, and baseline', question: 'Why does multiplying a log-probability gradient change policy in the right direction?',
  deepening: policyGradientDeepeningEn,
  derivation: [step('objective', 'Define a scalar policy objective', String.raw`J(\theta)=\mathbb E_{S\sim\eta_\theta}\left[v^{\pi_\theta}(S)\right]`, 'θ affects actions and the long-run state distribution.', 'Discounted average value and continuing average reward differ in detail but both support scalar optimization.', [], [[String.raw`\eta_\theta`, 'policy-induced state weighting']]), step('theorem', 'Apply the policy-gradient theorem', String.raw`\nabla_\theta J(\theta)=\sum_s\eta_\theta(s)\sum_a\nabla_\theta\pi_\theta(a\mid s)q^{\pi_\theta}(s,a)`, 'The gradient becomes a weighted state-action sum.', 'The theorem absorbs difficult distribution derivatives into η.', ['π is differentiable'], [[String.raw`q^{\pi_\theta}`, 'current-policy action value']]), step('log-trick', 'Use the score-function identity', String.raw`\nabla_\theta\pi_\theta(a\mid s)=\pi_\theta(a\mid s)\nabla_\theta\log\pi_\theta(a\mid s)`, 'Probability supplies sampling weight and log probability supplies direction.', 'The sum becomes an expectation under the current policy.', [String.raw`\pi_\theta(a\mid s)>0`], [[String.raw`\nabla\log\pi`, 'score function']]), step('sample-gradient', 'Estimate with one trajectory sample', String.raw`\widehat g_t=\nabla_\theta\log\pi_\theta(A_t\mid S_t)G_t`, 'High-return actions raise log probability; low-return actions push the other way.', 'Using full return produces REINFORCE: unbiased but often high variance.', ['trajectory follows the current policy'], [[String.raw`\widehat g_t`, 'sample policy-gradient estimate']]), step('baseline', 'Subtract an action-independent baseline', String.raw`\widehat g_t=\nabla_\theta\log\pi_\theta(A_t\mid S_t)\left(G_t-b(S_t)\right)`, 'Reward actions relative to the usual outcome at that state.', 'The expected score is zero, so a state baseline preserves the expected gradient while reducing variance.', ['b does not depend on A_t'], [[String.raw`b(S_t)`, 'state-dependent baseline']])],
  prelude: [section('value-policy', 'Changed representation', 'Policy becomes a differentiable probability function', ['Softmax preserves valid probabilities and permits continuous movement of probability mass.']), section('credit', 'Sample contribution', 'Score gives direction; long-term outcome gives strength', ['Their product forms one trajectory contribution.'])],
  sections: [section('softmax', 'Common parameterization', 'Softmax maps logits to probabilities', ['Raising one logit raises its action probability and lowers others through normalization.'], String.raw`\pi_\theta(a\mid s)=\frac{e^{h_\theta(s,a)}}{\sum_b e^{h_\theta(s,b)}}`), section('variance', 'Variance', 'The same action can receive different returns', ['More trajectories, baselines, and timely critics all improve gradient-estimate quality.']), section('forward', 'Next step', 'A critic learns the baseline and a timely advantage', ['Actor–Critic preserves the policy-gradient direction while changing its weight.'])],
  summary: ['Policy Gradient directly optimizes action probabilities.', 'The theorem expresses a long-term gradient as a sampleable expectation.', 'REINFORCE weights log-probability gradients by return.', 'A state baseline preserves expectation and lowers variance.'], explorer: { cue: 'Read the weight relative to baseline first, then current action probability; together they set direction and magnitude.' },
})

export const actorCriticChapter = chapter('actorcritic', [source('ac', 'Actor-Critic Methods', 'L10, pp.6–43')], {
  prerequisite: '前置：Policy Gradient、state value 与 TD error', eyebrow: 'Part III · 策略与价值协作', title: 'Critic 怎样给 Actor 更及时、低方差的学习信号？', intro: 'REINFORCE 用完整 return 更新策略，信号延迟且方差较高。Actor–Critic 把职责分开：Actor 参数化策略并决定动作概率，Critic 学习 state value；一次转移产生的 TD error 既更新 Critic，也作为 advantage 的样本近似来更新 Actor。', bridge: '从动作价值加权的策略梯度出发，减去 state baseline、得到 advantage，再用 TD error 构造一次同时更新 Actor 与 Critic 的闭环。',
  experimentIntro: 'Actor–Critic Loop 展示同一个 transition 怎样产生 TD target、TD error、Critic 更新和 Actor 步长。改变奖励、后继 value 与 importance ratio，观察两组参数如何共享一个信号。', interpretation: '正 TD error 表示结果好于 Critic 预期，Actor 增加该动作概率，同时 Critic 抬高当前状态 value；负误差产生相反更新。importance ratio 只在数据来自不同 behavior policy 时修正动作分布差异，过大的 ratio 会放大方差。',
  figure: '交互图 13.1 · Actor–Critic Loop', instruction: '沿一次 transition 追踪 Critic 与 Actor 的两次更新', question: '一个 TD error 为什么能够同时训练 value 和 policy？',
  deepening: actorCriticDeepeningZh,
  derivation: [step('q-gradient', '从动作价值加权的策略梯度开始', String.raw`\nabla_\theta J(\theta)=\mathbb E\left[\nabla_\theta\log\pi_\theta(A_t\mid S_t)q^{\pi}(S_t,A_t)\right]`, 'Actor 的方向由 score function 与动作价值共同决定。', '直接学习 q 可以形成最简单的 Q Actor–Critic，但 action value 估计仍可能方差较高。', [], [[String.raw`\theta`, 'Actor 参数']]), step('baseline-invariance', '减去不依赖动作的 state baseline', String.raw`\mathbb E_{A\sim\pi}\left[\nabla_\theta\log\pi_\theta(A\mid s)b(s)\right]=0`, 'baseline 项在动作期望下消失。', '因此可以选择 b(s)=vπ(s) 而不改变梯度期望，用状态平均水平消除共同波动。', ['b 与动作 A 无关'], [[String.raw`b(s)`, '方差降低基线']]), step('advantage', '把梯度权重写成 advantage', String.raw`A^{\pi}(s,a)=q^{\pi}(s,a)-v^{\pi}(s)`, '动作只需相对该状态的平均表现更好。', '这使 Actor 的更新关注“选择这个动作比平常好多少”，而不是回报的绝对尺度。', [], [[String.raw`A^{\pi}`, '动作相对状态平均水平的优势']]), step('td-advantage', '用一步 TD error 近似 advantage', String.raw`\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t)\approx A^{\pi}(S_t,A_t)`, '一次转移结束后即可得到低延迟权重。', '若 Critic 准确，给定状态与动作时 TD error 的条件期望等于 advantage。', ['Vφ 逼近当前策略的 state value'], [[String.raw`\phi`, 'Critic 参数']]), step('two-updates', '让一个误差驱动两组参数', String.raw`\phi\leftarrow\phi+\alpha_v\delta_t\nabla_\phi V_\phi(S_t),\qquad\theta\leftarrow\theta+\alpha_\pi\delta_t\nabla_\theta\log\pi_\theta(A_t\mid S_t)`, 'Critic 减小 value error，Actor 改变动作概率。', '两者在每个 transition 后形成闭环。Actor 改变数据分布，Critic 随之重新估计新策略。', [], [[String.raw`\alpha_v`, 'Critic 步长'], [String.raw`\alpha_\pi`, 'Actor 步长']]), step('importance', '用 importance ratio 处理 behavior 数据', String.raw`\rho_t=\frac{\pi_\theta(A_t\mid S_t)}{b(A_t\mid S_t)},\qquad\Delta\theta\propto\rho_t\delta_t\nabla_\theta\log\pi_\theta(A_t\mid S_t)`, 'ratio 把 behavior policy 下的动作样本重新加权到 target policy。', '当 π 与 b 差异很大时，ratio 的高方差会使更新不稳定；现代方法会限制策略偏移。', [String.raw`b(A_t\mid S_t)>0\ \text{whenever }\pi_\theta(A_t\mid S_t)>0`], [[String.raw`\rho_t`, '动作概率的重要性比率']])],
  prelude: [section('roles', '两种参数', 'Actor 表示策略，Critic 表示评判标准', ['Critic 不替 Actor 选择动作；它提供相对预期的学习信号。']), section('timing', '同一步闭环', 'transition 一到达，两组参数都可以更新', ['这比等待完整 return 更及时，同时引入 bootstrap bias。'])],
  sections: [section('variance-bias', '权衡', 'Critic 用可学习偏差换取更低方差', ['Critic 不准确时 advantage estimate 有偏；随着 value 改善，Actor 的更新权重也会改善。'], String.raw`\mathbb E[\delta_t\mid s,a]\approx A^{\pi}(s,a)`), section('two-timescales', '耦合训练', 'Actor 与 Critic 的学习速度需要协调', ['Critic 太慢会给出过时基线，Actor 太快会持续改变 Critic 的目标分布。实践中常分别设置步长和更新次数。']), section('forward', '进入 PPO', '旧策略数据复用需要限制概率比变化', ['importance ratio 连接 behavior 与 target policy。PPO 进一步保存 old-policy 概率并裁剪过度变化的 surrogate objective。'])],
  summary: ['Actor 参数化策略，Critic 估计 state value。', 'state baseline 保持策略梯度期望并降低方差。', 'TD error 是及时的 advantage 样本近似。', '一个 transition 同时产生 Critic 与 Actor 更新。', 'importance ratio 为 off-policy 与 PPO 建立接口。'], explorer: { cue: '按 TD target → δ → Critic step → Actor step 的顺序读图；两次更新共享误差，但梯度对象不同。' },
}, {
  prerequisite: 'Prerequisites: Policy Gradient, state value, and TD error', eyebrow: 'Part III · Policy and value cooperate', title: 'How does a critic give the actor timely, lower-variance feedback?', intro: 'REINFORCE waits for complete returns and often has high variance. Actor–Critic separates roles: the actor parameterizes action probabilities, the critic learns state value, and one transition produces a TD error that updates the critic and approximates advantage for the actor.', bridge: 'Start from action-value-weighted policy gradient, subtract a state baseline, obtain advantage, and use TD error to update actor and critic together.',
  experimentIntro: 'Actor–Critic Loop traces one transition through TD target, error, critic update, and actor step. Vary reward, successor value, and importance ratio.', interpretation: 'Positive TD error means the result exceeded the critic expectation: the actor raises action probability and the critic raises current value. Negative error reverses both. Importance ratios correct behavior-policy samples but can amplify variance.',
  figure: 'Interactive Figure 13.1 · Actor–Critic Loop', instruction: 'Trace one transition through critic and actor updates', question: 'Why can one TD error train both value and policy?',
  deepening: actorCriticDeepeningEn,
  derivation: [step('q-gradient', 'Start from action-value policy gradient', String.raw`\nabla_\theta J(\theta)=\mathbb E\left[\nabla_\theta\log\pi_\theta(A_t\mid S_t)q^{\pi}(S_t,A_t)\right]`, 'The actor direction combines score and action value.', 'Learning q directly gives Q Actor–Critic but can retain high variance.', [], [[String.raw`\theta`, 'actor parameters']]), step('baseline-invariance', 'Subtract an action-independent baseline', String.raw`\mathbb E_{A\sim\pi}\left[\nabla_\theta\log\pi_\theta(A\mid s)b(s)\right]=0`, 'The baseline term vanishes in expectation over actions.', 'Choose b(s)=vπ(s) to remove state-level common variation.', ['b is independent of A'], [[String.raw`b(s)`, 'variance-reduction baseline']]), step('advantage', 'Express the weight as advantage', String.raw`A^{\pi}(s,a)=q^{\pi}(s,a)-v^{\pi}(s)`, 'An action matters relative to the state average.', 'The actor now responds to how much better the action is than usual.', [], [[String.raw`A^{\pi}`, 'relative action quality']]), step('td-advantage', 'Approximate advantage with TD error', String.raw`\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t)\approx A^{\pi}(S_t,A_t)`, 'The weight is available after one transition.', 'With an accurate critic, conditional expected TD error equals advantage.', ['Vφ approximates current-policy state value'], [[String.raw`\phi`, 'critic parameters']]), step('two-updates', 'Drive two parameter updates with one error', String.raw`\phi\leftarrow\phi+\alpha_v\delta_t\nabla_\phi V_\phi(S_t),\qquad\theta\leftarrow\theta+\alpha_\pi\delta_t\nabla_\theta\log\pi_\theta(A_t\mid S_t)`, 'The critic reduces value error and the actor changes action probability.', 'Both update after every transition; actor changes the data distribution that critic must track.', [], [[String.raw`\alpha_v`, 'critic step size'], [String.raw`\alpha_\pi`, 'actor step size']]), step('importance', 'Correct behavior-policy data', String.raw`\rho_t=\frac{\pi_\theta(A_t\mid S_t)}{b(A_t\mid S_t)},\qquad\Delta\theta\propto\rho_t\delta_t\nabla_\theta\log\pi_\theta(A_t\mid S_t)`, 'The ratio reweights behavior actions toward the target policy.', 'Large policy mismatch produces high-variance ratios and motivates constrained policy updates.', [String.raw`b(A_t\mid S_t)>0\ \text{whenever }\pi_\theta(A_t\mid S_t)>0`], [[String.raw`\rho_t`, 'importance ratio']])],
  prelude: [section('roles', 'Two parameter sets', 'Actor represents policy; critic represents judgment', ['The critic does not choose actions for the actor; it supplies relative feedback.']), section('timing', 'One-step loop', 'Both parameter sets update when a transition arrives', ['This lowers delay while introducing bootstrap bias.'])],
  sections: [section('variance-bias', 'Tradeoff', 'The critic exchanges learnable bias for lower variance', ['An inaccurate critic biases advantage; better value estimates improve actor weights.'], String.raw`\mathbb E[\delta_t\mid s,a]\approx A^{\pi}(s,a)`), section('two-timescales', 'Coupled training', 'Actor and critic learning rates must coordinate', ['A slow critic supplies stale baselines; a fast actor continually changes the critic data distribution.']), section('forward', 'Toward PPO', 'Reusing old-policy data requires controlling ratio movement', ['PPO stores old probabilities and clips excessive surrogate improvement.'])],
  summary: ['Actor parameterizes policy; critic estimates state value.', 'A state baseline preserves expected policy gradient and lowers variance.', 'TD error is a timely advantage estimate.', 'One transition drives critic and actor updates.', 'Importance ratios connect Actor–Critic to PPO.'], explorer: { cue: 'Read TD target → δ → critic step → actor step; the error is shared, but each update differentiates a different function.' },
})

Object.assign(vfaChapter.zh, { title: '通过共享参数在状态之间传播价值信息' })
Object.assign(vfaChapter.en, { title: 'Transferring value across states with shared parameters' })
Object.assign(dqnChapter.zh, { title: 'Target network 与 replay 的稳定化分工' })
Object.assign(dqnChapter.en, { title: 'Distinct stabilization roles of target networks and replay' })
Object.assign(policyGradientChapter.zh, { title: '直接提高高回报动作的概率' })
Object.assign(policyGradientChapter.en, { title: 'Directly increasing the probability of high-return actions' })
Object.assign(actorCriticChapter.zh, { title: 'Critic 为 Actor 提供及时且低方差的学习信号' })
Object.assign(actorCriticChapter.en, { title: 'Timely, lower-variance actor feedback from a critic' })
Object.assign(monteCarloChapter.zh, { eyebrow: '第 6 章 · Monte Carlo 经验估计' })
Object.assign(monteCarloChapter.en, { eyebrow: 'Chapter 6 · Monte Carlo estimation from experience' })
Object.assign(tdChapter.zh, { eyebrow: '第 8 章 · TD 单步预测', derivationEyebrow: '单步 Bellman 残差', derivationTitle: '从一次环境转移得到 TD(0) 更新' })
Object.assign(tdChapter.en, { eyebrow: 'Chapter 8 · One-step TD prediction', derivationEyebrow: 'One-step Bellman residual', derivationTitle: 'Derive a TD(0) update from one transition' })
Object.assign(controlChapter.zh, { eyebrow: '第 9 章 · Sarsa 与 Q-learning 控制', derivationEyebrow: '动作价值控制', derivationTitle: '从动作价值评价得到 Sarsa 与 Q-learning 更新' })
Object.assign(controlChapter.en, { eyebrow: 'Chapter 9 · Sarsa and Q-learning control', derivationEyebrow: 'Action-value control', derivationTitle: 'Derive Sarsa and Q-learning updates from action-value evaluation' })
Object.assign(vfaChapter.zh, { eyebrow: '第 10 章 · 价值函数近似', derivationEyebrow: '参数共享', derivationTitle: '从参数化价值误差得到 semi-gradient 更新' })
Object.assign(vfaChapter.en, { eyebrow: 'Chapter 10 · Value-function approximation', derivationEyebrow: 'Parameter sharing', derivationTitle: 'Derive a semi-gradient update from parameterized value error' })
Object.assign(dqnChapter.zh, { eyebrow: '第 11 章 · 深度 Q-learning', derivationEyebrow: '稳定化训练步', derivationTitle: '把冻结 target 与 replay 写入同一次 Q-learning 更新' })
Object.assign(dqnChapter.en, { eyebrow: 'Chapter 11 · Deep Q-learning', derivationEyebrow: 'A stabilized training step', derivationTitle: 'Put a frozen target and replay into one Q-learning update' })
Object.assign(policyGradientChapter.zh, { eyebrow: '第 12 章 · 策略梯度', derivationEyebrow: '轨迹梯度估计', derivationTitle: '从策略目标得到可由轨迹估计的梯度' })
Object.assign(policyGradientChapter.en, { eyebrow: 'Chapter 12 · Policy gradient', derivationEyebrow: 'Trajectory gradient estimation', derivationTitle: 'Turn a policy objective into a trajectory-estimated gradient' })
Object.assign(actorCriticChapter.zh, { eyebrow: '第 13 章 · Actor–Critic', derivationEyebrow: '协同更新', derivationTitle: '用 TD error 同时更新 Critic 与 Actor' })
Object.assign(actorCriticChapter.en, { eyebrow: 'Chapter 13 · Actor–Critic', derivationEyebrow: 'Coupled updates', derivationTitle: 'Use TD error to update the critic and actor together' })
Object.assign(monteCarloChapter.zh.reasoningPath[0], { title: '未知模型使策略评价失去精确期望' })
Object.assign(monteCarloChapter.zh.reasoningPath[1], { title: '完整 episode 为价值估计提供 return 样本' })
Object.assign(monteCarloChapter.zh.reasoningPath[2], { title: '价值估计必须接回策略改善闭环' })
Object.assign(monteCarloChapter.en.reasoningPath[0], { title: 'An unknown model removes exact policy-evaluation expectations' })
Object.assign(monteCarloChapter.en.reasoningPath[1], { title: 'A complete episode supplies a return sample for value estimation' })
Object.assign(monteCarloChapter.en.reasoningPath[2], { title: 'Value estimation reconnects to the policy-improvement loop' })

export const part23Chapters = [monteCarloChapter, approximationChapter, tdChapter, controlChapter, vfaChapter, dqnChapter, policyGradientChapter, actorCriticChapter]
