import { assertFoundationChapterDefinition } from './schema.js'
import { ppoDeepeningEn, ppoDeepeningZh } from './modern-deepening.js'

const sources = [
  { id: 'actor-critic', label: 'Actor–Critic: baseline, advantage, and TD error', pages: 'L10, pp.6–22', href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning' },
  { id: 'ppo-paper', label: 'Proximal Policy Optimization Algorithms', pages: 'Sections 1–3', href: 'https://arxiv.org/abs/1707.06347' },
]

const zhDerivation = [
  { id: 'policy-gradient', rule: '从策略梯度的更新方向开始', latex: String.raw`\nabla_\theta J(\theta)=\mathbb E\!\left[\nabla_\theta\log\pi_\theta(A_t\mid S_t)\,Q^{\pi_\theta}(S_t,A_t)\right]`, short: '高价值动作的对数概率应被提高。', detail: 'Actor 直接参数化策略。乘在对数概率梯度后的权重决定该动作概率上升还是下降；最直接的权重是动作价值，但它通常方差较高。', assumptions: ['轨迹由当前策略采样', '期望与梯度可交换'], symbols: [[String.raw`J(\theta)`, '策略目标'], [String.raw`Q^{\pi_\theta}`, '当前策略下的动作价值']] },
  { id: 'baseline', rule: '减去不依赖动作的 baseline', latex: String.raw`A^{\pi}(s,a)\coloneqq Q^{\pi}(s,a)-V^{\pi}(s)`, short: '优势只衡量动作相对该状态平均水平好多少。', detail: '从策略梯度权重中减去只依赖状态的 Vπ(s)，不会改变梯度期望，却通常能降低方差。Actor 用优势决定方向，Critic 负责估计状态价值。', assumptions: ['baseline 不依赖动作'], symbols: [[String.raw`A^{\pi}(s,a)`, '动作优势'], [String.raw`V^{\pi}(s)`, '状态平均水平']] },
  { id: 'td-advantage', rule: '用一步 TD error 近似优势', latex: String.raw`\widehat A_t\approx\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t)`, short: '实际一步结果高于预期时，优势为正。', detail: 'Critic 比较“奖励加后继价值”和当前价值。这个差既能训练 Critic，也能作为 Actor 的低方差更新信号；多步 GAE 会在此基础上累积若干 TD error。', assumptions: ['Vφ 近似当前策略的状态价值'], symbols: [[String.raw`\delta_t`, '时间差分误差'], [String.raw`\phi`, 'Critic 参数']] },
  { id: 'ratio', rule: '把旧策略样本换算到新策略', latex: String.raw`r_t(\theta)\coloneqq\frac{\pi_\theta(A_t\mid S_t)}{\pi_{\theta_{\mathrm{old}}}(A_t\mid S_t)}`, short: '比值 1 表示该动作概率没有变化。', detail: 'rollout 由冻结的旧策略产生，而优化过程中 θ 会改变。概率比衡量新策略对已采样动作的相对偏好，为复用同一批数据提供重要性修正。', assumptions: [String.raw`\pi_{\theta_{\mathrm{old}}}(A_t\mid S_t)>0`], symbols: [[String.raw`r_t(\theta)`, '新旧动作概率比'], [String.raw`\theta_{\mathrm{old}}`, '采样策略快照']] },
  { id: 'surrogate', rule: '形成未裁剪的代理目标', latex: String.raw`L^{\mathrm{PG}}(\theta)=\mathbb E_t\!\left[r_t(\theta)\widehat A_t\right]`, short: '优势定方向，比值定变化幅度。', detail: '正优势样本希望 r_t 增大，负优势样本希望 r_t 减小。但若在同一批数据上更新太多轮，比值可能远离 1，而旧优势不再可靠。', assumptions: ['优势在一轮 PPO 优化期间固定'], symbols: [[String.raw`\widehat A_t`, '估计优势']] },
  { id: 'clipped-objective', rule: '截断继续远离旧策略的收益', latex: String.raw`L^{\mathrm{CLIP}}(\theta)=\mathbb E_t\!\left[\min\!\left(r_t\widehat A_t,\operatorname{clip}(r_t,1-\epsilon,1+\epsilon)\widehat A_t\right)\right]`, short: '超过近端区间后，继续把概率推远不再增加目标收益。', detail: 'min 必须与优势符号一起理解：正优势限制概率过度上升，负优势限制概率过度下降。它不是把参数锁在硬边界，而是为一批数据上的多轮小批量更新加入保守目标。', assumptions: [String.raw`0<\epsilon<1`], symbols: [[String.raw`\epsilon`, '裁剪半宽'], [String.raw`\operatorname{clip}`, '截断函数']] },
]

const enDerivation = [
  { id: 'policy-gradient', rule: 'Start from the policy-gradient direction', latex: String.raw`\nabla_\theta J(\theta)=\mathbb E\!\left[\nabla_\theta\log\pi_\theta(A_t\mid S_t)\,Q^{\pi_\theta}(S_t,A_t)\right]`, short: 'Increase the log-probability of valuable actions.', detail: 'The actor directly parameterizes the policy. The weight on the log-probability gradient sets the direction; action value is direct but often high variance.', assumptions: ['Trajectories come from the current policy', 'Gradient and expectation can be interchanged'], symbols: [[String.raw`J(\theta)`, 'policy objective'], [String.raw`Q^{\pi_\theta}`, 'action value under the current policy']] },
  { id: 'baseline', rule: 'Subtract an action-independent baseline', latex: String.raw`A^{\pi}(s,a)\coloneqq Q^{\pi}(s,a)-V^{\pi}(s)`, short: 'Advantage measures an action relative to the state average.', detail: 'Subtracting Vπ(s) leaves the expected policy gradient unchanged and usually reduces variance. The actor uses advantage; the critic estimates state value.', assumptions: ['The baseline does not depend on the action'], symbols: [[String.raw`A^{\pi}(s,a)`, 'action advantage'], [String.raw`V^{\pi}(s)`, 'state-average baseline']] },
  { id: 'td-advantage', rule: 'Approximate advantage with one-step TD error', latex: String.raw`\widehat A_t\approx\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t)`, short: 'A better-than-expected one-step outcome gives positive advantage.', detail: 'The critic compares reward plus successor value with current value. The difference trains the critic and supplies a lower-variance actor signal; GAE extends it across multiple steps.', assumptions: ['Vφ approximates current-policy value'], symbols: [[String.raw`\delta_t`, 'temporal-difference error'], [String.raw`\phi`, 'critic parameters']] },
  { id: 'ratio', rule: 'Reweight old-policy samples for the new policy', latex: String.raw`r_t(\theta)\coloneqq\frac{\pi_\theta(A_t\mid S_t)}{\pi_{\theta_{\mathrm{old}}}(A_t\mid S_t)}`, short: 'A ratio of one means the sampled action probability is unchanged.', detail: 'The rollout comes from a frozen old policy while θ changes during optimization. The ratio measures relative preference for the sampled action.', assumptions: [String.raw`\pi_{\theta_{\mathrm{old}}}(A_t\mid S_t)>0`], symbols: [[String.raw`r_t(\theta)`, 'new-to-old probability ratio'], [String.raw`\theta_{\mathrm{old}}`, 'sampling-policy snapshot']] },
  { id: 'surrogate', rule: 'Form the unclipped surrogate objective', latex: String.raw`L^{\mathrm{PG}}(\theta)=\mathbb E_t\!\left[r_t(\theta)\widehat A_t\right]`, short: 'Advantage sets direction; the ratio measures movement.', detail: 'Positive-advantage samples want the ratio to rise; negative ones want it to fall. Repeated updates can move too far from the data-collecting policy.', assumptions: ['Advantages stay fixed within one PPO optimization phase'], symbols: [[String.raw`\widehat A_t`, 'estimated advantage']] },
  { id: 'clipped-objective', rule: 'Cap gains from moving farther away', latex: String.raw`L^{\mathrm{CLIP}}(\theta)=\mathbb E_t\!\left[\min\!\left(r_t\widehat A_t,\operatorname{clip}(r_t,1-\epsilon,1+\epsilon)\widehat A_t\right)\right]`, short: 'Beyond the proximal interval, farther movement adds no objective gain.', detail: 'Read min together with the sign of advantage: it caps excessive probability increases for positive samples and excessive decreases for negative samples. It is a conservative objective, not a hard parameter constraint.', assumptions: [String.raw`0<\epsilon<1`], symbols: [[String.raw`\epsilon`, 'clip half-width'], [String.raw`\operatorname{clip}`, 'clipping operator']] },
]

export const ppoChapter = assertFoundationChapterDefinition({
  id: 'ppo', sources,
  zh: {
    prerequisite: '前置：状态价值、动作价值、策略梯度与 Actor–Critic', summaryTitle: 'PPO 保留 Actor–Critic，只改变 Actor 使用旧数据更新的方式', eyebrow: '现代策略优化 · Actor–Critic 与 PPO', title: 'Rollout 复用与策略更新幅度控制', intro: 'Actor 产生动作分布，Critic 估计状态价值；二者通过 advantage 相连。PPO 再记录采样时的旧策略概率，用新旧概率比衡量更新幅度，并用 clipped surrogate objective 抑制对同一批数据的过度优化。', derivationIntro: '公式链始终从已定义的状态价值和动作价值出发；点击任意一行可查看该步的假设、符号和直觉。', bridge: '先把 Actor、Critic、优势、旧策略快照和裁剪目标放到同一条链上，再观察参数怎样改变具体样本。', experimentIntro: '下面每个点代表旧策略采到的一个动作。横轴是已经估计好的优势，纵轴是新旧策略概率比；调整 ε 与更新强度，观察何时额外改进会被截断。', interpretation: '读图时先看优势的正负，再看比值是否越过对应边界。被裁剪不等于样本被删除，而是该方向上继续远离旧策略不再带来额外代理目标收益。', figure: '交互图 14.1 · PPO Clip Plane', instruction: '改变裁剪范围与更新强度，并逐个检查样本', question: '为什么同一个裁剪区间对正优势和负优势产生相反方向的保护？', derivation: zhDerivation, deepening: ppoDeepeningZh, prelude: [{ id: 'actor-critic-loop', kicker: '先建立接口', title: 'Actor 负责行动，Critic 负责比较预期', paragraphs: ['优势把动作结果与该状态的平均水平分开；PPO 不替代这个闭环，而是在 Actor 的更新目标上加入旧策略参照。'], formulas: [String.raw`A^{\pi}(s,a)=Q^{\pi}(s,a)-V^{\pi}(s)`] }], sections: [
      { id: 'gae', kicker: '优势估计', title: 'GAE 在一步 TD 与长回报之间调节时间尺度', paragraphs: ['一步 TD 信号及时但依赖 Critic 的 bootstrap；更长的回报包含更多真实奖励但方差更高。GAE 用 λ 对连续 TD error 做几何加权。', 'λ 接近 0 时更像一步 TD；接近 1 时利用更长时间范围。'], formula: String.raw`\widehat A_t^{\mathrm{GAE}(\gamma,\lambda)}=\sum_{l=0}^{T-t-1}(\gamma\lambda)^l\delta_{t+l}` },
      { id: 'update-cycle', kicker: '一次更新', title: '采样与优化必须分成两个清楚阶段', paragraphs: ['先冻结旧策略并收集 rollout，再固定优势与旧 log-probability，把样本打乱成 minibatch 做若干轮优化。完成后刷新旧策略快照并重新采样。', 'KL、裁剪比例和 value loss 是诊断量；它们共同提示策略是否已经离采样分布太远。'], formula: String.raw`\text{rollout with }\pi_{\theta_{\mathrm{old}}}\;\longrightarrow\;K\text{ minibatch epochs}\;\longrightarrow\;\theta_{\mathrm{old}}\leftarrow\theta` },
      { id: 'boundary', kicker: '边界', title: 'Clipping 是保守代理目标，不是绝对信赖域', paragraphs: ['梯度由整批样本共同决定，因此某个样本被裁剪并不保证最终参数对应的所有概率比都留在区间内。', '实践中仍需限制优化轮数、监控近似 KL，并检查价值函数与优势估计是否失真。'], formula: String.raw`r_t\notin[1-\epsilon,1+\epsilon]\ \text{can still occur after an update}` },
    ], summary: ['Actor–Critic 用价值基线把策略更新方向写成优势。', 'PPO 用旧策略概率比复用 rollout，并用裁剪目标抑制过度更新。', '优势符号决定应提高还是降低动作概率；裁剪只截断继续远离的收益。', '多轮 minibatch 更新必须与重新 rollout 的生命周期配套。'], explorer: {},
  },
  en: {
    prerequisite: 'Prerequisites: state value, action value, policy gradient, and Actor–Critic', summaryTitle: 'PPO keeps Actor–Critic and changes how the actor reuses old data', eyebrow: 'Modern policy optimization · Actor–Critic and PPO', title: 'Rollout reuse with controlled policy movement', intro: 'The actor produces an action distribution and the critic estimates state value; advantage connects them. PPO records old-policy probabilities, measures movement with a probability ratio, and uses a clipped surrogate to discourage over-optimizing one batch.', derivationIntro: 'The chain starts from defined values and keeps every step visible. Select a line to inspect its assumptions, symbols, and intuition.', bridge: 'Place the actor, critic, advantage, old-policy snapshot, and clipped objective on one chain before varying sample-level parameters.', experimentIntro: 'Each point is an action sampled by the old policy. The horizontal axis is estimated advantage and the vertical axis is the new-to-old ratio. Vary ε and update strength to see when additional movement is capped.', interpretation: 'Read the sign of advantage first, then test the corresponding ratio boundary. A clipped sample is not deleted; farther movement in that direction simply stops improving the surrogate.', figure: 'Interactive Figure 14.1 · PPO Clip Plane', instruction: 'Change clipping and update strength, then inspect individual samples', question: 'Why does one clip interval protect positive and negative advantages in opposite directions?', derivation: enDerivation, deepening: ppoDeepeningEn, prelude: [{ id: 'actor-critic-loop', kicker: 'Establish the interface', title: 'The actor acts; the critic compares against expectation', paragraphs: ['Advantage separates an action outcome from the state average. PPO preserves this loop and adds an old-policy reference to the actor objective.'], formulas: [String.raw`A^{\pi}(s,a)=Q^{\pi}(s,a)-V^{\pi}(s)`] }], sections: [
      { id: 'gae', kicker: 'Advantage estimation', title: 'GAE tunes the time scale between one-step TD and long returns', paragraphs: ['One-step TD is timely but bootstraps from the critic; longer returns include more observed rewards but have higher variance. GAE geometrically weights consecutive TD errors.', 'Near zero, λ behaves like one-step TD; near one, it includes a longer horizon.'], formula: String.raw`\widehat A_t^{\mathrm{GAE}(\gamma,\lambda)}=\sum_{l=0}^{T-t-1}(\gamma\lambda)^l\delta_{t+l}` },
      { id: 'update-cycle', kicker: 'One update', title: 'Sampling and optimization are distinct phases', paragraphs: ['Freeze the old policy for rollout collection, then hold advantages and old log-probabilities fixed while shuffling samples through several minibatch epochs. Refresh the snapshot and sample again afterward.', 'KL, clip fraction, and value loss diagnose whether optimization has moved too far from the data distribution.'], formula: String.raw`\text{rollout with }\pi_{\theta_{\mathrm{old}}}\;\longrightarrow\;K\text{ minibatch epochs}\;\longrightarrow\;\theta_{\mathrm{old}}\leftarrow\theta` },
      { id: 'boundary', kicker: 'Boundary', title: 'Clipping is a conservative surrogate, not an absolute trust region', paragraphs: ['The batch gradient couples samples, so clipping one sample does not guarantee every final probability ratio remains inside the interval.', 'Practice still limits epochs, monitors approximate KL, and checks value and advantage quality.'], formula: String.raw`r_t\notin[1-\epsilon,1+\epsilon]\ \text{can still occur after an update}` },
    ], summary: ['Actor–Critic uses a value baseline to express policy direction as advantage.', 'PPO reuses rollout data through old-policy ratios and discourages excessive movement with clipping.', 'Advantage sign determines whether probability should rise or fall; clipping caps gain from moving farther.', 'Repeated minibatch updates must be paired with a fresh-rollout lifecycle.'], explorer: {},
  },
})

Object.assign(ppoChapter.zh, { eyebrow: '第 14 章 · PPO 策略更新' })
Object.assign(ppoChapter.en, { eyebrow: 'Chapter 14 · PPO policy updates' })
