import { assertFoundationChapterDefinition } from './schema.js'
import { ppoDeepeningEn, ppoDeepeningZh } from './modern-deepening.js'

const sources = [
  { id: 'actor-critic', label: 'Actor–Critic: baseline, advantage, and TD error', pages: 'L10, pp.6–22', href: 'https://github.com/MathFoundationRL/Book-Mathematical-Foundation-of-Reinforcement-Learning' },
  { id: 'ppo-paper', label: 'Proximal Policy Optimization Algorithms', pages: 'Sections 1–3', href: 'https://arxiv.org/abs/1707.06347' },
]

const zhDerivation = [
  { id: 'policy-gradient', rule: '从策略梯度的更新方向开始', latex: String.raw`\nabla_\theta J(\theta)=\mathbb E\!\left[\nabla_\theta\log\pi_\theta(A_t\mid S_t)\,Q^{\pi_\theta}(S_t,A_t)\right]`, short: '高价值动作的对数概率应被提高。', detail: 'Actor 直接参数化策略。乘在对数概率梯度后的权重决定该动作概率上升还是下降；最直接的权重是动作价值，但它通常方差较高。', assumptions: ['轨迹由当前策略采样', '期望与梯度可交换'], symbols: [[String.raw`J(\theta)`, '策略目标'], [String.raw`Q^{\pi_\theta}`, '当前策略下的动作价值']] },
  { id: 'baseline', rule: '减去不依赖动作的 baseline', latex: String.raw`A^{\pi}(s,a)\coloneqq Q^{\pi}(s,a)-V^{\pi}(s)`, short: '优势只衡量动作相对该状态平均水平好多少。', detail: '从策略梯度权重中减去只依赖状态的 Vπ(s)，不会改变梯度期望，却通常能降低方差。Actor 用优势决定方向，Critic 负责估计状态价值。', assumptions: ['baseline 不依赖动作'], symbols: [[String.raw`A^{\pi}(s,a)`, '动作优势'], [String.raw`V^{\pi}(s)`, '状态平均水平']] },
  { id: 'td-advantage', rule: '用一步 TD error 近似优势', latex: String.raw`\widehat A_t\approx\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t)`, short: '实际一步结果高于预期时，优势为正。', detail: 'Critic 比较“奖励加后继价值”和当前价值。这个差既能训练 Critic，也能作为 Actor 的低方差更新信号；多步 GAE 会在此基础上累积若干 TD error。', assumptions: ['Vφ 近似当前策略的状态价值'], symbols: [[String.raw`\delta_t`, '时间差分误差'], [String.raw`\phi`, 'Critic 参数']] },
  { id: 'ratio', rule: '把旧策略样本换算到新策略', latex: String.raw`r_t(\theta)\coloneqq\frac{\pi_\theta(A_t\mid S_t)}{\pi_{\theta_{\mathrm{old}}}(A_t\mid S_t)}`, short: '比值 1 表示该动作概率没有变化。', detail: 'rollout 由冻结的旧策略产生，而优化过程中 θ 会改变。概率比衡量新策略对已采样动作的相对偏好，为复用同一批数据提供重要性修正。', assumptions: [String.raw`\pi_{\theta_{\mathrm{old}}}(A_t\mid S_t)>0`], symbols: [[String.raw`r_t(\theta)`, '新旧动作概率比'], [String.raw`\theta_{\mathrm{old}}`, '采样策略快照']] },
  { id: 'surrogate', rule: '形成未裁剪的代理目标', latex: String.raw`L^{\mathrm{PG}}(\theta)=\mathbb E_t\!\left[r_t(\theta)\widehat A_t\right]`, short: '优势定方向，比值定变化幅度。', detail: '正优势样本希望 r_t 增大，负优势样本希望 r_t 减小。但若在同一批数据上更新太多轮，比值可能远离 1，而旧优势不再可靠。', assumptions: ['优势在一轮 PPO 优化期间固定'], symbols: [[String.raw`\widehat A_t`, '估计优势']] },
  { id: 'clipped-objective', rule: '截断继续远离旧策略的收益', latex: String.raw`L^{\mathrm{CLIP}}(\theta)=\mathbb E_t\!\left[\min\!\left(r_t\widehat A_t,\operatorname{clip}(r_t,1-\epsilon,1+\epsilon)\widehat A_t\right)\right]`, short: '超过近端区间后，继续把概率推远不再增加目标收益。', detail: 'min 必须与优势符号一起理解：正优势限制概率过度上升，负优势限制概率过度下降。它不是把参数锁在硬边界，而是为一批数据上的多轮小批量更新加入保守目标。', assumptions: [String.raw`0<\epsilon<1`], symbols: [[String.raw`\epsilon`, '裁剪半宽'], [String.raw`\operatorname{clip}`, '截断函数']] },
]

const enDerivation = [
  { id: 'policy-gradient', rule: 'Start from the policy-gradient direction', latex: String.raw`\nabla_\theta J(\theta)=\mathbb E\!\left[\nabla_\theta\log\pi_\theta(A_t\mid S_t)\,Q^{\pi_\theta}(S_t,A_t)\right]`, short: 'Increase the log-probability of valuable actions.', detail: 'The actor directly parameterizes the policy. The weight on the log-probability gradient sets the direction; action value is direct but often high variance.', assumptions: ['Trajectories come from the current policy', 'Gradient and expectation can be interchanged'], symbols: [[String.raw`J(\theta)`, 'policy objective'], [String.raw`Q^{\pi_\theta}`, 'action value under the current policy']] },
  { id: 'baseline', rule: 'Subtract an action-independent baseline', latex: String.raw`A^{\pi}(s,a)\coloneqq Q^{\pi}(s,a)-V^{\pi}(s)`, short: 'Advantage measures an action relative to the state average.', detail: 'Subtracting Vπ(s) leaves the expected policy gradient unchanged and usually reduces variance. The actor uses advantage; the critic estimates state value.', assumptions: ['The baseline does not depend on the action'], symbols: [[String.raw`A^{\pi}(s,a)`, 'action advantage'], [String.raw`V^{\pi}(s)`, 'state-average baseline']] },
  { id: 'td-advantage', rule: 'Approximate advantage with one-step TD error', latex: String.raw`\widehat A_t\approx\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t)`, short: 'A better-than-expected one-step outcome gives positive advantage.', detail: 'The critic compares reward plus successor value with current value. The difference trains the critic and supplies a lower-variance actor signal; GAE extends it across multiple steps.', assumptions: ['Vφ approximates current-policy value'], symbols: [[String.raw`\delta_t`, 'temporal-difference error'], [String.raw`\phi`, 'critic parameters']] },
  { id: 'ratio', rule: 'Reweight old-policy samples for the new policy', latex: String.raw`r_t(\theta)\coloneqq\frac{\pi_\theta(A_t\mid S_t)}{\pi_{\theta_{\mathrm{old}}}(A_t\mid S_t)}`, short: 'A ratio of one means the sampled action probability is unchanged.', detail: 'The rollout comes from a frozen old policy while θ changes during optimization. The ratio measures relative preference for the sampled action.', assumptions: [String.raw`\pi_{\theta_{\mathrm{old}}}(A_t\mid S_t)>0`], symbols: [[String.raw`r_t(\theta)`, 'new-to-old probability ratio'], [String.raw`\theta_{\mathrm{old}}`, 'sampling-policy snapshot']] },
  { id: 'surrogate', rule: 'Form the unclipped surrogate objective', latex: String.raw`L^{\mathrm{PG}}(\theta)=\mathbb E_t\!\left[r_t(\theta)\widehat A_t\right]`, short: 'Advantage sets direction; the ratio measures movement.', detail: 'Positive-advantage samples want the ratio to rise; negative ones want it to fall. Repeated updates can move too far from the data-collecting policy.', assumptions: ['Advantages stay fixed within one PPO optimization phase'], symbols: [[String.raw`\widehat A_t`, 'estimated advantage']] },
  { id: 'clipped-objective', rule: 'Cap gains from moving farther away', latex: String.raw`L^{\mathrm{CLIP}}(\theta)=\mathbb E_t\!\left[\min\!\left(r_t\widehat A_t,\operatorname{clip}(r_t,1-\epsilon,1+\epsilon)\widehat A_t\right)\right]`, short: 'Beyond the proximal interval, farther movement adds no objective gain.', detail: 'Read min together with the sign of advantage: it caps excessive probability increases for positive samples and excessive decreases for negative samples. It is a conservative objective, not a hard parameter constraint.', assumptions: [String.raw`0<\epsilon<1`], symbols: [[String.raw`\epsilon`, 'clip half-width'], [String.raw`\operatorname{clip}`, 'clipping operator']] },
]

export const ppoChapter = assertFoundationChapterDefinition({
  id: 'ppo', sources,
  zh: {
    prerequisite: '前置：状态价值、动作价值、策略梯度与 Actor–Critic', summaryTitle: 'PPO 保留 Actor–Critic，只约束旧数据上的策略移动', eyebrow: '现代策略优化 · Actor–Critic 与 PPO', title: '怎样安全地重复使用一批旧策略轨迹', intro: 'Actor–Critic 已经能用优势更新策略，但若在同一批旧策略样本上连续优化，新策略会逐渐远离产生数据的策略，原来的优势估计也会失去代表性。PPO 保存采样时的动作概率，用新旧概率比衡量移动，并取消越过近端区间后继续移动所带来的额外收益。', derivationIntro: '前一章已经给出策略梯度、状态基线与优势。这里从真正新增的问题开始：旧策略采到的动作，怎样为正在变化的新策略提供有限而可信的更新依据。', bridge: '先明确旧批次为何会过期，再从新旧动作概率比推导替代目标与裁剪目标，最后把优势估计、价值损失和完整训练循环接回去。', experimentIntro: '图中每个点代表旧策略采到的一个动作。横轴是它的优势，纵轴是新旧动作概率比。调整裁剪宽度与更新强度，并选择样本，观察哪一侧的继续移动会失去目标收益。', interpretation: '先判断优势要求提高还是降低动作概率，再检查比值是否越过对应边界。裁剪不会删除样本，也不会把参数锁在区间内；它只是让该样本在危险方向上的进一步移动不再改善替代目标。', figure: '交互图 14.1 · PPO 裁剪平面', instruction: '改变裁剪宽度与更新强度，逐个检查样本的目标变化', question: '为什么同一个近端区间会分别限制正优势样本的上升和负优势样本的下降？', derivation: zhDerivation, deepening: ppoDeepeningZh, prelude: [{ id: 'actor-critic-loop', kicker: '尚未解决的问题', title: '优势给出方向，却没有限制一批旧数据能把策略推多远', paragraphs: ['正优势要求提高所选动作的概率，负优势要求降低它；但这个判断来自采样时的 Critic 与旧策略。', '若连续使用同一批样本，新策略会改变，而保存的优势不会随之更新。PPO 因此保留采样策略的动作概率，用它判断新策略已经离这批证据多远。'], formulas: [String.raw`A^{\pi}(s,a)=Q^{\pi}(s,a)-V^{\pi}(s)`] }], sections: [
      { id: 'gae', kicker: '优势估计', title: 'GAE 在一步 TD 与长回报之间调节时间尺度', paragraphs: ['一步 TD 信号及时但依赖 Critic 的 bootstrap；更长的回报包含更多真实奖励但方差更高。GAE 用 λ 对连续 TD error 做几何加权。', 'λ 接近 0 时更像一步 TD；接近 1 时利用更长时间范围。'], formula: String.raw`\widehat A_t^{\mathrm{GAE}(\gamma,\lambda)}=\sum_{l=0}^{T-t-1}(\gamma\lambda)^l\delta_{t+l}` },
      { id: 'update-cycle', kicker: '一次更新', title: '采样与优化必须分成两个清楚阶段', paragraphs: ['先冻结旧策略并收集 rollout，再固定优势与旧 log-probability，把样本打乱成 minibatch 做若干轮优化。完成后刷新旧策略快照并重新采样。', 'KL、裁剪比例和 value loss 是诊断量；它们共同提示策略是否已经离采样分布太远。'], formula: String.raw`\text{rollout with }\pi_{\theta_{\mathrm{old}}}\;\longrightarrow\;K\text{ minibatch epochs}\;\longrightarrow\;\theta_{\mathrm{old}}\leftarrow\theta` },
      { id: 'boundary', kicker: '方法边界', title: 'PPO 规定怎样更新，却不替任务定义一次决策', paragraphs: ['裁剪是保守的替代目标，不是参数的硬边界；整批样本共同产生梯度，因此更新后仍可能出现落在近端区间之外的概率比。训练仍需限制优化轮数，并监测近似 KL、价值误差与优势质量。', '更根本的是，PPO 只要求轨迹中存在状态、动作、奖励、终止标记与旧策略概率。把它用于语言模型之前，还必须回答：生成到哪个 token 构成状态，下一个 token 怎样成为动作，何时真正终止，何时只是被长度上限截断。下一章将补上这层序列决策定义。'], formula: String.raw`r_t\notin[1-\epsilon,1+\epsilon]\ \text{can still occur after an update}` },
    ], summary: ['Actor–Critic 用价值基线把策略更新方向写成优势。', 'PPO 用旧策略概率比复用 rollout，并用裁剪目标抑制过度更新。', '优势符号决定应提高还是降低动作概率；裁剪只截断继续远离的收益。', '多轮 minibatch 更新必须与重新 rollout 的生命周期配套。'], explorer: {},
  },
  en: {
    prerequisite: 'Prerequisites: state value, action value, policy gradient, and Actor–Critic', summaryTitle: 'PPO keeps Actor–Critic and constrains movement on old data', eyebrow: 'Modern policy optimization · Actor–Critic and PPO', title: 'Safely reusing a batch of old-policy trajectories', intro: 'Actor–Critic can update a policy from advantage, but repeated optimization on one old-policy batch gradually separates the new policy from the policy that produced the evidence. PPO stores sampled action probabilities, measures movement with a new-to-old ratio, and removes additional surrogate gain once movement crosses a proximal interval.', derivationIntro: 'The previous chapter established policy gradient, state baselines, and advantage. This derivation starts with the new problem: how old-policy actions can provide limited, trustworthy evidence for a changing policy.', bridge: 'First identify why a batch becomes stale, then derive the ratio, surrogate, and clipped objectives before reconnecting advantage estimation, value loss, and the complete training cycle.', experimentIntro: 'Each point is an action sampled by the old policy. The horizontal axis is its advantage and the vertical axis is the new-to-old action-probability ratio. Change clip width and update strength, then select samples to see which movement loses objective gain.', interpretation: 'First decide whether advantage calls for raising or lowering probability, then inspect the matching ratio boundary. Clipping neither deletes the sample nor locks parameters inside the interval; it only removes further surrogate gain in the unsafe direction.', figure: 'Interactive Figure 14.1 · PPO Clip Plane', instruction: 'Change clip width and update strength, then inspect each sample’s objective', question: 'Why does one proximal interval limit increases for positive advantages and decreases for negative ones?', derivation: enDerivation, deepening: ppoDeepeningEn, prelude: [{ id: 'actor-critic-loop', kicker: 'The unresolved problem', title: 'Advantage sets direction but does not limit how far an old batch can move the policy', paragraphs: ['Positive advantage calls for raising sampled-action probability and negative advantage for lowering it, but that judgment came from the critic and policy at collection time.', 'Repeated use changes the new policy while saved advantages stay fixed. PPO therefore retains old action probabilities to measure how far the policy has moved from the evidence.'], formulas: [String.raw`A^{\pi}(s,a)=Q^{\pi}(s,a)-V^{\pi}(s)`] }], sections: [
      { id: 'gae', kicker: 'Advantage estimation', title: 'GAE tunes the time scale between one-step TD and long returns', paragraphs: ['One-step TD is timely but bootstraps from the critic; longer returns include more observed rewards but have higher variance. GAE geometrically weights consecutive TD errors.', 'Near zero, λ behaves like one-step TD; near one, it includes a longer horizon.'], formula: String.raw`\widehat A_t^{\mathrm{GAE}(\gamma,\lambda)}=\sum_{l=0}^{T-t-1}(\gamma\lambda)^l\delta_{t+l}` },
      { id: 'update-cycle', kicker: 'One update', title: 'Sampling and optimization are distinct phases', paragraphs: ['Freeze the old policy for rollout collection, then hold advantages and old log-probabilities fixed while shuffling samples through several minibatch epochs. Refresh the snapshot and sample again afterward.', 'KL, clip fraction, and value loss diagnose whether optimization has moved too far from the data distribution.'], formula: String.raw`\text{rollout with }\pi_{\theta_{\mathrm{old}}}\;\longrightarrow\;K\text{ minibatch epochs}\;\longrightarrow\;\theta_{\mathrm{old}}\leftarrow\theta` },
      { id: 'boundary', kicker: 'Method boundary', title: 'PPO specifies an update, not what counts as one task decision', paragraphs: ['Clipping is a conservative surrogate rather than a hard parameter boundary. Because the batch gradient couples samples, final ratios may still fall outside the proximal interval; training must still limit epochs and monitor approximate KL, value error, and advantage quality.', 'More fundamentally, PPO only assumes that a trajectory supplies states, actions, rewards, termination flags, and old-policy probabilities. Before applying it to a language model, we must define a state at each token, the next-token action, true termination, and length-limit truncation. The next chapter supplies that sequence-decision model.'], formula: String.raw`r_t\notin[1-\epsilon,1+\epsilon]\ \text{can still occur after an update}` },
    ], summary: ['Actor–Critic uses a value baseline to express policy direction as advantage.', 'PPO reuses rollout data through old-policy ratios and discourages excessive movement with clipping.', 'Advantage sign determines whether probability should rise or fall; clipping caps gain from moving farther.', 'Repeated minibatch updates must be paired with a fresh-rollout lifecycle.'], explorer: {},
  },
})

Object.assign(ppoChapter.zh, { eyebrow: '第 14 章 · PPO 策略更新' })
Object.assign(ppoChapter.en, { eyebrow: 'Chapter 14 · PPO policy updates' })
