import { assertFoundationChapterDefinition } from './schema.js'
import { rlhfDeepeningEn, rlhfDeepeningZh } from './modern-deepening.js'

const sources = [
  { id: 'ppo', label: 'Proximal Policy Optimization Algorithms', pages: 'Sections 1–3', href: 'https://arxiv.org/abs/1707.06347' },
  { id: 'instructgpt', label: 'Training language models to follow instructions with human feedback', pages: 'Sections 2–3', href: 'https://arxiv.org/abs/2203.02155' },
]

const zhDerivation = [
  { id: 'lm-as-mdp', rule: '沿用 Token MDP 的序列决策对象', latex: String.raw`S_t=(x,y_{<t}),\qquad A_t=y_t,\qquad\pi_\theta(A_t\mid S_t)=\pi_\theta(y_t\mid x,y_{<t})`, short: '状态是 prompt 与前缀，动作是下一个 token。', detail: '第 15 章已经建立此映射。本章从这里出发，只加入 PPO-based RLHF 特有的模型角色和批次生命周期。', assumptions: ['模型使用自回归分解'], symbols: [[String.raw`x`, 'prompt'], [String.raw`y_{<t}`, '生成前缀']] },
  { id: 'reward-model', rule: '用冻结 reward model 给完整回答提供偏好分数', latex: String.raw`R_{\rm RM}=r_\psi(x,y)`, short: '偏好比较被学习成可计算的序列级标量。', detail: 'Reward model 由人类排序数据训练，在 PPO 阶段只前向打分，不随 policy minibatch 更新。', assumptions: ['reward model 在 PPO 阶段冻结'], symbols: [[String.raw`\psi`, 'reward model 参数']] },
  { id: 'reference-kl', rule: '逐 token 加入相对冻结 reference 的偏离代价', latex: String.raw`R_t^{\rm shaped}=R_t^{\rm task}-\beta\left[\log\pi_\theta(y_t\mid S_t)-\log\pi_{\rm ref}(y_t\mid S_t)\right]`, short: '偏好奖励负责前进，reference 约束负责防止分布失控。', detail: 'Reference 通常由 SFT 模型复制并长期冻结。它不是生成本批数据的 old policy。', assumptions: [String.raw`\beta\ge0`], symbols: [[String.raw`\pi_{\rm ref}`, '长期冻结参考策略']] },
  { id: 'token-gae', rule: '由 shaped reward 与 value model 计算逐 token GAE', latex: String.raw`\delta_t=R_{t+1}^{\rm shaped}+\gamma V_\phi(S_{t+1})-V_\phi(S_t),\qquad\widehat A_t=\sum_{l\ge0}(\gamma\lambda)^l\delta_{t+l}`, short: '序列分数经过 value baseline 变成 token 更新方向。', detail: 'Value model 读取每个前缀；mask、EOS 和 padding 必须与 policy 概率严格对齐。', assumptions: ['policy 与 value 使用同一 rollout batch'], symbols: [[String.raw`V_\phi`, '前缀价值模型']] },
  { id: 'ppo-update', rule: '用实际生成策略的旧概率构造裁剪更新', latex: String.raw`L^{\rm CLIP}=\mathbb E_t\!\left[\min\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)}\widehat A_t,\operatorname{clip}\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)},1-\epsilon,1+\epsilon\right)\widehat A_t\right)\right]`, short: 'Old policy 连接生成和训练，reference 约束长期行为。', detail: '分母必须对应实际生成该 token 的策略快照。用 reference 代替 old 会破坏重要性修正。', assumptions: ['old log-probability 与 token 位置一致'], symbols: [[String.raw`\pi_{\rm old}`, '生成当前 batch 的策略快照']] },
  { id: 'refresh-loop', rule: '更新 policy/value 并刷新 rollout worker', latex: String.raw`(\theta,\phi)\leftarrow\operatorname{Update}(\mathcal B),\qquad\psi\ \text{and}\ \pi_{\rm ref}\ \text{remain frozen}`, short: '训练后发布新 policy，再生成下一批数据。', detail: '固定 batch 只复用有限轮；过度异步会增加 policy lag。Reward 与 reference 在此阶段保持冻结。', assumptions: ['batch 在一次更新阶段固定'], symbols: [[String.raw`\mathcal B`, 'rollout batch']] },
]

const enDerivation = [
  { id: 'lm-as-mdp', rule: 'Reuse the sequential objects from Token MDP', latex: String.raw`S_t=(x,y_{<t}),\qquad A_t=y_t,\qquad\pi_\theta(A_t\mid S_t)=\pi_\theta(y_t\mid x,y_{<t})`, short: 'State is prompt plus prefix and action is the next token.', detail: 'Chapter 15 established this mapping. This chapter only adds PPO-based RLHF roles and lifecycle.', assumptions: ['The model factorizes autoregressively'], symbols: [[String.raw`x`, 'prompt'], [String.raw`y_{<t}`, 'generated prefix']] },
  { id: 'reward-model', rule: 'Score complete responses with a frozen reward model', latex: String.raw`R_{\rm RM}=r_\psi(x,y)`, short: 'Preference comparisons become a computable sequence scalar.', detail: 'The reward model is trained from rankings and only scores during PPO.', assumptions: ['Reward model is frozen during PPO'], symbols: [[String.raw`\psi`, 'reward-model parameters']] },
  { id: 'reference-kl', rule: 'Add tokenwise deviation cost from a frozen reference', latex: String.raw`R_t^{\rm shaped}=R_t^{\rm task}-\beta\left[\log\pi_\theta(y_t\mid S_t)-\log\pi_{\rm ref}(y_t\mid S_t)\right]`, short: 'Preference drives improvement while reference regularization prevents uncontrolled drift.', detail: 'The reference is a long-lived SFT copy and is not the old policy that generated this batch.', assumptions: [String.raw`\beta\ge0`], symbols: [[String.raw`\pi_{\rm ref}`, 'long-lived frozen reference']] },
  { id: 'token-gae', rule: 'Compute token GAE from shaped reward and value', latex: String.raw`\delta_t=R_{t+1}^{\rm shaped}+\gamma V_\phi(S_{t+1})-V_\phi(S_t),\qquad\widehat A_t=\sum_{l\ge0}(\gamma\lambda)^l\delta_{t+l}`, short: 'A sequence score becomes token update direction through the value baseline.', detail: 'Masks, EOS, and padding must align policy probabilities and value positions.', assumptions: ['Policy and value share one rollout batch'], symbols: [[String.raw`V_\phi`, 'prefix value model']] },
  { id: 'ppo-update', rule: 'Use probabilities from the actual generating policy for clipping', latex: String.raw`L^{\rm CLIP}=\mathbb E_t\!\left[\min\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)}\widehat A_t,\operatorname{clip}\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)},1-\epsilon,1+\epsilon\right)\widehat A_t\right)\right]`, short: 'Old connects generation to training; reference constrains long-term behavior.', detail: 'The denominator must match the policy snapshot that generated each token.', assumptions: ['Old log-probability aligns with token positions'], symbols: [[String.raw`\pi_{\rm old}`, 'snapshot that generated this batch']] },
  { id: 'refresh-loop', rule: 'Update policy/value and refresh rollout workers', latex: String.raw`(\theta,\phi)\leftarrow\operatorname{Update}(\mathcal B),\qquad\psi\ \text{and}\ \pi_{\rm ref}\ \text{remain frozen}`, short: 'Publish the policy and collect a fresh batch.', detail: 'A fixed batch is reused only finitely; excessive asynchrony creates policy lag.', assumptions: ['Batch is fixed within one update phase'], symbols: [[String.raw`\mathcal B`, 'rollout batch']] },
]

export const rlhfChapter = assertFoundationChapterDefinition({
  id: 'rlhf', sources,
  zh: {
    prerequisite: '前置：PPO、Token MDP 与 GAE', eyebrow: 'PPO-based RLHF 系统', title: 'Response 在五类模型角色之间形成 PPO batch', intro: 'PPO-based RLHF 是在线训练流程，而不只是一个损失函数。Policy 生成回答；old policy 记录采样分布；reference policy 约束长期漂移；reward model 给出偏好分数；value model 把序列结果变成逐 token advantage。理解这些角色的数据血缘，是把第 14 章 PPO 放进语言模型系统的关键。', bridge: '本章建立 PPO-based RLHF 的闭环：生成、打分、奖励整形、GAE、minibatch 更新和权重刷新。离线偏好优化与组相对在线优化分别留给第 17、18 章。', derivationIntro: '从已经定义的 Token MDP 出发，依次加入 reward、reference KL、value/GAE、old-policy ratio 与 worker 刷新。', experimentIntro: '固定一个 rollout batch，在算法视图和系统视图间切换，检查每个 token 的 old/reference 概率、reward、value、advantage 与更新目标是否保持同一位置。', interpretation: '系统的核心不变量是样本身份、token 位置和模型版本。Old 与 reference 都输出概率，但 old 负责采样校正，reference 负责长期约束；二者不能合并。Policy/value 更新，reward/reference 冻结。', figure: '交互图 16.1 · PPO-based RLHF Shared Batch', instruction: '在算法与系统视图追踪同一批 token 证据', question: '为什么 old policy 与 reference policy 都输出概率，却承担不同统计职责？', derivation: zhDerivation, deepening: rlhfDeepeningZh,
    prelude: [
      { id: 'pipeline-level', kicker: '先区分层级', title: 'SFT、reward modeling 与 PPO 是三个训练阶段', paragraphs: ['SFT 提供可用初始策略；偏好比较训练 reward model；在线 policy 再生成回答并接受 PPO 更新。模型来源和冻结关系决定后续数据是否有效。'], formulas: [String.raw`\mathrm{SFT}\rightarrow\mathrm{reward\ modeling}\rightarrow\mathrm{online\ rollout+PPO}`] },
      { id: 'role-separation', kicker: '角色分离', title: 'Old 是短期采样快照，reference 是长期行为锚点', paragraphs: ['每轮 rollout 前复制 old；reference 通常从 SFT 初始化后长期冻结。用同一对象承担两者会让 ratio 或 KL 目标失真。'], formulas: [String.raw`\theta_{\rm old}\leftarrow\theta\ \text{per rollout},\qquad\theta_{\rm ref}\leftarrow\theta_{\rm SFT}\ \text{and frozen}`] },
    ],
    sections: [
      { id: 'model-roles', kicker: '五类角色', title: 'Policy、old、reference、reward 与 value 各自回答一个问题', paragraphs: ['Policy 决定现在生成什么；old 说明本批数据从哪里来；reference 衡量长期漂移；reward 表达偏好；value 估计每个前缀的调整后未来回报。'], formula: String.raw`\pi_\theta\neq\pi_{\rm old}\neq\pi_{\rm ref},\qquad r_\psi\ \text{is not a policy}` },
      { id: 'batch-contract', kicker: '批次契约', title: 'Rollout 必须保存可重放的 token 级训练证据', paragraphs: ['Token、response mask、old log-probability、old value、终止位置和模型版本共同定义批次。Reference 概率与 reward 可以后算，但必须使用同一 tokenization。'], formula: String.raw`\mathcal B=\{x,y,m,\log\pi_{\rm old},V_{\rm old},R,\text{versions}\}` },
      { id: 'online-loop', kicker: '生命周期', title: '一次 PPO 更新结束，也是下一轮 rollout 的开始', paragraphs: ['有限轮 minibatch 后发布新 policy；生成端刷新权重并丢弃旧批次。吞吐优化必须服从这条统计边界。'], formula: String.raw`\text{generate}\rightarrow\text{score}\rightarrow\text{GAE}\rightarrow\text{update}\rightarrow\text{refresh}` },
    ], summaryTitle: 'PPO-based RLHF 是带严格数据血缘的在线闭环', summary: ['Policy、old、reference、reward 与 value 不能按名称相近随意合并。', 'Reference KL 与 old-policy ratio 解决不同问题。', 'Token、mask、概率与 value 必须位置对齐。', '更新完成后必须刷新 worker 并重新 rollout。'], explorer: {},
  },
  en: {
    prerequisite: 'Prerequisites: PPO, Token MDP, and GAE', eyebrow: 'PPO-based RLHF system', title: 'A response becomes a PPO batch across five model roles', intro: 'PPO-based RLHF is an online training process, not merely a loss. Policy generates; old policy records the sampling distribution; reference constrains long-term drift; reward model scores preference; value turns sequence outcome into token advantages. Their data provenance connects Chapter 14 PPO to a language-model system.', bridge: 'This chapter establishes the PPO-based RLHF loop: generation, scoring, shaping, GAE, minibatch updates, and weight refresh. Offline preference and group-relative online learning belong to Chapters 17 and 18.', derivationIntro: 'Starting from Token MDP, add reward, reference KL, value/GAE, old-policy ratios, and worker refresh in order.', experimentIntro: 'Keep one rollout batch fixed while switching algorithm/system views. Verify that old/reference probabilities, reward, value, advantage, and targets stay aligned to token positions.', interpretation: 'Sample identity, token position, and model version are invariants. Old corrects sampling while reference anchors behavior; they cannot merge. Policy/value update while reward/reference remain frozen.', figure: 'Interactive Figure 16.1 · PPO-based RLHF Shared Batch', instruction: 'Trace one token batch across algorithm and system views', question: 'Why do old and reference both output probabilities yet serve different statistical roles?', derivation: enDerivation, deepening: rlhfDeepeningEn,
    prelude: [
      { id: 'pipeline-level', kicker: 'Separate levels', title: 'SFT, reward modeling, and PPO are three training stages', paragraphs: ['SFT supplies the initial policy, comparisons train reward, and the online policy generates responses for PPO. Model provenance determines valid data.'], formulas: [String.raw`\mathrm{SFT}\rightarrow\mathrm{reward\ modeling}\rightarrow\mathrm{online\ rollout+PPO}`] },
      { id: 'role-separation', kicker: 'Separate roles', title: 'Old is a short-lived sampling snapshot; reference is a long-lived anchor', paragraphs: ['Copy old before each rollout; keep the SFT reference frozen. Merging them corrupts ratio or KL semantics.'], formulas: [String.raw`\theta_{\rm old}\leftarrow\theta\ \text{per rollout},\qquad\theta_{\rm ref}\leftarrow\theta_{\rm SFT}\ \text{and frozen}`] },
    ],
    sections: [
      { id: 'model-roles', kicker: 'Five roles', title: 'Policy, old, reference, reward, and value answer different questions', paragraphs: ['Policy chooses generation; old identifies batch provenance; reference measures drift; reward encodes preference; value predicts adjusted return.'], formula: String.raw`\pi_\theta\neq\pi_{\rm old}\neq\pi_{\rm ref},\qquad r_\psi\ \text{is not a policy}` },
      { id: 'batch-contract', kicker: 'Batch contract', title: 'A rollout must store replayable token-level evidence', paragraphs: ['Tokens, masks, old probabilities, old values, termination, and versions define the batch. Later scoring must preserve tokenization.'], formula: String.raw`\mathcal B=\{x,y,m,\log\pi_{\rm old},V_{\rm old},R,\text{versions}\}` },
      { id: 'online-loop', kicker: 'Lifecycle', title: 'Finishing one PPO update begins the next rollout', paragraphs: ['Publish the policy after finite minibatches, refresh workers, and discard the old batch. Throughput must respect this boundary.'], formula: String.raw`\text{generate}\rightarrow\text{score}\rightarrow\text{GAE}\rightarrow\text{update}\rightarrow\text{refresh}` },
    ], summaryTitle: 'PPO-based RLHF is an online loop with strict data provenance', summary: ['Policy, old, reference, reward, and value are distinct roles.', 'Reference KL and old-policy ratios solve different problems.', 'Tokens, masks, probabilities, and values must align.', 'Workers refresh and roll out again after updates.'], explorer: {},
  },
})
