import { assertFoundationChapterDefinition } from './schema.js'
import { rlhfDeepeningEn, rlhfDeepeningZh } from './modern-deepening.js'

const sources = [
  { id: 'ppo', label: 'Proximal Policy Optimization Algorithms', pages: 'Sections 1–3', href: 'https://arxiv.org/abs/1707.06347' },
  { id: 'instructgpt', label: 'Training language models to follow instructions with human feedback', pages: 'Sections 2–3', href: 'https://arxiv.org/abs/2203.02155' },
]

const zhDerivation = [
  { id: 'lm-as-mdp', rule: '沿用 Token MDP 的序列决策对象', latex: String.raw`S_t=(x,y_{<t}),\qquad A_t=y_t,\qquad\pi_\theta(A_t\mid S_t)=\pi_\theta(y_t\mid x,y_{<t})`, short: '状态是 prompt 与前缀，动作是下一个 token。', detail: '第 15 章已经建立此映射。本章从这里出发，只加入 PPO-based RLHF 特有的模型角色和批次生命周期。', assumptions: ['模型使用自回归分解'], symbols: [[String.raw`x`, 'prompt'], [String.raw`y_{<t}`, '生成前缀']] },
  { id: 'reward-model', rule: '用冻结 reward model 给完整回答提供偏好分数', latex: String.raw`R_{\rm RM}=r_\psi(x,y)`, short: '偏好比较被学习成可计算的序列级标量。', detail: 'Reward model 由人类排序数据训练，在 PPO 阶段只前向打分，不随 policy minibatch 更新。', assumptions: ['reward model 在 PPO 阶段冻结'], symbols: [[String.raw`\psi`, 'reward model 参数']] },
  { id: 'reference-kl', rule: '逐 token 加入相对冻结 reference 的偏离代价', latex: String.raw`R_t^{\rm shaped}=R_t^{\rm task}-\beta\left[\log\pi_\theta(y_t\mid S_t)-\log\pi_{\rm ref}(y_t\mid S_t)\right]`, short: '偏好奖励负责前进，reference 约束负责防止分布失控。', detail: 'Reference 通常由 SFT 模型复制并长期冻结。它不是生成本批数据的 old policy。', assumptions: [String.raw`\beta\ge0`], symbols: [[String.raw`\pi_{\rm ref}`, '长期冻结参考策略']] },
  { id: 'token-gae', rule: '由 shaped reward 与 value model 计算逐 token GAE', latex: String.raw`\delta_t=R_{t+1}^{\rm shaped}+\gamma V_\phi(S_{t+1})-V_\phi(S_t),\qquad\widehat A_t=\sum_{l\ge0}(\gamma\lambda)^l\delta_{t+l}`, short: '序列分数经过 value baseline 变成 token 更新方向。', detail: 'Value model 读取每个前缀；mask、EOS 和 padding 必须与 policy 概率严格对齐。', assumptions: ['policy 与 value 使用同一 rollout batch'], symbols: [[String.raw`V_\phi`, '前缀价值模型']] },
  { id: 'ppo-update', rule: '用实际生成策略的旧概率构造裁剪更新', latex: String.raw`L^{\rm CLIP}=\mathbb E_t\!\left[\min\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)}\widehat A_t,\operatorname{clip}\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)},1-\epsilon,1+\epsilon\right)\widehat A_t\right)\right]`, short: 'Old policy 连接生成和训练，reference 约束长期行为。', detail: '分母必须对应实际生成该 token 的策略快照。用 reference 代替 old 会破坏重要性修正。', assumptions: ['old log-probability 与 token 位置一致'], symbols: [[String.raw`\pi_{\rm old}`, '生成当前 batch 的策略快照']] },
  { id: 'refresh-loop', rule: '更新 policy/value 并刷新 rollout worker', latex: String.raw`(\theta,\phi)\leftarrow\operatorname{Update}(\mathcal B),\qquad\psi\ \text{and}\ \pi_{\rm ref}\ \text{remain frozen}`, short: '训练后发布新 policy，再生成下一批数据。', detail: '固定 batch 只复用有限轮；过度异步会增加 policy lag。Reward 与 reference 在此阶段保持冻结。', assumptions: ['batch 在一次更新阶段固定'], symbols: [[String.raw`\mathcal B`, 'rollout batch']] },
]

const enDerivation = [
  { id: 'lm-as-mdp', rule: 'Reuse the sequential objects from Token MDP', latex: String.raw`S_t=(x,y_{<t}),\qquad A_t=y_t,\qquad\pi_\theta(A_t\mid S_t)=\pi_\theta(y_t\mid x,y_{<t})`, short: 'State is prompt plus prefix and action is the next token.', detail: 'Chapter 15 established this mapping. This chapter only adds PPO-based RLHF roles and lifecycle.', assumptions: ['The model factorizes autoregressively'], symbols: [[String.raw`x`, 'prompt'], [String.raw`y_{<t}`, 'generated prefix']] },
  { id: 'reward-model', rule: 'Score complete responses with a frozen reward model', latex: String.raw`R_{\rm RM}=r_\psi(x,y)`, short: 'Preference comparisons become a computable sequence scalar.', detail: 'The reward model is trained from rankings and only scores during PPO.', assumptions: ['Reward model is frozen during PPO'], symbols: [[String.raw`\psi`, 'reward-model parameters']] },
  { id: 'reference-kl', rule: 'Add tokenwise deviation cost from a frozen reference', latex: String.raw`R_t^{\rm shaped}=R_t^{\rm task}-\beta\left[\log\pi_\theta(y_t\mid S_t)-\log\pi_{\rm ref}(y_t\mid S_t)\right]`, short: 'Preference drives improvement while reference regularization prevents uncontrolled drift.', detail: 'The reference is a long-lived SFT copy and is not the old policy that generated this batch.', assumptions: [String.raw`\beta\ge0`], symbols: [[String.raw`\pi_{\rm ref}`, 'long-lived frozen reference']] },
  { id: 'token-gae', rule: 'Compute token GAE from shaped reward and value', latex: String.raw`\delta_t=R_{t+1}^{\rm shaped}+\gamma V_\phi(S_{t+1})-V_\phi(S_t),\qquad\widehat A_t=\sum_{l\ge0}(\gamma\lambda)^l\delta_{t+l}`, short: 'A sequence score becomes token update direction through the value baseline.', detail: 'Masks, EOS, and padding must align policy probabilities and value positions.', assumptions: ['Policy and value share one rollout batch'], symbols: [[String.raw`V_\phi`, 'prefix value model']] },
  { id: 'ppo-update', rule: 'Use probabilities from the actual generating policy for clipping', latex: String.raw`L^{\rm CLIP}=\mathbb E_t\!\left[\min\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)}\widehat A_t,\operatorname{clip}\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)},1-\epsilon,1+\epsilon\right)\widehat A_t\right)\right]`, short: 'Old connects generation to training; reference constrains long-term behavior.', detail: 'The denominator must match the policy snapshot that generated each token.', assumptions: ['Old log-probability aligns with token positions'], symbols: [[String.raw`\pi_{\rm old}`, 'snapshot that generated this batch']] },
  { id: 'refresh-loop', rule: 'Update policy/value and refresh rollout workers', latex: String.raw`(\theta,\phi)\leftarrow\operatorname{Update}(\mathcal B),\qquad\psi\ \text{and}\ \pi_{\rm ref}\ \text{remain frozen}`, short: 'Publish the policy and collect a fresh batch.', detail: 'A fixed batch is reused only finitely; excessive asynchrony creates policy lag.', assumptions: ['Batch is fixed within one update phase'], symbols: [[String.raw`\mathcal B`, 'rollout batch']] },
]

export const rlhfChapter = assertFoundationChapterDefinition({
  id: 'rlhf', sources,
  zh: {
    prerequisite: '前置：PPO、Token MDP 与 GAE', eyebrow: 'PPO-based RLHF 系统', title: 'Response 在五类模型角色之间形成 PPO batch', intro: 'PPO-based RLHF 是在线训练流程，而不只是一个损失函数。Policy 生成回答；old policy 记录采样分布；reference policy 约束长期漂移；reward model 给出偏好分数；value model 把序列结果变成逐 token advantage。理解这些角色的数据血缘，是把第 14 章 PPO 放进语言模型系统的关键。', bridge: '本章建立 PPO-based RLHF 的闭环：生成、打分、奖励整形、GAE、minibatch 更新和权重刷新。离线偏好优化与组相对在线优化分别留给第 17、18 章。', derivationIntro: '从已经定义的 Token MDP 出发，依次加入 reward、reference KL、value/GAE、old-policy ratio 与 worker 刷新。', experimentIntro: '固定一个 rollout batch，在算法视图和系统视图间切换，检查每个 token 的 old/reference 概率、reward、value、advantage 与更新目标是否保持同一位置。', interpretation: '系统的核心不变量是样本身份、token 位置和模型版本。Old 与 reference 都输出概率，但 old 负责采样校正，reference 负责长期约束；二者不能合并。Policy/value 更新，reward/reference 冻结。', figure: '交互图 16.1 · PPO-based RLHF Shared Batch', instruction: '在算法与系统视图追踪同一批 token 证据', question: '为什么 old policy 与 reference policy 都输出概率，却承担不同统计职责？', derivation: zhDerivation, deepening: rlhfDeepeningZh,
    prelude: [
      { id: 'pipeline-level', kicker: '先区分层级', title: 'SFT、reward modeling 与 PPO 构成前后依赖的训练阶段', paragraphs: ['SFT 先把预训练模型变成能够响应指令的初始策略；人类偏好比较随后训练 reward model，把回答排序转成可计算分数。', '在线 PPO 阶段才由当前 policy 生成新回答并使用这些分数更新策略。三个阶段的数据来源、模型初始化和冻结关系不同，混在一起会破坏后续概率与奖励的含义。'], formulas: [String.raw`\mathrm{SFT}\rightarrow\mathrm{reward\ modeling}\rightarrow\mathrm{online\ rollout+PPO}`] },
      { id: 'role-separation', kicker: '角色分离', title: 'Old 记录本批数据来源，reference 约束长期漂移', paragraphs: ['每轮 rollout 前从当前 policy 复制 old snapshot，用它生成回答并保存逐 token 概率；优化期间 old 保持不变，作为重要性比值的分母。', 'Reference 通常从 SFT 模型初始化后长期冻结，用于计算 KL 约束。若同一对象同时承担两种职责，随批次刷新的 reference 会失去稳定锚点，长期不变的 old 又无法描述实际采样分布。'], formulas: [String.raw`\theta_{\rm old}\leftarrow\theta\ \text{per rollout},\qquad\theta_{\rm ref}\leftarrow\theta_{\rm SFT}\ \text{and frozen}`] },
    ],
    sections: [
      { id: 'model-roles', kicker: '五类角色', title: '每类模型只负责一种统计职责', paragraphs: ['Policy 决定当前生成什么，old 说明本批数据由哪个分布产生，reference 衡量策略相对长期锚点的偏移，reward model 把偏好转成序列分数，value model 估计每个前缀的调整后未来回报。', '它们可能共享网络架构或初始化权重，但训练状态和使用时机不同。判断一个张量来自哪个模型、哪个版本，比记住“五个名字”更重要。'], formula: String.raw`\pi_\theta\neq\pi_{\rm old}\neq\pi_{\rm ref},\qquad r_\psi\ \text{is not a policy}` },
      { id: 'batch-contract', kicker: '批次契约', title: 'Rollout 保存从生成到更新都可核对的 token 证据', paragraphs: ['Token、response mask、old log-probability、old value、终止位置和模型版本共同定义一条训练样本；这些字段必须在相同 token 位置上对齐。', 'Reference 概率与 reward 可以在生成后计算，但必须复用完全相同的 tokenization 与 mask。否则 advantage 或 ratio 虽然形状合法，统计对象却已经错位。'], formula: String.raw`\mathcal B=\{x,y,m,\log\pi_{\rm old},V_{\rm old},R,\text{versions}\}` },
      { id: 'online-loop', kicker: '生命周期', title: '更新完成后必须用新策略重新生成证据', paragraphs: ['固定 batch 只在有限轮 minibatch 中复用；优化结束后发布新 policy，rollout worker 刷新权重，并丢弃已经与当前策略相距过远的旧批次。', '并行与异步可以提高吞吐量，但不能打破样本版本边界。过大的 policy lag 会使概率比失真，并让裁剪频繁替代真正有效的学习信号。'], formula: String.raw`\text{generate}\rightarrow\text{score}\rightarrow\text{GAE}\rightarrow\text{update}\rightarrow\text{refresh}` },
    ], summaryTitle: 'PPO-based RLHF 是带严格数据血缘的在线闭环', summary: ['Policy、old、reference、reward 与 value 不能按名称相近随意合并。', 'Reference KL 与 old-policy ratio 解决不同问题。', 'Token、mask、概率与 value 必须位置对齐。', '更新完成后必须刷新 worker 并重新 rollout。'], explorer: {},
  },
  en: {
    prerequisite: 'Prerequisites: PPO, Token MDP, and GAE', eyebrow: 'PPO-based RLHF system', title: 'A response becomes a PPO batch across five model roles', intro: 'PPO-based RLHF is an online training process, not merely a loss. Policy generates; old policy records the sampling distribution; reference constrains long-term drift; reward model scores preference; value turns sequence outcome into token advantages. Their data provenance connects Chapter 14 PPO to a language-model system.', bridge: 'This chapter establishes the PPO-based RLHF loop: generation, scoring, shaping, GAE, minibatch updates, and weight refresh. Offline preference and group-relative online learning belong to Chapters 17 and 18.', derivationIntro: 'Starting from Token MDP, add reward, reference KL, value/GAE, old-policy ratios, and worker refresh in order.', experimentIntro: 'Keep one rollout batch fixed while switching algorithm/system views. Verify that old/reference probabilities, reward, value, advantage, and targets stay aligned to token positions.', interpretation: 'Sample identity, token position, and model version are invariants. Old corrects sampling while reference anchors behavior; they cannot merge. Policy/value update while reward/reference remain frozen.', figure: 'Interactive Figure 16.1 · PPO-based RLHF Shared Batch', instruction: 'Trace one token batch across algorithm and system views', question: 'Why do old and reference both output probabilities yet serve different statistical roles?', derivation: enDerivation, deepening: rlhfDeepeningEn,
    prelude: [
      { id: 'pipeline-level', kicker: 'Separate levels', title: 'SFT, reward modeling, and PPO form dependent training stages', paragraphs: ['SFT first turns a pretrained model into an instruction-following initial policy. Human comparisons then train a reward model that converts response ordering into a computable score.', 'Only the online PPO stage generates fresh responses with the current policy and updates from those scores. Data sources, initialization, and freezing differ across stages, so merging them destroys later probability and reward semantics.'], formulas: [String.raw`\mathrm{SFT}\rightarrow\mathrm{reward\ modeling}\rightarrow\mathrm{online\ rollout+PPO}`] },
      { id: 'role-separation', kicker: 'Separate roles', title: 'Old records batch provenance; reference constrains long-term drift', paragraphs: ['Before each rollout, an old snapshot is copied from the current policy, generates responses, and stores token probabilities. It remains fixed during optimization as the importance-ratio denominator.', 'The reference normally starts from SFT and stays frozen for KL regularization. A batch-refreshed reference loses its anchor, while a permanently frozen old policy cannot describe the actual sampler.'], formulas: [String.raw`\theta_{\rm old}\leftarrow\theta\ \text{per rollout},\qquad\theta_{\rm ref}\leftarrow\theta_{\rm SFT}\ \text{and frozen}`] },
    ],
    sections: [
      { id: 'model-roles', kicker: 'Five roles', title: 'Each model has one statistical responsibility', paragraphs: ['Policy determines current generation; old identifies the distribution that produced the batch; reference measures drift from a long-lived anchor; reward converts preference into a sequence score; value predicts adjusted future return at each prefix.', 'They may share architecture or initialization, but their training state and usage differ. Tracking which model version produced a tensor matters more than memorizing five names.'], formula: String.raw`\pi_\theta\neq\pi_{\rm old}\neq\pi_{\rm ref},\qquad r_\psi\ \text{is not a policy}` },
      { id: 'batch-contract', kicker: 'Batch contract', title: 'Rollout stores token evidence that remains auditable through training', paragraphs: ['Tokens, response masks, old log-probabilities, old values, termination positions, and model versions define a sample and must align at identical token positions.', 'Reference probabilities and reward may be computed later, but they must reuse exactly the same tokenization and mask. Otherwise ratios and advantages can have valid shapes while referring to misaligned objects.'], formula: String.raw`\mathcal B=\{x,y,m,\log\pi_{\rm old},V_{\rm old},R,\text{versions}\}` },
      { id: 'online-loop', kicker: 'Lifecycle', title: 'A completed update requires fresh evidence from the new policy', paragraphs: ['A fixed batch is reused for only finitely many minibatch epochs. Optimization then publishes a new policy, refreshes rollout workers, and discards data that has become too distant from current behavior.', 'Parallelism and asynchrony may increase throughput but cannot erase the version boundary. Excessive policy lag distorts ratios and makes clipping replace useful learning signal.'], formula: String.raw`\text{generate}\rightarrow\text{score}\rightarrow\text{GAE}\rightarrow\text{update}\rightarrow\text{refresh}` },
    ], summaryTitle: 'PPO-based RLHF is an online loop with strict data provenance', summary: ['Policy, old, reference, reward, and value are distinct roles.', 'Reference KL and old-policy ratios solve different problems.', 'Tokens, masks, probabilities, and values must align.', 'Workers refresh and roll out again after updates.'], explorer: {},
  },
})

Object.assign(rlhfChapter.zh, { eyebrow: '第 16 章 · PPO-based RLHF' })
Object.assign(rlhfChapter.en, { eyebrow: 'Chapter 16 · PPO-based RLHF' })
