import { assertFoundationChapterDefinition } from './schema.js'
import { rlhfDeepeningEn, rlhfDeepeningZh } from './modern-deepening.js'

const sources = [
  { id: 'ppo', label: 'Proximal Policy Optimization Algorithms', pages: 'Sections 1–3', href: 'https://arxiv.org/abs/1707.06347' },
  { id: 'instructgpt', label: 'Training language models to follow instructions with human feedback', pages: 'Sections 2–3', href: 'https://arxiv.org/abs/2203.02155' },
]

const zhDerivation = [
  { id: 'lm-as-mdp', rule: '把自回归生成写成序列决策', latex: String.raw`S_t=(x,y_{<t}),\qquad A_t=y_t,\qquad \pi_\theta(A_t\mid S_t)=\pi_\theta(y_t\mid x,y_{<t})`, short: '状态是提示与已生成前缀，动作是下一个 token。', detail: '从 prompt x 开始，每生成一个 token，前缀就变成下一状态。一条 response 对应一条轨迹；EOS 结束 episode。这个映射先定义决策对象，尚未引入奖励模型或 PPO。', assumptions: ['使用自回归语言模型'], symbols: [[String.raw`x`, 'prompt'], [String.raw`y_{<t}`, '第 t 个 token 前的生成前缀']] },
  { id: 'preference-reward', rule: '用奖励模型给完整回答打分', latex: String.raw`R_{\mathrm{RM}}=r_\psi(x,y)`, short: '偏好比较被学习成可计算的序列级奖励。', detail: '奖励模型由回答排序或比较数据训练，输入 prompt 与完整 response，输出标量。它提供优化信号，但不是正在生成 token 的策略。', assumptions: ['奖励模型在 PPO 阶段冻结'], symbols: [[String.raw`\psi`, '奖励模型参数'], [String.raw`y`, '完整 response']] },
  { id: 'reference-regularization', rule: '加入相对参考策略的偏离代价', latex: String.raw`R(x,y)=r_\psi(x,y)-\beta\sum_t\left[\log\pi_\theta(y_t\mid x,y_{<t})-\log\pi_{\mathrm{ref}}(y_t\mid x,y_{<t})\right]`, short: '偏好奖励推动改进，参考策略抑制分布漂移。', detail: '冻结参考模型为每个已生成 token 提供 log-probability。它与当前策略的差可逐 token 计入 shaped reward，使序列奖励能够向前缀分配。', assumptions: ['参考模型冻结', String.raw`\beta\ge0`], symbols: [[String.raw`\pi_{\mathrm{ref}}`, '冻结参考策略'], [String.raw`\beta`, 'KL 正则强度']] },
  { id: 'token-advantage', rule: '由 token 奖励与价值计算 GAE', latex: String.raw`\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t),\qquad \widehat A_t=\sum_{l\ge0}(\gamma\lambda)^l\delta_{t+l}`, short: '序列分数经过奖励整形后转成逐 token 更新信号。', detail: '价值模型读取每个前缀并预测未来调整后回报。TD error 与 GAE 把终局奖励、token 级 KL 代价和前缀价值结合成逐 token 优势。', assumptions: ['价值模型与策略使用同一批 rollout'], symbols: [[String.raw`V_\phi`, 'value model'], [String.raw`\widehat A_t`, 'token 级优势']] },
  { id: 'ppo-batch', rule: '用旧 log-probability 构造 PPO 小批量目标', latex: String.raw`L^{\mathrm{CLIP}}=\mathbb E_t\!\left[\min\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\mathrm{old}}(y_t\mid S_t)}\widehat A_t,\operatorname{clip}\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\mathrm{old}}(y_t\mid S_t)},1-\epsilon,1+\epsilon\right)\widehat A_t\right)\right]`, short: 'rollout 中保存的旧概率把生成阶段与训练阶段连接起来。', detail: '生成时必须保存 token、mask、旧 log-probability 和 value。训练时在相同位置重算新策略概率，形成 ratio 与裁剪目标；value target 同时训练 Critic。', assumptions: ['旧概率与 token 序列严格对齐'], symbols: [[String.raw`\pi_{\mathrm{old}}`, '生成该 batch 的策略快照']] },
  { id: 'lifecycle', rule: '明确一轮更新后的模型状态', latex: String.raw`(\theta,\phi)\leftarrow\operatorname{Update}(\mathcal B),\qquad \psi\ \text{and}\ \pi_{\mathrm{ref}}\ \text{remain frozen}`, short: '更新 policy 与 value，保持 reward 与 reference 冻结。', detail: '完成若干 minibatch epoch 后，新 policy 权重发布给 rollout workers，再生成下一批数据。若生成端继续使用过旧权重，保存的概率与当前优化目标会出现更大的策略滞后。', assumptions: ['一轮内批次 B 不变'], symbols: [[String.raw`\mathcal B`, 'rollout batch'], [String.raw`\phi`, 'value 参数']] },
]

const enDerivation = [
  { id: 'lm-as-mdp', rule: 'Write autoregressive generation as sequential decision making', latex: String.raw`S_t=(x,y_{<t}),\qquad A_t=y_t,\qquad \pi_\theta(A_t\mid S_t)=\pi_\theta(y_t\mid x,y_{<t})`, short: 'State is prompt plus prefix; action is the next token.', detail: 'Starting from prompt x, each generated token extends the prefix into the next state. A response is a trajectory and EOS ends the episode. This defines the decision process before adding rewards or PPO.', assumptions: ['The language model is autoregressive'], symbols: [[String.raw`x`, 'prompt'], [String.raw`y_{<t}`, 'generated prefix before token t']] },
  { id: 'preference-reward', rule: 'Score the completed response with a reward model', latex: String.raw`R_{\mathrm{RM}}=r_\psi(x,y)`, short: 'Preference comparisons become a computable sequence reward.', detail: 'A reward model trained from rankings consumes prompt and complete response and returns a scalar. It supplies an objective signal but is not the token-generating policy.', assumptions: ['The reward model is frozen during PPO'], symbols: [[String.raw`\psi`, 'reward-model parameters'], [String.raw`y`, 'complete response']] },
  { id: 'reference-regularization', rule: 'Add a penalty for departing from a reference policy', latex: String.raw`R(x,y)=r_\psi(x,y)-\beta\sum_t\left[\log\pi_\theta(y_t\mid x,y_{<t})-\log\pi_{\mathrm{ref}}(y_t\mid x,y_{<t})\right]`, short: 'Preference reward drives improvement; the reference discourages drift.', detail: 'The frozen reference supplies a log-probability for each generated token. Its difference from the current policy can be applied tokenwise as shaped reward.', assumptions: ['The reference model is frozen', String.raw`\beta\ge0`], symbols: [[String.raw`\pi_{\mathrm{ref}}`, 'frozen reference policy'], [String.raw`\beta`, 'KL regularization strength']] },
  { id: 'token-advantage', rule: 'Compute token advantages from reward and value', latex: String.raw`\delta_t=R_{t+1}+\gamma V_\phi(S_{t+1})-V_\phi(S_t),\qquad \widehat A_t=\sum_{l\ge0}(\gamma\lambda)^l\delta_{t+l}`, short: 'A sequence score becomes token-level update signals after reward shaping.', detail: 'The value model scores each prefix. TD errors and GAE combine terminal reward, tokenwise KL cost, and prefix values into per-token advantages.', assumptions: ['Value and policy use the same rollout batch'], symbols: [[String.raw`V_\phi`, 'value model'], [String.raw`\widehat A_t`, 'token-level advantage']] },
  { id: 'ppo-batch', rule: 'Build PPO minibatches from saved old log-probabilities', latex: String.raw`L^{\mathrm{CLIP}}=\mathbb E_t\!\left[\min\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\mathrm{old}}(y_t\mid S_t)}\widehat A_t,\operatorname{clip}\!\left(\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\mathrm{old}}(y_t\mid S_t)},1-\epsilon,1+\epsilon\right)\widehat A_t\right)\right]`, short: 'Saved old probabilities connect generation to training.', detail: 'Generation stores tokens, masks, old log-probabilities, and values. Training recomputes current probabilities at aligned positions to form ratios and clip targets while fitting the value target.', assumptions: ['Old probabilities align exactly with token positions'], symbols: [[String.raw`\pi_{\mathrm{old}}`, 'policy snapshot that generated the batch']] },
  { id: 'lifecycle', rule: 'State which models change after the update', latex: String.raw`(\theta,\phi)\leftarrow\operatorname{Update}(\mathcal B),\qquad \psi\ \text{and}\ \pi_{\mathrm{ref}}\ \text{remain frozen}`, short: 'Update policy and value; keep reward and reference frozen.', detail: 'After several minibatch epochs, publish new policy weights to rollout workers and collect a fresh batch. Stale workers increase policy lag between generation and optimization.', assumptions: ['Batch B is fixed within one update phase'], symbols: [[String.raw`\mathcal B`, 'rollout batch'], [String.raw`\phi`, 'value parameters']] },
]

export const rlhfChapter = assertFoundationChapterDefinition({
  id: 'rlhf', sources,
  zh: {
    prerequisite: '前置：PPO 的概率比、优势估计与裁剪目标', summaryTitle: 'PPO 是优化器；RLHF 是产生奖励、rollout 与训练批次的完整流程', eyebrow: '语言模型后训练 · PPO 系统视图', title: '一条 response 怎样从生成结果变成可训练的 token batch？', intro: '语言模型把 prompt 与已生成前缀当作状态，把下一个 token 当作动作。PPO-based RLHF 在此决策过程中加入偏好奖励、冻结参考策略与价值估计，并用在线 rollout 持续产生新训练数据。', derivationIntro: '先建立语言模型与序列决策的对应，再逐步加入奖励、参考约束、价值与 PPO；这样每个系统节点都有已经定义的算法对象。', bridge: '同一批 rollout 同时存在两种视角：算法视角检查概率比、优势和目标；系统视角检查哪些模型读写哪些张量。', experimentIntro: '下面切换“算法/系统”不会更换 batch。先选一条 response，再点击流水线节点，追踪 token、旧概率、参考概率、奖励、value、advantage 与更新目标如何对齐。', interpretation: '核心不变量是样本身份与 token 位置不能在两个视角间改变。Policy 和 value 在训练阶段更新；reference 与 reward model 只前向打分。完成更新后必须刷新生成端权重并重新 rollout。', figure: '交互图 16.1 · PPO Rollout Lifecycle', instruction: '固定一条样本，在算法和系统视图之间追踪同一批数据', question: '为什么 reference policy 与 old policy 都提供概率，却不能合并为同一个模型角色？', derivation: zhDerivation, deepening: rlhfDeepeningZh, prelude: [{ id: 'pipeline-not-optimizer', kicker: '先区分层级', title: 'RLHF 是训练流程，PPO 是其中的策略优化步骤', paragraphs: ['SFT 提供可用初始策略，偏好数据训练 reward model，在线策略再生成 response 并接受 PPO 更新。把三者混成一个算法会掩盖模型冻结关系与数据来源。'], formulas: [String.raw`\mathrm{SFT}\rightarrow\mathrm{reward\ model}\rightarrow\mathrm{online\ rollout+PPO}`] }], sections: [
      { id: 'model-roles', kicker: '四类模型', title: 'Policy、old、reference 与 reward 各自回答不同问题', paragraphs: ['当前 policy 是正在优化的生成模型；old policy 是本批数据采样时的快照；reference policy 是长期冻结的行为锚点；reward model 把偏好映射为分数。', 'Value model 另行估计每个前缀的未来调整后回报，给 GAE 提供 baseline。'], formula: String.raw`\pi_\theta\neq\pi_{\mathrm{old}}\neq\pi_{\mathrm{ref}},\qquad r_\psi\ \text{is not a policy}` },
      { id: 'batch-contract', kicker: '数据契约', title: '一条 rollout 必须携带可重放的训练证据', paragraphs: ['除了 token 本身，还需保存 attention mask、response mask、旧 log-probability、old value 与终止位置。Reference log-probability 和 reward 可以在生成后批量补算。', '任何截断、padding 或 tokenization 不一致都会破坏 ratio 与 advantage 的位置对应。'], formula: String.raw`\mathcal B=\{x,y,\text{masks},\log\pi_{\mathrm{old}},V_{\mathrm{old}},R\}` },
      { id: 'online-loop', kicker: '生命周期', title: '训练完成不是终点，而是下一轮 rollout 的起点', paragraphs: ['PPO 对固定 batch 做有限轮 minibatch 后，发布新 policy 权重；生成端加载后产生下一批更接近当前策略的数据。', '吞吐优化必须服从这个统计边界：过度异步会增加 policy lag，使旧样本与当前策略差异过大。'], formula: String.raw`\text{generate}\rightarrow\text{score}\rightarrow\text{estimate}\rightarrow\text{update}\rightarrow\text{refresh}` },
    ], summary: ['语言模型可写成 token 级序列决策，response 是一条轨迹。', 'Reward model 给偏好分数，reference policy 提供长期行为锚点，value model 估计前缀价值。', 'Old policy 保存本批采样分布，与冻结 reference 承担不同职责。', 'rollout、打分、GAE、minibatch 更新和权重刷新构成一个闭环。'], explorer: {},
  },
  en: {
    prerequisite: 'Prerequisites: PPO probability ratios, advantage estimation, and clipping', summaryTitle: 'PPO is an optimizer; RLHF is the full reward, rollout, and training-data process', eyebrow: 'Language-model post-training · PPO system view', title: 'How does one response become a trainable token batch?', intro: 'A language model treats prompt plus generated prefix as state and the next token as action. PPO-based RLHF adds preference reward, a frozen reference policy, and value estimation, then continually produces fresh data through online rollout.', derivationIntro: 'Map language modeling to sequential decisions first, then add reward, reference regularization, value, and PPO so every system node has a defined algorithmic object.', bridge: 'One rollout batch supports two views: the algorithm view inspects ratios, advantages, and targets; the system view inspects which models read and write which tensors.', experimentIntro: 'Switching Algorithm/System below never changes the batch. Select a response, then follow tokens, old probabilities, reference probabilities, reward, value, advantages, and update targets through aligned positions.', interpretation: 'The invariant is sample identity and token alignment. Policy and value update during training; reference and reward only score. After the update, rollout workers must refresh weights and collect new data.', figure: 'Interactive Figure 16.1 · PPO Rollout Lifecycle', instruction: 'Keep one sample fixed while tracing it through algorithm and system views', question: 'Why do reference and old policy both provide probabilities but remain distinct roles?', derivation: enDerivation, deepening: rlhfDeepeningEn, prelude: [{ id: 'pipeline-not-optimizer', kicker: 'Separate the levels', title: 'RLHF is a training process; PPO is its policy-update step', paragraphs: ['SFT supplies a usable initial policy, preference data trains a reward model, and the online policy then generates responses for PPO. Treating all three as one algorithm hides freezing and data provenance.'], formulas: [String.raw`\mathrm{SFT}\rightarrow\mathrm{reward\ model}\rightarrow\mathrm{online\ rollout+PPO}`] }], sections: [
      { id: 'model-roles', kicker: 'Four model roles', title: 'Policy, old, reference, and reward answer different questions', paragraphs: ['The current policy is optimized; old policy is the snapshot that sampled this batch; reference policy is a long-lived frozen anchor; reward model maps preferences to a score.', 'A value model estimates adjusted future return at each prefix and supplies the GAE baseline.'], formula: String.raw`\pi_\theta\neq\pi_{\mathrm{old}}\neq\pi_{\mathrm{ref}},\qquad r_\psi\ \text{is not a policy}` },
      { id: 'batch-contract', kicker: 'Data contract', title: 'A rollout carries replayable training evidence', paragraphs: ['Beyond tokens, store attention and response masks, old log-probabilities, old values, and terminal positions. Reference probabilities and reward can be scored afterward.', 'Any mismatch in truncation, padding, or tokenization breaks positional alignment for ratios and advantages.'], formula: String.raw`\mathcal B=\{x,y,\text{masks},\log\pi_{\mathrm{old}},V_{\mathrm{old}},R\}` },
      { id: 'online-loop', kicker: 'Lifecycle', title: 'Training completion starts the next rollout', paragraphs: ['After finite minibatch epochs on a fixed batch, publish new policy weights. Rollout workers load them and generate data closer to the current policy.', 'Throughput optimization must respect this statistical boundary: excessive asynchrony increases policy lag.'], formula: String.raw`\text{generate}\rightarrow\text{score}\rightarrow\text{estimate}\rightarrow\text{update}\rightarrow\text{refresh}` },
    ], summary: ['Language modeling is token-level sequential decision making; a response is a trajectory.', 'Reward scores preferences, reference anchors behavior, and value estimates prefix return.', 'Old policy records the batch distribution and is distinct from the frozen reference.', 'Rollout, scoring, GAE, minibatch updates, and weight refresh form one loop.'], explorer: {},
  },
})
