import { assertFoundationChapterDefinition } from './schema.js'
import { rlhfDeepeningEn, rlhfDeepeningZh } from './modern-deepening.js'

const sources = [
  { id: 'ppo', label: 'Proximal Policy Optimization Algorithms', pages: 'Sections 1–3', href: 'https://arxiv.org/abs/1707.06347' },
  { id: 'instructgpt', label: 'Training language models to follow instructions with human feedback', pages: 'Sections 2–3', href: 'https://arxiv.org/abs/2203.02155' },
]

const zhDerivation = [
  { id: 'lm-as-mdp', rule: '沿用 Token MDP 的序列决策对象', latex: String.raw`\begin{aligned}S_t&=(x,y_{<t}),\qquad A_t=y_t,\\ \pi_\theta(A_t\mid S_t)&=\pi_\theta(y_t\mid x,y_{<t})\end{aligned}`, short: '状态是 prompt 与前缀，动作是下一个 token。', detail: '第 15 章已经建立此映射。本章从这里出发，只加入 PPO-based RLHF 特有的模型角色和批次生命周期。', assumptions: ['模型使用自回归分解'], symbols: [[String.raw`x`, 'prompt'], [String.raw`y_{<t}`, '生成前缀']] },
  { id: 'reward-model', rule: '用冻结 reward model 给完整回答提供偏好分数', latex: String.raw`R_{\rm RM}=r_\psi(x,y)`, short: '偏好比较被学习成可计算的序列级标量。', detail: 'Reward model 由人类排序数据训练，在 PPO 阶段只前向打分，不随 policy minibatch 更新。', assumptions: ['reward model 在 PPO 阶段冻结'], symbols: [[String.raw`\psi`, 'reward model 参数']] },
  { id: 'reference-kl', rule: '逐 token 加入相对冻结 reference 的偏离代价', latex: String.raw`\begin{aligned}d_t^{\rm KL}&=\log\pi_\theta(y_t\mid S_t)-\log\pi_{\rm ref}(y_t\mid S_t),\\ R_t^{\rm shaped}&=R_t^{\rm task}-\beta d_t^{\rm KL}\end{aligned}`, short: '偏好奖励负责前进，reference 约束负责防止分布失控。', detail: 'Reference 通常由 SFT 模型复制并长期冻结。它不是生成本批数据的 old policy。', assumptions: [String.raw`\beta\ge0`], symbols: [[String.raw`\pi_{\rm ref}`, '长期冻结参考策略']] },
  { id: 'token-gae', rule: '由 shaped reward 与 value model 计算逐 token GAE', latex: String.raw`\begin{aligned}\delta_t&=R_{t+1}^{\rm shaped}+\gamma V_\phi(S_{t+1})-V_\phi(S_t),\\ \widehat A_t&=\sum_{l\ge0}(\gamma\lambda)^l\delta_{t+l}\end{aligned}`, short: '序列分数经过 value baseline 变成 token 更新方向。', detail: 'Value model 读取每个前缀；mask、EOS 和 padding 必须与 policy 概率严格对齐。', assumptions: ['policy 与 value 使用同一 rollout batch'], symbols: [[String.raw`V_\phi`, '前缀价值模型']] },
  { id: 'ppo-update', rule: '用实际生成策略的旧概率构造裁剪更新', latex: String.raw`\begin{aligned}r_t(\theta)&=\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)},\\ c_t(\theta)&=\operatorname{clip}(r_t,1-\epsilon,1+\epsilon),\\ L^{\rm CLIP}&=\mathbb E_t\!\left[\min(r_t\widehat A_t,c_t\widehat A_t)\right]\end{aligned}`, short: 'Old policy 连接生成和训练，reference 约束长期行为。', detail: '分母必须对应实际生成该 token 的策略快照。用 reference 代替 old 会破坏重要性修正。', assumptions: ['old log-probability 与 token 位置一致'], symbols: [[String.raw`\pi_{\rm old}`, '生成当前 batch 的策略快照']] },
  { id: 'refresh-loop', rule: '更新 policy/value 并刷新 rollout worker', latex: String.raw`\begin{aligned}(\theta,\phi)&\leftarrow\operatorname{Update}(\mathcal B),\\ \psi\ \text{and}\ \pi_{\rm ref}&\ \text{remain frozen}\end{aligned}`, short: '训练后发布新 policy，再生成下一批数据。', detail: '固定 batch 只复用有限轮；过度异步会增加 policy lag。Reward 与 reference 在此阶段保持冻结。', assumptions: ['batch 在一次更新阶段固定'], symbols: [[String.raw`\mathcal B`, 'rollout batch']] },
]

const enDerivation = [
  { id: 'lm-as-mdp', rule: 'Reuse the sequential objects from Token MDP', latex: String.raw`\begin{aligned}S_t&=(x,y_{<t}),\qquad A_t=y_t,\\ \pi_\theta(A_t\mid S_t)&=\pi_\theta(y_t\mid x,y_{<t})\end{aligned}`, short: 'State is prompt plus prefix and action is the next token.', detail: 'Chapter 15 established this mapping. This chapter only adds PPO-based RLHF roles and lifecycle.', assumptions: ['The model factorizes autoregressively'], symbols: [[String.raw`x`, 'prompt'], [String.raw`y_{<t}`, 'generated prefix']] },
  { id: 'reward-model', rule: 'Score complete responses with a frozen reward model', latex: String.raw`R_{\rm RM}=r_\psi(x,y)`, short: 'Preference comparisons become a computable sequence scalar.', detail: 'The reward model is trained from rankings and only scores during PPO.', assumptions: ['Reward model is frozen during PPO'], symbols: [[String.raw`\psi`, 'reward-model parameters']] },
  { id: 'reference-kl', rule: 'Add tokenwise deviation cost from a frozen reference', latex: String.raw`\begin{aligned}d_t^{\rm KL}&=\log\pi_\theta(y_t\mid S_t)-\log\pi_{\rm ref}(y_t\mid S_t),\\ R_t^{\rm shaped}&=R_t^{\rm task}-\beta d_t^{\rm KL}\end{aligned}`, short: 'Preference drives improvement while reference regularization prevents uncontrolled drift.', detail: 'The reference is a long-lived SFT copy and is not the old policy that generated this batch.', assumptions: [String.raw`\beta\ge0`], symbols: [[String.raw`\pi_{\rm ref}`, 'long-lived frozen reference']] },
  { id: 'token-gae', rule: 'Compute token GAE from shaped reward and value', latex: String.raw`\begin{aligned}\delta_t&=R_{t+1}^{\rm shaped}+\gamma V_\phi(S_{t+1})-V_\phi(S_t),\\ \widehat A_t&=\sum_{l\ge0}(\gamma\lambda)^l\delta_{t+l}\end{aligned}`, short: 'A sequence score becomes token update direction through the value baseline.', detail: 'Masks, EOS, and padding must align policy probabilities and value positions.', assumptions: ['Policy and value share one rollout batch'], symbols: [[String.raw`V_\phi`, 'prefix value model']] },
  { id: 'ppo-update', rule: 'Use probabilities from the actual generating policy for clipping', latex: String.raw`\begin{aligned}r_t(\theta)&=\frac{\pi_\theta(y_t\mid S_t)}{\pi_{\rm old}(y_t\mid S_t)},\\ c_t(\theta)&=\operatorname{clip}(r_t,1-\epsilon,1+\epsilon),\\ L^{\rm CLIP}&=\mathbb E_t\!\left[\min(r_t\widehat A_t,c_t\widehat A_t)\right]\end{aligned}`, short: 'Old connects generation to training; reference constrains long-term behavior.', detail: 'The denominator must match the policy snapshot that generated each token.', assumptions: ['Old log-probability aligns with token positions'], symbols: [[String.raw`\pi_{\rm old}`, 'snapshot that generated this batch']] },
  { id: 'refresh-loop', rule: 'Update policy/value and refresh rollout workers', latex: String.raw`\begin{aligned}(\theta,\phi)&\leftarrow\operatorname{Update}(\mathcal B),\\ \psi\ \text{and}\ \pi_{\rm ref}&\ \text{remain frozen}\end{aligned}`, short: 'Publish the policy and collect a fresh batch.', detail: 'A fixed batch is reused only finitely; excessive asynchrony creates policy lag.', assumptions: ['Batch is fixed within one update phase'], symbols: [[String.raw`\mathcal B`, 'rollout batch']] },
]

export const rlhfChapter = assertFoundationChapterDefinition({
  id: 'rlhf', sources,
  zh: {
    prerequisite: '前置：PPO、Token MDP 与 GAE', eyebrow: 'PPO-based RLHF 系统', title: '把偏好比较转成可验证的在线 PPO 更新', intro: '第 14 章已经说明 PPO 怎样限制一次策略更新，第 15 章也已经把回答写成 token 轨迹，但两者都没有给出语言模型的任务奖励。PPO-based RLHF 要补上的不是另一种优化器，而是一条完整的数据链：先用示范得到可用的初始策略，再从人类比较中学习奖励，最后让当前策略在线生成回答，并把序列级偏好分数变成逐 token 的 PPO 更新。', bridge: '这条链必须同时回答三个问题：奖励从哪里来，生成回答的分布怎样被记录，策略为什么不会为了追逐奖励而无限偏离原有语言能力。后面的模型角色都由这三个问题逐一引出，而不是一开始并列出现。', derivationIntro: '沿着一批真实回答的生命周期，先取得序列偏好分数，再加入 reference 约束，把 shaped reward 变成逐 token advantage，最后用生成该批回答的 old policy 构造 PPO 比值并刷新策略。', experimentIntro: '固定一批回答，在算法视图和系统视图之间切换，逐 token 核对 old/reference 概率、reward、value、advantage 和更新目标。若任一位置或模型版本错位，界面中的比值和优势虽然仍是数值，却不再描述同一条样本。', interpretation: '实验中的不变量不是“五个模型名称”，而是回答身份、token 位置和模型版本。Old policy 证明样本从哪个分布生成，reference policy 给出长期约束；policy 与 value 随 PPO 更新，reward model 与 reference 在这一阶段保持冻结。', figure: '交互图 16.1 · PPO-based RLHF Shared Batch', instruction: '沿同一批回答追踪生成、打分、优势计算与更新证据', question: '一条偏好分数怎样在不混淆模型版本的前提下变成逐 token 更新？', derivation: zhDerivation, deepening: rlhfDeepeningZh,
    prelude: [
      { id: 'pipeline-level', kicker: '奖励进入策略之前', title: '示范学习先建立可用策略，偏好比较再建立奖励', paragraphs: ['监督微调（supervised fine-tuning，SFT）使用 prompt 与高质量示范回答训练 next-token prediction，使预训练模型先具备基本的指令遵循能力；这个 SFT 模型既是在线优化的起点，也通常提供长期 reference 的初始权重。', '随后，同一 prompt 下的回答排序被用来训练 reward model，使它对完整回答给出一个偏好分数。直到这两个输入准备好，当前 policy 才在线生成新回答，并用 reward model 的分数执行 PPO。示范数据、偏好比较和 rollout 因此属于前后依赖的三个阶段，不能当作同一批训练样本。'], formulas: [String.raw`\mathrm{SFT}\rightarrow\mathrm{preference\ comparisons}\rightarrow\mathrm{online\ rollout+PPO}`] },
      { id: 'role-separation', kicker: '角色分离', title: 'Old 记录本批数据来源，reference 约束长期漂移', paragraphs: ['每轮 rollout 前从当前 policy 复制 old snapshot，用它生成回答并保存逐 token 概率；优化期间 old 保持不变，作为重要性比值的分母。', 'Reference 通常从 SFT 模型初始化后长期冻结，用于计算 KL 约束。若同一对象同时承担两种职责，随批次刷新的 reference 会失去稳定锚点，长期不变的 old 又无法描述实际采样分布。'], formulas: [String.raw`\theta_{\rm old}\leftarrow\theta\ \text{per rollout},\qquad\theta_{\rm ref}\leftarrow\theta_{\rm SFT}\ \text{and frozen}`] },
    ],
    sections: [
      { id: 'model-roles', kicker: '五类角色', title: '每类模型只负责一种统计职责', paragraphs: ['Policy 决定当前生成什么，old 说明本批数据由哪个分布产生，reference 衡量策略相对长期锚点的偏移，reward model 把偏好转成序列分数，value model 估计每个前缀的调整后未来回报。', '它们可能共享网络架构或初始化权重，但训练状态和使用时机不同。判断一个张量来自哪个模型、哪个版本，比记住“五个名字”更重要。'], formula: String.raw`\pi_\theta\neq\pi_{\rm old}\neq\pi_{\rm ref},\qquad r_\psi\ \text{is not a policy}` },
      { id: 'batch-contract', kicker: '批次契约', title: 'Rollout 保存从生成到更新都可核对的 token 证据', paragraphs: ['Token、response mask、old log-probability、old value、终止位置和模型版本共同定义一条训练样本；这些字段必须在相同 token 位置上对齐。', 'Reference 概率与 reward 可以在生成后计算，但必须复用完全相同的 tokenization 与 mask。否则 advantage 或 ratio 虽然形状合法，统计对象却已经错位。'], formula: String.raw`\mathcal B=\{x,y,m,\log\pi_{\rm old},V_{\rm old},R,\text{versions}\}` },
      { id: 'online-loop', kicker: '下一批证据', title: '策略更新之后，旧回答不再代表新的生成分布', paragraphs: ['同一批回答可以被切成 minibatch 做有限轮更新，但保存的 old log-probability、advantage 和 return 必须保持不变。优化完成后，新的 policy 被发布到 rollout worker；下一轮回答必须由这个新版本重新生成，才能继续保持“样本—生成分布—PPO 分母”的对应关系。', '异步 worker 可以提高吞吐量，却会带来 policy lag：生成端落后得越多，current/old ratio 越容易偏离裁剪区间，原先的优势也越难代表当前策略。PPO-based RLHF 因而以在线探索换来持续生成、版本管理和多模型前向的系统成本；下一章将考察固定偏好数据能否绕开这条在线闭环。'], formula: String.raw`\text{generate}\rightarrow\text{score}\rightarrow\text{GAE}\rightarrow\text{update}\rightarrow\text{refresh}` },
    ], summaryTitle: '偏好奖励只有经过对齐的数据链才能成为 PPO 更新', summary: ['SFT 建立初始策略，偏好比较训练 reward model，在线 rollout 才产生 PPO 数据。', 'Old policy 记录本批数据来源，reference policy 约束长期漂移。', '序列 reward、逐 token KL、value、mask 和概率必须位置对齐。', '策略更新后需要刷新 worker，并用新版本重新生成证据。'], explorer: {},
  },
  en: {
    prerequisite: 'Prerequisites: PPO, Token MDP, and GAE', eyebrow: 'PPO-based RLHF system', title: 'Turn preference comparisons into auditable online PPO updates', intro: 'Chapter 14 explained how PPO constrains a policy update, and Chapter 15 represented a response as a token trajectory, but neither supplied a language-model task reward. PPO-based RLHF is not another optimizer. It is a data chain: demonstrations create a usable initial policy, human comparisons teach a reward, and the current policy generates fresh responses whose sequence scores become token-level PPO updates.', bridge: 'The chain must establish where reward comes from, which distribution generated each response, and why reward optimization cannot drift without bound. Model roles appear as answers to those problems instead of an opening list.', derivationIntro: 'Follow one response batch through sequence scoring, reference shaping, token advantage, an old-policy PPO ratio, and finally policy publication and rollout refresh.', experimentIntro: 'Hold one response batch fixed and switch between algorithm and system views. Check old/reference probabilities, reward, value, advantage, and targets at every token; a positional or version mismatch leaves plausible numbers that no longer describe one sample.', interpretation: 'The invariants are response identity, token position, and model version. Old identifies the generating distribution; reference supplies a long-lived constraint. Policy and value update during PPO, while reward and reference stay frozen.', figure: 'Interactive Figure 16.1 · PPO-based RLHF Shared Batch', instruction: 'Trace one response batch from generation and scoring to advantage and update', question: 'How does one preference score become token updates without confusing model versions?', derivation: enDerivation, deepening: rlhfDeepeningEn,
    prelude: [
      { id: 'pipeline-level', kicker: 'Before reward reaches the policy', title: 'Demonstrations establish a usable policy before comparisons establish reward', paragraphs: ['Supervised fine-tuning (SFT) trains next-token prediction on prompts and high-quality demonstrations so the pretrained model first acquires usable instruction-following behavior. This SFT model initializes online optimization and commonly the long-lived reference.', 'Responses to the same prompt are then ranked to train a reward model that scores a complete answer. Only after those inputs exist does the current policy generate fresh responses for PPO. Demonstrations, comparisons, and rollout therefore belong to dependent stages rather than one interchangeable batch.'], formulas: [String.raw`\mathrm{SFT}\rightarrow\mathrm{preference\ comparisons}\rightarrow\mathrm{online\ rollout+PPO}`] },
      { id: 'role-separation', kicker: 'Separate roles', title: 'Old records batch provenance; reference constrains long-term drift', paragraphs: ['Before each rollout, an old snapshot is copied from the current policy, generates responses, and stores token probabilities. It remains fixed during optimization as the importance-ratio denominator.', 'The reference normally starts from SFT and stays frozen for KL regularization. A batch-refreshed reference loses its anchor, while a permanently frozen old policy cannot describe the actual sampler.'], formulas: [String.raw`\theta_{\rm old}\leftarrow\theta\ \text{per rollout},\qquad\theta_{\rm ref}\leftarrow\theta_{\rm SFT}\ \text{and frozen}`] },
    ],
    sections: [
      { id: 'model-roles', kicker: 'Five roles', title: 'Each model has one statistical responsibility', paragraphs: ['Policy determines current generation; old identifies the distribution that produced the batch; reference measures drift from a long-lived anchor; reward converts preference into a sequence score; value predicts adjusted future return at each prefix.', 'They may share architecture or initialization, but their training state and usage differ. Tracking which model version produced a tensor matters more than memorizing five names.'], formula: String.raw`\pi_\theta\neq\pi_{\rm old}\neq\pi_{\rm ref},\qquad r_\psi\ \text{is not a policy}` },
      { id: 'batch-contract', kicker: 'Batch contract', title: 'Rollout stores token evidence that remains auditable through training', paragraphs: ['Tokens, response masks, old log-probabilities, old values, termination positions, and model versions define a sample and must align at identical token positions.', 'Reference probabilities and reward may be computed later, but they must reuse exactly the same tokenization and mask. Otherwise ratios and advantages can have valid shapes while referring to misaligned objects.'], formula: String.raw`\mathcal B=\{x,y,m,\log\pi_{\rm old},V_{\rm old},R,\text{versions}\}` },
      { id: 'online-loop', kicker: 'Evidence for the next update', title: 'After a policy update, old responses no longer represent the new generator', paragraphs: ['A response batch may support a finite number of minibatch epochs, but stored old log-probabilities, advantages, and returns remain fixed. Optimization then publishes a new policy to rollout workers, and that version must generate the next responses to preserve the sample–behavior–denominator contract.', 'Asynchronous workers improve throughput but introduce policy lag. Staler generation pushes current/old ratios outside the clip range and makes fixed advantages less representative. PPO-based RLHF therefore trades online exploration for continual generation, version management, and multi-model inference; the next chapter asks what changes when preference data are fixed offline.'], formula: String.raw`\text{generate}\rightarrow\text{score}\rightarrow\text{GAE}\rightarrow\text{update}\rightarrow\text{refresh}` },
    ], summaryTitle: 'Preference reward becomes PPO evidence only through an aligned data chain', summary: ['SFT creates the initial policy, comparisons train reward, and online rollout creates PPO data.', 'Old records batch provenance while reference constrains long-term drift.', 'Sequence reward, token KL, values, masks, and probabilities must align.', 'Updated workers generate fresh evidence for the next round.'], explorer: {},
  },
})

Object.assign(rlhfChapter.zh, { eyebrow: '第 16 章 · PPO-based RLHF', title: '把偏好比较转成可验证的在线 PPO 更新' })
Object.assign(rlhfChapter.en, { eyebrow: 'Chapter 16 · PPO-based RLHF', title: 'Turn preference comparisons into auditable online PPO updates' })
