export const terminologyPolicy = Object.freeze({
  trajectory: {
    zh: '轨迹',
    en: 'trajectory',
    aliases: ['trajectory'],
    firstUse: { chapterId: 'mdp', destinationId: 'trajectory-return' },
    definitionCue: /状态.*动作.*奖励|state.*action.*reward/is,
  },
  episode: {
    zh: '回合',
    en: 'episode',
    aliases: ['episode'],
    firstUse: { chapterId: 'mdp', destinationId: 'task-types' },
    definitionCue: /终止|结束|terminate|end/is,
  },
  return: {
    zh: '回报',
    en: 'return',
    aliases: ['Return', 'return'],
    firstUse: { chapterId: 'returns', destinationId: 'reward-to-return' },
    definitionCue: /未来.*奖励.*权重|future rewards.*weight/is,
  },
  stateValue: {
    zh: '状态价值',
    en: 'state value',
    aliases: ['state value', 'value'],
    firstUse: { chapterId: 'returns', destinationId: 'return-to-value' },
    definitionCue: /期望|均值|expectation|mean/is,
  },
  target: {
    zh: '更新目标',
    en: 'update target',
    aliases: ['target'],
    firstUse: { chapterId: 'bellman', destinationId: 'target-anatomy' },
    definitionCue: /即时奖励.*后继价值|immediate reward.*successor value/is,
  },
  bootstrapping: {
    zh: '自举',
    en: 'bootstrapping',
    aliases: ['Bootstrapping', 'bootstrap'],
    firstUse: { chapterId: 'bellman', destinationId: 'bootstrapping' },
    definitionCue: /估计更新估计|estimate to update another/is,
  },
  fixedPoint: {
    zh: '不动点',
    en: 'fixed point',
    aliases: ['fixed point'],
    firstUse: { chapterId: 'bellman', destinationId: 'matrix-and-iteration' },
    definitionCue: /方程.*解|迭代.*收敛|solution.*equation|iteration.*conver/is,
  },
  behaviorPolicy: {
    zh: '行为策略',
    en: 'behavior policy',
    aliases: ['behavior policy'],
    firstUse: { chapterId: 'control', destinationId: 'policy-roles' },
    definitionCue: /探索.*采样|samples experience/is,
  },
  referencePolicy: {
    zh: '参考策略',
    en: 'reference policy',
    aliases: ['reference policy'],
    firstUse: { chapterId: 'tokenmdp', destinationId: 'reward-placement' },
    definitionCue: /KL.*约束|KL.*regular/is,
  },
  termination: {
    zh: '真正终止',
    en: 'termination',
    aliases: ['terminal', 'termination'],
    firstUse: { chapterId: 'mdp', destinationId: 'task-types' },
    definitionCue: /终止状态后停止|stops at a terminal state/is,
  },
  truncation: {
    zh: '截断',
    en: 'truncation',
    aliases: ['truncation', 'truncated'],
    firstUse: { chapterId: 'tokenmdp', destinationId: 'terminal-vs-truncated' },
    definitionCue: /外部.*预算|长度.*边界|external budget|length boundary/is,
  },
})
